### ISSUE TITLE
[Homework 2] A suggestion for the IR interpreter related to bitwise shift operators

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#103]
Hi.

For me, the current version of the IR interpreter seems to use a too restrictive condition for binary operators. When a binary operator is applied to two integers, [it checks whether the types of the integers are the same](https://github.com/kaist-cp/kecc-public/blob/3bef06455ea35c39555020fe44fdee496dba402d/src/ir/interp.rs#L628-L629). However, to the best of my knowledge, the C semantics does not require the same type for bitwise shift operators. The following is from Section 6.5.7 **Bitwise shift operators** of the C specification:

> The integer promotions are performed on each of the operands. The type of the result is that of the promoted left operand. If the value of the right operand is negative or is greater than or equal to the width of the promoted left operand, the behavior is undefined.

Since integer promotion cannot guarantee that the two operands have the same type, shift operators can be applied to integers whose types are different from each other.

Even if I can implement IRgen correctly under the current version of the interpreter, I believe it would be better to check types only when a given operator is not a bitwise shift operator. For example:

```diff
--- a/src/ir/interp.rs
+++ b/src/ir/interp.rs
@@ -625,8 +625,14 @@ mod calculator {
                     is_signed: rhs_s,
                 },
             ) => {
-                assert_eq!(lhs_w, rhs_w);
-                assert_eq!(lhs_s, rhs_s);
+                match op {
+                    ast::BinaryOperator::ShiftLeft |
+                        ast::BinaryOperator::ShiftRight => (),
+                    _ => {
+                        assert_eq!(lhs_w, rhs_w);
+                        assert_eq!(lhs_s, rhs_s);
+                    },
+                };

                 calculate_integer_binary_operator_expression(op, lhs, rhs, lhs_w, lhs_s)
             }
```

Thank you.

**Comment by cmpark0126** [comment]
Thank you for the suggestion! What you've pointed out is definitely what we've missed. I'll try to fix it as soon as possible.

**Comment by cmpark0126** [comment]
Thank you for the suggestion! I agree with your suggestion.

However, Unfortunately, `LLVM` does not work that way. Please refer the below:
```c
long a = 0;
int b = 1; // right operand is less than the width of the promoted left operand

int main (void)
{
    return a >> b;
}
```
```llvm
define dso_local i32 @main() #0 !dbg !15 {
  ...
  %2 = load i64, i64* @a, align 8, !dbg !18
  %3 = load i32, i32* @b, align 4, !dbg !19
  %4 = zext i32 %3 to i64, !dbg !20
  %5 = ashr i64 %2, %4, !dbg !20
  %6 = trunc i64 %5 to i32, !dbg !18
  ret i32 %6, !dbg !21
}
```
As you pointed out, if we use a > b, we don't need to typecast. But `LLVM` typecast `b` to `long`. For this reason, `kecc-public` was implemented to operate in the same way.

**Comment by Medowhill** [comment]
I see. Thank you for the kind explanation.
