### ISSUE TITLE
[HW2] What is usage of member `structs` in ir::TranslationUnit?

### ISSUE THREAD

**Issue by lomotos10** [kaist-cp/cs420#107]
At the time of recording the lecture, the member `structs` was absent from `ir::TranlationUnit`. Because of this, it is tricky to infer what this member is for. Especially, why it needs to be separately considered from already existing `decls` member.
For now, the firstmost question I have for the new `ir::TranslationUnit` struct is this: For `struct` declarations and `typedef struct` declarations made in global scope, should both of these structs be added to `ir::TranslationUnit.structs`? Not doing this results in test error, since `interp.rs` checks if name of each `struct` operand is included in `ir::TranslationUnit.structs`.

**Comment by wenko99** [comment]
I believe that, for `struct` declaration, we need to add a mapping to `structs`, and for `typedef struct` declaration, we need to add mappings to both `structs` and `decls`.

<br/>

And an additional question on `structs` in `ir::TranslationUnit` :

I guess `structs` is a map from the name of a struct to its definition. 

I wonder if we have to resolve the actual definition of the structs in our translation. 

When we declare a struct variable in functions, the helper functions in `src/ir/dtype.rs`, `ir::Dtype::try_from_ast_declaration_specifiers` gives a `ir::Dtype::Struct` type with empty definition. Then, I think, when applying helper functions to the `ir::Dtype::Struct` type with empty definition, we pass `structs` as a parameter for the helper function to resolve the actual definition of the empty `ir::Dtype::Struct`. (For example, the `ir::Dtype::get_struct_offset_field` function)

So, when translating a `C` code like below, should the translated `IR` be `1`or `2`?

```c
struct Foo {
    int x;
};

int main() {
    struct Foo foo;
}
```

1. type of `foo` is a `ir::Dtype::Struct` type with empty definition

```
struct Foo : { i32 }

fun i32 @main {
init:
  bid: b0
  allocations: 
    %l0: struct Foo:foo

block b0:
  ret 0:i32
}
```

2. type of `foo` is a `ir::Dtype::Struct` type with its definition resolved

```
struct Foo : { i32 }

fun i32 @main {
init:
  bid: b0
  allocations: 
    %l0: struct Foo:<x:i32>:foo

block b0:
  ret 0:i32
}
```

Thank you in advance!

**Comment by lomotos10** [comment]
Thank you for your comment. Regarding your additional question, while working on this issue, I found this helper function `ir::Dtype::resolve_structs()` that functions similar to `resolve_typedefs()`:
```
    /// If the struct type has a definition, it is saved to the struct table
    /// and transformed to a struct type with no definition.
    pub fn resolve_structs(
        self,
        structs: &mut HashMap<String, Option<Dtype>>,
        tempid_counter: &mut usize,
    ) -> Result<Self, DtypeError> {
```
However, the function crashes when the struct field is empty: e.g. `typedef struct {} a`. Could the TAs clarify on what I am doing wrong in this issue? Thanks in advance.

**Comment by cmpark0126** [comment]
Thank you for the report! We've missed the case when the struct field is empty. I'll fix this issue in the next update.

By the way, you don't need to consider this case anyway. Because empty struct is undefined behavior. The following is from section 6.7.2.1 **Structure and union specifiers** of the C specification:

> If the struct-declaration-list does not contain any named members, either directly or via an anonymous structure or anonymous union, the behavior is undefined.

**Comment by wenko99** [comment]
May I ask for more clarification on the example I posted? 

Executing either codes seems to work fine as long as I have the correct `structs` member for `ir::TranslationUnit`, but I just want to make sure it conforms with the original intention of the `KECC IR`

**Comment by cmpark0126** [comment]
@wenko99 
As you expected, it is okay to leave `ir::Dtype::Struct` as empty when translating.

FYI, here is my IR of the code you mentioned above
```llvm
struct Foo : { i32 }

fun i32 @main {
init:
  bid: b0
  allocations: 
    %l0: struct Foo:foo

block b0:
  ret 0:i32
}
```

**Comment by wenko99** [comment]
@cmpark0126 

Thank you for the clarification!

**Comment by cmpark0126** [comment]
Closing. Feel free to reopen it if you have further questions :)
