### ISSUE TITLE
[Homework 2] Initializer List

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#110]
Now, we have to consider initializer list for HW1 (https://github.com/kaist-cp/cs420/issues/8#issuecomment-616396938)

Should we need to handle initializer list for homework 2 and later?

**Comment by Pusnow** [comment]
Oh, current `ir` implementation directly uses `ast::Initializer`. 
Is it really intended? 
I think KECC should provide IR version of initializer.

https://github.com/kaist-cp/kecc-public/blob/9a2dd840d2f95630edf8b17172ee8e9ccf9552ea/src/ir/mod.rs#L26-L35

**Comment by cmpark0126** [comment]
Thank you for the report! 

As you expected, yes it is intended. I understand what you confused about, but I expect that there will be no problem in proceeding with your homework :)

**Comment by Pusnow** [comment]
Okay, I figured it out.
