### ISSUE TITLE
[HW2] Fuzzer initializes global value with non compile-time constant 

### ISSUE THREAD

**Issue by lomotos10** [kaist-cp/cs420#111]
Creduce on struct.c resulted in this code:
```
typedef struct {
  struct {
    int a[4][5];
  };
} b;
b c;
int (*d)[5] = c.a;
int main() {}
```
After copying the code from the lecture, this would not work, because the initializing value is not a compile-time constant. However, I'm inclined to believe we should handle situations like these because it's so commonly used in C. Any starting tips on handling this situation?

**Comment by cmpark0126** [comment]
Thank you for the report. We've missed this case you mentioned above. Now we work on this issue, and please wait for the next update.

By the way, why not you retry `fuzzer` & `creduce`? Actually, our test case has no like this case. So, I hope you don't spend too much time here.

**Comment by cmpark0126** [comment]
Does this case keep happening?

**Comment by jeehoonkang** [comment]
Closing; feel free to reopen it if the problem continues to happen.
