### ISSUE TITLE
[Homework 2] IR's Typedef

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#113]
I cannot understand what is the main point of IR's Typedef.

If it is part of IR spec, IR interpreter may process it. (not implemented)
If it is not part of IR spec, it may be removed in `enum Dtype`.

So, my question is: when I translate operators, should I let operand's typedef unchanged or resolve it?

**Comment by cmpark0126** [comment]
Thank you for the question. You should translate all expressions after resolving it.

**Comment by cmpark0126** [comment]
Closing. Feel free to reopen it if you have further questions :)
