### ISSUE TITLE
[Homework 2] is_scalar may return true for pointers.

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#114]
In C11 6.2.5 Types, 21. says
> Arithmetic types and pointer types are collectively called scalar types. Array and structure types are collectively called aggregate types.
 
Therfore, `is_scalar` should return for `true` for pointers. ( https://github.com/kaist-cp/kecc-public/blob/3bef06455ea35c39555020fe44fdee496dba402d/src/ir/dtype.rs#L707-L714 )

It's little bit confusing.

**Comment by cmpark0126** [comment]
Thank you for the suggestion. I will fix it soon. Please wait for the next update.

**Comment by cmpark0126** [comment]
We updated the skeleton in this commit: https://github.com/kaist-cp/kecc-public/commit/e81247ba542bf30f0fb4d87a069085d772d6378a#diff-f945d21482e8ffa7e29b8aa7dde99124R721
