### ISSUE TITLE
[HW2] TDD-based approach to do Homework 2

### ISSUE THREAD

**Issue by Ngiong** [kaist-cp/cs420#118]
Hello...

I am just wondering if we are still encouraged to do homework 2 using TDD.
I found that some `write_ir` and `interp` implementation are still in-progress.
Is this implementation going to be given to us in the future?

```rust
todo!(
    "ast::BinaryOperator::WriteOp: write operation for {:?} is needed",
    self
),
```

Currently, my irgen implementation has passed 13 of the given examples (but also skipped 9 examples due to this question).

Honestly, I'm still unsure whether I should wait for the implementation to be completed?
(and start working the next homework (hw3, hw4, ...),
since it probably doesn't depend on the incomplete implementation)

Or should I try to finish the homework 2 first, but without TDD approach?
(and manually compare the IR result with LLVM IR, 
because I think the other students don't feel difficulties like I'm having right now (?))

Thank you very much. I greatly appreciate any information/suggestions you could provide.

p.s.: and sorry, I don't have access to label this issue as `question` :disappointed:

**Comment by cmpark0126** [comment]
Thank you for the question! I fully understand what you wondering :)

1. While some `write_ir.rs` and `interp.rs` implementation are still in progress, there will be no impact in proceeding with the homework. Actually, I've mentioned at https://github.com/kaist-cp/cs420/issues/35#issuecomment-621549319 also. 

    So, please use TDD actively. (FYI, even using TDD, manually compare the IR result with LLVM IR is still needed I think)

2. The part about which homework you do first is up to you. Free to proceed.

P.S. If you interrupted by the `todo!` code you mentioned above, I think it is the case that binary operator is not translated directly manner in KECC and LLVM. Please check carefully what binary operator makes interrupt when you encounter the message and please check how to handle that case in the LLVM.

**Comment by Ngiong** [comment]
I see, okay thank you ^^
