### ISSUE TITLE
assert_supported for FunctionDefinition

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#12]
In KECC, it seems that 
```rust
self.declarations.is_empty();
```
at the 96th line of `src/parse.rs` should be
```rust
assert_eq!(true, self.declarations.is_empty());
```

**Comment by jeehoonkang** [comment]
Thank you for pointing out the mistake.  We'll fix it real soon now.

**Comment by cmpark0126** [comment]
I have fixed this issue with https://github.com/kaist-cp/kecc-public/commit/241a66fcc16a10312d74c82349150274d043e340
