### ISSUE TITLE
[HW2] How to interpret structs without definition

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#122]
Hello!

When using fuzzer it always generates structs with only declaration and no definition:

i.e. for example
```
Struct A;
```
I wonder how it is meant to be translated when we create our translation.
Should we put it in the "structs"-hashmap with "None" as value. Or should we put it in the "structs"-hashmap with value a struct-dtype with empty ("None") fields. Or should we not put it in the structs-hashmap at all (i.e. only as a declaration)?

Br
Jesper Amilon

**Comment by cmpark0126** [comment]
Thank you for the question. 

You should put it `structs` hashmap with `None` as value.

**Comment by christofides** [comment]
Thank you for the answer, I think I get it now. I think my problem was that I also put the struct definitions/declaration in the decls list (as a tip if anyone else is struggling with the same issue).
