### ISSUE TITLE
[HW2] Return of void main function

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#123]
In the lecture video about functions, the professor mentioned that we should always return 0 from the main function, even if the main function is defined as void.

But when I tst  a program using the test file tests/tests_examples.rs (on my computer, ubuntu 18.04) it says that GCC returns some non-zero number.

For example when running this program:
```
void main() {
  int x= 3;
}
```
I get this error:
```
gcc: -54, kecc: 0
thread 'test_examples_irgen' panicked at 'assertion failed: `(left == right)`
  left: `-54`,
 right: `0`', src/tests.rs:118:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
I,e, I return 0 but GCC returns some seemingly random number. I wonder if this is undefined behaviour such that we do not have to consider it or is there some way to infer what "should" be returned for such a program?

Br
Jesper Amilon

**Comment by cmpark0126** [comment]
Thank you for the question. We don't consider the main function whose return type is not compatible with `int`, so you don't need to consider the case you mentioned above.

(FYI)
Since C99, If the return type of the main function is not compatible with `int` (e.g. `void main(void)`), the value returned to the host environment is unspecified. Based on this, we can see that `-54` is an unspecified number. (link: https://en.cppreference.com/w/c/language/main_function)

**Comment by christofides** [comment]
Okey, I see, thanks for good answer!

**Comment by christofides** [comment]
Maybe could be good to mention the reason for asking. When I use fuzzer with --reduce on homework 2 Irgen, the reducer leaves me with this short program:

```
void main() {}
```

**Comment by cmpark0126** [comment]
Our reduce criteria has been configured so that fuzzer don't create such `void main()`: [tests/reduce-criteria-template.sh#L11](https://github.com/kaist-cp/kecc-public/blob/773eeda067f88122b151ed2f25c07a749a748e89/tests/reduce-criteria-template.sh#L11)

Could you check if your `kecc` is up to date?

**Comment by wenko99** [comment]
@cmpark0126 

Actually, I also got 

```c
# 3 "" 3
void main() {}
```

from reducing, while my `kecc` is up to date.

But fuzzing and then reducing again gives a good buggy program :)

**Comment by cmpark0126** [comment]
@wenko99 Thank you for the report. We'll see why this is happening soon.

**Comment by cmpark0126** [comment]
If this problem continues to occur after trying `creduce` several times, please let me know again.

**Comment by cyron1259** [comment]
@cmpark0126 

Hi, I am having the same problem with the reducer.

I have the latest `kecc` and tried fuzzing and reducing multiple times, but it's still producing the same result.

**Comment by cyron1259** [comment]
@cmpark0126 Oh nvm, now it correctly produces `int main(void) {}`.

**Comment by hyunwooj** [comment]
I got this too from fuzzer.

```c
# 1 "" 3
void main() {}
```

My `kecc` is up-to-date.

**Comment by cmpark0126** [comment]
We updated `kecc-public`. Please refer to the latest update: https://github.com/kaist-cp/kecc-public/commit/62c52086311c5b9964b74bb83dc668ef43283890

If the same problem occurs again, please reopen this issue.
