### ISSUE TITLE
[HW2] Fuzzer skips test

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#126]
When running the fuzzer for homework 2, I seem to pass all tests that are generated. However, sometimes it seems as generated code is skipped. For example, when running the fuzzer 100 times, it skipped 5 tests.

Im just curious what it means that a test is skipped and does it mean that my code do not pass the test?

Br
Jesper

**Comment by cmpark0126** [comment]
We just skip when encountering the cases below:
1. Fail to compile with `gcc`,
2. Executable file compiled with `gcc` runs 500ms or more,
3. Failed to get exit code from executable file compiled with `gcc`,
4. KECC interpreter runs 60 sec or more.

The above cases are not suitable for grading homework within a limited time, so we skip them.

**Comment by christofides** [comment]
Ok, I see, thx for answer!
