### ISSUE TITLE
[Homework 2] Pointer comparison

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#127]
When comparing two pointers, KECC(interpreter) does not check offset of them.

https://github.com/kaist-cp/kecc-public/blob/773eeda067f88122b151ed2f25c07a749a748e89/src/ir/interp.rs#L647-L655

Why is it enough to compare?

**Comment by cmpark0126** [comment]
Oh! Thank you for the report. It's obviously our mistake. We'll fix it ASAP.

FYI, you don't have to worry about this part because it doesn't affect the grading.

**Comment by cmpark0126** [comment]
We updated the skeleton in this commit: https://github.com/kaist-cp/kecc-public/commit/e81247ba542bf30f0fb4d87a069085d772d6378a#diff-68fdd6657b57178736d09f2f77b3b5b3R647
