### ISSUE TITLE
A timeout from fuzz.py

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#13]
In KECC, if one has not built the binary in the release mode before running the fuzzer, the fuzzer results in a timeout since it tries to build the binary in 10 seconds. I believe that to solve the issue, it would be better to add
```python
subprocess.Popen(["cargo", "build", "--release"]).communicate()
```
at the 105th line before
```python
for i in iterator:
```
in `tests/fuzz.py` or to revise the file similarly.

**Comment by jeehoonkang** [comment]
Thank you for raising a concern.  We're fixing it real soon now.

**Comment by cmpark0126** [comment]
I have fixed this issue with https://github.com/kaist-cp/kecc-public/commit/241a66fcc16a10312d74c82349150274d043e340
