### ISSUE TITLE
[HW2] How to use Godbolt Properly?

### ISSUE THREAD

**Issue by Ngiong** [kaist-cp/cs420#130]
Hi,

Can I ask how to use the godbolt.org so that I can get similar result with our KECC's unoptimized IR?
Or is it not possible?

I tried to use x86-64 clang 10.0.0 with argument `-emit-llvm -O0` but I can't get similar result with our IR. 

Thank you.

**Comment by Ngiong** [comment]
Or, is it possible for us to get the IR solutions for each C program in the `examples` folder (just like in HW3, so that we can compare the input & output for each program)?

I think this will totally helpful for us :sob: :sob:

**Comment by cmpark0126** [comment]
Thank you for the question. 

1. I expect that in most cases, LLVM IR is similar to KECC IR. Could you attach your specific example?

2. Thank you for the suggestion. We will update KECC IR example for each c program in the `examples/c` folder. Please wait for the next update.

**Comment by Ngiong** [comment]
Hello,

1. Sometimes I'm confused regarding `dtype` result of each instruction, which is not provided in LLVM IR (cmiiw)

```c
int main() {
    int a[2][2] = {{1,2},{3,4}};
    return a[0][0];
}
```

```
fun i32 @main {
init:
  bid: b0
  allocations: 
    %l0:[2 x [2 x i32]]:a

block b0:
  %b0:i0:*[2 x i32] = getelementptr %l0 offset 0
  %b0:i1:*i32 = getelementptr %b0:i0 offset 0
  %b0:i2:i32 = typecast 1:i32 to i32
  %b0:i3:unit = store %b0:i2:i32 %b0:i1:*i32
  %b0:i4:*i32 = getelementptr %b0:i0 offset 1
  %b0:i5:i32 = typecast 2:i32 to i32
  %b0:i6:unit = store %b0:i5:i32 %b0:i4:*i32
  %b0:i7:*[2 x i32] = getelementptr %l0 offset 1
  %b0:i8:*i32 = getelementptr %b0:i7 offset 0
  %b0:i9:i32 = typecast 3:i32 to i32
  %b0:i10:unit = store %b0:i9:i32 %b0:i8:*i32
  %b0:i11:*i32 = getelementptr %b0:i7 offset 1
  %b0:i12:i32 = typecast 4:i32 to i32
  %b0:i13:unit = store %b0:i12:i32 %b0:i11:*i32
  %b0:i14:*[2 x i32] = getelementptr %l0 offset 0
  %b0:i15:[2 x i32] = load %b0:i14:*[2 x i32] **<< here's the buggy line**
  %b0:i16:*i32 = getelementptr %b0:i15 offset 0
  %b0:i17:i32 = load %b0:i16:*i32
  %b0:i18:i32 = typecast %b0:i17:i32 to i32
  ret %b0:i18:i32

block b1:
  ret 0:i32
}
```

Here's the LLVM's IR (with non-constant value as you suggested [here](https://github.com/kaist-cp/cs420/issues/117#issuecomment-625056606)
```llvm
define dso_local i32 @main() #0 !dbg !7 {
  %1 = alloca i32, align 4
  %2 = alloca i32, align 4
  %3 = alloca [2 x [2 x i32]], align 16
  store i32 0, i32* %1, align 4
  call void @llvm.dbg.declare(metadata i32* %2, metadata !12, metadata !DIExpression()), !dbg !13
  store i32 1, i32* %2, align 4, !dbg !13
  call void @llvm.dbg.declare(metadata [2 x [2 x i32]]* %3, metadata !14, metadata !DIExpression()), !dbg !18
  %4 = getelementptr inbounds [2 x [2 x i32]], [2 x [2 x i32]]* %3, i64 0, i64 0, !dbg !19
  %5 = getelementptr inbounds [2 x i32], [2 x i32]* %4, i64 0, i64 0, !dbg !20
  %6 = load i32, i32* %2, align 4, !dbg !21
  store i32 %6, i32* %5, align 4, !dbg !20
  %7 = getelementptr inbounds i32, i32* %5, i64 1, !dbg !20
  store i32 2, i32* %7, align 4, !dbg !20
  %8 = getelementptr inbounds [2 x i32], [2 x i32]* %4, i64 1, !dbg !19
  %9 = getelementptr inbounds [2 x i32], [2 x i32]* %8, i64 0, i64 0, !dbg !22
  store i32 3, i32* %9, align 4, !dbg !22
  %10 = getelementptr inbounds i32, i32* %9, i64 1, !dbg !22
  store i32 4, i32* %10, align 4, !dbg !22
  %11 = getelementptr inbounds [2 x [2 x i32]], [2 x [2 x i32]]* %3, i64 0, i64 0, !dbg !23
  %12 = getelementptr inbounds [2 x i32], [2 x i32]* %11, i64 0, i64 0, !dbg !23
  %13 = load i32, i32* %12, align 16, !dbg !23
  ret i32 %13, !dbg !24
}
```

My instruction is similar with LLVM's IR, but sadly (:sob: :sob:)
the interpreter rejects it because `'pointer' must be 'Value::Pointer' to access memory`

Also, yesterday I got stuck because our KECC provides 1-sized integer (boolean), while AFAIK C program doesn't provide boolean (but thank God it has been resolved today)

2. Great! Thank you very much.

**Comment by Ngiong** [comment]
Additional answer to Q1:

And I think even though I've put -O0 as clang's argument, they still do optimization (while our KECC do not)
```c
int main() {
    return 1+2;
}
```

```llvm
define dso_local i32 @main() #0 !dbg !7 {
  %1 = alloca i32, align 4
  store i32 0, i32* %1, align 4
  ret i32 3, !dbg !12
}
```

**Comment by cmpark0126** [comment]
We uploaded the IR examples in this commit: https://github.com/kaist-cp/kecc-public/commit/e81247ba542bf30f0fb4d87a069085d772d6378a. I expect this update will help you to resolve the Q1 also.

**Comment by cmpark0126** [comment]
>Additional information for Q1:

Thank you for pointing out that. We'll fix it.

By the way, you don't have to worry about this part because it doesn't affect the grading.
