### ISSUE TITLE
Questions about domination (Q&A)

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#131]
Hello, I have 2 questions that could be suitable for Q&A,

Question 1:
I have a question about the definition for Dom(X). In the beginning it is defined as:
Dom(B) = {A | A dominates B}.

However, when used to define the dominance frontier, it seems as Dom(B) defines the set of nodes that is dominated by set B, i.e. Dom(B) = {A | B dominates A}. I wonder if there are 2 different definitions used or if I have misunderstood something?

Question2:
I also have a further question about the definition of the dominance frontier. In the lecture video, it is described that Y is in the dominance frontier of X if all of its predecessors are dominated by X. Would this not automatically mean that Y is also dominated by X (i.e. it should be that some predecessor of Y is dominated by X, but not all)?

**Comment by jeehoonkang** [comment]
- Answer 1: oh sorry, I was confused.  Let's say the latter is the right definition from now on: dom(A) = {B | A dominates B}.

- Answer 2: oh sorry again, I was confused again.  B in DF(A) if A does not dominate B; and **there exists a predecessor C of A** such that [A=C or A dominates C].  "For all predecessors" is wrong: "ther exists a predecessor" is right.

Sorry for confusions.  I'll correct it soon.

**Comment by jeehoonkang** [comment]
I changed my mind: let's say dom(B) = [the set of B's dominators] = {A | A dominates B}.  I updated the slides.  Sorry again for confusion.

**Comment by jeehoonkang** [comment]
Hope everything is clarified; if not, please feel free to reopen it!
