### ISSUE TITLE
[Homework 2] `struct` / `typedef` name resolution

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#134]
In the video, prof only mantains single `structs` / `typedefs` `HashMap`.

However, I think we should maintain a list of struct / typedef tables to obtain correct struct / type. (see below)

Am I right?

And, `resolve_typedefs`, `resolve_structs` may be changed to support vector of hashmap.

```c
#include <assert.h>

typedef short TempInt;
struct TempStruct
{
    short a;
};

int main()
{
    {
        struct TempStruct
        {
            long a;
        };
        typedef long TempInt;
        assert(sizeof(TempInt) == 8);
        assert(sizeof(struct TempStruct) == 8);
    }
    assert(sizeof(TempInt) == 2);
    assert(sizeof(struct TempStruct) == 2);

    return 0;
}
```

**Comment by wenko99** [comment]
Hi, I believe such case is not supported in `KECC`.

According to [src/c/parse.rs#L299-336](https://github.com/kaist-cp/kecc-public/blob/773eeda067f88122b151ed2f25c07a749a748e89/src/c/parse.rs#L299-L336),

I think typedef / struct definition is only allowed in External Declarations. :-)

**Comment by Pusnow** [comment]
@wenko99 Oh, you are right. Thanks.
