### ISSUE TITLE
[Homework 2] How to run arbitrary C or IR code?

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#136]
Is there an option to run arbitrary C or IR code using the KECC interpreter?

**Comment by cmpark0126** [comment]
We've added `irrun` option to run arbitrary C or IR code using the KECC interpreter. Please refer to the latest update: https://github.com/kaist-cp/kecc-public/commit/e81247ba542bf30f0fb4d87a069085d772d6378a

**Comment by Pusnow** [comment]
Thank you for the update.
