### ISSUE TITLE
[Hw2] broken code after merge

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#141]
Hi. I recently merged the past 2 updates to the upstream, as I wanted to at least make my code compile before dealing with the changes to the upstream.
However, after merging the changes, a lot of the ir methods (try_from, resolve_typedefs, etc.) are returning signature mismatches, like "this function takes 2 arguments but 1 argument was supplied".
This problem didn't exist before, and most of the code with these errors are same as the lecture video.
Has there been a large change in the function signatures? If so, what arguments were added? I can't see the cargo docs for IR as I currently cannot build my program.

**Comment by KunJeong** [comment]
Actually, I just found out that all the problems were generated from the 'structs' in IR. 
https://github.com/kaist-cp/cs420/issues/107#issue-611267491
I guess this issue addresses the 'structs' member, but I don't understand most of it as I seem to lack the basic understanding of what the member is for.
Could you please explain about the role of 'structs' in IR?

**Comment by cmpark0126** [comment]
I expect the below explanation helps you understand why `structs` needed in our IR:

1. KECC stores all of the pre-declared struct types in 'structs'.
2. When a struct type variable is declared, struct type's 'name' is 'Some' and 'field' is 'None', and KECC assumes the actual definition is stored in 'structs'.
    - Please refer to below example code
    ```c
    // Declare global variable 'var'
    struct A {
        int member1;
        int member2;
    } var;
    ```
    ```rust
    `structs`: {'A': ir::Dtype::Struct{
                       name: Some('A'),
                       fields: Some({member1: i32, member2: i32})
                       ...
                     }
                }
    `var`: {'var': ir::Declaration::Variable{
                     dtype: ir::Dtype::Struct{
                              name: Some('A'),
                              // actual definition is stored in 'structs'.
                              fields: None, 
                              ...
                            }
                   }
           }
    ```
3.  When you need a struct type definition (e.g., when supporting `ast::MemberOperator`),  you can find and use it in `structs`. 

If you have further questions related to this issue, feel free to ask.

**Comment by cmpark0126** [comment]
Closing. Feel free to reopen it if you have further questions :)
