### ISSUE TITLE
[Hw2] try_from for Initializer

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#142]
Hi. First, let me apologize if this late-night issue wakes anyone. I found it urgent as I need to finish as much of hw2 as possible within the week.

I've watched the hw2 code videos countless times upto the point that I'm quite confident I have made no mistakes.

Some of the code from the video require updates for upstream changes, sure, I get that. Most of those changes were fixed quite easily.

However, there was one error that I couldn't seem to fix, and I'm pretty sure it existed before the upstream merge:
```rust
if let Some(initializer) = init_decl.node.initializer.as_ref() {
    let value = ir::Constant::try_from(&initializer.node).map_err(|_| {
        IrgenError::new(
            source.write_string(),
            IrgenErrorMessage::Misc {
                message: "initializer element is not a compile-time constant"
                    .to_string(),
            },
        )
    })?;
````

I've read through the documentations on `Try_From`, and have a good idea of what it does. 
I'm also pretty sure there is no such implementation of `try_from` for these datatypes(initializer -> constant) in our IR code.
Am I supposed to implement my own in the IR..?(I hope not..) If not, has it been deleted in an upstream change?(if so, why??) Or is it another just an intended error in the original code that I should find out how to fix on my own?

I thought `ir::Value::try_from_initializer` would be the solution but it seems it cannot be used because it's a private associated function.

I would really appreciate some help. Thank you.

**Comment by KunJeong** [comment]
I found the commit that deleted the particular helper function, and figured out the solution based on what changed in the commit.

Could you consider providing a more detailed commit message for breaking changes in the future? I'm totally fine with skeleton improvements but it's quite difficult to look through the whole commit history to find which commit broke my code 😥

**Comment by cmpark0126** [comment]
Sorry for the inconvenience. 

From now on, I will try to check the factors that could cause errors in the students' code more strictly and notify them in advance.

**Comment by KunJeong** [comment]
Thank you so much.

**Comment by junsooo** [comment]
Could you give some kind of hint for this problem? 
There are many commits added after this question raised, so I think it is hard to find the exact commit which deleted helper function.

**Comment by junsooo** [comment]
Thank you.
I imitated the behavior of erased helper function and it worked.
