### ISSUE TITLE
[Rust] collecting into slices

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#145]
Hi. I'm having some trouble with rust slices.
In the model code for HW2, translate_parameter_decl takes the argument `parameters` of type `&[String]`
I recognized this as a slice type, and I was trying to implement the `name_of_params_from_function_declarator` to return the same type, but I encountered some trouble along the way.

Since everything in the C AST is defined as a vector, I am looking for a way to
1. iterate over a vector
2. map with a function that returns a String
3. collect the results in to a &[String]

While 1 and 2 are simple, I cannot find a way to do 3. (I've done a lot of searching and reading through the docs, but there seems to be no `append`-like method to slices nor a `collect` that can collect an iterator into a slice. I did find the crate `collect_slice` that seems to do the job, but I'm unsure if we can use external libraries)
Based on my experience from other functional languages, I've tried fold as well but it seems it expects the initial slice and the resulting slice to have the same type `&[_; 0]`, which means the same size as well.
As an alternate solution, I could change all the slices in the code into vectors, but I'm not confident about the differences between slices and vectors and thus unsure.

So I guess my question is
1. is there an efficient way to do 3?
2. ~~if not, can I use an external crate?~~ -> Edit: I guess not since modifications to `cargo.toml` won't be included in the submission
3. ~~finally, is there a specific reason that this part of the code defined as a slice?~~ -> Edit: answered below
Thank you.

**Comment by codingskynet** [comment]
From the professor code,
```
...
Dtype::try_from_ast_declaration_specifiers(&declaration.specifiers) ...
```
The parameter of function is `specifiers: &[Node<ast::DeclarationSpecifier>]`,
but as you know `&declaration.specifiers` is `Vec<Node<ast::DeclarationSpecifier>>`.
So, I think we should not change it into slices.

**Comment by KunJeong** [comment]
@codingskynet Oh yeah you're right. I guess that answers the last question, thanks.

**Comment by jeehoonkang** [comment]
Regarding 3.: the following works:

```rust
fn foo(_args: &[usize]) {}

let v = vec![0usize, 1, 2];
foo(&v);
```

In short, `&Vec<T>` can be automagically converted to `&[T]`.  See https://doc.rust-lang.org/stable/std/ops/trait.Deref.html and https://doc.rust-lang.org/std/vec/struct.Vec.html#deref-methods .

**Comment by KunJeong** [comment]
Wow that's quite amazing. Thanks you!
