### ISSUE TITLE
[HW2] Handling typedef not defined struct

### ISSUE THREAD

**Issue by codingskynet** [kaist-cp/cs420#146]
On fuzzer, I found that the below code is a problem on my compiler:
```
struct a;
typedef struct a B;

int main() {}
```
It can be compiled well on gcc, but this produces a problem on my compiler:
```
error: variable has incomplete type 'struct a'
```
I think this is caused by `resolve_structs`:
```
...
if struct_type.is_none() {
    return Err(DtypeError::Misc {
        message: format!("variable has incomplete type 'struct {}'", name),
    });
}
...
```

This side case is allowed on our compiler? Or, what can I do for resolving this problem?

**Comment by codingskynet** [comment]
I can resolve it by removing the previous code from dtype.rs.
Is it really a solution?

**Comment by scturtle** [comment]
My workaround is skipping `resolve_structs` if `field` is empty.

**Comment by codingskynet** [comment]
@scturtle Oh, I don't think the solution. Thank you!
