### ISSUE TITLE
[HW2] Is interpreter wrong for integer overflow?

### ISSUE THREAD

**Issue by scturtle** [kaist-cp/cs420#149]
C:
```c
typedef signed char int8_t;
int main() {
    int8_t a = 88, b = 9;
    return (int8_t)(a * b) == 24;
}
```

IR:
```llvm
fun i32 @main {
init:
  bid: b0
  allocations:
    %l0:i8:a
    %l1:i8:b

block b0:
  %b0:i0:i8 = typecast 88:i32 to i8
  %b0:i1:unit = store %b0:i0:i8 %l0:*i8
  %b0:i2:i8 = typecast 9:i32 to i8
  %b0:i3:unit = store %b0:i2:i8 %l1:*i8
  %b0:i4:i8 = load %l0:*i8
  %b0:i5:i8 = load %l1:*i8
  %b0:i6:i8 = mul %b0:i4:i8 %b0:i5:i8
  %b0:i7:i32 = typecast %b0:i6:i8 to i32
  %b0:i8:u1 = cmp eq %b0:i7:i32 24:i32
  %b0:i9:i32 = typecast %b0:i8:u1 to i32
  ret %b0:i9:i32

block b1:
  ret 0:i32
}
```

Interpreter output: 0
GCC output: 1

**Comment by thecasterian** [comment]
Refer to C11 6.3.1.3:
> Otherwise, the new type is signed and the value cannot be represented in it; either the result is implementation-defined or an implementation-defined signal is raised.

Therefore, the result of expression `(int8_t)(a * b)` depends on the implementation; either 0 or 1 is OK.

**Comment by wenko99** [comment]
I think `integer promotion` will take care of this issue!

i.e, before multiplying the load results, they should first be promoted to integers.

And Here's a tip that elaborates on this issue: #106
