### ISSUE TITLE
Mem2Reg - undef in test case

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#152]
Hello, in the example test case for mem2reg (i.e. mem2reg.input.ir) there are two functions (single_block and multi_block) where the first block loads from a variable which has no assigned value yet. I just wanted to ask if it is intended to test this undef case or if it would be better to first store some value into the variable before loading it. 

For example, the function single_block looks like this in the given input file:
```
fun i32 @single_block {
init:
  bid: b0
  allocations:
    %l0:i32:x

block b0:
  %b0:i0:i32 = load %l0:*i32

  %b0:i1:unit = store 42:i32 %l0:*i32
  %b0:i2:i32 = load %l0:*i32

  %b0:i3:unit = store 37:i32 %l0:*i32
  %b0:i4:i32 = load %l0:*i32

  %b0:i5:unit = call @sink(%b0:i0:i32)
  %b0:i6:unit = call @sink(%b0:i2:i32)
  %b0:i7:unit = call @sink(%b0:i4:i32)

  ret 0:i32
}
```
And it is translated into this in the given output file, where the parameter of the first function call to sink now is deemed as undefined.
```
fun i32 @single_block {
init:
  bid: b0
  allocations:
    %l0:i32:x

block b0:
  %b0:i0:unit = nop

  %b0:i1:unit = nop
  %b0:i2:unit = nop

  %b0:i3:unit = nop
  %b0:i4:unit = nop

  %b0:i5:unit = call @sink(undef:i32)
  %b0:i6:unit = call @sink(42:i32)
  %b0:i7:unit = call @sink(37:i32)

  ret 0:i32
}
```

Br
Jesper Amilon

**Comment by jeehoonkang** [comment]
Hi, it's expected.  If you're reading from an uninitialized memory location, it should be `undef`, and your `mem2reg` should take this into account.

**Comment by christofides** [comment]
Okey, then I see what I should fix :).
Thanks for answer!
