### ISSUE TITLE
Typecast to bool

### ISSUE THREAD

**Issue by hyunwooj** [kaist-cp/cs420#153]
Here is C code in question
```c
int a;
int main() {
  if (6)
    --a;
  return a;
}
```
and my IR
```
var i32 @a = default

fun i32 @main {
init:
  bid: b0
  allocations: 


block b0:
  %b0:i0:u1 = typecast 7:i32 to u1
  br %b0:i0:u1, b1(), b2()

block b1:
  %b1:i0:i32 = load @a:*i32
  %b1:i1:i32 = sub %b1:i0:i32 1:i32
  %b1:i2:unit = store %b1:i1:i32 @a:*i32
  j b3()

block b2:
  j b3()

block b3:
  %b3:i0:i32 = load @a:*i32
  ret %b3:i0:i32

block b4:
  ret 0:i32
}
```
My irgen generates typecast ir to typecast 6 In the if-condition expression to bool. I expected that 6 would be converted to 1 because 6 is not zero and estimated as true. However, it seems that it is converted 0 and estimated false. Replacing 6 with 7 produces the expected result though. So I guess typecast ir just drops left bits except for the right most bit. Is it correct? If so, should I compare 6 with zero to make it bool type? What if the expression is float?

**Comment by jeehoonkang** [comment]
- Yes, compare `value` with 0 for `(bool) value`.
- You can compare `f_value` with `0.0` for `(bool) f_value`.

**Comment by hyunwooj** [comment]
Thanks!
