### ISSUE TITLE
[HW2] Question regarding the unsupported BinaryOperators

### ISSUE THREAD

**Issue by zoonoo** [kaist-cp/cs420#157]
While implementing HW2, I get the following IR for `simple_for.c`.

```
; IR for simple_for.c

define i32 @main() {
init:
  bid: b0
  allocations: 
    %l0:i32:i
    %l1:i32:sum

block b0
  %b0:i0:unit = store 0:i32 %l1:i32*
  j b1([])

block b1
  %b1:i0:i32 = load %l0:i32*
  %b1:i1:i32 = assign %b1:i0:i32 0:i32
  j b2([])

...
...
...
...
block b6
}

```

In block b1, I have `assign` operator, which is not implemented in `calculate_binaary_operator_expression` in `ir/interp.rs`.

In this IR assign operator is supposed to assign 0 for the variable `i` as I understand it.

I presume that I'm missing something in the implementation of irgen, but could you explain why the method does not support assign operator, and what should be done in the irgen implementation to replace it?

**Comment by codingskynet** [comment]
I think why these operators are not implemented is that these operators can be implemented by the combination of other operators. For example, the assign operator in your code can be implemented to:
```
%b1:i1:unit = store 0:i32 %l0:i32*
```
Also, other operators like LogicalAnd, AssignPlus can be implemented by BitwiseAnd(or branch), Plus and Assign(Store operation).

**Comment by zoonoo** [comment]
@codingskynet 
Oh right, so I guess I would have to convert those cases in `translate_binary_op`.
Thank you!
