### ISSUE TITLE
 Printing the ir output for simplify_cfg and mem2reg

### ISSUE THREAD

**Issue by umartaufiqul** [kaist-cp/cs420#158]
I am currently trying to debug my code for simplfy_cfg. However, I can only check it correctness by using "cargo test test_examples_write_c", and there seems to be an error in the output ir, the test is stuck in loop. 
Is there anyway to just print out the output ir without interpreting them? If yes, I would also like to know if the option is also available for mem2ref

**Comment by cmpark0126** [comment]
Please try to use `--iroutput` and `--simplfy_cfg` (or `mem2reg`) simultaneously.

(e.g., `cargo run -- --simplify-cfg --iroutput examples/simplify_cfg/const_prop.input.ir`)

**Comment by umartaufiqul** [comment]
That's very helpful. Thank you.
