### ISSUE TITLE
Error for ssh connection with vscode, and its solution

### ISSUE THREAD

**Issue by KAIST-JongchanPark** [kaist-cp/cs420#16]
I'm using Window 10, Vscode 1.43.1

For me, I have successful ssh connection with cmd, by instruction of README.
However, with vscode, it doesn't work with instuction of README and provided youtube lecture.
(Retry connection so many times when I connect to server with vscode.)

I suffered from this issue for lots of time and I want to share for everyone who has same issues.

The solution is below.

This is an open issue in VSCode Remote-SSH version 0.50.0. See Issue #2527.

The way I resolved it was to downgrade to version 0.49.0.

In VSCode, Ctrl+Shift+X to open extensions
Click the Manage icon next to the Remote - SSH extension
Click Install Another Version... from the options
Select the version to install (0.49.0)
I also recommend disabling the Extensions Auto Update in settings so this type of thing doesn't happen in the future with this or any other extensions.

(Solution From https://stackoverflow.com/questions/60642938/vscode-v1-43-remote-ssh-cannot-connect-v1-42-works)

**Comment by GetRusty** [comment]
Thanks!
I had a similar issue, for having problems only connecting via VSCode, but downgrading versions didn't help, so I reinstalled vscode server on the remote. 
[https://code.visualstudio.com/docs/remote/troubleshooting#_cleaning-up-the-vs-code-server-on-the-remote](url)

**Comment by cmpark0126** [comment]
Thank you for the Information!

I close this issue. If someone has further discussion about this issue, feel free to reopen it. Thanks!
