### ISSUE TITLE
[Homework 7] Assembly generation (due: 8th of July)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#160]
- For homework 7, implement assembly generation: https://github.com/kaist-cp/kecc-public/blob/master/src/asmgen/mod.rs  Given an IR AST, you should generate a RISC-V assembly AST.

- The forthcoming lecture videos will explain how to do this work.

- The purpose of this homework is to generate a correct assembly, not to generate an efficient assembly.  Generating efficient assembly (register allocation, in particular) will be the topic of the CS420 performance competition (which will be announced soon).  For this homework, please do whatever you can to generate a correct assembly.  It's still not super easy.

- While it is due on the 8th of July, I strongly recommend you to start as early as possible.  We will enjoy other pieces of homework at the later stage of the semester.

- The grading scheme is simple: you either implement a complete asmgen or not.  You can submit your code multiple times.  Grader will be provided.  You can grade your submission yourself by running, e.g., `cargo test --release test_examples_asmgen`.  (IMPORTANT: it'll be updated.)

- Submit your `asmgen/mod.rs` to https://gg.kaist.ac.kr (TBA).

**Comment by jeehoonkang** [comment]
We just updated the skeleton code.  It's not yet fully done, as `asm/mod.rs` misses a few instructions, but I hope it'll be a solid ground for you to start working on homework 7.

Further, `cargo test test_examples_asmgen` now assumes you have a good irgen.  We will fix this soon.

**Comment by jeehoonkang** [comment]
I'm happy to declare that homework 7 is the last homework (except for the final project #168).

**Comment by jeehoonkang** [comment]
The skeleton is updated, and now `cargo test test_examples_asmgen` will partially test your asmgen.

*IMPORTANT*: the test will be updated to consider more examples.

**Comment by jeehoonkang** [comment]
You don't need to observe the calling convention for homework 7.

**Comment by jeehoonkang** [comment]
The ["small" grader](https://gg.kaist.ac.kr/assignment/15/) and the ["large" grader](https://gg.kaist.ac.kr/assignment/14/) are now available at gg.kaist.ac.kr.  Please submit your code.

IMPORTANT: the graders are updated.  Please see [kecc-public](https://github.com/kaist-cp/kecc-public).

**Comment by cmpark0126** [comment]
**IMPORTANT**: We just nullified the existing submissions of homework 7 to gg.kaist.ac.kr due to #270.

Please resubmit your solution. Sorry for the inconvenience.

**Comment by cmpark0126** [comment]
**IMPORTANT**: Due to #270, you must follow the naming convention of the label below:

```c
int nonce; // global variable
int main() { ... } // function
```
```
        .globl  main
        .section        .text
        .type   main, @function
main:                                        # label of function
        ...
        .globl  nonce
        .section        .data
        .type   nonce, @object
nonce:                                       # label of global variable
        .word   0x0
```

**Comment by jeehoonkang** [comment]
- You can submit the final project to gg now: https://gg.kaist.ac.kr/assignment/16/
- It's running on a RISC-V machine: [SiFive HiFive Unleashed](https://www.sifive.com/boards/hifive-unleashed) running Linux
