### ISSUE TITLE
[HW2] What is the role of `convert_array_to_pointer` method?

### ISSUE THREAD

**Issue by zoonoo** [kaist-cp/cs420#161]
In `translate_expr_rvalue`, I understand that we need additional parsing of the operand to handle variables pointing to array.

But what exactly does this method do to the operand? I imagined that it would change the dtype of the operand ptr like the following : 

```
Pointer { inner: Array { inner: Int { width: 32, is_signed: true, is_const: false }, size: 5 }, is_const: false }
-->
Pointer { inner: Int { width: 32, is_signed: true, is_const: false }, is_const: false }
```

My implementation is wrong, as it interprets `p[i]` of `array.c` as strange values that looks like pointer address (`Int { value: 50462976, width: 32, is_signed: true }`. Has anyone encountered similar problems?

```
block b4
  %b4:i0:i32 = load %l2:i32* // result = 0
  %b4:i1:i32* = load %l1:i32** //  p[]
  %b4:i2:i32 = load %l3:i32* // i == 0, 1, 2, 3, 4
  %b4:i3:i32* = getelementptr %b4:i1 offset %b4:i2
  %b4:i4:i32 = load %b4:i3:i32* // //  loads strange values : Int { value: 50462976, width: 32, is_signed: true }
  %b4:i5:i32 = add %b4:i0:i32 %b4:i4:i32   ;  
  %b4:i6:unit = store %b4:i5:i32 %l2:i32*
  j b3([])

```

**Comment by junsooo** [comment]
I also have question for role of convert_array_to_pointer.
So, Is this statement from question correct?(Just change Array to Int is OK?)
```
But what exactly does this method do to the operand? I imagined that it would change the dtype of the operand ptr like the following :

Pointer { inner: Array { inner: Int { width: 32, is_signed: true, is_const: false }, size: 5 }, is_const: false }
-->
Pointer { inner: Int { width: 32, is_signed: true, is_const: false }, is_const: false }
```

@minseongg

**Comment by minseongg** [comment]
@junsooo Yes. The role of `convert_array_to_pointer` function is changing the type of operand from `[T; N]*` to `T*`.

**Comment by junsooo** [comment]
Hello, now i'm implementing array part. 
I have question about translate_initializer. On video, i saw that initializer for list is not supported like this:
Initializer::List(_) => panic!("Initializer::List is not supported"),
But what i'm thinking is, we have to implement logic for each List's item, recursively call translate_initializer to support List initializer. Is it true? Or is there any suitable place to translate initializer for array?

**Comment by minseongg** [comment]
> But what i'm thinking is, we have to implement logic on translate_expr_rvalue for each List's item, recursively call translate_initializer to support List initializer. Is it true?

Yes. You need to modify the code in the video to support List initializer.

**Comment by junsooo** [comment]
I have question for list initializer.
1. So, to initialize array, i wanted to add logic for insert_instruction on translate_initializer with GetElementPtr. But GetElementPtr needs ptr for left side of array(for example int a[5]), which is made on self.translate_alloc which is after translate_initializer.
If i alloc_tempid() on initializer, the result is different with solution ir. So how can i solve this problem?

Also, If i make new ir::Operand::constant, it doesn't have constant for pointer or array. So i have to make ir::Operand::Register for array in translate_initializer. But it needs ptr for argument. But that ptr is also made on translate_alloc, and translate_alloc needs the initialized array value. I think it is somekind of cycle. how can i solve this problem?

**Comment by minseongg** [comment]
You can allocate local variables without initial value. (In video https://youtu.be/jFahkyxm994?t=1163, `translate_alloc` takes `Option<ir::Operand>` as initial value. `None` means there is no initial value.)

I think these problems can be solved by first allocating a local variable without initial value and then modifying its value.
