### ISSUE TITLE
cargo.toml build fail

### ISSUE THREAD

**Issue by zzanggu9399** [kaist-cp/cs420#162]
![스크린샷 2020-05-30 오후 5 02 35(2)](https://user-images.githubusercontent.com/48054186/83323108-a0d07980-a297-11ea-8f7b-c17d28ad6785.png)

안녕하세요 과제를 하고있는 수강생입니다. 지금까지 과제를 하면서 이 에러가 뜨는게 당연하다고 여기고 있었는데 다른 친구들이나 인터넷을 찾아보니 이 에러는 없고 코딩을 하는 과정에서 에러가 생기는게 맞다고 하더라구요... 이 에러를 어떻게 해결할 수 있을까요?

**Comment by jeehoonkang** [comment]
제가 추측하기로는 dependency 버전 문제일 것 같습니다.  Upstream change 머지하시고 (`git fetch origin && git rebase origin/master`) `cargo update` 하시고 다시 시도해보세요.

**Comment by zzanggu9399** [comment]
그래도 여전히 저 상태입니다.... 처음부터 아예 다 삭제하고 다시 git clone을 해도 저 상태인데 무엇이 문제일까요...

**Comment by jeehoonkang** [comment]
- 숙제 하신 버전 말고 `kecc-public` 그대로 받아서 해도 위 에러가 뜨나요?
- 만일 아니라면 숙제하시다가 뭔가를 잘못 건드리신 것 같습니다.  Git binary search를 통해 문제를 찾아보시길 권해드립니다.
- 만일 그렇다면 학번 이메일로 보내주시면 좀 살펴보겠습니다.

**Comment by zzanggu9399** [comment]
네 kecc public을 다시 클로닝 해와도 에러가 뜨네요....메일 드렸습니다

**Comment by zzanggu9399** [comment]
20170364입니다 교수님 감사합니다

**Comment by jeehoonkang** [comment]
- 저도 reproduce 했습니다.
- 그런데 보니까 개발하는데 크게 지장은 없어보입니다.  위 에러가 떠도 그냥 무시하고 개발하면 될 것 같아요
- 혹시나 해서- vscode 최신버전으로 한번 업데이트해보세요.

**Comment by zzanggu9399** [comment]
네 감사합니다 교수님 그러나 여전히 되지 않네요... 서버에 새로생긴 kecc-public-clean 버전에서 또한 에러가 생기네용... 신경써주셔서 감사합니다..
