### ISSUE TITLE
[HW1] fuzz issue with local environment

### ISSUE THREAD

**Issue by zzanggu9399** [kaist-cp/cs420#165]
I had perfectly same issue with this issue #133  after I moved my code environment from Linux server to Local Mac OS. Everything without this fuzz are same between online server and local ...

How can I fix it? I tried ```cargo run -- -p tests/test_polished.c ``` but I don't know why this error occurred. 

```thread 'main' panicked at 'assertion failed: struct_type.node.declarations.is_none()', src/c/parse.rs:325:33```

온라인 서버에서는 되는데 로컬에서는``` python3 tests/fuzz.py --print``` 가 위의 #133 과 똑같은 오류가 납니다... 제가 뭘 놓치고 있는걸까요?

p.s) I already finished HW1, but after I moved the code to local repository, I post this issue  because it bothers me. Is there any problem with the following assignments?

_Originally posted by @zzanggu9399 in https://github.com/kaist-cp/cs420/issues/133#issuecomment-636322681_

**Comment by jeehoonkang** [comment]
That's probably because some elements coming from the header files in macOS.  But we won't fix this, because we only support Ubuntu 18.04 and 20.04.  Sorry.
