### ISSUE TITLE
[HW4] Understanding DF(X) [Dominance Frontier]

### ISSUE THREAD

**Issue by Ngiong** [kaist-cp/cs420#166]
Hello,

I am still trying to understand where to put phinodes, which is at dominance frontiers.
In my first step, I am trying to run the mem2reg algorithm on the HW4's example

using what I've learned, but I'm confused...

```
fun i32 @single_location {
init:
  bid: b666
  allocations:
    %l0:i32:x

block b666:
  j b0()

block b0:
  %b0:i0:i32 = load %l0:*i32
  %b0:i1:unit = call @sink(%b0:i0:i32)
  %b0:i2:unit = store 0:i32 %l0:*i32
  switch undef:i32 default b1() [
    2:i32 b2()
    3:i32 b3()
  ]

block b1:
  %b1:i0:i32 = load %l0:*i32
  %b1:i1:unit = call @sink(%b1:i0:i32)
  %b1:i2:unit = store 100:i32 %l0:*i32
  j b2()

block b2:
  %b2:i0:i32 = load %l0:*i32
  %b2:i1:unit = call @sink(%b2:i0:i32)
  %b2:i2:unit = store 200:i32 %l0:*i32
  j b3()

block b3:
  %b3:i0:unit = store 300:i32 %l0:*i32
  j b0()
}
```

Store instructions are placed in blocks: `{0, 1, 2, 3}`
and with my current understanding, I calculated `DF(X)` for this example are
```
DF(0): {0}
DF(1): {2}
DF(2): {3}
DF(3): {0}
```

But I still don't get why we don't place phinode at block 3,
I thought we are supposed to put phinodes at `DF(...) U DF(DF(...)) U ..`
and `DF({0, 1, 2, 3})` should be `{0, 2, 3}`

Am I misunderstanding something here? :sob: 
Thank you.

**Comment by jeehoonkang** [comment]
The reason is we actually don't need to know the stored value at the beginning of `b3`.  The first instruction is storing a value to `%l0`, overwriting whatever value that was stored just before.

We're inserting phinodes only when their values are necessary.

**Comment by Ngiong** [comment]
I see, so we have to do another checking whether phinodes are really required to be inserted in the DF*(...) blocks then...
Thank you for your answer, Prof. @jeehoonkang 
I'll close this, and re-open if I have another question :grinning:
