### ISSUE TITLE
[HW2] A more effective reduce criteria

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs420#167]
When I tried out the fuzzer/reducer for irgen, the reducer often reduced the code into

```c
int main() { }
```

which means that the reducer simply stripped off away everything. This code is considered 'interesting' to creduce because this code causes the IR interpreter to panic. That is because the resulting IR from the c code above causes the blockexit to be unreachable. I know that this is a wrong implementation, and I must add code so that such cases are handled gracefully via `IrgenError`. 

However, I think that some people might just leave it to panic, instead of handling errors. Therefore,   I made a new reduce criteria like the following. Replacing this with the bottom of `reduce-criteria-template.sh` should do the work.

```bash
#!/usr/bin/env bash
...
cargo run --manifest-path $PROJECT_DIR/Cargo.toml --release --bin fuzz -- $FUZZ_ARG test_reduced.c 2>&1 | grep -q "(left == right)";
if [ "$?" = 0 ]
then
  exit 0;
else 
  exit 1;
fi;
```

Originally, the creduce criteria catches all rust panics. However, the new reduce criteria only catches the panic in `src/test.rs` where the gcc and kecc return values are mismatched. Therefore, I think that it can be useful for lazy people like me. However though, this should be temporary and in the end all panics should be replaced with `IrgenError`s.

**Comment by cmpark0126** [comment]
Thank you for your suggestion. I'm sure this will help many students when they reduce their buggy code! We will upload this to `kecc-publc` as well.

**Comment by cmpark0126** [comment]
We updated `kecc-public`. Please refer to the latest update: https://github.com/kaist-cp/kecc-public/commit/62c52086311c5b9964b74bb83dc668ef43283890
