### ISSUE TITLE
[HW2] Pointer on condition

### ISSUE THREAD

**Issue by codingskynet** [kaist-cp/cs420#169]
For example, there can exist some C code like:
```
int *p;

int main()
{
    if (p)
        return 1;
    else
        return 0;
}

```

To generate IR from this code, I should convert the pointer of int 'p' to bool.
I tried to do like general integer like:
```
let result = context.insert_instruction(ir::Instruction::GetElementPtr {
    ptr: target,
    offset: ir::Operand::constant(ir::Constant::int(0 as u128, Dtype::LONG)),
    dtype: Dtype::LONG,
}?;
let result = context.insert_instruction(ir::Instruction::BinOp {
    op: BinaryOperator::NotEquals,
    lhs: result.clone()
    rhs: ir::Operand::constant(ir::Constant::int(0 as u128, Dtype::LONG))
    dtype: Dtype::BOOL,
})?;
```
But, the `GetElementPtr` cannot be `Dtype::LONG`. Then, how to compare the pointer with nullptr(integer constant 0)?

**Comment by cmpark0126** [comment]
It looks make-sense. However, you don't have to worry about this part because it doesn't affect the grading.

By the way, Is it created by `creduce` or just you found out?

**Comment by codingskynet** [comment]
I just found it since the pointer in if condition is very useful for checking nullptr on the real world
like:
```
if (p && *p == 1)
```

**Comment by cmpark0126** [comment]
Closing. Feel free to reopen it if you have further questions :)
