### ISSUE TITLE
Could not establish connection to 'cs420'

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#17]
I connected to the server yesterday, but I cannot connect to the server 'cs420' with error message as above. I tried all the solutions already uploaded, but I still cannot solve this problem. May I ask some help?

Thank you.

**Comment by cmpark0126** [comment]
Please follow the steps:

1. Remove your previous SSH key: `~/.ssh/id_ed25519` (private key), `~/.ssh/id_ed25519.pub` (public key)
Even though you renamed the key file, removes all of them.

2. Please follow the steps proposed by https://gg.kaist.ac.kr/assignment/6/ again.
Note: Do not rename the key file, leave the default settings as it is. (just `Enter` when you on the `key-gen` command)

3. After that, you can see new key file pair: `~/.ssh/id_ed25519` (private key), `~/.ssh/id_ed25519.pub` (public key)
Just leave them, and please email me your `public key` and student id: chunmyong.park@kaist.ac.kr

**Comment by mechu1205** [comment]
do i need to use kvpn to access the server?

**Comment by cmpark0126** [comment]
@mechu1205 FYI, you don't need to use kvpn to access the server.

**Comment by mechu1205** [comment]
is the server down right now?

**Comment by KunJeong** [comment]
Same here, I think it's down

**Comment by jeehoonkang** [comment]
Sorry it's due to an unexpected maintenance. Will be back soon

**Comment by coolofficials** [comment]
I still receive same message. Is it down now?

**Comment by jeehoonkang** [comment]
@coolofficials It'd been up for a while.  Did you follow @cmpark0126 's [instruction](https://github.com/kaist-cp/cs420/issues/17#issuecomment-602457389)?

**Comment by coolofficials** [comment]
@jeehoonkang It works right now. I think it was just temporary error.

**Comment by jeehoonkang** [comment]
Closing, as the connection problems seem largely solved.  But feel free to reopen this issue and ask more questions on SSH problems.

**Comment by mechu1205** [comment]
Is the server down again? Can't access the server by either Putty nor VSCode.

**Comment by jeehoonkang** [comment]
@mechu1205 I'm able to connect to the server.

Due to the recent increase of network demands, it is sometimes difficult to connect to the server inside the campus...
