### ISSUE TITLE
HW2 Fuzzer Error

### ISSUE THREAD

**Issue by hyunwooj** [kaist-cp/cs420#170]
When I run fuzzer, the following error occurs:

```sh
$ python3 tests/fuzz.py -i --reduce;
Building KECC..
    Finished release [optimized] target(s) in 0.36s

C-Reduce cannot run because the interestingness test does not return
zero. Please ensure that it does so not only in the directory where
you are invoking C-Reduce, but also in an arbitrary temporary
directory containing only the files that are being reduced. In other
words, running these commands:

  DIR=`mktemp -d`
  cp /home/s20205332/cs420-kecc/tests/test_reduced.c $DIR
  cd $DIR
  /home/s20205332/cs420-kecc/tests/reduce-criteria.sh
  echo $?

should result in "0" being echoed to the terminal.

See "creduce --help" for more information.


Traceback (most recent call last):
  File "tests/fuzz.py", line 276, in <module>
    creduce(tests_dir, fuzz_arg)
  File "tests/fuzz.py", line 198, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy ./reduce-criteria.sh test_reduced.c` failed with exit code 1.
```

I followed the instruction and saw that `echo $?`printed `1`.
How can I fix this problem?

**Comment by cmpark0126** [comment]
Could you try to use `creduce` after restoring the previous version of `tests/reduce-criteria-template.sh`? 
I think the latest update may make undesirable behavior...

Here is the previous version of `tests/reduce-criteria-template.sh`:
https://github.com/kaist-cp/kecc-public/blob/1c0c9a5dbc42c54d7d55fb46509970d40536bc29/tests/reduce-criteria-template.sh

If it works, please let me know, I will fix this issue after than.

**Comment by cmpark0126** [comment]
Before you use the above instruction...

I assume your IR cannot be interpreted by IR interpreter. 

Please use the command below, and check why it cannot pass the fuzzer test:
`cargo run -- tests/test_polished.c --irrun` or
`cargo run --release --bin tests/test_polished.c -i`

**Comment by hyunwooj** [comment]
It works with the previous version. Thanks!

I reverted it to the latest version and tried `cargo run -- tests/test_polished.c --irrun` and `cargo run --release --bin tests/test_polished.c -i`.

```
$ cargo run -- tests/test_polished.c --irrun
    Finished dev [unoptimized + debuginfo] target(s) in 0.26s
     Running `target/debug/kecc tests/test_polished.c --irrun`
thread 'main' panicked at '`rid` must be assigned before it can be used', src/ir/interp.rs:354:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

$ cargo run --release --bin tests/test_polished.c -i
error: Found argument '-i' which wasn't expected, or isn't valid in this context

USAGE:
    cargo run --bin <NAME>... --release

For more information try --help
```

**Comment by cmpark0126** [comment]
Closing. Feel free to reopen it if you have further questions :)
