### ISSUE TITLE
[HW2,3] IRparse on command

### ISSUE THREAD

**Issue by codingskynet** [kaist-cp/cs420#171]
After finishing HW3, I wanted to check the result of my optimization on ir files in examples.
But, now I cannot work `--irrun`, `--simplify-cfg --iroutput` since the program produces the error:
```
ParseError(ParseError { location: LineCol { line: 23, column: 15, offset: 304 }, expected: ExpectedSet { expected: {"\'0\' ..= \'9\'"} } })
```
`cargo run --release -- --simplify-cfg --iroutput ./examples/ir/for_continue_break.ir`
On just simple ir code like `alignof.ir` works well, but on some complex ir code like `for_continue_break.ir` doesn't work.
I checked it with pure(I can run `--irrun` without any modification) up-to-date kecc-public. I think some problem on irparse.

**Comment by codingskynet** [comment]
Oh, I have some mistake and misunderstanding. Sorry.

**Comment by codingskynet** [comment]
I have some question about commands. In `kecc.rs`, I think that it can run not only *.c but also *.ir. But, when I try to use ir for running program the error on the top occurs.

Coundn't I use the *.ir on `--irrun` and `--simplify-cfg --iroutput`?

**Comment by KunJeong** [comment]
I'm having the same issue. In my case,
`cargo run -- --irrun examples/c/logical_op.c` results in "assertion failed", and
`cargo run -- --irrun examples/ir/logical_op.ir` results in a ParseError.

**Comment by cmpark0126** [comment]
@codingskynet @KunJeong 
> Coundn't I use the *.ir on `--irrun` and `--simplify-cfg --iroutput`?
>
> `cargo run -- --irrun examples/ir/logical_op.ir` results in a ParseError.

We designed KECC to make all `--ir*` command works with `*.ir` file. 
Unfortunately, IR parser is not fully implemented yet. 
So, please wait for the next update of `kecc-public`.

**Comment by cmpark0126** [comment]
Current IR parser only works with optimization examples for `gvn`, `deadcode`, and so on.

**Comment by codingskynet** [comment]
@cmpark0126 Thank you!
