### ISSUE TITLE
[Homework 2] What should be return in translate_index_op_inner and translate_index_op?

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#172]
I have several question doing HW2.
1. I cannot recognize what should be returned in translate_index_op_inner, and translate_index_op. I think former should return Load and latter should return Pointer, but I am not confident. Can I ask whether my opinion is right?
What is the difference between these two functions? 

2. While coding translate_func_call, I think I should typecast from input to dtype of parameters, but I cannot get an idea how to do. I tried various ways of doing, but I failed. Is my approach right? If so, may I ask some hints?

**Comment by KunJeong** [comment]
2. I'm pretty sure translate_func_call is covered in one of the videos.

**Comment by cmpark0126** [comment]
> What is the difference between these two functions?

`translate_index_op` receives `ast::Expression` type parameters.
```rust
fn translate_index_op(
    &mut self,
    base: &Expression,
    index: &Expression,
    context: &mut Context,
) -> Result<ir::Operand, IrgenErrorMessage> {
    // <-- snip -->
}
```

`translate_index_op_inner` receives `ir::Operand` type parameters.
```rust
fn translate_index_op_inner(
    &mut self,
    base: ir::Operand,
    index: ir::Operand,
    context: &mut Context,
) -> Result<ir::Operand, IrgenErrorMessage> {
    // <-- snip -->
}
```

As you see the above code, the role of each parameter is not different, and the type of return value is the same.

To explain a little bit more, `translate_index_op` translates `base` and `index` to `ir::Operand`, and than calls `translate_index_op_inner` to translate the index operator expression to `getelementptr` instruction.

**Comment by cmpark0126** [comment]
> I think I should typecast from input to dtype of parameters, ...

Please try to use `Typecast` instruction: https://github.com/kaist-cp/kecc-public/blob/62c52086311c5b9964b74bb83dc668ef43283890/src/ir/mod.rs#L213-L216

FYI, please refer to https://github.com/kaist-cp/kecc-public/blob/62c52086311c5b9964b74bb83dc668ef43283890/src/ir/interp.rs#L738-L810 also.
