### ISSUE TITLE
[HW4] Intended Store Use in @multi_location TestCase?

### ISSUE THREAD

**Issue by Ngiong** [kaist-cp/cs420#173]
Hello,

I want to ask regarding HW4 @multi_location function.
I think I found possibly incorrect use of Store instruction (CMIIW)
[here](https://github.com/kaist-cp/kecc-public/blob/62c52086311c5b9964b74bb83dc668ef43283890/examples/mem2reg/mem2reg.input.ir#L116)

```
%b666:i0:unit = store %l3:*i8 42:i8
```
Shouldn't it be constant first, then the pointer like [this](https://github.com/kaist-cp/kecc-public/blob/62c52086311c5b9964b74bb83dc668ef43283890/examples/mem2reg/mem2reg.input.ir#L98)?
```
%b2:i2:unit = store 200:i32 %l0:*i32
%b3:i0:unit = store 300:i32 %l0:*i32
```

Or is that intended?
Thank you ^^

**Comment by jeehoonkang** [comment]
Sorry for the late response.  It's fixed now: https://github.com/kaist-cp/kecc-public/commit/8134a569669985a5d1738cccde504d772ecbc2d6

Thank you for reporting this!
