### ISSUE TITLE
[HW3] Handling a special case in CFG Merge

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs420#174]
I watched the video dealing with CFG simplification again, and thought about the following case.

```
fun i32 @foo {
init:
  bid: b0
  allocations: 

block b0:
  j b1()

block b1:
  j b2()

block b2:
  ret 37:i32
}
```

In this case, block b0, b1, and b2 can all be merged, because the indegrees of b1 and b2 are all 1.  However, after the merging of b0 and b1, b1 will not be present in `code.blocks` and I think this will cause the code to panic (or crash), if we use the code that the professor wrote. 

I have implemented the optimization pass in a different way so that I don't suffer from this issue. However though, I was curious if this can be problematic in the reference code. Thanks!

**Comment by jeehoonkang** [comment]
Yeah, I fixed the crash after creating the video.  It's fine (and encouraging, actually) to implement the optimizations in your own way, as far as it works as expected.  What's your `cargo test test_examples_simplify_cfg` result?

**Comment by pr0cf5** [comment]
All the testcases pass.
Would it be okay to close this issue?

**Comment by jeehoonkang** [comment]
I think so.  Closing..
