### ISSUE TITLE
[Homework 4] IR parser result

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#176]
In homework 4, KECC reports parsed output of `mem2reg.input.ir`.
However, it seems KECC does not parse it correctly.

1. Order of blocks does not match. (input: sink -> sinkptr -> ...  vs parsed: multi_block -> ...)
2. Function signature does not parsed correctly. (input: `fun unit @sink`  vs parsed: `fun i32 @sink`)

Please, check them.

My parsed result:
```
[before opt]
fun i32 @multi_block {
init:
  bid: b0
  allocations: 
    %l0:i32:x

...

fun i32 @sink {
init:
  bid: b0
  allocations: 


block b0:
  %b0:p0:i32
  ret unit:unit
}

fun i32 @sinkptr {
init:
  bid: b0
  allocations: 


block b0:
  %b0:p0:*i8
  ret unit:unit
}

[after opt]
...
```

**Comment by Pusnow** [comment]
Oh, 1. is due to BTree.

**Comment by cmpark0126** [comment]
Thank you for reporting the bug. We'll fix this issue you mentioned at `2.` in the next update.

**Comment by cmpark0126** [comment]
We updated `kecc-public`. Please refer to the latest update: https://github.com/kaist-cp/kecc-public/commit/7bb9ed11b5eef22bf0f41edc7fadafba789f9439

I expect the function signature will be parsed correctly now.

**Comment by Pusnow** [comment]
Great. Thanks!
