### ISSUE TITLE
[HW4] Question about register promotion algorithm

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs420#179]
Hello, I am watching [[KAIST CS420, 2020 Spring] Register Promotion (Code 1)](https://www.youtube.com/watch?v=BX9yQiR1Hds) again to get a better understanding of register promotion implementation.

Now here's what I failed to understand:

Before the insertion of phinodes takes place, every instruction in every block is scanned and modified with the following algorithm.
```
If INST is STORE && addr is promotable:
    update end_value
else if INST is LOAD && addr is promotable:
    fetch value by looking at the following sources in order
    1. the end value of the current block
    2. the end value of the 'nearest block'
    3. phinode registers??
   update replacement_table
```

== edited ==
I'm confused about (3). In the video option 3 means that we are going to insert phinode registers in the current block and use them as the value. What I don't undestand is where these phinode values come from. Thank you

**Comment by jeehoonkang** [comment]
- Let's say each of the blocks A and B has an outgoing edge to the block C, and we're inserting a phinode for C at the algorithm step 3.

- Then the phinode should be consisting of two values, one from A and the other from B.  The value from A should be A's last value, and that from B should be B's last value.

- These values are not determined at the scan time.  So we just remember the equations that the new phinode %phi = phi(Xa, Xb), where Xa, Xb are **algorithm variables** that represent the last values of A and B, respectively.

- Later, these variables are resolved thanks to the fact that A and B should also have been resolved for the time being.

I'm not sure this answers your question; feel free to ask follow-up questions!

**Comment by pr0cf5** [comment]
Thank you for the answer.

The answer is what I wanted. **So, the first two cases are where load value is deterministic and the third case is where the load value is dependent on control flow, is that correct?**

Also, I have a  follow-up question related to this.

The next operation done right after the pseudocode I wrote is `generate phinodes recursively`. I understood this operation as the following: traverse previous nodes in the same manner, until the load value becomes deterministic. This deterministic value is eventually passed to the block via 'chain' of phinodes. Is this understanding correct?
