### ISSUE TITLE
Suggestion to turn on Do Not Disturb when recording video

### ISSUE THREAD

**Issue by Shavakan** [kaist-cp/cs420#18]
I've been replaying the homework 1 video and every single time I heard a slack notification sound I couldn't resist but to check on my slack, when and notification was in fact coming from the video.

I suppose this harms the focus of the viewers in video lecture. Could you consider turning on Do Not Disturb when recording future videos?

**Comment by jeehoonkang** [comment]
Thanks for the feedback.  In the new videos for the tomorrow's session, I didn't record sound from the computer.  I'll try my best to improve the video quality!
