### ISSUE TITLE
[HW2] array5.c

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs420#182]
I think someone already mentioned it but it was closed before getting any feedback.
In array5.c the initializer is out-of-bounds.
```c
int a[5] = {init, 2, 3, 4, -5, 6};
```

Actually, I made this cause an error in KECC since the initializer and array size is mismatched. Is this intended or is this a typo? If i remove one of the elements the code works fine.

**Comment by cmpark0126** [comment]
Thank you for reporting the bug. We'll fix the problem you mentioned above in the next update.

**Comment by jeehoonkang** [comment]
Fixed in this commit: https://github.com/kaist-cp/kecc-public/commit/54004932e3023735001d548c17df95041999ece9
