### ISSUE TITLE
[HW2] array5.c test failure

### ISSUE THREAD

**Issue by cyron1259** [kaist-cp/cs420#184]
Hi, I'm getting the below error when testing my irgen with array5.c.
```
[testing "examples/c/array5.c"]
thread 'test_examples_irgen' panicked at 'main:b0:13 / fail to store Int { value: 340282366920938463463374607431768211451, width: 32, is_signed: true } into memory with bid: 3, offset: 20', src/tests.rs:105:30
```
Is it because of the out-of-bounds issue (#182) or is the error on my side?

**Comment by christofides** [comment]
You can edit the code in array5.c yourself to remove the bug and check if the error is still there

**Comment by cyron1259** [comment]
Thanks! Fixed the issue by editing the file.
