### ISSUE TITLE
[HW 3-6]

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#187]
Hello!

Out of curiosity, I wonder if the examples provided for the optimization homeworks were generated from actual c-code? If so, I wonder if it is possible to see the C-code that was used to generate the IR's. It would be interesting to see the connections between the optimizations and the high-level code.

Br
Jesper Amilon

**Comment by jeehoonkang** [comment]
No, all of them are hand-written by me.

**Comment by jeehoonkang** [comment]
But I guess that from the explanation, you can "fabricate" example C codes for which the optimization will kick in.. :)

**Comment by christofides** [comment]
Okey, thank you for answer! I'll try to come up with some interesting examples!
