### ISSUE TITLE
[HW6] deadcode.input.ir, deadcode.output.ir store instruction operands

### ISSUE THREAD

**Issue by yh2369** [kaist-cp/cs420#188]
deadcode.input.ir과 deadcode.output.ir의 store instruction의 value와 ptr의 순서가 바뀐 것 같습니다.
https://github.com/kaist-cp/kecc-public/blob/54004932e3023735001d548c17df95041999ece9/examples/deadcode/deadcode.input.ir#L22
https://github.com/kaist-cp/kecc-public/blob/54004932e3023735001d548c17df95041999ece9/examples/deadcode/deadcode.input.ir#L33
https://github.com/kaist-cp/kecc-public/blob/54004932e3023735001d548c17df95041999ece9/examples/deadcode/deadcode.output.ir#L19
https://github.com/kaist-cp/kecc-public/blob/54004932e3023735001d548c17df95041999ece9/examples/deadcode/deadcode.output.ir#L29

deadcode.input.ir의 경우 아래처럼 바뀌어야 할 것 같고
```c
%b0:i3:unit = store %l1:i32 %b0:i0:i32
%b2:i0:unit = store %l1:i32 42:i32
```
=>
```c
%b0:i3:unit = store %b0:i0:i32 %l1:*i32 
%b2:i0:unit = store 42:i32 %l1:*i32
```
deadcode.output.ir의 경우 아래처럼 바뀌어야 할 것 같습니다.
```c
%b0:i1:unit = store %l0:i32 %b0:i0:i32
%b2:i0:unit = store %l0:i32 42:i32
```
=>
```c
%b0:i1:unit = store %b0:i0:i32 %l0:*i32
%b2:i0:unit = store 42:i32 %l0:*i32
```

**Comment by jeehoonkang** [comment]
Thank you for finding a nasty bug!  It's fixed in https://github.com/kaist-cp/kecc-public/commit/ea97330e037ac0bb8c8e3d7a608b8bc86c48e620 .
