### ISSUE TITLE
[Homework 2] How to get structure type

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#191]
While doing homework 2, I got stuck for getting structure in member expression. I got structure inside the pointer, but the name and size_align_offsets are None. I saw the previous issue and tried to find structure from self.structs, but I do not know how to get it with 'None' name structure.  May I ask some help?

**Comment by pr0cf5** [comment]
You need to use `ir::Dtype::get_offset_struct_field`. This function takes `self.structs` as the second parameter, so even if the `size_align_offsets` is None the function will search it from the `self.structs` hashmap and yield the offset.

**Comment by cmpark0126** [comment]
Closing. 

I expect @pr0cf5's answer will help you. 

Feel free to reopen it if you have further questions :)

**Comment by HwangSeongha** [comment]
I still do not know how to put structure into 'structs'.... Is it right that I should do it add_declaration function?
여전히 structure를 structs라는 곳에 넣는 법을 모르겠는데... add_declaration에서 이 일을 처리하는 것이 맞나요?
