### ISSUE TITLE
[Homework 7] Short (.half) type 

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#192]
According to [A Whirlwind Tour of RISC-V](https://www.notion.so/A-Whirlwind-Tour-of-RISC-V-a7cae7ace87d4ebcbf490f59c4793033), 

```c
char g_char = 1;
short g_short = 1;
int g_int = 1;
long g_long = 1;
```
should be translated to

```bash
g_char:
        .byte   1                       # 0x1
g_short:
        .half   1                       # 0x1
g_int:
        .word   1                       # 0x1
g_long:
        .quad   1
```
.

However, [GodBolt](https://godbolt.org/z/us4Kt7) translate it to

```bash
g_char:
        .byte   1                       # 0x1

g_short:                              # <----------------  ???

g_int:
        .word   1                       # 0x1

g_long:
        .quad   1

```

Why is this happening?

**Comment by cmpark0126** [comment]
I think it is a bug of `GodBolt`...

If you uncheck `Directives` options in the filter menu at the top of the compiler window, you'll find `.word 1`. Please try it.

**Comment by Pusnow** [comment]
Oh, I see.
