### ISSUE TITLE
[HW2] stuck with a reduced testcase

### ISSUE THREAD

**Issue by cyron1259** [kaist-cp/cs420#193]
creduce has been producing this testcase:
```
int a;
int main() {
  int b;
  a = 8;
  for (; a > 0; a--) {
    b & 1;
    b = 0;
  }
}
```

where my IR looks like this:
```
var i32 @a = default

fun i32 @main () {
init:
  bid: b0
  allocations:
    %l0:i32:b

block b0:
  %b0:i0:unit = store 8:i32 @a:*i32
  j b1()

block b1:
  j b2()

block b2:
  %b2:i0:i32 = load @a:*i32
  %b2:i1:u1 = cmp gt %b2:i0:i32 0:i32
  br %b2:i1:u1, b3(), b5()

block b3:
  %b3:i0:i32 = load %l0:*i32
  %b3:i1:i32 = and %b3:i0:i32 1:i32
  %b3:i2:unit = store 0:i32 %l0:*i32
  j b4()

block b4:
  %b4:i0:i32 = load @a:*i32
  %b4:i1:i32 = sub %b4:i0:i32 1:i32
  %b4:i2:unit = store %b4:i1:i32 @a:*i32
  j b2()

block b5:
  ret 0:i32
}
```

For me it looks like the IR is correct, but creduce keeps producing this one.
Or am I missing some mistake I didn't notice?

**Comment by yh2369** [comment]
b in uninitialized value, so  when we interpret ```%b3:i1:i32 = and %b3:i0:i32 1:i32```, ```%b3:i0:i32``` is undef value, so ```calculate_binary_operator_expression()``` returns `Err()`

**Comment by yh2369** [comment]
My ir is the same as your ir

**Comment by codingskynet** [comment]
Did you keep your project up-to-date?
I also had same problem in irgen, and it was resolved by new reduce policy(comparing kecc output with gcc output).

**Comment by cmpark0126** [comment]
@cyron1259 

As @yh2369 's answer, the code created by `creduce` has uninitialized value `b`, and it makes undefined behavior. So, It is natural for the KECC to generate an error.

Please retry reducing the code, and it may create another helpful example.

**Comment by cyron1259** [comment]
Thanks all :) retying the reduction worked.

**Comment by cyron1259** [comment]
@cmpark0126 I thought the problem was solved but after some time, the fuzzer keeps generating another problematic example:
```
int a;
int main() {
  int b;
  for (; a < 6; a++) {
    b & 1;
    b = 0;
  }
}
```
I have the latest KECC. Should I retry until it produces another example?
