### ISSUE TITLE
[Homework2] handling implicit typecast

### ISSUE THREAD

**Issue by h2oche** [kaist-cp/cs420#198]
Hello, while I evaluated my irgen using fuzzer, I had some question.

Here is C code and corresponding IR generated by my irgen.

```c
int main()
{
  short k = 50000;
  return k;
}
```

```llvm
fun i32 @main () {
init:
  bid: b0
  allocations:
    %l0:i16:k

block b0:
  %b0:i0:i16 = typecast 50000:i32 to i16
  %b0:i1:unit = store %b0:i0:i16 %l0:*i16
  %b0:i2:i16 = load %l0:*i16
  %b0:i3:i32 = typecast %b0:i2:i16 to i32
  ret %b0:i3:i32

block b1:
  ret 0:i32
}
```

And this is result of interpreting IR above.

```
[result] Int { value: 340282366920938463463374607431768195920, width: 32, is_signed: true }
```

I guess `typecast 50000:i32 to i16` is problematic, but I can't come up with alternative solution. Does typecasting from `int` to `short` need extra works?

**Comment by cmpark0126** [comment]
It's because KECC prints your result as `u128` when you use `--irrun`: https://github.com/kaist-cp/kecc-public/blob/5101b294b65f5d7a84a9a18929123f96974e34f2/bin/kecc.rs#L117-L121
I'll fix this issue. Please wait for the next update.

FYI, you don't need extra works for this.

**Comment by cmpark0126** [comment]
Fixed in this commit: https://github.com/kaist-cp/kecc-public/commit/9ca05ba893c067a572269338ade415b7a530a0c5
