### ISSUE TITLE
cargo doc --open doesn't work

### ISSUE THREAD

**Issue by Seojin-Kim** [kaist-cp/cs420#20]
Hello.

I'm trying to start HW1.

But when I run the command 'cargo doc --open', below error occurs.

warning: Couldn't open docs: command 'xdg-open (internal)' did not execute successfully; exit code: 3
command stderr:
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LANGUAGE = (unset),
        LC_ALL = (unset),
        LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
Couldn't find a suitable web browser!
Set the BROWSER environment variable to your desired browser.
Warning: program returned non-zero exit code #1
sh: 881: www-browser: not found
sh: 881: links2: not found
sh: 881: elinks: not found
sh: 881: links: not found
sh: 881: lynx: not found
sh: 881: w3m: not found
xdg-open: no method available for opening '/home/s20160108/Works/kecc-public/target/doc/kecc/index.html'

Can you help me with this problem?

Thank you.

**Comment by jeehoonkang** [comment]
It's because the server doesn't have a web browser.  Here's some workarounds:

- Build the repository in your local machine, and do `cargo doc --open`.
- Do `cargo doc` on the server, and copy the generated html files to your local machine, and open it.

**Comment by jeehoonkang** [comment]
Closing.  Feel free to reopen it if you have further questions
