### ISSUE TITLE
[HW7] About negative immediate values

### ISSUE THREAD

**Issue by LockOne** [kaist-cp/cs420#201]
Hello,

There are some instruction which uses negative immediate values, such as
`addi sp, sp, -32`
or
`sw a0, -20(s0)` (I assumed that this instruction's type is S type, but I'm not sure...).

I thought the immediate value of the instruction should be negative, but the asmgen implementation says that `asm::Immediate::Value` takes an unsigned value (u64).

How should I put negative values for immediate values?

Thank you.

**Comment by cmpark0126** [comment]
Thank you for the question.

When you want to use a negative value, just typecast it to u64 like below:
```rust
asm::Immediate::Value(-1 as u64)
```
FYI, casting between two integers of the same size (e.g. i64 -> u64) is lossless: https://doc.rust-lang.org/stable/reference/expressions/operator-expr.html#semantics
