### ISSUE TITLE
[Homework 7] Do we have to follow RISC-V conventions?

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#207]
There are many conventions such as calling convention and register convention (saved/temp/arg).
Do we have to strictly follow them?

**Comment by jeehoonkang** [comment]
Yes, please.  For the final project, the compilation result will be linked with some test driver.

**Comment by Pusnow** [comment]
Ok, I see.

**Comment by jeehoonkang** [comment]
As contrary to what I said above, for homework 7, you don't need to observe the calling convention: https://github.com/kaist-cp/cs420/issues/209#issuecomment-643937143
