### ISSUE TITLE
[Question] Does JavaScript really use dynamic scoping?

### ISSUE THREAD

**Issue by h2oche** [kaist-cp/cs420#21]
In lecture 3(intermediate representation), professor mentioned JavaScript as one particular example of languages that use dynamic scoping. However, as far as I know, JavaScript uses lexical scoping like C, C++. Here is concrete example.

```javascript
function foo() {
    console.log(a);
}

function bar() {
    var a = "local";
    foo();
}

var a = "global";
foo(); // global
bar(); // global
```

**Comment by jeehoonkang** [comment]
Thank you for pointing out my error.  Yes, indeed JavaScript is using static scopes.

The reason I was confused is the `this` keyword, which has some flavor of dynamic scoping.  I'm sorry to say incorrect statement based on my vague memory.
