### ISSUE TITLE
[HW7] Feature Request: align directive

### ISSUE THREAD

**Issue by hestati63** [kaist-cp/cs420#210]
As memory-alignment affects the performance (I'm not sure on riscv5), I want to align some variables with word size. But there is no way to generate the '.align' directives.
Can you add a align directive to `asm::Directive`?

Thank you.

**Comment by cmpark0126** [comment]
We added `asm::Directive::Align` in this commit: https://github.com/kaist-cp/kecc-public/commit/e8a69a32768cfcb3ef42fd837803173c759d40af

Please use it!
