### ISSUE TITLE
Inconsistent initial block phinode syntax.

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#212]
In KECC's IR, arg registers in initial block represent function parameters. [link](https://github.com/kaist-cp/kecc-public/blob/e8a69a32768cfcb3ef42fd837803173c759d40af/src/ir/mod.rs#L401-L404)

Therefore, in these cases phinode declaration should be omitted. [link](https://github.com/kaist-cp/kecc-public/blob/e8a69a32768cfcb3ef42fd837803173c759d40af/examples/ir3/simple_if.ir#L8-L10) (b0:p0 used without declaration)

However, in another cases, a phinode in the initial block is declared. [link](https://github.com/kaist-cp/kecc-public/blob/e8a69a32768cfcb3ef42fd837803173c759d40af/examples/gvn/gvn.input.ir#L16-L19) (b0:p0 is declared)

Which one should we follow?

**Comment by Pusnow** [comment]
+ Is it possible to jump to initial block with arguments?
If so, should I declare phinodes?

**Comment by jeehoonkang** [comment]
Yes, it's our bug.  Thank you for report.  We'll fix it soon.

**Comment by cmpark0126** [comment]
> + Is it possible to jump to initial block with arguments?
It is not possible to jump to the initial block.

We fixed the problem you pointed out above in this commit: https://github.com/kaist-cp/kecc-public/commit/833f26b01347d3c5bdf050d0090a32e518c67caf
