### ISSUE TITLE
[HW6] Grader accepting non-implemented solution

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#213]
Hello

It seems to be something strange with the grader for deadcode.
The grader accepts my solution even though I haven't even implemented the code yet (I simply return false). The reason I tested this on the gg grader is because I passed the testing locally so I was confused as to why this was happening locally and if there was some bug with my local machine.

Br
Jesper Amilon

**Comment by jeehoonkang** [comment]
- Thanks, it's hot-fixed: https://github.com/kaist-cp/kecc-public/commit/0bdcfa7bc12dac980979278d489f73655db729a6

- Gradings for hw3-hw6 will be nullified soon.  Sorry for inconvenience.
