### ISSUE TITLE
Missing implementation of IsEquiv

### ISSUE THREAD

**Issue by hestati63** [kaist-cp/cs420#214]
In `is_equiv_block` function, check of phinode equivalence and instruction equivalence cannot be conducted by `!=` as their operands' `bid` are different.

I think there should be more logic to check phinode and instruction equivalence.

Thanks.

**Comment by jeehoonkang** [comment]
While phinodes and instructions have bid inside them in the printed IR, they don't in the in-memory representation of IR.  So we can just compare them with the `==` operator.

**Comment by hestati63** [comment]
It seems RegisterId hold the bid as follow:
https://github.com/kaist-cp/kecc-public/blob/master/src/ir/mod.rs#L404
https://github.com/kaist-cp/kecc-public/blob/master/src/ir/mod.rs#L412

**Comment by jeehoonkang** [comment]
@hestati63 thanks for raising up the issue.  It's just fixed: https://github.com/kaist-cp/kecc-public/commit/73d006f1118f175d2f78eed4816e390ac0a6f49e

Closing, but feel free to reopen it if the problem persists.

**Comment by hestati63** [comment]
@jeehoonkang  As I cannot reopen the issue, sorry for mention you if it disturbance you.

These three lines also should be changed by utilizing `is_equiv_operand`.

https://github.com/kaist-cp/kecc-public/blob/73d006f1118f175d2f78eed4816e390ac0a6f49e/src/ir/equiv.rs#L267
https://github.com/kaist-cp/kecc-public/blob/73d006f1118f175d2f78eed4816e390ac0a6f49e/src/ir/equiv.rs#L290
https://github.com/kaist-cp/kecc-public/blob/73d006f1118f175d2f78eed4816e390ac0a6f49e/src/ir/equiv.rs#L317

Thanks a lot!

**Comment by jeehoonkang** [comment]
@hestati63 thank you for a thoughtful comment.  here's a fix you suggested: https://github.com/kaist-cp/kecc-public/commit/67920894bbba5e08907faa3492ddba94a87586f7

**Comment by hestati63** [comment]
@jeehoonkang I found one more missing thing.

```diff
diff --git a/src/ir/equiv.rs b/src/ir/equiv.rs
index 7bfbec2..e53ea4d 100644
--- a/src/ir/equiv.rs
+++ b/src/ir/equiv.rs
@@ -306,6 +306,9 @@ fn is_equiv_block_exit(lhs: &BlockExit, rhs: &BlockExit, map: &HashMap<BlockId,
             }
             true
         }
+        (BlockExit::Return { value }, BlockExit::Return { value: value_other }) => {
+            is_equiv_operand(value, value_other, map)
+        }
         _ => lhs == rhs,
     }
 }
```
Thank you!

**Comment by jeehoonkang** [comment]
@hestati63 Thank you, it's fixed: https://github.com/kaist-cp/kecc-public/commit/dcc09cb4726578bf5bed1a461f5cc60dac001cc2

And sorry for making so many bugs...

**Comment by hestati63** [comment]
Thank you for fixing!
