### ISSUE TITLE
[HW3] Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by gfhd0054** [kaist-cp/cs420#215]
I'm debugging my simplifyCfgMerge.
After simplifying merge.input.ir, this FunctionDefinition is generated.
```
 FunctionDefinition {
allocations: [],
blocks: {
    BlockId(0): Block {
        phinodes: [],
        instructions: [Named { name: None, inner: BinOp { op: Plus, lhs: Constant(Int { value: 42, width: 32, is_signed: true }), rhs: Constant(Int { value: 37, width: 32, is_signed: true }), dtype: Int { width: 32, is_signed: true, is_const: false } } }],
        exit: Return { value: Register { rid: Temp { bid: BlockId(0), iid: 0 }, dtype: Int { width: 32, is_signed: true, is_const: false } } } }}, 
bid_init: BlockId(0) }
```

This is same with the FunctionDefinition of merge.output.ir. However, it generates the error
`Illegal instruction (core dumped)`

I am currently replacing the operands in the merged ir by mutating what the operand is pointing, such as
```
match instr {
    ...
    ir::Instruction::UnaryOp{operand, .. }
    | ir::Instruction::Load{ptr: operand}
    | ir::Instruction::TypeCast{value: operand, .. } => {
          *operand = replace_operands(operand, replaces);
    }
...
}
```
Is there any way to fix this error?

Thanks in advance.

**Comment by jeehoonkang** [comment]
Would you please give us more information on the core dump?

- Please specify which is generating the core dump.  Is it compiler?  Interpreter?
- Probably it'll be helpful to investigate the stack trace with `RUST_BACKTRACE=1`.

**Comment by gfhd0054** [comment]
It was message from the Rust itself while removing element from BTreeMap.
I thought my simplified ir generates illegal instructions.

Now I have solved it by substituting remove() to other way.
Thanks for comment.
