### ISSUE TITLE
Video on asm.rs

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#220]
@Ngiong said:

> By the way, will there any code walkthrough video to explain the syntax/semantics of asm/mod.rs? So now I'm pretty don't know what to do to start HW7, and I planned to "manually" construct asm::TranslationUnit from godbolt's output for fibonacci.c (I hope this is a good example for starter (?))

It seems they removed the comment, but I feel I should have recorded such a video.  I'll make one and share it tomorrow.

**Comment by Ngiong** [comment]
I feel pretty bad after posting the comment, that's why I removed it.
But thank you if you're willing to record a video for us :)
