### ISSUE TITLE
[Question] Not possible to jump to init_block?

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#221]
Hello

In issue #212 the TA mentioned that you cannot jump to the init block, which makes sense since it simplifies the optimization algorithms.

My question is, out of interest, if it is guaranteed/proven that the algorithm used for IR-gen (in this course and irgen algorithms in general) will never produce an IR that jumps to the init block?

Br
Jesper Amilon

**Comment by jeehoonkang** [comment]
Yeah, irgen doesn't make jumps to the initial block, as it always inserts jumps only to newly created blocks.

**Comment by christofides** [comment]
Aha, okey I understand, thanks for answer!
