### ISSUE TITLE
[HW2] How ir0~ir4 directories in src/examples are different?

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/cs420#224]
![image](https://user-images.githubusercontent.com/20202266/84745454-8fa19f80-afef-11ea-9102-1d94a7feccaa.png)

Hi.

There was one ir directory which contains .ir files, but now there are five directories containing .ir files. It seems those are updated by [this commit](https://github.com/kaist-cp/kecc-public/commit/833f26b01347d3c5bdf050d0090a32e518c67caf).

Files having same name in different directory have different contents. For example, simple.ir in ir0 directory and simple.ir in ir4 directory have different contents.

So how ir0~ir4 directories in src/examples are different?
Thanks in advance.

**Comment by jeehoonkang** [comment]
Probably this link would help you understand the roles of those directories: https://github.com/kaist-cp/kecc-public/blob/master/tests/test_examples.rs#L127

**Comment by kimjungwow** [comment]
Thank you!! :)
