### ISSUE TITLE
Parse Error doing TDD

### ISSUE THREAD

**Issue by rust-lover** [kaist-cp/cs420#225]
![image](https://user-images.githubusercontent.com/66996577/84753167-a0efa980-aff9-11ea-92b8-15d14069cd35.png)

Why is parse error occurs?
I'm using windows10 locally.

I didn't implement anything in write_c yet since I want to follow TDD framework.
However, I think this is not related to write_c

**Comment by jeehoonkang** [comment]
- oh, you love Rust...
- Please paste the error log in text so that we can more easily investigate the log.
- it seems `testAST.c` is your own C file.  Can you paste it here?

**Comment by rust-lover** [comment]
@jeehoonkang 
testAST.c is as below.

int main() {}

**Comment by jeehoonkang** [comment]
- It works for me (Ubuntu 20.04).
- I suspect maybe the carriage-return in Windows is the problem.  Would you please test your code in Linux?

**Comment by rust-lover** [comment]
@jeehoonkang 
Okay, maybe I will first try for WSL(Windows Subsystem for Linux)
