### ISSUE TITLE
[Slides] Request for individual slide divided by lecture

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#226]
Hi. Maybe it's a bit late for this, but since the slides are completed, may I ask for a individual file for each part of the lecture? Currently it's all in one google presentation, making access a bit slow and uncomfortable, so I think a file for each part would be helpful.
I heard you were sick and I hope you get well soon. Thank you.

**Comment by jeehoonkang** [comment]
Thanks for your kind words.  I'd like to ask if you could copy and divide the slides on your own.  Because I'd like to keep the only one "authoritative" version of the slides, which is the current one.  You can do that by `File > Make a copy > ...`.

**Comment by KunJeong** [comment]
Oh I see. I'll do that.
