### ISSUE TITLE
[TDD] Checking C-AST

### ISSUE THREAD

**Issue by rust-lover** [kaist-cp/cs420#227]
- Your question is more than welcome.  I'd like the students to ask many many questions.
- You may change `src/tests.rs`'s `test_write_c` by adding `println!("translation unit:\n{:?}\n", unit);` so that you can see the parsing results.  It'll the given C code's AST (which is unfortunately slightly difficult to read).

_Originally posted by @jeehoonkang in https://github.com/kaist-cp/cs420/issues/23#issuecomment-604515318_

**Comment by rust-lover** [comment]
I'm still quite not sure how to print AST.
Where in test_write_c should I put println!("translation unit:\n{:?}\n", unit);?
And how can I get print C_AST before implementing write_c.rs?

I'm trying to TDD with my own small test, and I want to print C_AST of my test before implementing.

**Comment by kimjungwow** [comment]
You can put in `impl WriteLine for TranslationUnit` in `src/c/write_c.rs` like below code.  
  
```  
impl WriteLine for TranslationUnit {  
    fn write_line(&self, _indent: usize, _write: &mut dyn Write) -> Result<()> {  
        for _i in &self.0 {  
            println!("{:#?}",_i);  
        }  
        todo!("homework 1")  
    }  
}  
```

**Comment by rust-lover** [comment]
@kimjungwow 
Thank you!
