### ISSUE TITLE
[HW 4] Unexpected Undef

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#228]
Homework 4를 하던 중 이해가 가지 않는 상황이 생겼습니다. 
logical_op test case에서 expected result는 다음과 같습니다.
`block b11:
  %b11:i0:unit = nop
  j b12(0:i32, 0:u1)`

그런데 제 경우에는,
`block b11:
  %b11:i0:unit = nop
  j b12(undef:i32, 0:u1)`
이 나옵니다. 여기서 Undef가 아니라 i32의 0이 출력되어야 하는 이유는 무엇인가요? 그리고 그 부분의 operandVar의 block id가 0인데 이것을 (load instruction이 없음에도) phinode_index에 집어넣어야 하나요?

**Comment by jeehoonkang** [comment]
- 혹시 undef여야 하는 이유를 설명해주시면 감사하겠습니다.  제가 생각하기에 0이 맞을 것 같은데, 왜냐하면 `0:i32`가 `%b12:p0:i32`로 들어가고 그게 다시 `%b9:p0:i32:d`에 들어간 후에 `%b13:i1:u1 = cmp eq %b9:p0:i32 2:i32` 에서 사용되는 것 같아서요.  

- operandvar의 block id가 0이라는 말씀을 잘 이해하지 못했습니다.  혹시 좀더 자세히 설명해주시겠어요?

**Comment by HwangSeongha** [comment]
말씀을 듣고보니 제가 착각했다는 걸 깨달았습니다. 감사합니다.
