### ISSUE TITLE
[HW5] Does GVN consider side effects of function call?

### ISSUE THREAD

**Issue by LockOne** [kaist-cp/cs420#229]
Here's a reduced example from `examples/ir3/pointer.ir`

IR input : 
```
%b0:i2:i32* = load %l1:i32**
%b0:i3:i32* = load %l1:i32**
%b0:i4:i32* = call @foo:[ret:i32* params:(i32*)]*(%b0:i3:i32*)
%b0:i5:i32* = load %l1:i32**
%b0:i6:i32* = call @foo:[ret:i32* params:(i32*)]*(%b0:i5:i32*)
...
%b0:i14:i32* = call @foo:[ret:i32* params:(i32*)]*(%b0:i2:i32*)
%b0:i15:i32* = call @foo:[ret:i32* params:(i32*)]*(%b0:i2:i32*)
```
IR expected output (i.e. the code in `examples/ir4/pointer.ir`,  same as input):
```
%b0:i2:i32* = load %l1:i32**
%b0:i3:i32* = load %l1:i32**
%b0:i4:i32* = call @foo:[ret:i32* params:(i32*)]*(%b0:i3:i32*)
%b0:i5:i32* = load %l1:i32**
%b0:i6:i32* = call @foo:[ret:i32* params:(i32*)]*(%b0:i5:i32*)
...
%b0:i14:i32* = call @foo:[ret:i32* params:(i32*)]*(%b0:i2:i32*)
%b0:i15:i32* = call @foo:[ret:i32* params:(i32*)]*(%b0:i2:i32*)
```
I interpreted the expected output as I have to consider the side effects of function calls.

1. Do I have to consider the side effect of the function call on b0:i4, and consider that the b0:i3 and b0:i5 are different values?

2. Still, I think b0:i2 and b0:i3 have the same value. Should I remove %b0:i3 instruction, and replace the operand of function call in b0:i4 as b0:i3 to b0:i2?

**Comment by jeehoonkang** [comment]
For GVN, let's pessimistically assume that the results of two loads may be different, even if they are adjacent.  In general, to conclude two load results are the same, we need to perform alias analysis (that is beyond the scope of this course).
