### ISSUE TITLE
[Hw1 Question] How do we find out what nodes are in the AST?

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#23]
So for homework 1, we are supposed to implement the function write_line for TranslationUnit, which is the root node of a AST by recursively implementing write_line(or write_string) for each child case of the TranslationUnit.
Is there a way to know what kind of nodes exist and have what nodes have what children? Or is this considered basic background knowledge or is easily found? I've searched the codebase with `cargo doc --open` but I only see the datatype declarations. I've also googled for clang translationUnit, but I only see Node and Tree, which don't really solve my problem?
This is probably a dumb question, but I am stuck from the beginning, might as well ask.

**Comment by hestati63** [comment]
You can find those information in [lang_c documentation](https://docs.rs/lang-c/0.7.0/lang_c/).

**Comment by kimjungwow** [comment]
Take a look at `lang_c::ast` in result of `cargo doc --open`. It seems what @hestati63 uploads is different from `lang_c::ast` in our project (I guess it's because our project uses different version?)

**Comment by KunJeong** [comment]
Okay, I found the docs, thanks. But not entirely sure what I'm looking at... Should the meaning of the fields in each struct be obvious to me..? For instance, I have no idea what the`specifiers`, `declarator `, `declarations ` and `statement ` fields of struct `FunctionDefinition` are supposed to mean. Is there any other available reference to help figure out what fields to use and what data to print?

**Comment by kimjungwow** [comment]
@KunJeong I'm pretty sure [this standard](http://www.open-std.org/jtc1/sc22/wg14/www/docs/n1570.pdf) will help you.  
For example, if you are implementing `lang_c::ast::FunctionDefinition`, doc says `C11 6.9.1` in the lower part of below screenshot which means you have to check 6.9.1 part of above link.
![image](https://user-images.githubusercontent.com/20202266/77533397-228fd980-6eda-11ea-8a3d-88cba8ab73bc.png)

**Comment by jeehoonkang** [comment]
I also recommend you to employ TDD (test-driven development).  Start with a very simple program, say `int main() {}`, and see how it is parsed.  After understanding a few sub-cases of the AST, implement the printer for those sub-cases.  Repeat this procedure until you get the 100% coverage.

**Comment by KunJeong** [comment]
Thank you all for your helpful answers!

**Comment by KunJeong** [comment]
Actually, I have one more question. I am trying to use TDD as recommended, but how do I view the parsing results of a C code, without having an AST printer in the first place(basically, a catch-22)? Is there an external source and/or a command within our KECC where I can input C code and get the AST results? Maybe I'm asking for too much, but I really want to get started on the assignment and I'm frustrated with myself that I can't seem to grasp how exactly I should get started. Thank you.

**Comment by jeehoonkang** [comment]
- Your question is more than welcome.  I'd like the students to ask many many questions.
- You may change `src/tests.rs`'s `test_write_c` by adding `println!("translation unit:\n{:?}\n", unit);` so that you can see the parsing results.  It's not a C code, but it'll print its AST (which is unfortunately slightly difficult to read).

**Comment by KunJeong** [comment]
So it's using the basic print function to print the nested structure of a struct! Yes, I think those print results will definitely help me grasp the structure of the AST. Thank you very much for your help. Now I can (hopefully) start coding in peace XD

**Comment by KunJeong** [comment]
Currently, I am working on HW1 with the following workflow.
1. Find buggy input with
`python3 tests/fuzz.py --print --reduce
cat tests/test_reduced.c`
2. See the output of my printer with `cargo run -- -p tests/test_reduced.c` and compare with 1, the expected output
3. Search the docs generated by `cargo doc --open` to see which AST node of my implementation is problematic
4. Fix the bug and repeat

The suggestion on the above
> * You may change `src/tests.rs`'s `test_write_c` by adding `println!("translation unit:\n{:?}\n", unit);` so that you can see the parsing results.  It'll the given C code's AST (which is unfortunately slightly difficult to read).

seems to have the potential to greatly improve **Step 3** of my workflow.

However, the above code only seems to work when running `cargo test --nocapture test_examples_write_c`, and not with `cargo run`.
Is there a way to run `cargo test` with my own test, namely `tests/test_reduced.c`?

**Comment by KunJeong** [comment]
Closing for now - I found a solution by putting `dbg!(self);` in the `WriteLine for TranslationUnit` extension.
Any ideas for improvement are very welcome.

**Comment by rust-lover** [comment]
I'm still quite not sure how to print AST.
Where in test_write_c should I put `println!("translation unit:\n{:?}\n", unit);`?
And how can I get print C_AST before implementing write_c.rs?

I'm trying to TDD with my own small test, and I want to print C_AST of my test before implementing.
