### ISSUE TITLE
Why 'ir::Operand' does not have 'Eq' trait?

### ISSUE THREAD

**Issue by codingskynet** [kaist-cp/cs420#231]
I start working on HW5: GVN. To make register tables, I use HashMap<Operand, usize>.
But, since 'ir::Operand' does not have that trait I cannot use it on HashMap's key.
It's not defined since it doesn't need for reference code? Then, do I implement that trait?

**Comment by LockOne** [comment]
You can implement your own trait... 
I implemented Eq trait of Operand by myself on gvn.rs code.

I just added
```
impl Eq for Operand {
}
```
in gvn.rs

You can do same thing for Hash trait.
```
impl Hash for Operand {
    fn hash<H: Hasher> (&self, state: &mut H) {
        match self {
            Self::Constant (c) => c.hash(state),
            Self::Register {rid, dtype} => {
                rid.hash(state);
                dtype.hash(state);
            },
        }
    }
}
```

**Comment by jeehoonkang** [comment]
- Thanks, it's fixed now: https://github.com/kaist-cp/kecc-public/commit/4c12d47939b216a498b93c3ff8ca9660f919a974
- It introduces a minor backward incompatibility, but I think it's not a big deal for most of you...
