### ISSUE TITLE
[HW 7] RISC-V addi instruction

### ISSUE THREAD

**Issue by LockOne** [kaist-cp/cs420#232]
Currently, asm writer is writing datasize as the postfix of addi instruction.

On line 332 of write_asm.rs
`Self::Addi(data_size) => format!("addi{}", data_size.write_string()),`

It makes `addiw` and `addid` instructions, but it seems there is no `addid` instruction in RISC-V architecture.

I couldn't compile the assembly code with addid instructions with my compiler, but
I'm using my own machine, and I built riscv compiler by my own, so I'm not sure whether it is the right instruction or not.

Can you confirm it?

Thank you

**Comment by cmpark0126** [comment]
Thank you for the question. You are right. `addid` is not an instruction of rv64. 

FYI, when you use `IType::Addi(Option<DataSize>)`, `Option` should be `None` except when `DataSize` is `Word`. Please refer to this link: https://github.com/kaist-cp/kecc-public/blob/master/src/asm/mod.rs#L407-L413

**Comment by LockOne** [comment]
Ah, I should be careful when I put Addi...
Thank you

**Comment by goekce** [comment]
> there is no `addid` instruction in RISC-V architecture

> You are right. `addid` is not an instruction of rv64.

To clarify: `addid` is an RV128 instruction:

https://github.com/riscv/riscv-isa-manual/blob/cb3b9d1dcdacefbde6602ada7a0050f5c723ddee/src/rv128.tex#L43-L48
