### ISSUE TITLE
[HW3] illegal hardware instruction (core dumped)

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#235]
Hi. I'm currently getting my SimplifyCfgMerge to work, but I keep getting core dump, specifically `illegal hardware instruction (code dumped) RUST_BACKTRACE=1 cargo run -- --simplify-cfg --iroutput`
without any other messages.

To debug my code, I've rolled back to the code identical to the one in the lecture videos, except for changing `HashMap` to `BTreeMap` in the following line:
`unsafe { &mut *(&mut code.blocks as *mut BTreeMap<BlockId, Block>) }`
I've already implemented walk and this seems unrelated, as commenting out some parts of my code still cause the same error.

I guess this might be related to #215 , and it might be because of the BTreeMap in the unsafe code, but unsafe features are still quite scary and difficult to me, so I have no clue how to fix this. Could you give me some advice?

Thank you.

**Comment by LockOne** [comment]
Although I don't know the reason to use unsafe operation,
I guess this might can be helped: #129

**Comment by jeehoonkang** [comment]
Yeah, as @LockOne, I suggest you don't use unsafe operations as discussed in #129.

**Comment by KunJeong** [comment]
Okay, I'll try that solution. Closing for now.
