### ISSUE TITLE
[Homework 4] Stuck in "simple_cond.ir"

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#236]
이전 issue에서 언급해주신 다음과 같은 알고리즘을 기준으로 코드를 짜던 중 이해가 가지 않는 부분이 있습니다.
1. consider the current block, say bid.
2. if it has an end value, it's the load result.
3. else if it's a join point, insert a phinode and the phinode is the load result.
4. otherwise, consider bid's immediate dominator and loop from the beginning.

제가 막힌 곳은 simple_cond인데, 다음과 같은 부분이 있습니다.
`block b3:`
` %b3:i0:i32 = load %l2:i32*`
`  %b3:i1:unit = store %b3:i0:i32 %l1:i32*`
`  %b3:i2:i32 = load %l0:i32*`
`  %b3:i3:i32 = load %l1:i32*`
`  %b3:i4:u1 = cmp lt %b3:i2:i32 %b3:i3:i32`
`  br %b3:i4:u1, b4(), b5()`

여기서 expected opt는 다음과 같이 나옵니다.
`block b3:`
`  %b3:p0:i32:t0`
`  %b3:i0:unit = nop`
`  %b3:i1:unit = nop`
`  %b3:i2:unit = nop`
`  %b3:i3:unit = nop`
`  %b3:i4:u1 = cmp lt %b0:i2:i32 %b3:p0:i32`
`  br %b3:i4:u1, b4(), b5()`

그런데 말씀해주신 알고리즘으로 생각해보면 input에서 %b3:i3:i32을 optimize할 때 end_value인 %b3:i1:unit = store %b3:i0:i32 %l1:i32*가 존재하여 결과적으로 %b3:i0:i32가 나오는 것 같습니다. 제 코드를 통한 결과물도 다음과 같이 나옵니다.

`block b3:`
`  %b3:p0:i32:t0`
`  %b3:i0:unit = nop`
`  %b3:i1:unit = nop`
`  %b3:i2:unit = nop`
`  %b3:i3:unit = nop`
`  %b3:i4:u1 = cmp lt %b0:i2:i32 %b3:i0:i32`
`  br %b3:i4:u1, b4(), b5()`

그런데 %b3:i0:i32는 후에 nop로 바뀌므로 들어가지 말아야 할 값이 들어간 것 같은데 제가 알고리즘에서 놓치는 부분이 있는건가요?

**Comment by LockOne** [comment]
I think the `end_value` table is not properly updated.
When you iterate through instructions and get `end_values`,
`%b3:i1` has a temp register as a value operand (`%b3:i0`), and it would be replaced by `%b3:p0`, but 
it seems you just put `%b3:i0` into the end_values table.

**Comment by HwangSeongha** [comment]
덕분에 해결했습니다. 감사합니다.
