### ISSUE TITLE
HW2_small submission grader gives "no method named `write_string` found"

### ISSUE THREAD

**Issue by umartaufiqul** [kaist-cp/cs420#239]
Hello. I'm trying to submit my solution for HW2 small version. I've checked that it passed the "cargo test test_examples_irgen_small" test. But when I uploaded the mod.rs file to the submission grader in gg.kaist.ac.kr, the grader gives out error "no method named `write_string` found".

Is it an error on my part?

**Comment by jeehoonkang** [comment]
Probably due to https://github.com/kaist-cp/cs420/issues/35#issuecomment-641722665

**Comment by umartaufiqul** [comment]
Ah I see. Thanks!
