### ISSUE TITLE
test failures?

### ISSUE THREAD

**Issue by mechu1205** [kaist-cp/cs420#24]
I downloaded and ran the 'cargo test' command on kecc-public, and got the following error.

running 2 tests
test test_examples_irgen ... FAILED
test test_examples_write_c ... FAILED

failures:

---- test_examples_irgen stdout ----
[testing "examples/alignof.c"]
thread 'test_examples_irgen' panicked at 'parse failed "examples/alignof.c": ParseError(PreprocessorError(Os { code: 2, kind: NotFound, message: "지정된 파일을 찾을 수 없습니다." }))', tests\test_examples.rs:22:25
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_examples_write_c stdout ----
[testing "examples/alignof.c"]
thread 'test_examples_write_c' panicked at 'parse failed "examples/alignof.c": ParseError(PreprocessorError(Os { code: 2, kind: NotFound, message: "지정된 파일을 찾을 수 없습니다." }))', tests\test_examples.rs:22:25

am i missing something here?

**Comment by jeehoonkang** [comment]
I guess you're on Windows.  I'm sorry to inform you that we support only Linux for this course.  Would you please work on homework in Linux?  You can also connect to the cs420 remote server via Visual Studio Code.
