### ISSUE TITLE
[Homework 4] Deal with Global Variable

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#240]
I got stuck for following input.
`block b0:`
`  %b0:i0:i32 = load @g:i32*`
`  %b0:i1:unit = store %b0:i0:i32 %l0:i32*`
`  %b0:i2:i32 = load %l0:i32*`
`  %b0:i3:i32 = load %l0:i32*`
`  %b0:i4:i32 = call @foo:[ret:i32 params:(i32, i32)]*(%b0:i2:i32, %b0:i3:i32)`

expected output is :
`block b0:`
`  %b0:i0:i32 = load @g:i32*`
`  %b0:i1:unit = nop`
`  %b0:i2:unit = nop`
`  %b0:i3:unit = nop`
`  %b0:i4:i32 = call @foo:[ret:i32 params:(i32, i32)]*(%b0:i0:i32, %b0:i0:i32)`

Since `%b0:i0:i32` is global variable, and there is no end value and phinode does not have it, my code returns undef. 
I do not know how to handle the global variable. May I ask some help?

my output : 
`block b0:`
`  %b0:i0:i32 = load @g:i32*`
`  %b0:i1:unit = nop`
`  %b0:i2:unit = nop`
`  %b0:i3:unit = nop`
`  %b0:i4:i32 = call @foo:[ret:i32 params:(i32, i32)]*(undef:i32, undef:i32)`

**Comment by jeehoonkang** [comment]
Hmm, `%b0:i0:i32` is not a global variable.  It's a local register.

(Not sure this helps you---please ask follow-up questions.)

**Comment by HwangSeongha** [comment]
저기에서 @g가 global variable인데 global variable에 대한 정보가 블록 안에(함수 안에) 없어서 그런지 undef를 가져오는 것 같습니다.
```
var i32 @g = 10

fun i32 @main () {
init:
  bid: b0
  allocations: 
    %l0:i32:i

block b0:
  %b0:i0:i32 = load @g:i32*
  %b0:i1:unit = nop
  %b0:i2:unit = nop
  %b0:i3:unit = nop
  %b0:i4:i32 = call @foo:[ret:i32 params:(i32, i32)]*(undef:i32, undef:i32)
  %b0:i5:u1 = cmp eq %b0:i4:i32 30:i32
  %b0:i6:i32 = typecast %b0:i5:u1 to i32
  ret %b0:i6:i32
}
```

**Comment by HwangSeongha** [comment]
해결했습니다. 감사합니다.
