### ISSUE TITLE
[Homework 5] GVN algorithm in the slide: when some of the phinode arguments are constant

### ISSUE THREAD

**Issue by kimkanu** [kaist-cp/cs420#241]
The slide describe the algorithm as follows:

+ For a block B,
  + LT@B<sub>init</sub> = LT@idom(B)<sub>final</sub>
  + For a phinode %p = ϕ(%a, %b) of B, // %a and %b (or more) are registers
    + If RT(%a)=RT(%b)=Ⓝ, then RT(%p)=Ⓝ. // so that RT(%a) makes sense
    + Otherwise, %p is assigned with a new number, say Ⓝ.
...

But what if the phinode arguments are constants, not registers? It seems that we need to implement the gvn for this case: for instance, `@func_10` of `complete_cond.ir`.

```
block b34:
  j b36(0:i32)

block b35:
  j b36(0:i32)

block b36:
  %b36:p0:i32:t9
  j b30(%b36:p0:i32)

|
v

block b34:
  j b36(0:i32)

block b35:
  j b36(0:i32)

block b36:
  %b36:p0:i32:t9
  j b30(0:i32)
```
So, maybe we need to change our `register_table: (Hash)Map<RegisterId, Num>` into something like `value_table: (Hash)Map<Operand?, Num>` as in the slide before updates. Are these cases supposed to be done additionally to the algorithm in the slide?

**Comment by LockOne** [comment]
I recommend implementing another algorithm to deal with phinodes with constant arguments because I also tried to migrate the constant case with the existing algorithm (which the register_table), and I found that it was much complicated than I thought...
I just implemented another algorithm which dealt with the constant phinodes before registers.

**Comment by jeehoonkang** [comment]
In my implementation, `RT(o)` is actually not a number, but a [number + constant] (i.e., either a number of a constant).  I believe, in doing so, you can naturally generalize the slide's algorithm to take into account constants.

**Comment by kimkanu** [comment]
I was just curious because the algorithm in slide is dealing with phinode arguments which are registers. With `[num + const]` type, I successfully implemented the gvn, so I close it.
