### ISSUE TITLE
[HW7] SRA instruction is written as SRL instruction in KECC.

### ISSUE THREAD

**Issue by LockOne** [kaist-cp/cs420#243]
On `write_asm.rs` line 211,
The instruction Sra is written as Srl.
```
Self::Srl(data_size) => format!("srl{}", data_size.write_string()),
Self::Sra(data_size) => format!("srl{}", data_size.write_string()),
```
I guess it is a typo?

**Comment by cmpark0126** [comment]
Thank you for reporting the bug. I will fix it soon. Please wait for the next update.

**Comment by jeehoonkang** [comment]
If it's not yet fixed, let's reopen this.

**Comment by cmpark0126** [comment]
It's fixed now: https://github.com/kaist-cp/kecc-public/commit/f4611c6eef40fe3d864ec58226b9788f0a953e0a
