### ISSUE TITLE
[HW7] Request for slliw, srliw, srai, sraiw

### ISSUE THREAD

**Issue by hestati63** [kaist-cp/cs420#244]
Although `slliw, srliw, srai, sraiw` are useful to implement the casting, there aren't implementations of them in asm/asm.rs.
Can you add them to the template?

**Comment by Pusnow** [comment]
`slti` and `sltiu` are also useful.
Could you please implement complete IType instructions?

**Comment by hestati63** [comment]
Also, can you consider to allow submit multiple files for hw7?
The lines of code are quite big to maintain all things in a single file.

**Comment by cmpark0126** [comment]
@hestati63 @Pusnow 
Thank you for posting the issue. We will add the requested instructions soon. Please wait for the next update.

**Comment by cmpark0126** [comment]
Added in this commit: https://github.com/kaist-cp/kecc-public/commit/f79106c03dee4f37eaff4d705bdbb96bf2f12b30
