### ISSUE TITLE
[HW2] How can I get the parsed result of irgen?

### ISSUE THREAD

**Issue by robotjoaa** [kaist-cp/cs420#246]
I compared all irgen blocks with the answer ir files.
But the compile results between kecc (which was 0)and gcc(which was 1) were different.
So I would like to look at irgen parsed results to compare.
Is there any way to look at the irgen parsed results? (like other .ir files in ir folder)

**Comment by kimjungwow** [comment]
I hope `cargo run -- -i examples/c/EXAMPLE.c` may show what you want.

**Comment by robotjoaa** [comment]
> I hope `cargo run -- -i examples/c/EXAMPLE.c` may show what you want.

thanks!
