### ISSUE TITLE
[HW7] Godbolt no directive for type short for global variables

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#247]
Hello!

When I use short variables as global variable in GodBolt, it does not add any directive for initialization of short variables, which differs from behaviour for other types.

For example, this code snippet:
```
// global variables
short sh = 30;
int in = 34;

int main() {
    if (sh < in) {
        return sh;
    } 
    return in;
}
```
Is translated into this, when using -O1 optimization for RISC-V rv64gc clang (trunk) compiler (note that no directive is added when using -O0 either)
```
main:                                   # @main
        lui     a0, %hi(sh)
        lh      a0, %lo(sh)(a0)
        lui     a1, %hi(in)
        lw      a1, %lo(in)(a1)
        blt     a0, a1, .LBB0_2
        add     a0, zero, a1
.LBB0_2:
        ret
sh: 

in:
        .word   34                      # 0x22
```
As seen, there is no initialization of the variable sh. Since this looks strange to me, I wonder if anybody knows why this is happening (or if you get different behavior for short variables)?

Br
Jesper Amilon

**Comment by Pusnow** [comment]
See #192.

**Comment by christofides** [comment]
Aha, I see, thank you, I am sorry for bringing it up again!
