### ISSUE TITLE
[HW6] online grader problem

### ISSUE THREAD

**Issue by ilbeom** [kaist-cp/cs420#248]
The online submission grader of hw6 dies with:

./check.sh: line 20: unzip: command not found

Is this problem of my submission file, or the submission page?

**Comment by jeehoonkang** [comment]
I believe the problem is now resolved.  Would you please upload your submission again?

**Comment by ilbeom** [comment]
I resubmitted, and the grader is now well-working.
Thanks for help in this late time!
