### ISSUE TITLE
[HW7] Request for fmv.d and fmv.s instruction in asmgen

### ISSUE THREAD

**Issue by LockOne** [kaist-cp/cs420#251]
Hello,
I need to move floating numbers from a register to another register, (like mv instruction for integer)
but I can't find a proper way to do so.
Can you add it to KECC?

Thank you

(+ float.ir is included in asmgen small ignore list, but float2.ir is not. It is intentional? )

**Comment by cmpark0126** [comment]
Thank you for reporting the issue. I will add `fmv.d` and `fmv.s` instruction to kecc soon. Please wait for the next update.

> (+ float.ir is included in asmgen small ignore list, but float2.ir is not. It is intentional? )

FYI, it is intended.

**Comment by cmpark0126** [comment]
Added in this commit: https://github.com/kaist-cp/kecc-public/commit/56aabbe35d9a726e09b2a6b113a22d4743a665f6
