### ISSUE TITLE
Question about overall structure of performance competition

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs420#253]
This might be a really dumb question.

Currently all the test programs' return values can be determined statically, because the program takes no input. So, I thought that if we copy and paste the entire code of IR interpreter to the assembly generation code, figure out the return value of main by running the IR interpreter, and emitting `ret <that value>` for asmgen, we can pass all testcases. I haven't tried this out yet but I think it's not impossible.

So I thought that there must be a way to dynamically run a generated program to test our implementations correctly. What do you think about this concern?

**Comment by jeehoonkang** [comment]
Actually, @cmpark0126 and I thought a lot about this issue.  Thank you for raising up an important issue.

I will soon answer to your concern.

**Comment by cmpark0126** [comment]
Thank you again for raising up the issue. We updated tester in this commit: https://github.com/kaist-cp/kecc-public/commit/d64e9f622eedd54b0848da952c121d962b7812b3.
