### ISSUE TITLE
[HW7] See asmgen assembly code

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#254]
Hello!

I wonder if it is possible to see the assembly code generated by the reference solution (i.e. the one by TA/professor)? Similar to that we were given the IR-code for the tests for homework 2.

I know that at Godbolt we can  generate the assembly code but for example the labels seem to have different naming convention in Godbolt and in the KECC compiler so it could be helpful to see assembly generated by the KECC reference compiler as well.

Best regards
Jesper Amilon

**Comment by cmpark0126** [comment]
Thank you for the suggestion.

However, we decided not to provide assembly code in this course. 

I believe Godbolt gives you enough information, and the naming convention is not critical to solving the problem.

**Comment by christofides** [comment]
Okey, I see, thanks for reply.
