### ISSUE TITLE
[hw2] block register 관련

### ISSUE THREAD

**Issue by ehfkzla** [kaist-cp/cs420#255]
안녕하세요,
 hw2에서 질문이 있습니다.
 
 아래의 ir은 제가 임의로 simple_for.c를 변환한 것입니다.
그런데, 다른 부분도 마찬가지지만, block b2에서 `cmp lt &l0:i32* 11:i32` 이런 식으로 나오는데요.
원래는 `cmp %b2:i0:i32 11:i32`로 되야하는 것으로 알고 있습니다.
 
제가 궁금한 것은 cmp의 인자를 block register(ex: &b0:i, ...) 로 표현하는 방법입니다. 
어떤 식으로 block register를 표현할 수 있는지를 모르겠습니다.
 
또한 어느 경우에 block register로 나타내야하는지가 궁금합니다.
 
```
fun i32 @main () {
init:
bid: b0
allocations:
%l0:i32:i
%l1:i32:sum
 
block b0:
%b0:i0:unit = store 0:i32 %l1:i32*
j b1()
 
block b1:
%b1:i0:unit = store 0:i32 %l0:i32*
j b2()
 
block b2:
%b2:i0:i32 = load %l0:i32*
%b2:i1:u1 = cmp lt %l0:i32* 11:i32 // here!
br %l0:i32*, b3(), b5()
 
block b3:
%b3:i0:i32 = load %l1:i32*
%b3:i1:i32 = load %l0:i32*
%b3:i2:i32 = add %l1:i32* %l0:i32
%b3:i3:unit = store %l1:i32* %l1:i32*
j b4()
 
block b4:
%b4:i0:i32 = load %l0:i32*
%b4:i1:i32 = load %l0:i32*
%b4:i2:i32 = add %l0:i32* %l0:i32
%b4:i3:unit = store %l0:i32* %l0:i32*
j b2()
 
block b5:
%b5:i0:i32 = load %l1:i32*
%b5:i1:u1 = cmp eq %l1:i32* 55:i32
ret %l1:i32
 
block b6:
ret 0:i32

```

**Comment by kimjungwow** [comment]
Block register appears as like `%b2:i1:u1 = cmp lt %b2:i0:i32 11:i32`, as shown in the 19th line of [simple_for.ir](https://github.com/kaist-cp/kecc-public/blob/master/examples/ir0/simple_for.ir).  

And I believe checking ir files in kecc-public/examples/ir0 may help you to get idea about when block register appears!

**Comment by ehfkzla** [comment]
@kimjungwow 
제가 translation을 했을 때는 cmp 인자에  %b2:i0:i32가 아니라 %l0:i32 로 나오는데요. %b2:i0:i32를 어떻게 가리키게 할 수 있는지가 궁금합니다ㅜㅜ

**Comment by cmpark0126** [comment]
When you use instruction, it must return its result.

For example, `%b2:i0:i32 = load %l0:i32*` use `ir::Instruction::Load`, and it is the first instruction of `block b2`.
In this case, you need to create `%b2:i0:i32` object using `RegisterId::Temp` if you want to use the result of `load` instruction as an operand of other instructions.

**Comment by ehfkzla** [comment]
I see. Then how to know Temp's bid(block id) and iid(instruction id)?

**Comment by cmpark0126** [comment]
@ehfkzla 
Is up to your implementation.

**Comment by ehfkzla** [comment]
Thanks!

**Comment by ehfkzla** [comment]
@cmpark0126 by the way, could you explain how to know Temp's aid?

**Comment by cmpark0126** [comment]
1. When you create `Operand::Register` object with `RegisterId::Temp`, you need to set the `dtype` carefully. 

    For example, the result of `load %l0:i32*` must be `i32` value. If you want to know `dtype` of the result of instruction, please use `dtype()` method of `HasDtype` trait: [src/ir/mod.rs#L227-L246](https://github.com/kaist-cp/kecc-public/blob/56aabbe35d9a726e09b2a6b113a22d4743a665f6/src/ir/mod.rs#L227-L246)

2. `rid` must be `RegisterId::Temp`. The answer to the `dtype` was given above.

3. `RegisterId::Temp` has no `aid` field: [src/ir/mod.rs#L412](https://github.com/kaist-cp/kecc-public/blob/56aabbe35d9a726e09b2a6b113a22d4743a665f6/src/ir/mod.rs#L412)
Do you mean `RegisterId::Arg`?

**Comment by ehfkzla** [comment]
@cmpark0126 oh sorry, yes i mean iid.

**Comment by cmpark0126** [comment]
@ehfkzla 
You probably try to make `Vec<ir::Instruction>` to make `ir::Block`. In this case, you can use `Vec`'s length as `iid` before pushing `load` instruction.
