### ISSUE TITLE
[Homework 2] Fuzzer error

### ISSUE THREAD

**Issue by kimkanu** [kaist-cp/cs420#257]
```bash
python3 tests/fuzz.py -i
python3 tests/fuzz.py -i --reduce
```
gives
```
C-Reduce cannot run because the interestingness test does not return
zero. Please ensure that it does so not only in the directory where
you are invoking C-Reduce, but also in an arbitrary temporary
directory containing only the files that are being reduced. In other
words, running these commands:

  DIR=`mktemp -d`
  cp /home/keonwoo/Projects/rust/kecc/tests/test_reduced.c $DIR
  cd $DIR
  /home/keonwoo/Projects/rust/kecc/tests/reduce-criteria.sh
  echo $?

should result in "0" being echoed to the terminal.
```
^ running the commands above, it results in "1."

I tried to use previous `reduce-criteria.sh` as mentioned in #170, but `creduce --tidy ./tests/reduce-criteria.sh tests/test_reduced.c` with previous reduce criteria gives:
```
===< 10922 >===
running 2 interestingness tests in parallel
===< pass_unifdef :: 0 >===
===< pass_comments :: 0 >===
===< pass_ifs :: 0 >===
===< pass_includes :: 0 >===
===< pass_line_markers :: 0 >===
Died at /usr/share/creduce/perl/pass_line_markers.pm line 26.
 at /usr/bin/creduce line 35.
        main::__ANON__("Died at /usr/share/creduce/perl/pass_line_markers.pm line 26.\x{a}") called at /usr/share/creduce/perl/pass_line_markers.pm line 26
        pass_line_markers::count_line_markers("test_reduced.c", 0) called at /usr/share/creduce/perl/pass_line_markers.pm line 40
        pass_line_markers::new("test_reduced.c", 0) called at /usr/bin/creduce line 372
        main::call_new("pass_line_markers", "test_reduced.c", 0) called at /usr/bin/creduce line 609
        main::delta_pass(HASH(0x55abb6a17588)) called at /usr/bin/creduce line 1080
```

How can I make the reducer work properly? Thanks.

**Comment by cmpark0126** [comment]
`creduce` runs based on the error example (`tests/test_polished.c`) generated by `python3 tests/fuzz.py -i`.

Did you try to run `python3 tests/fuzz.py -i` before using `creduce`? If not, please try this first.

If you have tried to run `python3 tests/fuzz.py -i` before using `creduce`, please share your error message generated by `cargo run --bin fuzz tests/test_polished.c -i`.

**Comment by kimkanu** [comment]
> Did you try to run `python3 tests/fuzz.py -i` before using `creduce`?

Yes, I did. And now `creduce` with previous interestingness test gives the same error with the previous one (I don't know why): 
```
C-Reduce cannot run because the interestingness test does not return
zero.
... (omitted)
```

The result generated by `cargo run --bin fuzz tests/test_polished.c -i` is as follows:
```
gcc: 225, kecc: 132
thread 'main' panicked at 'assertion failed: `(left == right)`
  left: `225`,
 right: `132`', src/tests.rs:119:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It seems that my implementation certainly has a bug, but it is too difficult to find it since `creduce` does not work. 

I followed the procedures above many times, and they resulted the same.

**Comment by kimjungwow** [comment]
@kimkanu Although it's an unwise solution but if ad-hoc solution is also fine,  
clone KECC-PUBLIC repository again,
modify irgen/mod.rs in newly cloned KECC as your implementation,
and execute `python3 tests/fuzz.py -i`, and `python3 tests/fuzz.py -i --reduce` in your newly cloned KECC.

**Comment by kimkanu** [comment]
@kimjungwow Unfortunately it also failed and resulted in the same situation. :cry:

**Comment by cmpark0126** [comment]
```bash
  DIR=`mktemp -d`
  cp /home/keonwoo/Projects/rust/kecc/tests/test_reduced.c $DIR
  cd $DIR
  /home/keonwoo/Projects/rust/kecc/tests/reduce-criteria.sh
  echo $?
```

As you said, this commands return `1` right?

I want to know two information related to this to debug:
1. Please share your `tests/reduce-criteria.sh` file contents it is generated by `python3 tests/fuzz.py -i -r`.

2. Please share the log generated after running `/home/keonwoo/Projects/rust/kecc/tests/reduce-criteria.sh`.

**Comment by kimkanu** [comment]
@cmpark0126 Oh, I didn't notice there is the output log `out.txt`. It said that I haven't installed `clang` and the reducer works after installing it. (though it took lots of time...) Thank you for your help!

In fact, I cannot access to the remote server as I mistakenly reset my ssh keys. And I need to access to it since my local env is based on Ubuntu 18, not 20 so that I realized that asmgen does not work on my machine. Could you allow me to submit new ssh keys?

**Comment by cmpark0126** [comment]
@kimkanu Sure thing! Please send me an email with a new ssh key and your student id: chunmyong.park@kaist.ac.kr

**Comment by kimkanu** [comment]
@cmpark0126 I sent my SSH public key. Now I close this issue.

Also thanks to @kimjungwow for your attention to my issue!
