### ISSUE TITLE
[HW4] fib5.ir fail due to old algorithm?

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#259]
Hi. I've implemented Hw4, caught some major bugs but I'm getting a small error - specifically, I fail at `fib5.ir` after passing 22 other examples. After going through the repo, I suspect this might have been the 'old algorithm' problem. Can anyone confirm my suspicions?

*At block 7 of function `@fibonacci`, I get `ret %b5:i6:i32` instead of the expected `ret %b5:i2:i32`.

**Comment by christofides** [comment]
I cannot say with 100% certainty but if I remember correctly I was also stuck on this test case before changing to the new algorithm.

**Comment by KunJeong** [comment]
That's good enough for me. I really appreciate it thanks!
