### ISSUE TITLE
[Session 5] March, 31th (REALTIME Q&A)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#26]
- On 31th of March, we will have a realtime Q&A session.  Please join in Google Hangout Meet (https://meet.google.com/bms-btcx-ohp) at 10:30am.

- It's not mandatory: I'll not ask attendance quiz.

- If you have questions, please ask them in the issue tracker first, and label them as `question`.  You can write down questions in Korean.  For management purposes, I may not be able to answer pop questions during the realtime Q&A session.

**Comment by hyunsukimsokcho** [comment]
Suggesting title change: **REAMTIME Q&A** -> **REALTIME Q&A**
