### ISSUE TITLE
[Hw7] Scope of asmgen

### ISSUE THREAD

**Issue by hestati63** [kaist-cp/cs420#260]
Do I need to support computation on initializing global variable?

For example:
```C
int g = 10 + 10;
int main() { return g; }
```
As this cannot be run with the `--irrun` option, I raise up this question.

Also, can you expose the `Value::try_from_initializer` method? This is quite useful while implementing the global variable initialization.

**Comment by cmpark0126** [comment]
Thank you for raising up the issue. 

First, you don’t need to consider the case you mentioned above. We are only interested in the initializer using constant, not expression. (except minus unary operator expression)

Second, ok. I will expose `Value::try_from_initializer` method. Please wait for the next update.

**Comment by hestati63** [comment]
Then, can i assume that our scope is the c program that interp.rs can interpret?

**Comment by cmpark0126** [comment]
@hestati63 

Yes, you are right. :)

**Comment by cmpark0126** [comment]
We just updated kecc-public: https://github.com/kaist-cp/kecc-public/commit/c3237276dcb89167e403442ea655abff61eca339
