### ISSUE TITLE
[HW1] Fuzzing issue

### ISSUE THREAD

**Issue by KAIST-JongchanPark** [kaist-cp/cs420#261]
I realize I have an fuzzer error for HW1 recently and I have a same issue with #133 .

```
cargo run -- -p tests/test_polished.c
```
In #133 issue, exit code 101 means ```panic!``` occurs and I tried above command to check where ```panic!``` occurs.

However, I get no ```panic!``` error and it returns normal output.

My ```test_polished.c```  has about 5k lines and it's very hard to debug where I mistake.

**Comment by cmpark0126** [comment]
Please try to use `python3 tests/fuzz.py -p -r`.

**Comment by KAIST-JongchanPark** [comment]
I tried ``` python3 tests/fuzz.py -p -r ``` command and get below result.

```
Traceback (most recent call last):
  File "tests/fuzz.py", line 276, in <module>
    creduce(tests_dir, fuzz_arg)
  File "tests/fuzz.py", line 198, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy ./reduce-criteria.sh test_reduced.c` failed with exit code 1.
```

I tried to use the solution in #170 and get another problem same as #83 , test_reduce.c has only ```;``` ,
(I am using remote server)

I also updated my code. What should be the problem?

**Comment by cmpark0126** [comment]
In order to debug, please share the result of `cargo run --bin fuzz -p tests/test_polished.c` and `cargo run --bin fuzz -p tests/test_reduce.c` after trying to use `creduce`.

**Comment by KAIST-JongchanPark** [comment]
```
error: package `tests/test_polished.c` is not a member of the workspace
```
and
```
error: package `tests/test_reduced.c` is not a member of the workspace
```
These are the result of each command...

**Comment by cmpark0126** [comment]
Sorry. It's my mistake. please try to use `cargo run --bin fuzz tests/test_polished.c -p` and `cargo run --bin fuzz tests/test_reduced.c -p`

**Comment by KAIST-JongchanPark** [comment]
They result so long translation unit and both look like same

```
pan: 118023…121599 } }, span: 118007…121599 }), span: 118007…121599 }])`', src/c/ast_equiv.rs:510:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

This is end of the result

**Comment by cmpark0126** [comment]
Please try to replace 

```
cargo run --manifest-path $PROJECT_DIR/Cargo.toml --release --bin fuzz -- $FUZZ_ARG test_reduced.c 2>&1 | grep -q '(left == right)'
```

to 

```
cargo run --manifest-path $PROJECT_DIR/Cargo.toml --release --bin fuzz -- $FUZZ_ARG test_reduced.c > outb.txt 2>&1

if
  [ $FUZZ_ARG = '-i' ]
then
  grep -q '(left == right)' outb.txt
else
  grep -q '(left.is_equiv(right))' outb.txt
fi
```

at the `tests/reduce-criteria-template.sh`

**Comment by KAIST-JongchanPark** [comment]
Thanks! From this solution, I solved fuzzing issue and pass the fuzzing error! :D

So, I close this issue
