### ISSUE TITLE
[Homework 7] Request for more tests on struct (especially floating point struct)

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#266]
Currently, it seems that `struct` tests do not cover whole floating point struct calling conventions.
There are many corner cases, and I think we should test them well.

eg)
```c struct T{ float a; } ```, ```c struct T{ float a; int b;}; ```, ```c struct T { struct { float a; } float b; }``` ...

**Comment by cmpark0126** [comment]
Thank you for the great suggestion!

However, I believe that many students have not enough time to cover new examples. 

So we're not going to increase the number of examples this semester.

**Comment by Pusnow** [comment]
Ok, I see.
