### ISSUE TITLE
[HW7] Question about RISC-V stack structure

### ISSUE THREAD

**Issue by lomotos10** [kaist-cp/cs420#268]
I have a question about the data inside the stack address of `sp`.
To get a grasp about RISC-V stack structure, I ran the following code on `RISC-V gcc 8.2.0` with flag `-O0`:
```
int main() {
    int a = 1;
    return a;
}
```
Which resulted in the following RISC-V code:
```
main:
        addi    sp,sp,-32
        sd      s0,24(sp)
        addi    s0,sp,32
        li      a5,1
        sw      a5,-20(s0)
        lw      a5,-20(s0)
        mv      a0,a5
        ld      s0,24(sp)
        addi    sp,sp,32
        jr      ra
```
While in function body, I understood the stack structure to be as follows:
![캡처](https://user-images.githubusercontent.com/48435475/86103383-a66bea00-baf7-11ea-98d8-04935af5215b.PNG)
which seems like a lot of wasted space inside the stack.
Specifically, while experimenting with different codes, it seemed like the topmost block inside the stack (block `sp`) is never used for any task.
Is there a reason for not using the topmost block? Or am I misunderstanding something about the assembly code?

Thank you very much in advance.

**Comment by cmpark0126** [comment]
Thank you for the question.

In the standard RISC-V calling convention, the stack pointer is always kept 16-byte aligned.
Perhaps this is why it seems to be wasting space in this case.

Please refer to this link: https://riscv.org/specifications/isa-spec-pdf/ (107p)

**Comment by cmpark0126** [comment]
```c
int main() {
    long a = 1;
    long b = 1;
    return a + b;
}
```
```
addi    sp,sp,-32
        sd      s0,24(sp)
        addi    s0,sp,32
        li      a5,1
        sd      a5,-24(s0)
        li      a5,1
        sd      a5,-32(s0)
        ld      a5,-24(s0)
        sext.w  a4,a5
        ld      a5,-32(s0)
        sext.w  a5,a5
        addw    a5,a4,a5
        sext.w  a5,a5
        sext.w  a5,a5
        mv      a0,a5
        ld      s0,24(sp)
        addi    sp,sp,32
        jr      ra
```

Actually, the above case does not waste memory space.

**Comment by lomotos10** [comment]
Thank you! I'll leave this up for the time being.
Please close if necessary.
