### ISSUE TITLE
[HW7] issue on integer_literal testcase

### ISSUE THREAD

**Issue by cyron1259** [kaist-cp/cs420#269]
I'm having an issue on the integer_literal testcase.

Unlike other testcases, running this one produces nothing, not even the `[testing "examples/ir0/integer_literal.ir"]`:
```
test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out

     Running target/debug/deps/test_examples-0f404fad24ae210a

running 1 test
error: test failed, to rerun pass '--test test_examples'
```
I'm suspecting it has something to do with the number `4294967163` in `unsigned int temp2 = 4294967163;`, as there's no such issue if I change the number into something else.

This is the assembly code generated from my code:
```
        .globl  main
main:
        addi    sp,sp,-32
        sd      ra,24(sp)
        sd      s0,16(sp)
        addi    s0,sp,32
        mv      a0,zero
        sw      a0,-20(s0)
        addi    a0,zero,0
        sh      a0,-22(s0)
        addi    a0,zero,4294967163
        sw      a0,-28(s0)
        lh      a0,-22(s0)
        mv      a1,a0
        lwu     a0,-28(s0)
        mv      a2,a0
        xor     a0,a1,a2
        mv      a1,a0
        addi    a2,zero,123
        xor     a0,a1,a2
        seqz    a0,a0
        ld      s0,16(sp)
        ld      ra,24(sp)
        addi    sp,sp,32
        ret
```
I don't think there's any serious issues in the code, or is there something that I'm missing?

**Comment by cmpark0126** [comment]
There are two problems here.

First, you use `addi` instruction illegal way. 
`addi` instruction only can use 11-bit for immediate value, but `4294967163` is over the range of 11-bit.
In this case, I recommend you use `li` instruction instead.

Second, you don't consider typecast seriously. 

Here is the solution code. Please check what is different from original code.

```
        .globl  main
main:
        addi    sp,sp,-32
        sd      ra,24(sp)
        sd      s0,16(sp)
        addi    s0,sp,32
        mv      a0,zero
        sw      a0,-20(s0)
        addi    a0,zero,0
        sh      a0,-22(s0)
        li      a0,4294967163 # use `li` instruction
        sw      a0,-28(s0)
        lh      a0,-22(s0)
        mv      a1,a0
        sext.w  a1,a1
        lwu     a0,-28(s0)
        mv      a2,a0
        xor     a0,a1,a2
        mv      a1,a0
        andi    a1,a1,255  # typecast `a1` to byte size
        addi    a2,zero,123
        xor     a0,a1,a2
        seqz    a0,a0
        ld      s0,16(sp)
        ld      ra,24(sp)
        addi    sp,sp,32
        ret
```

**Comment by cyron1259** [comment]
Thanks! It was really helpful.
I have one more question though. I'm having the same issue in the typecast testcase. Below is my assembly code.
```
        .globl  main
main:
        addi    sp,sp,-32
        sd      ra,24(sp)
        sd      s0,16(sp)
        addi    s0,sp,32
        mv      a0,zero
        sw      a0,-20(s0)
        li      a0,61238
        andi    a0,a0,255
        mv      a1,a0
        lui     a0, %hi(temp)
        sb      a1,%lo(temp)(a0)
        li      a0,61238
        andi    a0,a0,255
        mv      a1,a0
        addi    a2,zero,2
        slt     a0,a1,a2
        xori    a0,a0,1
        ld      s0,16(sp)
        ld      ra,24(sp)
        addi    sp,sp,32
        ret
temp:
        .byte   0x0
```
Is there something I've missed regarding typecast? Or is the problem coming from somewhere else?

Sorry for asking another debug question, but I really don't have a clue on how to solve this as the tester isn't producing any information..

**Comment by cmpark0126** [comment]
If you want to update `temp` global variable in runtime, you need to define `temp` as `.data` section as below:

```c
        .section	.data
temp:
        .byte   0x0
```

**Comment by cyron1259** [comment]
Thank you so much!
