### ISSUE TITLE
**IMPORTANT**: The Tester Is Updated to Prevent Cheating

### ISSUE THREAD

**Issue by cmpark0126** [kaist-cp/cs420#270]
Previously, all the test examples' return values could be determined statically because the program takes no input. For this reason, the cheating problem was raised (#253).

So, we modified some examples to run with external input, and update tester to test them with randomly generated input. Please refer to this commit: https://github.com/kaist-cp/kecc-public/commit/d64e9f622eedd54b0848da952c121d962b7812b3

FYI, we just nullified the existing submissions of homework 2 and 7 to gg.kaist.ac.kr due to this update. Please resubmit your homework 2 and 7. Sorry for the inconvenience.

**Comment by hestati63** [comment]
As the programs's "nonce" is uninitialized, it is natural to be store into the bss section.
But the grader modifies the nonce to non zero value, the assembler raises the error.

Can you modify C code to supply the initial value to the nonce?

**Comment by cmpark0126** [comment]
@hestati63 

If an arithmetic type object that has static storage duration is not initialized explicitly, it is initialized to (positive or unsigned) zero.

Please refer to 6.7.8/10 in the [C99 Standard (PDF document)](http://www.open-std.org/JTC1/sc22/wg14/www/docs/n1256.pdf)
> If an object that has automatic storage duration is not initialized explicitly, its value is indeterminate. If an object that has **static storage duration** is not initialized explicitly, then:
— if it has pointer type, it is initialized to a null pointer;
— if it has arithmetic type, it is initialized to (positive or unsigned) zero;
— if it is an aggregate, every member is initialized (recursively) according to these rules;
— if it is a union, the first named member is initialized (recursively) according to these rules.

When you solve the homework 7, you must consider this.

FYI, KECC Interpreter works in a similar way: [interp.rs#L1220-L1223](https://github.com/kaist-cp/kecc-public/blob/d64e9f622eedd54b0848da952c121d962b7812b3/src/ir/interp.rs#L1220-L1223)

**Comment by hestati63** [comment]
Yes. They are implicitly initialized to zero and store into the bss section.
But the grading code tries to assign non zero value into the variable that assigned to the bss.

**Comment by cmpark0126** [comment]
Ah, I understand. I will revise this.

**Comment by cmpark0126** [comment]
@hestati63 
Fixed in this commit: https://github.com/kaist-cp/kecc-public/commit/5395c1e9ba4d757705ffafbb2cd4d0a8afe6610e

**Comment by LockOne** [comment]
Would the submission be nullified again?

**Comment by cmpark0126** [comment]
I don't expect this revision to affect grading. So, I won't nullify it.

**Comment by cmpark0126** [comment]
@LockOne 
I don't expect this revision to affect grading. So, I won't nullify it.

**Comment by Ngiong** [comment]
@cmpark0126 can I get a more intuitive explanation: when should I put BSS in my global variable declaration?
My current implementation checks if the initialization == 0? If yes, put BSS

But now I think this is not working since the test script modify the initializer _after_ the asmgen translation.

```
let mut asm = Asmgen::default()
        .translate(&ir)
        .expect("fail to create riscv assembly code");

    // Resolve examples
    let rand_num = rand::thread_rng().gen();
    println!("Your rand num is: {}", rand_num);
    modify_ir(&mut ir, rand_num);
    modify_asm(&mut asm, rand_num);
```

Do you think it's better to also remove the BSS header too (if exist) when modifying the global variable initializer?
Thank you.

**Comment by cmpark0126** [comment]
Ah.. it's my mistake...

I will change it `int nonce = 0` to `int nonce = 1`. Then, `nonce` must be allocated to data section.

Sorry for the confusion. Please wait for the next update.

**Comment by cmpark0126** [comment]
@Ngiong 
Ah.. it's my mistake... I will change it `int nonce = 0` to `int nonce = 1`. Then, `nonce` must be allocated to data section.

Sorry for the confusion. Please wait for the next update.

**Comment by Ngiong** [comment]
@cmpark0126 
Seems great. But I think if you do that, you cannot inject `nonce` to become 0.
(Otherwise, please also inject the BSS header too in our ASM translation unit :pray:)

**Comment by cmpark0126** [comment]
@Ngiong 
We just set the range of the random number `[1, 100)` in this commit: https://github.com/kaist-cp/kecc-public/commit/1483614cad34f84ac502fee65c9a68631e7573d3

So, there will be no situation where `nonce` has zero. :)
