### ISSUE TITLE
[Homework 5] Chosen Block

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#272]
Homework 5를 하던 중 logical_op.ir에서 이해가 가지 않는 부분이 생겼습니다.

```
block b0:
  %b0:i0:u1 = cmp ne 1:i32 0:i32
  br %b0:i0:u1, b4(), b5()

block b1:
  %b1:i0:i32 = add %b6:p0:i32 1:i32
  j b3(%b1:i0:i32)

block b3:
  %b3:p0:i32:b
  %b3:i0:u1 = cmp ne 1:i32 0:i32
  br %b3:i0:u1, b10(), b11()

block b4:
  j b6(0:i32, 1:u1)

block b5:
  %b5:i0:u1 = cmp ne 1:i32 0:i32
  j b6(1:i32, %b5:i0:u1)

block b6:
  %b6:p0:i32:b
  %b6:p1:u1:t0
  br %b6:p1:u1, b1(), b3(%b6:p0:i32)

block b7:
  %b7:i0:i32 = add %b12:p0:i32 1:i32
  j b9(%b7:i0:i32)

block b9:
  %b9:p0:i32:d
  %b9:i0:u1 = cmp eq %b3:p0:i32 1:i32
  br %b9:i0:u1, b13(), b14()

block b10:
  %b10:i0:u1 = cmp ne 1:i32 0:i32
  j b12(1:i32, %b10:i0:u1)
```

위 코드는 before opt의 부분인데, `b10`의 idom은 `b3`이어서 제 코드에서는 jump argument에 있는 `%b10:i0:u1`이 `%b3:i0:u1`으로 바뀝니다.
하지만 실제 opt에서는 `b0:i0:u1`으로 바뀝니다. block 0 -> block 4/5 -> block 6 -> block 1 -> block 3 때문인 것 같습니다.
그런데 제 코드에서는 block 순서대로 table을 setting하기 때문에 block 3에서는 block 0의 leader table을 가져오지 않습니다.
어떻게 해결할지 감이 안오는데 도와주실 수 있나요?

**Comment by KunJeong** [comment]
Does your algorithm follow the reverse post order?

**Comment by HwangSeongha** [comment]
앗 그 부분에 실수가 있었네요 감사합니다!!
