### ISSUE TITLE
[HW7] handling local float variable allocations

### ISSUE THREAD

**Issue by cyron1259** [kaist-cp/cs420#274]
This could be a dumb question.

For putting float (or double) values to local variables (say `double a = 0.9300494635562769f;`), godbolt makes a number of assembly instructions, like
```
        lui     a0, 511
        addiw   a0, a0, 1761
        slli    a0, a0, 12
        addi    a0, a0, 1977
        slli    a0, a0, 29
        sd      a0, -32(s0)
```
whereas my asmgen simply loads as an `u64` value (similar to #269), converts the value into float, and stores to its location.
```
        li      a0,4606552360519467008
        fcvt.s.l        fa0,a0
        fcvt.d.s        fa0,fa0
        fsd     fa0,-32(s0)
```

I'm not sure whether this way also works (tester gets killed while testing `float2.ir`, which I don't know why, so I can't compare the return values). Is it okay to implement like this?

**Comment by cyron1259** [comment]
Also, would it be possible to get a hint on some possible causes that make the tester to fail without printing any information (I suspect it got killed by doing something wrong)?

**Comment by cmpark0126** [comment]
Yes. I load the float constant value in a similar way.

> Also, would it be possible to get a hint on some possible causes that make the tester to fail without printing any information (I suspect it got killed by doing something wrong)?

If this occurs, please check the behavior of the assembly code by using `qemu-riscv64-static` by yourself: https://github.com/kaist-cp/kecc-public#cross-compilation-and-architecture-emulation
It probably give you meaningful information.

**Comment by cyron1259** [comment]
Thanks!
