### ISSUE TITLE
[HW6] 'not yet implemented' error in online grading

### ISSUE THREAD

**Issue by Conatee** [kaist-cp/cs420#275]
Hi. I think I finished implementing hw6, and it passes all the testcases after running `RUST_MIN_STACK=33554432 cargo test test_examples_deadcode`.
However, when I try to submit it to course management website, its log returns 
```
thread 'test_examples_deadcode' panicked at 'not yet implemented', src/c/write_c.rs:51:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
How can I solve this problem?

**Comment by cmpark0126** [comment]
Please refer to this comment: https://github.com/kaist-cp/cs420/issues/200#issuecomment-641713503

Implementing `write_c.rs` is for HW1. HW1 and HW6 need to be independent for grading.

If you use the functions from `write_c.rs` when implementing HW6, please delete these functions from your original solution before submitting it to gg.

**Comment by Conatee** [comment]
Thank you for the answer, but as far as I know, I didn't use any functions from `write_c.rs` in `deadcode.rs` or `opt_utils.rs`. I tried running `RUST_MIN_STACK=33554432 cargo test test_examples_deadcode` after reverting `write_c.rs` in my code and it still passes all the testcases in my machine. Are there any other possible causes for the problem?

**Comment by cmpark0126** [comment]
Could you share your whole error messages generated by gg.kaist.ac.kr?

**Comment by Conatee** [comment]
```
running 1 test
[test_opt] actual outcome mismatches with the expected outcome.

[before opt]test test_examples_deadcode ... FAILED

failures:

---- test_examples_deadcode stdout ----
[testing "examples/ir2/temp2.ir" to "examples/ir3/temp2.ir"]
[testing "examples/ir2/bar.ir" to "examples/ir3/bar.ir"]
[testing "examples/ir2/logical_op.ir" to "examples/ir3/logical_op.ir"]
[testing "examples/ir2/array.ir" to "examples/ir3/array.ir"]
[testing "examples/ir2/minus_constant.ir" to "examples/ir3/minus_constant.ir"]
[testing "examples/ir2/test.ir" to "examples/ir3/test.ir"]
[testing "examples/ir2/float2.ir" to "examples/ir3/float2.ir"]
[testing "examples/ir2/fibonacci.ir" to "examples/ir3/fibonacci.ir"]
[testing "examples/ir2/negate.ir" to "examples/ir3/negate.ir"]
[testing "examples/ir2/simple_if.ir" to "examples/ir3/simple_if.ir"]
[testing "examples/ir2/comma.ir" to "examples/ir3/comma.ir"]
[testing "examples/ir2/for_continue_break.ir" to "examples/ir3/for_continue_break.ir"]
[testing "examples/ir2/simple_for.ir" to "examples/ir3/simple_for.ir"]
[testing "examples/ir2/while_continue_break.ir" to "examples/ir3/while_continue_break.ir"]
thread 'test_examples_deadcode' panicked at 'not yet implemented', src/c/write_c.rs:51:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    test_examples_deadcode

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 10 filtered out

error: test failed, to rerun pass '--test test_examples'
```
This is the error message generated by gg.kaist.ac.kr.

**Comment by cmpark0126** [comment]
Could you check if your kecc-public is up to date?

**Comment by Conatee** [comment]
I think it's the problem I was looking for. Thank you for your reply!
