### ISSUE TITLE
[HW7] About '.zero' directive

### ISSUE THREAD

**Issue by codingskynet** [kaist-cp/cs420#276]
From 'array5.c', the global array `int g_a[5] = {1, 2, 3};` can be translated into asm like:
```
g_a:
        .word   1
        .word   2
        .word   3
        .zero   8
```
(from Godbolt RISC-V gcc 8.2.0)
But, in 'asm.mod' there isn't that directive.
It is because we can make like this?:
```
g_a:
        .word   1
        .word   2
        .word   3
        .word   0
        .word   0
```

**Comment by cmpark0126** [comment]
Yes, it is. And I will add `.zero` directive also. Please wait for the next update.

**Comment by cmpark0126** [comment]
Added in this commit: https://github.com/kaist-cp/kecc-public/commit/87a17b2bb9cfe2578c21fc91acf66aa0ccb1522c
