### ISSUE TITLE
[Homework 7] Bug in `tests.rs`

### ISSUE THREAD

**Issue by Pusnow** [kaist-cp/cs420#277]
In my computer, asmgen files are removed before read by `qemu-riscv64-static`.
Please, removes asmgen files at the end of the function.

https://github.com/kaist-cp/kecc-public/blob/87a17b2bb9cfe2578c21fc91acf66aa0ccb1522c/src/tests.rs#L346-349

**Comment by cmpark0126** [comment]
Ok, I will resolve it. Thank you for reporting it.

**Comment by cmpark0126** [comment]
Fixed in this commit: https://github.com/kaist-cp/kecc-public/commit/2d8d1e7fb44af5cfb8aba41d8f174456ecb025d6

Please check if it works properly.

**Comment by Pusnow** [comment]
It works. Thanks.
