### ISSUE TITLE
[Final Project] two_dimension_array.c

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#278]
Hi.

Currently, the [two_dimension_array](https://github.com/kaist-cp/kecc-public/blob/87a17b2bb9cfe2578c21fc91acf66aa0ccb1522c/bench/two_dimension_array.c#L13) benchmark has the following loop:

```c
  for (int i = 0; i < n; ++i) {
    for (int j = 0; i < n; ++i) {  // check and increase i
      two_dimension_array_arr[i] += two_dimension_array_arr[j];
    }
  }
```

rather than

```c
  for (int i = 0; i < n; ++i) {
    for (int j = 0; j < n; ++j) {
      two_dimension_array_arr[i] += two_dimension_array_arr[j];
    }
  }
```

I am just wondering whether it is intended.

Thank you.

**Comment by cmpark0126** [comment]
Fixed in this commit: https://github.com/kaist-cp/kecc-public/commit/2d8d1e7fb44af5cfb8aba41d8f174456ecb025d6

Thank you for reporting it!
