### ISSUE TITLE
Incorrect Equivalence Checking for ASTs

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#28]
The fuzzer said that my pretty printer was wrong, but I could not find any problem. After inspecting the `ast_equiv.rs` file, I found that there was a small bug.

```diff
@@ -102,6 +102,7 @@ impl IsEquiv for Declarator {
 impl IsEquiv for DeclaratorKind {
     fn is_equiv(&self, other: &Self) -> bool {
         match (self, other) {
+            (Self::Abstract, Self::Abstract) => true,
             (Self::Identifier(identifier), Self::Identifier(other_identifier)) => {
                 identifier.node.name == other_identifier.node.name
             }
```

After fixing the bug, it seems that the fuzzer correctly compares ASTs.

**Comment by jeehoonkang** [comment]
Thanks.  It's fixed in a recent update: https://github.com/kaist-cp/kecc-public/commit/938390821fefdc84940a398c43bcde9895c24dad
