### ISSUE TITLE
[HW7] how to see asm output of input ir

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#281]
Hi. Being stuck at HW2 (previous issue), I've just started HW7. And this seems like a very stupid thing to be stuck at, but I cannot find the flags for running KECC for asmgen. I've tried `--help` on both KECC and the fuzzer, but there seem to be no flags for asmgen.
I guess [Running RISC-V Binaries](https://github.com/kaist-cp/kecc-public#running-risc-v-binaries) is for HW7, but as far as I understand it's supposed to run the output of KECC. I can't generated this output.

Again, it seems like a very stupid question. Can anyone please help me?

**Comment by christofides** [comment]
Hello!

No flag needed for asmgen, there is info in the readme file,

`cargo run -- examples/c/foo.c`     # to run on c-program
`cargo run -- examples/c/foo.ir`     # to run on pre-generated ir-code

**Comment by KunJeong** [comment]
Ah thanks. I didn't think 'compile' was same as 'asmgen', but now I realize it is if the input is IR. You're a life saver :)
