### ISSUE TITLE
[Hw7] Interference graph construction

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs420#282]
I have a question about interference graph construction.

In the slide an idea for calculating interference between registers was presented. It uses domination relation between defs and usages.

To implement this, I thought of the following algorithm. I want to know if this algorithm is valid. 

1. Store all the instructions in a linear storage by traversing blocks in RPO manner.
2. For each register, mark the definition and usage points.
3. The liveness range for each register is from the first definition instruction to the last usage definition. It can be represented as a tuple (`start_index`, `end_index`)

Is my understanding correct?

**Comment by jeehoonkang** [comment]
- It's probably related to final project, right? :)
- Your algorithm looks working, but you can also think of a register's live range as a set of [def-point, use-point].  Since def dominates every use, each interval's meaning is well defined.

**Comment by pr0cf5** [comment]
* Thank you for the quick reply. Also, thank you so much for answering to our questions during the weekend.
* I have one more follow-up question. You said that a register's live range can be seen as a **set of [def-point, use-point]**. And the algorithm that I proposed defines the live range as the first definition to the last definition. So, I guess your definition is more 'fine-grained', is that right?

**Comment by jeehoonkang** [comment]
Yes, you're right.  The approach mentioned in the original post (which basically linearizes the blocks and ranges) will give you a more coarse-grained (aka bigger) interference graph.

**Comment by pr0cf5** [comment]
Thank you for the answer. I will close this issue.

I think there will be more questions about register allocation for the next three days, it's pretty hard...
