### ISSUE TITLE
[Homework 7] Can I use RISC-V rv64gc clang for HW7 asmgen?

### ISSUE THREAD

**Issue by kimjungwow** [kaist-cp/cs420#283]
I open the issue because I can't re-open the [previous issue](https://github.com/kaist-cp/cs420/issues/209#issue-637528332).

I'm confusing whether I can use `RISC-V rv64gc clang` for asmgen.

Professor said [`For homework 7, you don't need to observe the calling convention. All test functions have the signature () -> (), for which calling conventions don't matter at all.`](https://github.com/kaist-cp/cs420/issues/209#issuecomment-643937143), so I thought I can use `RISC-V rv64gc clang` for asmgen.

But I'm confusing now because TA had said [`So, please implement asmgen by referring to the behavior of RISC-V gcc 8.2.0.`](https://github.com/kaist-cp/cs420/issues/209#issuecomment-643796368).

I am sorry for asking same question after the previous issue closed, but can I use `RISC-V rv64gc clang` for HW7 asmgen?

**Comment by jeehoonkang** [comment]
- For hw7, you don't need to observe the calling convention.  So you can consult either clang's results or gcc's results.
- For project, you should observe the calling convention and consult gcc's results.

**Comment by kimjungwow** [comment]
Thank you for being so clear, professor!
