### ISSUE TITLE
[Final Project] Live range of phinode

### ISSUE THREAD

**Issue by yh2369** [kaist-cp/cs420#284]
initial block이 아닌 block의 phinode의 definition point는 어떻게 되나요?
그 block의 predecessor의 가장 끝 (jump나 conditional jump,나 switch에서 argument를 전달하는 시점)으로 봐야 되나요?

**Comment by jeehoonkang** [comment]
- The question is, what's the definition point of a phinode (that is not in the initial block)?
- It's more or less a matter of interpretation, but I prefer to think a phinode is defined at the beginning of the enclosing block.  Probably your question is related to a concrete context.  If you share the context, it'll be easier for me to give you more useful information.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have further questions.
