### ISSUE TITLE
[Everything] Due date

### ISSUE THREAD

**Issue by pr0cf5** [kaist-cp/cs420#285]
For every project, the due date is stated as July, 8th.

Does this mean we have to submit until July, 7th 11:59PM or July, 8th 11:59PM?

thank you

**Comment by jeehoonkang** [comment]
8th of July, 11:59pm (KST = UTC+9).

**Comment by pr0cf5** [comment]
![image](https://user-images.githubusercontent.com/38807869/86554361-5920ca00-bf88-11ea-9605-4d9a2d46be87.png)
Hello, sorry for reopening this issue.
It says here that the due date is 3:00AM. Does that mean we have 3 extra hours or is it a typo?

**Comment by LockOne** [comment]
I remember that the time zone setting in gg.kaist.ac.kr was different from KST. (not sure why)
I think it will be July 8th, 11:49PM KST.
