### ISSUE TITLE
[Final Project] Using opt/opt_utils.rs in a different directory

### ISSUE THREAD

**Issue by wenko99** [kaist-cp/cs420#286]
Hi, I am currently working on register allocation. (specifically, constructing the interference graph)

And I am implementing the algorithm in a separate file, `asmgen/reg_alloc.rs`. In this file, I want to make use of the functions that I have implemented in `opt/opt_utils.rs`. However, I cannot find a clear way to use `opt/opt_utils.rs` in `asmgen/reg_alloc.rs`. 

Currently, I have just copied and pasted the codes from `opt/opt_utils.rs`.  But I think there must be a better way to use `opt/opt_utils.rs`. May I ask for any hints to do so?

Thank you in advance : )

**Comment by jeehoonkang** [comment]
- for final project, you can freely rearrange directory structure, since you're going to submit the enrtire `/src` directory.
- You can refer `opt_utils.rs` by `crate::opt::opt_utils`, if opt_utils itself is public.

**Comment by wenko99** [comment]
Thank you for the reply!

I just wanted to make my directories look clean. And I figured out that I forgot to add `pub mod opt_utils;` in `opt/mod.rs`!
