### ISSUE TITLE
[HW5] How can I manually check output of optimization for each file

### ISSUE THREAD

**Issue by robotjoaa** [kaist-cp/cs420#287]
I am trying to debug my gvn code.
I tried to use --nocapture option while test, but I it didn't work.
Is there any way that I can directly compare the output ir of optimization one by one?

**Comment by KunJeong** [comment]
The dbg! macro is a big help when debugging.
Also, I think `cargo test` tells you which test case you failed, and you could do `cargo run` on that specific test case.

**Comment by robotjoaa** [comment]
> The dbg! macro is a big help when debugging.
> Also, I think `cargo test` tells you which test case you failed, and you could do `cargo run` on that specific test case.
Sorry but my problem is that while running the test,
I think it stucks in a infinite loop, I need a debugging message but if the test can't 
stop, it does not gives the stdout. 
So can you specifically explain how to run each case with cargo run?

**Comment by lomotos10** [comment]
Running test with `-- --nocapture` should give output of each test case.

**Comment by jeehoonkang** [comment]
Closing, but feel free to reopen it if you have further questions.
