### ISSUE TITLE
[HW2] dtype of GEP

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#288]
Hi. I'm trying to support 2-D arrays in my hw2 code, but I'm confused about the dtype of GEP instruction.
here is a snippet from `examples/ir0/array2.ir`.
```llvm
%b0:i9:[5 x i32]* = getelementptr %b0:i6:[5 x i32]* offset %b0:i8:i64
%b0:i10:i32* = getelementptr %b0:i9:[5 x i32]* offset 0:i32
```
the two instructions have same dtype for base, and offsets are i32/i64. However, their return types are array/integer.
I've observed that this difference appears depending on whether the offset is zero or non-zero.

Does that mean that we should insert different dtypes into `ir::Instruction::GetElementPtr` depending on the offset value?
Thank you.

**Comment by cmpark0126** [comment]
For convenience, I will explain it in Korean first. I will translate it into English and upload it soon.

혼란스러울 수 있는 요소일 것이라 생각합니다.

우선 offset 값은 중요하지 않고, 그냥 IR로 해석하는 과정에서 임의로 선택해야 합니다.

```
  %b8:i3:i64 = mul %b8:i2:i64 20:i64 // why 20?
  %b8:i4:[5 x i32]* = getelementptr %b8:i0:[5 x i32]* offset %b8:i3:i64 // -1-
  %b8:i5:i32* = getelementptr %b8:i4:[5 x i32]* offset 0:i32 // -2-
  ...
  %b8:i8:i64 = mul %b8:i7:i64 4:i64 // why 4?
  %b8:i9:i32* = getelementptr %b8:i5:i32* offset %b8:i8:i64 // -3-
```

가령, `-1-`의 결과의 타입은 `[5 x i32]*` 입니다. `examples/ir0/array2.ir`을 보면 아시겠지만 이 결과는 추후에 `-2-`를 거쳐 `i32*`로 데이터 타입이 변환되고 `-3-`에서 operand로 사용됩니다. 중요한 점은 `getelementptr`에서 operand로 사용될 때 데이터 타입이 어떤가입니다.

`-1-`에서 보면 `getelementptr`에 앞서 index value(`%b8:i2:i64`)에 20을 곱하고 있습니다. 그 이유는 `[5 x i32]`의 사이즈가 20이기 때문입니다. 
`-2-`에서 보면 index value(`%b8:i7:i64`)에 4를 곱하고 있습니다. `i32`의 사이즈가 4이기 때문입니다. 

같은 index를 가지고도 `getelementptr`의 operand 타입이 어떠하냐에 따라서 동작이 달라집니다. 이 때문에 `[5 x i32]*`에서 `i32*`로 타입을 변환하기 위해서 `-2-`과정이 들어갑니다. 이 때 중요한 점은 0인덱스를 사용해서 실제 저장된 주소 값은 변하지 않는 것을 보장하고 타입만 변하도록 합니다.

이 작업은 IR 해석의 편의를 위해서 추가되는 작업으로 사실 offset이 0이냐 아니냐는 관계가 없습니다. 실제로 -1-의 offset인 `%b8:i3:i64`은 0이 될 수도 있습니다. 사실 만약 할 수 있다면 아래와 같이 해석하도록 하셔도 문제는 없습니다.

```
%b8:i4:i32* = getelementptr %b8:i0:[5 x i32]* offset %b8:i3:i64 // merge -1- and -2-
```

답변이 도움이 되었길 바랍니다.

**Comment by cmpark0126** [comment]
정리하자면 `[5 x i32]*`를 operand로 하는 `getelementptr`의 결과는 `[5 x i32]*` 혹은 `i32*`가 될 수 있고, 이는 해석하는 맥락에 맞게 임의로 잘 선택하시면 됩니다.

**Comment by KunJeong** [comment]
이해했습니다 친절한 설명 정말 감사합니다.
