### ISSUE TITLE
Error from test_examples_irparse

### ISSUE THREAD

**Issue by lomotos10** [kaist-cp/cs420#289]
Running `cargo test` results in the following error from test case `float2.c` in `test_examples_irparse`:
```
thread 'test_examples_irparse' panicked at 'assertion failed: `(left == right)`
  left: `Int { width: 128, is_signed: true, is_const: false }`,
 right: `Float { width: 64, is_const: false }`', src/ir/parse.rs:275:17
```

The panic can be traced to `src/tests.rs:212`:
```
    let ir0 = ir::Parse::default()
        .translate(&temp_file_path.as_path())
        .expect("parse failed while parsing the output from implemented printer");
```
which seems like a problem with the internal irgen. Can you check this issue? Thank you.

**Comment by cmpark0126** [comment]
In my case, it works well...
Could you check if your kecc is up-to-date?

**Comment by lomotos10** [comment]
It seems like it may be a hidden error in my code from back in mem2reg.
I will report as such if this fixes the issue.

**Comment by lomotos10** [comment]
I think I have found out the reason.
If float constant in ir file has no decimal point, ir::Parse returns error.

In other words, instructions like
`  %b0:i4:f32 = add 0:f32 %b0:i3:f32` will panic,
while instructions like
`  %b0:i4:f32 = add 0.0:f32 %b0:i3:f32` will not.

**Comment by LockOne** [comment]
I agree that the implementation of KECC should be changed with your patch.
The implementation of `write_ir.rs` depends on `fmt` of float,
and it seems `fmt` of float does not put a period when the value is an integer value. 

I think other students didn't make such case or just ignored it because 
`%b0:i4:f32 = add 0.0:f32 %b0:i3:f32`
is basically a nop.

**Comment by lomotos10** [comment]
I have found this affects only `test_examples_irparse` and has no effect on the other tests, or the final project benchmark.
So, this has no direct effect on any of the homework submissions.

**Comment by Lee-Janggun** [comment]
Solved by https://github.com/kaist-cp/kecc-public/commit/55ebcad3470bef66112824bf51aaabb36f28fc90
