### ISSUE TITLE
What does the --release option do?

### ISSUE THREAD

**Issue by mechu1205** [kaist-cp/cs420#29]
AFAIK building with the --release option causes the use of different configurations.
So would 'cargo build' and 'cargo build --release' create two different files?
What does the 'build result' file look like and where can I see it?
Why would one need to use the --release option while doing the homeworks?

**Comment by jeehoonkang** [comment]
- `cargo build --release` produces a release build, while `cargo build` produces a debug build.
- `target/debug/kecc` and `target/release/kecc` are the debug and release build results, respectively.
- We use `--release` for reducing the Carbon footprint.  Of course you can test your compiler with a debug build, too.
