### ISSUE TITLE
[Homework 7] How to check the test file

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#290]
Homework 7이 tester update 이후로 기존 test file(examples/ir0/array.ir의 결과 등)에 대한 결과는 보여지지 않는 것 같은데, 개별 test file에 대해서 asmgen이 잘 작동하는지 결과를 보는 방법은 없나요?

**Comment by cmpark0126** [comment]
test file에 대한 결과가 보여지지 않는다는 것이 어떤 의미인지 잘 모르겠습니다. 더 자세히 알려주실 수 있나요?

**Comment by codingskynet** [comment]
저도 비슷한 일을 겪었습니다. 업데이트 전까지는  fail 뜨면 어디 테스트 케이스까지 통과하고 어디 테스트 케이스에서 실패해서 kecc, qemu 값이 다르다 이렇게 떴습니다. 근데 업데이트 이후에는 그냥 fail 뜨면 아무 출력도 없이 단순히 테스트 실패만 뜨더라고요.

**Comment by cmpark0126** [comment]
음... 저도 정확하게 왜 그런지는 모르겠네요. @codingskynet 님께서 하신 것처럼 `cargo test -- --nocapture` 를 사용하시는 것을 추천합니다.
그리고 개별 파일에 대해서 테스트 결과를 확인하시고 싶으시면 `cargo run --bin fuzz examples/ir0/array.ir`와 같은 명령어를 쓰시면 됩니다.

**Comment by HwangSeongha** [comment]
답변 감사합니다. 혹시 개별 파일에 대해서 제 코드로 테스트한 결과가 정답인지 알 수 있는 방법은 없나요? 직접 계산해보면서 정답인지를 유추해야 하나요?

**Comment by cmpark0126** [comment]
> 그리고 개별 파일에 대해서 테스트 결과를 확인하시고 싶으시면 `cargo run --bin fuzz examples/ir0/array.ir`와 같은 명령어를 쓰시면 됩니다.

이 답변으로 해결되지 않는 문제인가요 혹시?

**Comment by HwangSeongha** [comment]
cargo run --bin fuzz examples/ir0/cmp.ir을 사용하면,
![picture](https://user-images.githubusercontent.com/48053735/86728724-a889f780-c067-11ea-8474-38de08361709.png)

와 같이 나오고 코드를 통한 어셈블리어 파일만이 만들어집니다. 이것이 통과했다는 뜻인가요?
아니면 이렇게 나온 어셈블리어 코드와 Godbolt의 결과를 비교해보아야 하나요?

**Comment by cmpark0126** [comment]
이 경우는 kecc를 사용해서 직접 어셈블리 코드를 만들고, https://github.com/kaist-cp/kecc#cross-compilation-and-architecture-emulation 에서 알려주는 방법을 사용해서 문제가 발생하는지 확인하시면 됩니다. 아마 컴파일 단계 혹은 런타임에 어떤 문제가 발생하고 있는지 메세지를 띄어줄 겁니다.

**Comment by HwangSeongha** [comment]
Link를 클릭하면 404 Error가 뜨는데 확인해주실 수 있나요?

**Comment by cmpark0126** [comment]
@HwangSeongha 고쳤습니다

**Comment by HwangSeongha** [comment]
앗 감사합니다. 그리고 영문을 모르겠는데 갑자기 kecc interp과 qemu가 잘 출력됩니다.
