### ISSUE TITLE
[Homework 7] qemu

### ISSUE THREAD

**Issue by HwangSeongha** [kaist-cp/cs420#295]
![last_picture](https://user-images.githubusercontent.com/48053735/86786006-64661980-c09e-11ea-83d3-c0b263f82746.jpg)

아래 글과 동일한 문제를 겪고 있는 학생입니다. 댓글에서 인용해주신 issue를 읽어보았는데 잘 이해가 되지 않습니다.
1. 결론적으로는 제 코드가 틀려서 생기는 문제가 맞나요? 
2. 그리고 kecc interp의 값이 제 코드를 통한 출력 값이 맞는건가요?
3. 또 simple.ir을 테스트 해보면, 같은 코드로 돌려도 kecc interp의 결과값은 계속 변하는데, qemu 값은 72로 고정되어있습니다. 친구들에게 물어보니 둘다 계속 변한다고 하는데, kecc interp의 값이 제 코드의 결과값이 맞다면 왜 저는 qemu 값이 고정될까요?
감사합니다.

**Comment by lomotos10** [comment]
왼쪽은 예제 ir를 interp.rs로 직접 실행시켜서 나온 결과,
오른쪽은 asmgen으로 생성한 .S 파일을 qemu로 실행시켜서 나온 결과입니다.
왼쪽이 정답이라 보시면 되겠습니다.

매번 정답이 달라지는 이유는,
global variable로 `int nonce = 1`이라는 변수들이 있는 예제들이 있습니다.
이 nonce 전역 변수는 프로그램 실행마다 값이 달라지는 채점용 변수이므로,
그 경우에 해당된다고 보시면 되겠습니다.
#270 을 참고하시면 좋을 것 같습니다.
