### ISSUE TITLE
[hw2] fuzzer error

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#297]
Hi. Sorry to bother you at such a late time. After passing irgen_large, I thought I had finished hw2, but I'm getting fuzzer errors.

The problem is that I cannot reduce because my program panics, but the panic comes from `'typedef should be replaced by real dtype', src/ir/dtype.rs:1246:37`. Since I cannot reduce with panics, my `test_polished.c` is huge and I cannot debug my code (more so because it passes irgen_large...). And since the panic is from ir internals, I cannot replace it with IrgenError.

Is there any workarounds for this? I cannot think of a way to fix my code in this state. Thank you.

**Comment by cmpark0126** [comment]
Maybe this link will help: https://github.com/kaist-cp/cs420/issues/170

**Comment by KunJeong** [comment]
Ah, I think the previous criteria works, though it does take a lot of time. Sorry for not thoroughly searching previous issues - I thought panic was the source of the error and panicked.

**Comment by KunJeong** [comment]
Hi again. Before, I could reduce to the smallest test case that caused the fuzzer to panic. Now, my irgen never panics, and I can't get reduce to work again.

My `cargo run --release --bin fuzz -I tests/test_polished.c` fails with assertion failed, but `python3 tests/fuzz.py -i -r` does not work again. I also tried changing the reduce criteria back to the new version, but it still doesn't work.

Can you please help me? I'm pretty sure this is almost the last bug, since I already pass average 30~40 fuzz cases on Ubuntu.

**Comment by cmpark0126** [comment]
If you pass average 30~40 fuzz cases on Ubuntu, try to submit your solution to gg.kaist.ac.kr. We only check 30 consecutive passes.

If you cannot pass the tester, please send me an email with your solution code (`irgen/mod.rs`): chunmyong.park@kaist.ac.kr

**Comment by KunJeong** [comment]
Ah that actually worked. Thank you!!
