### ISSUE TITLE
(hw2) gg.kaist.ac.kr irgen small grader gives different result with kecc

### ISSUE THREAD

**Issue by jade227** [kaist-cp/cs420#298]
Similar as #242 case 
but I uploaded irgen/mod.rs correctly
and cargo run -- -i examples/c/logical_op.c gives same result with ir0/logical_op.ir
and cargo run --bin fuzz examples/c/logical_op.c gives result like this.

kaist-cp-cs420:~/Works/kecc-public$ cargo run --bin fuzz examples/c/logical_op.c -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.14s
     Running `target/debug/fuzz examples/c/logical_op.c -i`
gcc: 1, kecc: 1

I don't know which part is in trouble.

**Comment by jeehoonkang** [comment]
Maybe try release build?  As gg uses release

**Comment by jade227** [comment]
Building done with no problem too

~/Works/kecc-public$ cargo build --release
   Compiling kecc v0.1.0 (/home/s20150342/Works/kecc-public)
    Finished release [optimized] target(s) in 11.00s

**Comment by jeehoonkang** [comment]
Try `cargo run --release --bin fuzz examples/c/logical_op.c -i`

**Comment by jeehoonkang** [comment]
In more general, I cannot see what's the problem here.  Would you please elaborate the problem you're experiencing more clearly?

**Comment by jade227** [comment]
I passed test_examples_irgen_small and the fuzzer also said no problem for my irgen/mod.rs
However, the gg.kaist.ac.kr grader gives fail for the irgen_small case.

I searched issue list to find someone who suffered same problem with me and #242 case was similar with my case.
So I tried all solution suggested from that issue but I cannot solve the problem.

**Comment by KunJeong** [comment]
Did you check the log file in gg?

**Comment by cmpark0126** [comment]
Could you send me an email with your solution code? chunmyong.park@kaist.ac.kr

**Comment by jade227** [comment]
I sent email

**Comment by cmpark0126** [comment]
@jade227 
I found what the problem is.
Maybe this link will help: https://github.com/kaist-cp/cs420/issues/35#issuecomment-641722665

**Comment by jade227** [comment]
@cmpark0126 
Ah I missed that...
The problem solved. Thank you a lot.
