### ISSUE TITLE
[HW2] function pointers vs arithmetic types

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#301]
Hi. Sorry to keep spamming..but I'm fuzz testing and I keep getting cases I don't really understand.
`void (a)() { 0 != (a); }`
The reduces gave me this case, and I'm unsure about the C specifications - are we allowed to compare function pointers with integers? Or is it just possible for zero?
Thanks.

**Comment by cmpark0126** [comment]
Please refer to this link: https://github.com/kaist-cp/cs420/issues/93#issuecomment-620403706

**Comment by KunJeong** [comment]
Thank you very much for your help.
