### ISSUE TITLE
[Final project] Score worse on gg grader

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#304]
Hello,

I know its almost deadline so I understand if there is no time to answer, but I'll ask it anyway ;)

When running gg grader my average score is roughly 20% worse than when running it using make run from the bench folder. I run it on the provided ssh-server and with updated kecc-public.

I just wanted to check if this is expected behaviour or if it indicates that I might be doing something strange when submitting to gg.

Best regards
Jesper Amilon

**Comment by jeehoonkang** [comment]
Its kinda expected; the RISC-V machine is not as beefy as the dev server.
