### ISSUE TITLE
Homework 1 Pretty Printer 

### ISSUE THREAD

**Issue by haroonrl** [kaist-cp/cs420#307]
Hi !

I am facing following issue in Homework 1 , please help me to figure out. KECC is properly build with no error. but when i ran first example program , i get the following error message:

haroon@haroon-HP-ZBook-17-G4:~/hello/kecc-public$ cargo run -- -p examples/c/fib2.c # parse

    Finished dev [unoptimized + debuginfo] target(s) in 0.05s

     Running `target/debug/kecc -p examples/c/fib2.c`

thread 'main' panicked at 'not yet implemented: homework 1', src/c/write_c.rs:45:9

note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

haroon@haroon-HP-ZBook-17-G4:~/hello/kecc-public$

**Comment by jeehoonkang** [comment]
To resolve the error, you need to fill out `writes_c.rs:45`.  It's meant to be the homework 1.

**Comment by haroonrl** [comment]
I getting  the following Error while executing this snippet: 
no field `unit` on type `std::result::Result<lang_c::driver::Parse, `lang_c::driver::Error>

`use lang_c::driver::{Config, parse,Parse};
fn main() {
 
let config = Config::default();
let ast=parse(&config, "example.c");
  

    println!("{:?}",ast);  //works

//   println!("{:?}",ast.unit);  //doest not work.  Error: no unit type field on ast

}`

**Comment by jeehoonkang** [comment]
`ast`'s type is `Result`, which doesn't have `unit` field.  See: https://doc.rust-lang.org/std/result/enum.Result.html

**Comment by haroonrl** [comment]
What does this mean by " Result of a successful parse".
https://docs.rs/lang-c/0.9.0/lang_c/driver/struct.Parse.html

```
 Struct lang_c::driver::Parse
−]
pub struct Parse {
    pub source: String,
    pub unit: TranslationUnit,
}
[−]
Result of a successful parse

Fields
source: String
[−]
Pre-processed source text

unit: TranslationUnit
[−]
Root of the abstract syntax tree
```

**Comment by jeehoonkang** [comment]
- If the returned `Result` value is `Ok`, it will contain a `Parse` value.  Otherwise, it's an `Err`.
- I suggest you first finish reading the Rust book.  Especially [this chapter](https://doc.rust-lang.org/book/ch09-02-recoverable-errors-with-result.html).

**Comment by haroonrl** [comment]
Thank you  for your comments. what made me confused is the below snippet from parser.rs

```
#[derive(Default)]
pub struct Parse {}

impl<P: AsRef<Path>> Translate<P> for Parse {
    type Target = TranslationUnit;
    type Error = Error;

    fn translate(&mut self, source: &P) -> Result<Self::Target, Self::Error> {
        let config = Config::default();
        let ast = parse(&config, source).map_err(Error::ParseError)?;
        let unit = ast.unit;    //THIS CREATED CONFUSION
	println!("{:?}",ast.unit);
        unit.assert_supported();
        Ok(unit)
    }
}
```

**Comment by jeehoonkang** [comment]
See the "?".  It's discussed in the book.  "ast" is not Result.

Also I suggest you use vscode and rls or rust-analyzer. It will show each variable's types.

**Comment by jeehoonkang** [comment]
In general, every byte counts in programs.  You probably didn't know the meaning of "?", which is an artifact of Rust.  Then you should google "Rust question mark" or similar.  Then the Rust book reference will show up and you should read it.

By the way, you need to change only the part that says something like `todo!("homework 1")`.  You can print your ast there.

**Comment by haroonrl** [comment]
Thank you, Professor, for your comments. Although, I read most of the RUST book, but need extensive exercise.

**Comment by jeehoonkang** [comment]
One more thing: you should ask questions as much detailed as possible.  For example, your last question says you are confused, but you need to explain (1) what you understood and (2) what you are confused with more clearly.  Just pointing to a line isn't clear enough.

**Comment by haroonrl** [comment]
Noted with thanks !
