### ISSUE TITLE
[Hw2] About the code in Introduction video

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#310]
I found out that there were introduction video for the assignments, and have a question about the code in [video](https://www.youtube.com/watch?v=HjARCUoK08s&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=12).
This is the code for TranslationUnit in the video 5:27.
```Rust
impl Translate<TranslationUnit> for Irgen {
    type Target = ir::TranslationUnit;
    type Error = IrgenError;

    fn translate(&mut self, _unit: &TranslationUnit) -> Result<Self::Target, Self::Error> {
        for extern_decl in &_unit.0{
            match extern_decl.node {
                ExternalDeclaration::Declaration(ref decl) => {
                    self.add_declaration(&decl.node)
                },
                ExternalDeclaration::StaticAssert(_) => panic!("StaticAssert not supported"),
                ExternalDeclaration::FunctionDefinition(ref fundef) => {
                    self.add_function_definition(&fundef.node)
                }
            };
        }

        let decls = mem::replace(&mut self.decls, HashMap::new());
        Ok(Self::Target {decls})
    }
}
```
I think this code has an error. `mem::replace` will return dest value, which is `Irgen.decls`, having type `Hashmap<String:, ir::Declaration>`. But For the return, it returns `Self::Target` typed value, which is `ir::TranslationUnit`. And `ir::Translation`'s decl field has `BTreeMap<String, Declaration>`. So the last line seems to have a type error since it is Initializing `ir::TranslationUnit`'s `decls` field which is `BTreeMap<String, Declaration>` with `HashMap<String, Declaration>`. Am I misunderstanding some structures of the code?

**Comment by jeehoonkang** [comment]
You're right---the type has been changed after the video was recorded. There are many such places where the video and the up-to-date skeleton code mismatches.

**Comment by jirheee** [comment]
Thank you professor!

**Comment by jirheee** [comment]
I also want to ask something else(I don't think this is relevant with the homework, but just for curiosity). 

At the last line of code, `memory::replace` function is being used. 
I think we can just initialize a new TranslationUnit like below.
```Rust
Self::Target {decls: self.decls, structs: self.structs}
```

Is there a special reason for this?

**Comment by jeehoonkang** [comment]
@jirheee would you please try it? If it works, please send a PR to the skeleton code.

**Comment by jirheee** [comment]
Oh that part is not from the skeleton code, it is from the video.(So I think I shouldn't send PR...?) 

My question was about the implementation: about the advantage or reason of using `memory::replace` instead of `clone`(Both seems to do the same job)

And I think I should change the code to
```Rust
Ok(
  Self::Target {
      decls: self.decls.clone(),
      structs: self.structs.clone()
  }
)
```

**Comment by jeehoonkang** [comment]
replace vs. clone: clone needs to re-create the elements, which can be costly; on the other hand, replace will just "take" the original value and doesn't re-create the elements. So the purpose of replace is optimization.

**Comment by jirheee** [comment]
Thank you professor!
