### ISSUE TITLE
[HW2] About implicit typecasting in if statement

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#311]
While translating the condition of if statement, we need to do implicitly typecast the condition expression to bool. I am little bit confused here since there is no bool type in both C and kecc ir. Should we insert instructions that checks if the instruction is 0 or not?

In addition, is there a document I can consult about kecc's typecasting rules and type merging rules? (Or is it just enough to consult the official c documentations?)

Thank you in advance :)

**Comment by jeehoonkang** [comment]
https://cp-git.kaist.ac.kr/cs420/kecc/-/blob/main/src/ir/dtype.rs#L544

**Comment by jirheee** [comment]
Thank you professor!
