### ISSUE TITLE
[Homework 1] C AST Printer (due: 4/30)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#320]
Implement C AST Printer.

- **goal**: understanding the C AST provided by KECC
- **instruction**: https://www.youtube.com/watch?v=SOzsb09GldA&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=6
- **skeleton**: https://github.com/kaist-cp/kecc-public/blob/main/src/c/write_c.rs
    + fill out `todo!()`.
    + **don't fork this repository.**  It'll be public!
- **self grader**: https://github.com/kaist-cp/kecc-public/blob/main/scripts/grade-hw1.sh
    + run `./scripts/grade-hw1.sh`.
- **submission**: https://gg.kaist.ac.kr/assignment/49/
- **due**: 4/30 23:59:59 (KST = UTC+9)
- **Rust tutorial**: https://doc.rust-lang.org/book/
    + Chapters 1-15 and 18 would be especially beneficial to read.

**Comment by minseongg** [comment]
@TanapTheTimid 

Thanks for the report. Could you please try again? We updated the permission in https://github.com/kaist-cp/kecc-public/commit/f6f156ba81047d89db43267bbea3e0cfec716d6e.

**Comment by gmlwns2000** [comment]
@jeehoonkang 
Why only the result of HW1 is nullified? Shouldn't we nullify the result of HW2 submission too? 
Thanks!

**Comment by minseongg** [comment]
@gmlwns2000

We will nullify the submissions for homework 2 after change the submission format to allow to upload `write_c.rs`.
