### ISSUE TITLE
[Question] Lab submission website's password reset functionality is not working

### ISSUE THREAD

**Issue by iamlsm97** [kaist-cp/cs420#324]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

Lab submission website's password reset functionality is not working.

As following the instruction in [registration](https://github.com/kaist-cp/cs420#registration) section, I tried to reset my password at https://gg.kaist.ac.kr/accounts/password_reset/.
But when I click "Reset my password" button, I received "Server Error (500)" response.
Please check the status of gg.kaist.ac.kr server.
FYI. My email address is lsm9706@kaist.ac.kr.

**Comment by minseongg** [comment]
It seems the server is down now. Please wait until the server is stabilized...

**Comment by minseongg** [comment]
@murat1999 Yes. We will finish the server stabilization work soon. Sorry for the inconvenience.

**Comment by jeehoonkang** [comment]
@iamlsm97 I believe a reset email has been sent to you. sorry for inconvenience.

**Comment by iamlsm97** [comment]
I received the reset email and successfully changed my password. Thanks for your support 🙂
