### ISSUE TITLE
[Question] cp-service.kaist.ac.kr:13002 is not working

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#325]
SSH server is not working. 

Even I tried to connect the server under KAIST network, the ssh server is not responding.

**Comment by minseongg** [comment]
It seems the server is down for the resource issue. We will fix it as soon as possible. Really sorry for the inconvenience...

**Comment by jeehoonkang** [comment]
it works again. we'll stabilize the servers in this week.
