### ISSUE TITLE
server network issue

### ISSUE THREAD

**Issue by Jongjunp** [kaist-cp/cs420#326]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--
I got following error message when i tried to install rustup in the server.

input command: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
output message: curl: (28) Connection timed out after 300000 milliseconds

Does this error occur because of the server problem?

**Comment by minseongg** [comment]
It seems the server network issue. We will fix it as soon as possible..

**Comment by jeehoonkang** [comment]
sorry, I believe it works again now.

though I need to re-create the machine and all your ids as well. Please clear your known SSH hosts. Sorry for the inconvenience.

I'll close this issue later when this issue is 100% resolved.

**Comment by Jongjunp** [comment]
I think the problem is solved now. It is able to build and run. Thank you !!
