### ISSUE TITLE
[Question] Git is not working on server.

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#328]
`git push` took infinite time. I think the internet connection is broken on the server... So I tried to `ping 1.1.1.1` and `ping 8.8.8.8`, and it failed to ping.

```sh
s20200535@kaist-cp-cs420:~/library/kecc-ainl$ ping 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
^C
--- 1.1.1.1 ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7154ms

s20200535@kaist-cp-cs420:~/library/kecc-ainl$ ping 8.8.8.8
PING 8.8.8.8 (8.8.8.8) 56(84) bytes of data.
^C
--- 8.8.8.8 ping statistics ---
6 packets transmitted, 0 received, 100% packet loss, time 5109ms
```

**Comment by minseongg** [comment]
There is a network issue on the server. (Similar issue: https://github.com/kaist-cp/cs420/issues/326).

We will fix it as soon as possible. Sorry for the inconvenience.

**Comment by jeehoonkang** [comment]
We'll handle this issue in #326 .
