### ISSUE TITLE
[Question] Cannot connect to the server - permission denied when trying ssh connection

### ISSUE THREAD

**Issue by O0laf** [kaist-cp/cs420#329]
Hi!
I reset my password earlier this week and tried to connect to it today morning but it output that permission is denied.
Now I am trying to register public key using ssh-copy-id but it again complains that permission is denied(publickey,password) for both my password and original password.
What should I try in this situation?
Thanks.

**Comment by minseongg** [comment]
Can you try again after remove your `~/.ssh/known_hosts`?

If it does not work, please write down your input/output/configuration in more details so that we can help you debug the connection problem.

**Comment by jeehoonkang** [comment]
- It seems the machine I used for cs420 class, was bad. I switched to another server.
- Please remove `~/.ssh/known_hosts` or similar files to successfully SSH to the server.
- The password is reset to `123454321`. use it to log in to your accounts, and change it ASAP.

**Comment by jeehoonkang** [comment]
I wish now all problems are gone. Please try again.

**Comment by O0laf** [comment]
It works now!
I really appreciate your help. :)
