### ISSUE TITLE
**IMPORTANT**: please do not fork `kaist-cp/kecc-public`

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#33]
you should not expose your work to others. In particular, you should not fork the [upstream](https://github.com/kaist-cp/kecc-public) and push there. Please read the following documentation: https://github.com/kaist-cp/cs420#tools

**Comment by jeehoonkang** [comment]
If you already forked it, please delete it to hide your development.  Thanks.

**Comment by jeehoonkang** [comment]
I'd like to ask if you could remove your forks.  Sorry for inconvenience.

@gfhd0054
@jjm7307
@kippem9088
@lumiknit
@mechu1205
@MerHS
@metamon123
@Shavakan
@zoonoo

**Comment by jeehoonkang** [comment]
Sorry for noise again, pinging @gfhd0054 @mechu1205 @metamon123

**Comment by jeehoonkang** [comment]
Sorry for noise again, pinging again @gfhd0054 @mechu1205 @metamon123

**Comment by gfhd0054** [comment]
Sorry but currently I cannot connect to my server... and I have erased my old codes and followed the instruction...

**Comment by cmpark0126** [comment]
@gfhd0054 Could you explain more detail? If you need personal help, please email me: chunmyong.park@kaist.ac.kr

**Comment by gfhd0054** [comment]
I would check my SSH condition and email later! However, I have cloned the kecc-public according to the instruction
`$ git clone --origin upstream https://github.com/kaist-cp/kecc-public.git`

Is it same with the 'fork'?

**Comment by cmpark0126** [comment]
@gfhd0054 No, `fork` means replicate git repository to your repository pool. If you use only `git clone` instruction in your private server, you don't have to worry.

**Comment by jeehoonkang** [comment]
@gfhd0054 @ktaebum friendly ping again; please remove your forked repository.
