### ISSUE TITLE
[Question] (Lab submission cannot login and reset password)

### ISSUE THREAD

**Issue by murat1999** [kaist-cp/cs420#333]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I cannot log in to the lab server, and also cannot reset my password. My student id is 20180805

**Comment by jeehoonkang** [comment]
@murat1999 please describe what you've done and experienced. is it about the SSH server or gg.kaist.ac.kr? What did you do? What did you expect, and what did it say?

**Comment by murat1999** [comment]
I did not find my password, or what is the default password? And I tried to reset my password, but the I did not receive any email

**Comment by jeehoonkang** [comment]
@murat1999 please describe what you've done and experienced. is it about the SSH server or gg.kaist.ac.kr? What did you do? What did you expect, and what did it say?

**Comment by murat1999** [comment]
can you give me the password for lab website?

**Comment by murat1999** [comment]
I think I do not have account in lab website. Or can you give me the id and password? @jeehoonkang

**Comment by jeehoonkang** [comment]
@murat1999 I wish you could answer my questions more specifically. I asked "is it about the SSH server or gg.kaist.ac.kr?", and you replied "I did not find my password, or what is the default password? And I tried to reset my password, but the I did not receive any email" and "can you give me the password for lab website?".

I can "guess" (for 90% sure) what you've meant from the context, but I'd like to ask for another round of clarification.

- please describe what you've done and experienced. it's better to paste URL you accessed or SSH command you've entered.
- is it about the SSH server or gg.kaist.ac.kr? The answer should be "SSH server", "gg.kaist.ac.kr", or "neither".

**Comment by murat1999** [comment]
It is about https://gg.kaist.ac.kr/accounts/login/?next=/

**Comment by jeehoonkang** [comment]
@murat1999 at the url, what did you do? please describe the situation in as much as details. It's inefficient for us to guess what happened in your machine. Otherwise, I cannot help continuing to ask "what happened?"

**Comment by murat1999** [comment]
for the username I typed my email and id, and for password I tried my student id, default 123454321 but it did not work out. I tried to reset my password but the email did not send.

**Comment by murat1999** [comment]
I missed the first 2 lectures and I do not know what is the default password for lab submission website

**Comment by Lee-Janggun** [comment]
I just successfully reset my password. For the email, did you use your KAIST email?

**Comment by murat1999** [comment]
now I reset my password, but this error shows me
<img width="1053" alt="Снимок экрана 2022-03-07 в 08 39 52" src="https://user-images.githubusercontent.com/40897372/156958542-35984eb4-4acd-4617-b725-aba1ce1e3852.png">

**Comment by murat1999** [comment]
It works. I used https://gg.kaist.ac.kr/ without any path
