### ISSUE TITLE
[Question] Attendance grading

### ISSUE THREAD

**Issue by murat1999** [kaist-cp/cs420#335]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

1. I wanted to know whether attendance will be in grading since 80% is homework and 205 is the final exam. Do we have to submit attendance quizzes?
2. And can we get partial scores on homework assignments?

**Comment by jeehoonkang** [comment]
- you should answer the attendance quizzes. if you miss too many quizzes, you're going to be deducted. missing 3-4 quizzes will be fine (no deduction).
- no partial scores for each homework assignment.

**Comment by murat1999** [comment]
can I get at least some points if for example I pass som etest cases? Or is it either full or zero?

**Comment by jeehoonkang** [comment]
No partial points.
