### ISSUE TITLE
[Question] Recorded lectures (2022)

### ISSUE THREAD

**Issue by nybunny** [kaist-cp/cs420#336]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

Will the recorded lectures be uploaded somewhere?

**Comment by jeehoonkang** [comment]
I'm not entirely sure whether I'll upload the videos. I believe they are not so much different from the 2020 videos, though... I'll keep this open until I decide and announce the policy for the 2022 videos.

**Comment by jeehoonkang** [comment]
I'd like **NOT** to make the 2022 videos public. The primary reason is they are almost the same as the 2020 videos. Sorry for the inconvenience.
