### ISSUE TITLE
[Question] About assignment schedule

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#338]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

It seems that there will be other homework released before the hw1 due since the due is 4/30 and we have 8 assignments. Are there any tentative schedules for the assignments?

**Comment by jeehoonkang** [comment]
Many of the homework assignments will be due right after the final exam period. A few will be due in May.

**Comment by murat1999** [comment]
so each assignment weights 10%? @jeehoonkang

**Comment by jeehoonkang** [comment]
@murat1999 all assignments will have the same weight. irgen and asmgen may have "small" variants that have the same weight as well, though.
