### ISSUE TITLE
[Homework 2] IR Generation (due: 5/31)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#341]
Implement IR generation.

- **goal**: understanding the IR provided by KECC
- **instruction**
    + https://www.youtube.com/watch?v=HjARCUoK08s&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=12
    + https://www.youtube.com/watch?v=Rszt9x0Xu_0&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=13
- **skeleton**: https://github.com/kaist-cp/kecc-public/blob/main/src/irgen/mod.rs
    + fill out `todo!()`.
    + **don't fork this repository.**  It'll be public!
- **self grader**
    + https://github.com/kaist-cp/kecc-public/blob/main/scripts/grade-hw2-small.sh (small)
    + https://github.com/kaist-cp/kecc-public/blob/main/scripts/grade-hw2.sh
- **submission**: run `./scripts/make-submissions.sh` and then submit `hw2.zip`.
    + https://gg.kaist.ac.kr/assignment/50/ (small)
    + https://gg.kaist.ac.kr/assignment/51/
- **due**: 5/31 23:59:59 (KST = UTC+9)
- **note**: I suggest you begin with the small hw2 and then move on to the full hw2. Each of the small and full hw2 assignments has the same weight as the other assignments.
- **model solution**: submit C files to https://gg.kaist.ac.kr/assignment/58/ .

**Comment by TanapTheTimid** [comment]
I am getting this error:
```
---- test_examples_irgen_small stdout ----
[testing "examples/c/typecast.c"]
thread 'test_examples_irgen_small' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', src/tests.rs:138:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Since it's in `src/tests.rs` I don't think it's my mistake. The test runs fine locally.

**Comment by jeehoonkang** [comment]
@TanapTheTimid it's now resolved. thanks for the report!

**Comment by TanapTheTimid** [comment]
I have another issue with the irgen *full* grader. The grader process is stuck with return code: None, and the status says "checking" forever on the submission page. The logs looks fine to me, it passes all tests and the fuzzer reaches 30 cases.

The output looks like this:

```
running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/test_examples.rs (target/release/deps/test_examples-dd2b560e79caef77)

running 2 tests
test test_examples_irgen_large ... ok
test test_examples_irgen_small ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 8.78s

    Finished release [optimized] target(s) in 0.03s
Building KECC..
Fuzzing with 30 test cases.
Test case #0 (skipped: 0)
Test case #1 (skipped: 0)
Test case #1 (skipped: 1)
Test case #2 (skipped: 1)
Test case #3 (skipped: 1)
Test case #3 (skipped: 2)
Test case #4 (skipped: 2)
Test case #4 (skipped: 3)
Test case #5 (skipped: 3)
Test case #6 (skipped: 3)
Test case #7 (skipped: 3)
Test case #8 (skipped: 3)
Test case #9 (skipped: 3)
Test case #10 (skipped: 3)
Test case #11 (skipped: 3)
Test case #12 (skipped: 3)
Test case #12 (skipped: 4)
Test case #13 (skipped: 4)
Test case #14 (skipped: 4)
Test case #15 (skipped: 4)
Test case #15 (skipped: 5)
Test case #16 (skipped: 5)
Test case #17 (skipped: 5)
Test case #17 (skipped: 6)
Test case #18 (skipped: 6)
Test case #19 (skipped: 6)
Test case #20 (skipped: 6)
Test case #20 (skipped: 7)
Test case #20 (skipped: 8)
Test case #20 (skipped: 9)
Test case #20 (skipped: 10)
Test case #20 (skipped: 11)
Test case #20 (skipped: 12)
Test case #21 (skipped: 12)
Test case #22 (skipped: 12)
Test case #23 (skipped: 12)
Test case #23 (skipped: 13)
Test case #23 (skipped: 14)
Test case #24 (skipped: 14)
Test case #25 (skipped: 14)
Test case #25 (skipped: 15)
Test case #26 (skipped: 15)
Test case #26 (skipped: 16)
Test case #27 (skipped: 16)
Test case #28 (skipped: 16)
Test case #29 (skipped: 16)
Test case #29 (skipped: 17)
Test case #30 (skipped: 17)
```

**Comment by jeehoonkang** [comment]
@TanapTheTimid strange, would you please submit your solution once again?

**Comment by TanapTheTimid** [comment]
@jeehoonkang I've submitted again twice and got the same result.

**Comment by gmlwns2000** [comment]
#314 #256 #106 #78 
There is an extra explanation for HW2 in previous issues. I left this comment just for someone who couldn't found them (include me :( )

**Comment by jirheee** [comment]
When are other assignments coming out..? I believe assignments untill 4 should have been out before the midterm period since there are total 8 assignments. The workload will explode if everything comes out at once 😢 I'm sorry for urging, but I am just worried about the schedule..

**Comment by jeehoonkang** [comment]
**CRUCIAL**: since the grader has been updated, all previous submissions were nullified. PLEASE SUBMIT YOUR SOLUTION AGAIN. Please read `README.md` to submit your solution.

**Comment by jeehoonkang** [comment]
**CRUCIAL**: now you can check the model solution here: https://gg.kaist.ac.kr/assignment/58/

**Comment by ljb7977** [comment]
Can we follow the skeleton codes in the model solution described in the instruction videos? or we should design and implement our own structure?

**Comment by minseongg** [comment]
@ljb7977 You can follow the skeleton codes in the instruction videos.

**Comment by ljb7977** [comment]
@minseongg Thanks!
