### ISSUE TITLE
[Question] Question about SSA and 

### ISSUE THREAD

**Issue by Jongjunp** [kaist-cp/cs420#342]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--
In class, I didn't get a clear concept of SSA and its motivation.
I hope to get additional comments about SSA and its motivation.

Also, I have a question about lecture slide 33.
In the slide, %var's value can not be changed, because a register is only defined at most once in a code.
Then, Does variable 'i' assigned to memory instead of register?

**Comment by jeehoonkang** [comment]
I believe this question was answered in the previous session. If so, please close the issue; otherwise, please ask follow-up questions. Thanks!
