### ISSUE TITLE
[Question] About `Named<ir::Dtype>` in `add_declaration` for `resolved_typedefs`

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#343]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I was trying to follow the given videos to implement Irgen.

While doing it, I ran into this piece of code to resolve typedefs in the dtype we infered from declarators and specifiers:
```rust
let dtype = base_dtype
      .clone()
      .with_ast_declarator(declarator)
      .map_err(|e| {
          IrgenError::new(
              source.write_string(),
              IrgenErrorMessage::InvalidDtype { dtype_error: e },
          )
      })?;

let dtype = dtype
    .resolve_typedefs(&self.typedefs, &self.structs)
    .map_err(|e| {
        IrgenError::new(
            source.write_string(),
            IrgenErrorMessage::InvalidDtype { dtype_error: e },
        )
    })?;
```

But the code didn't compile with this error:
```
cannot move out of dereference of `ir::Named<dtype::Dtype>`
move occurs because value has type `dtype::Dtype`, which does not implement the `Copy` traitrustc[E0507](https://doc.rust-lang.org/error-index.html#E0507)
```

I first thought this is because resolve_typedefs takes the ownership of the `dtype` because it takes `self` in the implemetation, so tried to `clone` it first, then call `resolve_typedefs`, But it didn't work. 

So I tried below workaround: first create a empty `ir::Dtype`, then clone the dtype from `Named<ir::Dtype>`. 

```rust
let mut d = ir::Dtype::default();
d.clone_from(&dtype);

let dtype = d
    .clone()
    .resolve_typedefs(&self.typedefs, &self.structs)
    .map_err(|e| {
        IrgenError::new(
            source.write_string(),
            IrgenErrorMessage::InvalidDtype { dtype_error: e },
        )
    })?;
```

It seems like it compiles, but I still have a question. Is this the right way to do it? (I don't even get why this works at all... haha...) Or am I misunderstanding rust's memory management and there is a better way of doing this?

**Comment by minseongg** [comment]
> I first thought this is because resolve_typedefs takes the ownership of the `dtype` because it takes `self` in the implemetation, so tried to `clone` it first, then call `resolve_typedefs`, But it didn't work. 

The cause of compilation error is that `Named<Dtype>` cannot be coerced to `Dtype`.

After the first declaration of `dtype`, type of `dtype` is `Named<Dtype>`.

In the next declaration of `dtype`, it calls the method `resolve_typedefs` which takes `self` for the argument. So `dtype` should have a type which can be coerced to `Dtype`. However, `Named<Dtype>` cannot be coerced to `Dtype` and it fails to compilation.

```rust
// `dtype` has `Named<Dtype>` type.
let dtype = base_dtype
      .clone()
      .with_ast_declarator(declarator)
      .map_err(|e| {
          IrgenError::new(
              source.write_string(),
              IrgenErrorMessage::InvalidDtype { dtype_error: e },
          )
      })?;

// `Named<Dtype>` cannot be coerced to `Dtype`.
let dtype = dtype
    .resolve_typedefs(&self.typedefs, &self.structs)
    .map_err(|e| {
        IrgenError::new(
            source.write_string(),
            IrgenErrorMessage::InvalidDtype { dtype_error: e },
        )
    })?;
```

Since `Named<T>` implements `Deref<Target=T>` ([mod.rs#L861-L867](https://github.com/kaist-cp/kecc-public/blob/main/src/ir/mod.rs#L861-L867)), `&Named<Dtype>` can be dereferenced to `&Dtype`. Therefore, one way to solve the error is that clone after deref. (This is actually your workaround.)

e.g)

```rust
use std::ops::Deref;

// `dtype` has `Dtype` type.
let dtype = base_dtype
      .clone()
      .with_ast_declarator(declarator)
      .map_err(|e| {
          IrgenError::new(
              source.write_string(),
              IrgenErrorMessage::InvalidDtype { dtype_error: e },
          )
      })?
      .deref()
      .clone();

let dtype = dtype
    .resolve_typedefs(&self.typedefs, &self.structs)
    .map_err(|e| {
        IrgenError::new(
            source.write_string(),
            IrgenErrorMessage::InvalidDtype { dtype_error: e },
        )
    })?;
```

**Comment by jirheee** [comment]
Thank you! Now I understand what is happening 👍
