### ISSUE TITLE
[Question] Why is 100 characters the default limit for code width in rust?

### ISSUE THREAD

**Issue by ShinWonho** [kaist-cp/cs420#344]
Hello.

I'm used to coding with 80 characters for the line limit, and it is standard line limit as I know.

However, the default limit is 100 in rust.

Is there any reason for this?

**Comment by jeehoonkang** [comment]
displays are larger than before, so many programming projects set 100 characters as the default line limit. Rust does that, too. We didn't intend to change Rust's default.

**Comment by ShinWonho** [comment]
Thank you for the answer!
