### ISSUE TITLE
[HW1] Debugging failed fuzzer test: test_reduced.c generates nonsense code

### ISSUE THREAD

**Issue by aehnh** [kaist-cp/cs420#345]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

All the provided example tests passed, so I ran the fuzzer:

```
$ python3 tests/fuzz.py -p
```

But it fails with the following error:

```
Fuzzing with infinitely many test cases.  Please press [ctrl+C] to break.
Test case #0 (skipped: 0)
Traceback (most recent call last):
  File "tests/fuzz.py", line 280, in <module>
    fuzz(tests_dir, fuzz_arg, args.num)
  File "tests/fuzz.py", line 238, in fuzz
    raise Exception("Test `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Test `cargo run --features=build-bin --release --bin fuzz -- -p /home/s20150910/kecc-public/tests/test_polished.c` failed with exit code 101.
```

When I reduced the polished code with the following command:
```
$ python3 tests/fuzz.py -p -r
```
The C code in the `test_reduced.c` file doesn't make much sense semantically:
```
char a { b((c, d)); }
```
Nevertheless, my implementation successfully reproduces the reduced code:
```
$ cargo run --features="build-bin" -- -p tests/test_reduced.c
```
```
char a
{
  b(c, d);
}
```

Since test_reduced.c isn't very helpful in this case, I was wondering if there are any other ways to debug the failure of my implementation.  I ran the fuzzer/reducer multiple times and it generates similar code every time.

**Comment by minseongg** [comment]
The problem that the fuzzer generates nonsense code is fixed in https://github.com/kaist-cp/kecc-public/commit/bce209c613e432430866a7500fda35ac27e1e055.
