### ISSUE TITLE
[Question] Aren't we going to check attendance today?

### ISSUE THREAD

**Issue by novwaul** [kaist-cp/cs420#347]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

Aren't we going to check attendance today?
I'm asking because there is no quiz coming up at gg.kaist.ac.kr.
Thanks!

**Comment by jeehoonkang** [comment]
https://github.com/kaist-cp/cs420/issues/319#issuecomment-1068787637
