### ISSUE TITLE
[Question] Our prof.'s aura

### ISSUE THREAD

**Issue by nybunny** [kaist-cp/cs420#348]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

Where is the professor's aura?
Also there was an attendance check sheet for COVID19 at the back of the classroom. If we checked our place & date on that paper but failed to answer the attendance quiz, what will our attendance record for the day's lecture be?

**Comment by minseongg** [comment]
The answer is "belly".

The attendance check sheet for COVID19 does not affect the attendance record, you need to pass the attendance quiz.
