### ISSUE TITLE
[Question] (Expression::SizeOfTy)

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs420#349]
While doing HW1, I was implementing `WriteString` for `Expression`.
I used pattern matching like this:
```
match self {
...
Self::SizeOf(_) => todo!(),
...
}
```
, and my rust-analyzer vomits this error message:
> no variant or associated item named `SizeOf` found for enum `lang_c::ast::Expression` in the current scope
> variant or associated item not found in `lang_c::ast::Expression`
> variant or associated item not found in `lang_c::ast::Expression`rustc[E0599](https://doc.rust-lang.org/error-index.html#E0599)
> [write_c.rs(286, 19): ]()there is a variant with a similar name: `SizeOfTy`

However, when I looked at [ast::Expression documentation](https://docs.rs/lang-c/0.5.2/lang_c/ast/enum.Expression.html), it indicates that enum `Expression` has SizeOf varient.
What should I do?

**Comment by minseongg** [comment]
You're now looking at an old version of `lang-c` crate documentation. (0.5.2)

We're using `lang-c` crate with version 0.11.0 ([Cargo.toml#L34](https://github.com/kaist-cp/kecc-public/blob/main/Cargo.toml#L34)), so please look at the latest version of documentation.

In the latest version of documentation, `SizeOf` variant is splitted into `SizeOfTy` and `SizeOfVal`. (https://docs.rs/lang-c/latest/lang_c/ast/enum.Expression.html)

**Comment by woojinnn** [comment]
thanks!
