### ISSUE TITLE
[Question] Online console for kecc

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#352]
I think it is good that if there is an online console for `kecc` just like [compiler explorer](https://godbolt.org/). I understand that not providing an actual binary of `kecc` because of the risk of decompiling or some reverse engineering (but I am sure reverse engineering rust binary is much harder than just solving homework :D ).

It is very hard to create my own example of IRgen result instead of using pre-generated IR files in `examples/ir*/*`. I want to investigate how my compiler works differently with `kecc`. I think this would be really helpful to understand how a compiler works and how to implement my solution.

I was **relatively** easily working with a small test set because there are no structs (which is a very high-level object on IR). It was kind of easy to work with simple data types such as `int` and `float` (but they were still complicated because of implicit legacies.) because they are easy to think about IR code (alloc./load/store -> typecast -> unary/binary operation -> repeat). I am not familiar with IR codes so, I could not expect how the IRgen result should be on my own example (I wanna try to find edge cases too).

**Comment by minseongg** [comment]
We discussed about it today. One way considered is to add a feature that generates IR output by submitting a C input program into [gg.kaist.ac.kr](https://gg.kaist.ac.kr).

We're now thinking about the policy. We'll notice about it when there's an update.

**Comment by gmlwns2000** [comment]
@jirheee Thank you for your response, the [Compiler Explorer](https://godbolt.org/) was really useful.
@minseongg However, it is good to hear! 
I think many try-and-error during constructing basic feature of compiler could be removed by providing IR code console! I hope to see it :)

**Comment by jeehoonkang** [comment]
https://gg.kaist.ac.kr/assignment/58/
