### ISSUE TITLE
[Question] [HW2] Express constant in KECC IR

### ISSUE THREAD

**Issue by hyn2028** [kaist-cp/cs420#354]
I'm currently dealing with initializers of ***global variables***.

Looking at the 2020 video, the type of ```ir::Declaration::Variable::initializer``` is expected to be ```Option<ir::Constant>```. However, in newer versions of KECC this has been changed to ```Option<ast::Initializer>```.

Looking at 2020, that initializer should be a complete constant that does not need to be processed anymore, but the latest version seems to just throw the Initailizer right away.

If I just put the initilizer obtained from C AST as it is, does another step (after IRGen stage) change it to a constant and handle an error later? Or do I have to arbitrarily handle only ```initializer::Expression::constant``` ?

If I do not deal with, ```int a = -3 + 1``` will be ```var i32 @a = ((-(3)) + (1))``` . Is this a valid KECC IR form?

If not, why did you change the type from ```Option<ir::Constant>```  to ```Option<ast::Initializer>``` to add degrees of freedom?

Thank you.

**Comment by minseongg** [comment]
The purpose of replacing `Option<ir::Constant>` to `Option<ast::Initializer>` is supporting list initializer. (`int a[5] = {1, 2, 3, 4, 5};`)

However, as you mentioned, the current KECC IR does not support every constant expression. (including `-3 + 1`) So it is a bug of KECC, we are planning to update the [src/c/parse.rs](https://github.com/kaist-cp/kecc-public/blob/main/src/c/parse.rs) to restrict the form of the expression of initializer and change the type for IR initializer to resolve that degree of freedom issue.

For now, you can assume that initializer for global variables consists of single numbers. (`int a = -1`, `float b = 0.3`, `int c[5] = {1, 2, 3, 4, 5}`, ...)

Sorry for the inconvenience. Thanks for reporting!

**Comment by hyn2028** [comment]
So, in the case of global variables, you're going to update the C parser to treat non-constant initializers as syntax errors in C code? 
In other words, (if I don't care about the array initializer) can I interpret it as only having to implement the case of ```initializer::Expression::constant``` for the global variable initializer?

**Comment by minseongg** [comment]
> So, in the case of **global variables**, you're going to update the C parser to treat **non-constant initializers as syntax errors** in C code? 

Yes. We will not support it for this semester.

> In other words, (if I don't care about the array initializer) can I interpret it as only having to implement the case of ```initializer::Expression::constant``` for the global variable initializer?

`Expression::Constant` and `Expression::UnaryOperator` with `UnaryOperator::Minus` op. (for supporting negative value such as `-1`)

**Comment by hyn2028** [comment]
Thanks for your kind reply. The problem has been clearly resolved.

**Comment by minseongg** [comment]
We updated C parser to restrict the form of global initializer. https://github.com/kaist-cp/kecc-public/commit/6c2adf84ed4c5e2efb9e1f742bf797ac99cd88aa
