### ISSUE TITLE
[Question, HW2] Why does UnaryOpeartor::Complement is not working on kecc?

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#355]
Should I convert `UnaryOperator::Complement` to `UnaryOperator::Negate`?
If so then, I think it is good to add complement operation on to test cases. 
I have never encountered this error before running fuzz.

-- edit --

I convert to negate, and I found out interpreter only supports negate operation for u1... How can I implement complement?

**Comment by minseongg** [comment]
There are some ways to represent `~x` with other operators.

For example, `~x = x ^ (-1)`.

**Comment by gmlwns2000** [comment]
@minseongg Thank you for the feedback.
And I think it is good to add `sizeof(a++)` into examples too!

**Comment by minseongg** [comment]
We added complement example. https://github.com/kaist-cp/kecc-public/commit/c8813ac7a2c95913b710b87136209e6b2b43e399
