### ISSUE TITLE
[HW2] How can I debug interpreter assertion?

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#356]
![image](https://user-images.githubusercontent.com/4879345/159911924-4b61f956-1320-43d2-a912-75e8c8f8fa77.png)
```
4: kecc::ir::interp::calculator::calculate_binary_operator_expression
             at ./src/ir/interp.rs:619:17
```

I am trying to debug my compiler on fuzz. However, I encounter a typecast error. I think I miss typecast somewhere :( So I know what is problem but I cannot know **where** is the problem. I think if the interpreter prompts the current cursor location when error then it is very good to debugging. 

However, I am going to comment `test_polished.c` partially to find out the error line.

**Comment by minseongg** [comment]
Could you try to reduce the buggy program by `python3 tests/fuzz.py -i -r`?

**Comment by gmlwns2000** [comment]
```c
int main() {
  if ((105 | 5) % 5)
    return 1;
}
```

Wow, it emits errors too! This is my first time using reduce tool. Thank you.

I will try to fix this error first.

**Comment by minseongg** [comment]
> My generated IR code is following, and I think the typecasting is suspicious. Should I convert to boolean by manually? (`value == 0`)

Yes.
