### ISSUE TITLE
[HW2] Fuzz: fuzz created not useful code.

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#357]
- Fuzz result:
```c
int main() { 0x1p49f / 0; }
```

- kecc/fuzz result:
![image](https://user-images.githubusercontent.com/4879345/159928777-6ca3e620-c6e1-411b-99ae-dce2f3668a32.png)

- gcc result:
![image](https://user-images.githubusercontent.com/4879345/159928643-e670aa40-0c45-4c1f-9f05-a2eb3642ca6a.png)

The reduced code generates errors in both GCC and kecc. Therefore I think this code is running well on my compiler...
What is happening here?

**Comment by minseongg** [comment]
Fixed in https://github.com/kaist-cp/kecc-public/commit/448335dc39696dcf6b255c724f455e9766c46802.

**Comment by gmlwns2000** [comment]
@minseongg it seems fixed :)
