### ISSUE TITLE
[FUZZ] How can I speed up fuzz?

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#359]
# Make gcc and clang less optimize

In `reduce-cirteria-template.sh`, there is three call of `gcc` and `clang`.
1. `gcc` in line 9
2. `clang` in line 17
3. `gcc` in line 40

So I tried to add flag `-O0` to each lines.

0. default: `5:23`
1. `-O0` in `2`: `5:15`
2. `-O0` in `2, 1`: `5:13`
3. `-O0` in `2, 1, 3`: `4:40`

So if I set `-O0` to all compile, I could save 40 seconds.

# `-O0` is predictable, while `-O1` doesn't

#360 , I encountered undefined behavior of the compiler. So `fuzz` failed, since my `kecc` generates only predictable results, while `clang` generates random results on undefined local/global variables.

**Comment by minseongg** [comment]
We updated the test code to use `-O0` instead of `-O1` and `-O2`. (https://github.com/kaist-cp/kecc-public/commit/c4ec2c7881de5e1b766e7ee2977ecc1364aedbfd)
