### ISSUE TITLE
[HW2] `fuzz -n30` seems not enough to filter out bad compiler

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#361]
# Lucky day :)
I know my IR generator is very bad, but it is passing over 30 cases sometimes even without `--easy` flag (my best record is 291 cases). 
So if someone is very lucky, then they would be passed. 

# Seed fixation required.
Also for reproducibility and fairness, I think seed fixation is required for fuzz in grader.

**Comment by minseongg** [comment]
We updated grader to test for 80 test cases and fixed seed. https://github.com/kaist-cp/kecc-public/commit/bd581d09e959b670cc18a78b99e33e4293aaccc5
