### ISSUE TITLE
[HW2] `xor -> typecast -> shr` instruction seems not good.

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#362]
# `xor -> typecast -> shr` produce wrong result.

```c
int main() {
  return ((int)(~((unsigned char)0))) >> 1;
}
```
```llvm
block b0:
  %b0:i0:u8 = typecast 0:i32 to u8                   //should be 0u8
  %b0:i1:u8 = xor %b0:i0:u8 255:u8                   //should be 255u8
  %b0:i2:i32 = typecast %b0:i1:u8 to i32
  %b0:i3:i32 = shr %b0:i2:i32 1:i32
  ret %b0:i3:i32
}
```
output => 255
clang => 127

In this code, `%b:i1:u8` should be `255u8`. In [ir/interpt.rs#481](https://github.com/kaist-cp/kecc-public/blob/271e95ab1d63bb603c1e38a836ecaa7f472adae6/src/ir/interp.rs#L481), `ast::BinaryOperator::BitwiseXor => lhs ^ rhs,`. Therefore actual value container (`u128`) gonna be `0u128 ^ 255u128 = 255u128`. So it must be fine. Lets check other operations.

# First, I only left `shr`
```c
int main() {
  return 255 >> 1;
}
```
```llvm
block b0:
  %b0:i0:i32 = shr 255:i32 1:i32
  ret %b0:i0:i32
```
output => 127
clang => 127

# Second, I only left `typecast -> shr`
```c
int main() {
  return ((int)((unsigned char)255)) >> 1;
}
```
```llvm
block b0:
  %b0:i0:u8 = typecast 255:i32 to u8
  %b0:i1:i32 = typecast %b0:i0:u8 to i32
  %b0:i2:i32 = shr %b0:i1:i32 1:i32
  ret %b0:i2:i32
```
output => 127
clang => 127

# Therefore `typecast -> xor -> typecast` operation seems problem

I think when xor operation is performed, the bits in u128 is going wrong.

**Comment by minseongg** [comment]
For the first example, you wanted to say that the return value of the output is 127 and of the clang is 255, right? Then it seems there is no problem with IR interpreter. I think the problem comes from integer promotion.

In the C specification 6.5.3.3, it says that integer promotions are performed on the operand. 

> The result of the ~ operator is the bitwise complement of its (promoted) operand (that is, each bit in the result is set if and only if the corresponding bit in the converted operand is not set). The integer promotions are performed on the operand, and the result has the promoted type.

Therefore, you need to perform `xor` for the `i32` instead of `u8`.

**Comment by gmlwns2000** [comment]
@minseongg First of all, thank you for your answer!!

> For the first example, you wanted to say that the return value of the output is 127 and of the clang is 255, right? 

The clang result is 127, and my result was 255 for 
```llvm
block b0:
  %b0:i0:u8 = typecast 0:i32 to u8                   //should be 0u8
  %b0:i1:u8 = xor %b0:i0:u8 255:u8                   //should be 255u8
  %b0:i2:i32 = typecast %b0:i1:u8 to i32
  %b0:i3:i32 = shr %b0:i2:i32 1:i32
  ret %b0:i3:i32
```

As you mentioned, I fix the broken integer promotion (I miss it when hard code XOR in Complement operation :( ). But still the error is coming out...
```llvm
  %b0:i0:u8 = typecast 0:i32 to u8
  %b0:i1:i32 = typecast %b0:i0:u8 to i32
  %b0:i2:i32 = typecast 255:u8 to i32
  %b0:i3:i32 = xor %b0:i1:i32 %b0:i2:i32
  %b0:i4:i32 = shr %b0:i3:i32 1:i32
  ret %b0:i4:i32
```

This looks just fine for me...

**Comment by minseongg** [comment]
> The clang result is 127, and my result was 255

That's weird because the clang result is 255 in my environment..

> As you mentioned, I fix the broken integer promotion (I miss it when hard code XOR in Complement operation :( ). But still the error is coming out...

That's because you need to xor with 4294967295 (2^32 - 1), not 255 (2^8 - 1).

**Comment by gmlwns2000** [comment]
@minseongg , Before you leave the comment I appended the previous comment. Could you check it?

> That's weird because the clang return value of below program is 255 in my environment..

That's weird. I manually compiled clang, and it got `255`..., but the output of clang in fuzz is `127`...
```bash
s20200535@kaist-cp-cs420:~/library/kecc-ainl/tests$ clang -O1 test_reduced.c 
s20200535@kaist-cp-cs420:~/library/kecc-ainl/tests$ ./a.out
s20200535@kaist-cp-cs420:~/library/kecc-ainl/tests$ echo $?
255
```

> That's because you need to xor with 4294967295 (2^32 - 1), not 255 (2^8 - 1).

Even if so, the left-hand side was an 8bit register, therefore there is no reason there is some kind of bit over 8bit field.

**Comment by minseongg** [comment]
> That's weird. I manually compiled clang, and it got `255`..., but the output of clang in fuzz is `127`...

What is the output of `cargo run --features=build-bin --bin fuzz -- -i <C FILE>`? Also, could you try the same command in the latest kecc-public with modified `src/c/write_c.rs` and `src/irgen/mod.rs` to your implementation?

> Even if so, the left-hand side was an 8bit register, therefore there is no reason there is some kind of bit over 8bit field.

Let me explain more details about it. Following is the semantic of ~ operator in the C specification. (6.5.3.3)

> The result of the ~ operator is the bitwise complement of its (promoted) operand (that is, each bit in the result is set if and only if the corresponding bit in the converted operand is not set). The **integer promotions are performed on the operand**, and **the result has the promoted type**. If the promoted type is an unsigned type, the expression `~E` is equivalent to the maximum value representable in that type minus `E`.

According to the semantics, we do not need to convert the result to the original type of the operand. For example, the result of `~((unsigned char)0)` expression has `int` type with `0xffffffff`. This is the reason why I mentioned that you need to do xor with 4294967295 instead of 255. (the result is 32bit, not 8bit.)

Also, the correct return value of the program is 255. I recommend you to think about the reason.

**Comment by gmlwns2000** [comment]
> What is the output of cargo run --features=build-bin --bin fuzz -- -i <C FILE>? 

The clang result seems fine now! It is now `255` as expected, and my kecc IR emit `255` as expected too.

> Let me explain more details about it. Following is the semantic of ~ operator in the C specification. (6.5.3.3)

Yes now I understand how it is going on `~`. I was confused because `clang` result showed nonsense value.
Thank you so much for helping! I really study a lot about compiler now :) I am happy.
