### ISSUE TITLE
[HW2] GG: Please allow me to upload `write_c.rs` in HW2 for compatibility with HW1 impl.

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#363]
I just tried to submit my code to gg small task, but I find out `write_c.rs` in the grading script is different to mine.

However, my `mod.rs` is heavily dependent on `write_c.rs`, because of writing debugging error messages.

Could you allow me to submit `write_c.rs`? I think my `write_c.rs` is different to the grading script...

--edit--

I fix this problem by just manually removing all `*.write_string()` function call in `irgen/mod.rs`.
However, I hope the grader inputs previous homework too, since further homework may depend on previous homework especially `write_c.rs`. It is really useful when generating debug messages :)

**Comment by minseongg** [comment]
As the professor said in class, we will allow to upload `write_c.rs` file for the homework 2.

**Comment by jeehoonkang** [comment]
@hyn2028 @gmlwns2000 I believe this issue has been fixed. Would you please have a look?

**Comment by gmlwns2000** [comment]
Thank you for the update! I think the zip command is not working in the server.

```bash
s20200535@kaist-cp-cs420:~/library/kecc-ainl$  ./scripts/make-submissions.sh
./scripts/make-submissions.sh: line 7: zip: command not found
./scripts/make-submissions.sh: line 8: zip: command not found
./scripts/make-submissions.sh: line 9: zip: command not found
./scripts/make-submissions.sh: line 10: zip: command not found
./scripts/make-submissions.sh: line 11: zip: command not found
./scripts/make-submissions.sh: line 12: zip: command not found
s20200535@kaist-cp-cs420:~/library/kecc-ainl$ zip
bash: zip: command not found
```

**Comment by minseongg** [comment]
@gmlwns2000 We installed `zip` and `unzip` in the server. Could you try again?

**Comment by gmlwns2000** [comment]
I tried it and it works well including GG submission! Thank you!
