### ISSUE TITLE
[Question] Question about local variable allocation

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#364]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I was working on the test case `fib2.c`, and I found something strange is happening to my translated ir.

It works well(when you run the test code), but when I compare my translated result and `examples/ir0/fib2.ir`, there is small difference which is found as below.

```
--- result.ir   2022-03-28 17:17:21.181015629 +0900
+++ examples/ir0/fib2.ir        2022-02-28 23:55:47.331976709 +0900
@@ -6,6 +6,7 @@
     %l0:i32:n
 
 block b0:
+  %b0:p0:i32:n
   %b0:i0:unit = store %b0:p0:i32 %l0:i32*
   %b0:i1:i32 = load %l0:i32*
   %b0:i2:u1 = cmp lt %b0:i1:i32 2:i32
```

This `%b0:p0:i32:n` is in the reference, but not in mine. And I am curious what this instruction is(I cannot find it in the `ir::Instruction`), and how to insert it to our context.

Thank you in advance.

**Comment by gmlwns2000** [comment]
I was curious too. I think it is phinode, which is not needed for IRgen.

**Comment by minseongg** [comment]
The register with prefix "p" denotes a phinode.

In our reference IR, we used phinodes for representing function parameters. You can insert it to your IR by using `phinodes` field in the `Block` struct.

**Comment by gmlwns2000** [comment]
@minseongg Do I have to insert phinodes? I passed the test cases without them...

**Comment by minseongg** [comment]
@gmlwns2000 Yes, you need to insert phinodes for the initial block because we pass the function parameters as the phinodes. Actually, there was a bug in the IR interpreter that we do not check the declaration of phinodes before assigning the value to the phinodes. We'll fix this..

**Comment by gmlwns2000** [comment]
Oh, so even if I did messed up phinode, the `test_examples_irgen_*` passes successfully right?

Okay then, I have to fix my code :)

**Comment by minseongg** [comment]
We updated IR interpreter to check that the args of call instruction and phinodes of function's init block have compatible dtype. https://github.com/kaist-cp/kecc-public/commit/5264066a3cb1cf999416340556a30a6855670e53

Now you need to insert phinodes for representing function parameters.

**Comment by gmlwns2000** [comment]
I tried the updated `kecc` with phinode insertion, it works without any bugs! Thank you for update :)

**Comment by jeehoonkang** [comment]
@jirheee Closing, as it seems the issue at hand is resolved. Please feel free to reopen this issue if you have further questions!
