### ISSUE TITLE
[HW2] Creduce create float division by zero.

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#366]
# Creduce divides float by zero.

I tried `creduce`, as usual, my daily routine. Then I found out `creduce` creates unexpectable code again.

# C code
```c
float a, b;
int main() { a / b; }
```

# In kecc

This code fails on my `kecc` implementation because `float @b = default`, and the interpreter emits `float could not divide by 0.0`. However, I think the interpreter should not emit the error because `0.0f/0.0f = Float.NaN`.

# Clang result

However the result of `clang` is weird. I compile the code with `clang -O0 tests_reduced.c` then result is following.

```bash
s20200535@kaist-cp-cs420:~/library/kecc-ainl/tests$ clang -O0 test_reduced.c 
test_reduced.c:2:16: warning: expression result unused [-Wunused-value]
int main() { a / b; }
             ~ ^ ~
1 warning generated.
s20200535@kaist-cp-cs420:~/library/kecc-ainl/tests$ ./a.out
s20200535@kaist-cp-cs420:~/library/kecc-ainl/tests$ echo $?
130
```

**Comment by minseongg** [comment]
Thanks for the reporting.

We updated the kecc to skip the test when the C input program contains a floating point division by zero. https://github.com/kaist-cp/kecc/commit/dc7a37d2e0bc265e2299113b498987fe04567d1f

**Comment by minseongg** [comment]
Closing. If you meet the same problem, please leave a comment!
