### ISSUE TITLE
[HW2] Why is sizeof2.c included in small test?

### ISSUE THREAD

**Issue by hyn2028** [kaist-cp/cs420#367]
The ```irgen_small``` test is expected to exclude ```struct``` and ```array``` as shown below.
```rust
const IRGEN_SMALL_TEST_IGNORE_LIST: [&str; 10] = [
    "examples/c/array.c",
    "examples/c/array2.c",
    "examples/c/array3.c",
    "examples/c/array4.c",
    "examples/c/array5.c",
    "examples/c/float.c",
    "examples/c/struct.c",
    "examples/c/struct2.c",
    "examples/c/struct3.c",
    "examples/c/temp2.c",
];
```

But sizeof2.c also contains an array like below.
```c
int main() {
    char a = 42, b = 5;
    long c[10];

    return sizeof(a) == 1 && sizeof(a + b) == 4 && sizeof(c) == 80;
}
```

Why isn't this excluded from the small test?

**Comment by minseongg** [comment]
Oh, It was my mistake when I updated the testcases..

We updated to remove `sizeof2` example from small test cases. (https://github.com/kaist-cp/kecc-public/commit/5f5fef54bd8a6adf13c0d5f8eabdbc1d0d4b3e4a) Sorry for the inconvenience.

**Comment by hyn2028** [comment]
Thank you!!
