### ISSUE TITLE
[HW2] illegal memory access example from fuzzer

### ISSUE THREAD

**Issue by zzz845zz** [kaist-cp/cs420#369]
I got the illegal memory access example from irgen fuzzer likes below, but I think this example should not be generated because:
* It is buggy code and
* It causes `thread 'main' panicked at 'non-integer value occurs', bin/kecc.rs:211:58` when executing my ir using irrun command. 

```c
int a, b;
float c; // size: 4
void d(char *e, int f) {
  for (; b < f; b++)
    a = e[b]; // this line causes illegal memory access because b can be greater than or equal to size of c 
}
int main() {
  d(&c, sizeof(0x1EC9A7p45)); // sizeof(0x1EC9A7p45): 8
  return a;
}
```

Of course, my irgen may not be correct, but I think it is not the case because panic does not occur if I fix the bug by increasing size of variable `c` (from float to double). What do you think?

**Comment by minseongg** [comment]
Thanks for reporting!

We fixed fuzzer to forbid incompatible pointer conversions (`float *` to `char *` in your case). https://github.com/kaist-cp/kecc-public/commit/3a36e47985decfc1188550c915c952a458030e59

If you meet the same problem, please leave a comment.

**Comment by zzz845zz** [comment]
Thank you! It seems the problem is solved.
