### ISSUE TITLE
[HW2] Module 'tqdm' not found error on submission

### ISSUE THREAD

**Issue by zzz845zz** [kaist-cp/cs420#373]
There is a module not found error on submission of "Homework 2: IR Generation (full)". I think it should be fixed.

```
running 2 tests
test test_examples_irgen_large ... ok
test test_examples_irgen_small ... ok

test result: ok. 2 passed; 0 failed; 0 ignored; 0 measured; 9 filtered out; finished in 8.72s

Traceback (most recent call last):
  File "tests/fuzz.py", line 17, in <module>
    import tqdm
ModuleNotFoundError: No module named 'tqdm'
```

**Comment by minseongg** [comment]
We fixed it: https://github.com/kaist-cp/kecc-public/commit/5f1a38534f00614a596bdb7033d9e363373d4560

Could you please try again? Sorry for the inconvenience.

**Comment by zzz845zz** [comment]
Thank you! Now it works fine.
