### ISSUE TITLE
[Question] SSH still asking for password after public key authentication

### ISSUE THREAD

**Issue by jeromeryu** [kaist-cp/cs420#374]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I made ed25519 key using
```
ssh-keygen -t ed25519
```
, put pub key it in authorized_keys in server, but it still asks for password.
Is there anything I'm doing wrong?
Here are my setting and error logs

config in my computer
<img width="218" alt="log1" src="https://user-images.githubusercontent.com/54859212/161686461-64d0d252-836b-4bad-84d8-2b8d10d58688.PNG">

<img width="403" alt="log2" src="https://user-images.githubusercontent.com/54859212/161686909-82d3e876-da3b-4058-b765-c87506b00831.PNG">

error log
![log3_LI](https://user-images.githubusercontent.com/54859212/161688529-b3c9df57-7993-44ad-aefe-3c5af7d13813.jpg)

authorized_keys contains same line in ed_25519.pub

**Comment by minseongg** [comment]
Could you please try again after remove `~/.ssh/known_hosts` in your local environment?

If it doesn't work, then could you try `ssh <username>@cp-service.kaist.ac.kr -p13002 -i ~/.ssh/id_ed25519` and show your result?

**Comment by minseongg** [comment]
We modified something in your `~/.ssh/authorized_keys` in your server. Could you please try again?

**Comment by jeromeryu** [comment]
It still does not work and asks for password.
![image](https://user-images.githubusercontent.com/54859212/161709663-6e3bc2be-56cd-42d8-8590-50935af64df5.png)
This is what happens when typing yes, no, fingerprint value in ```ssh <username>@cp-service.kaist.ac.kr -p13002 -i ~/.ssh/id_ed25519```

**Comment by minseongg** [comment]
Could you try `ssh <username>@cp-service.kaist.ac.kr -p13002` again?

If it does not work, please show your result of `ssh <username>@cp-service.kaist.ac.kr -p13002 -v`.

**Comment by jeromeryu** [comment]
This is the result.
Is there any difference in my account than others? 

![image](https://user-images.githubusercontent.com/54859212/161729392-e9530caa-c3e0-41c0-a932-23c8eda439e0.png)

**Comment by minseongg** [comment]
It seems there is no problem with the log you uploaded..

Could you upload the additional log that comes out when you type `yes` on that screen?

**Comment by jeromeryu** [comment]
Oh now it works! Thank you for your help. Can you tell me what you did to fix my server?

**Comment by minseongg** [comment]
We fixed a typo in your `~/.ssh/authorized_keys`. ("sh-ed25519" -> "ssh-ed25519")

**Comment by jeromeryu** [comment]
I don't know why copying to vim in command prompt dropped first letter. Sorry for my silly mistake and thank you for your help! I will close this issue.
