### ISSUE TITLE
[Homework 2] Purpose of typecast() function pre-defined in Constant struct

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#377]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

From my understanding, our implementation of `translate_typecast()` is supposed to simply insert a typecast instruction, instead of actually performing the typecast operation in the IRgen stage of the compilation.  Is my understanding correct?

If so, I was confused why there was a `typecast()` function provided in `ir/mod.rs` that actually performs the typecast for us.  If we use this provided function, then we won't ever have to create a typecast instruction for constants.

**Comment by minseongg** [comment]
> From my understanding, our implementation of `translate_typecast()` is supposed to simply insert a typecast instruction, instead of actually performing the typecast operation in the IRgen stage of the compilation.  Is my understanding correct?

Yes.

> If so, I was confused why there was a `typecast()` function provided in `ir/mod.rs` that actually performs the typecast for us.  If we use this provided function, then we won't ever have to create a typecast instruction for constants.

Actually, you do not need to use `typecast()` function to generate correct IR. As you mentioned, we can translate the typecast of constant by inserting typecast instruction to the IR.

You can consider `typecast()` function as a helper function for implementing additional IR optimizations which are related to constants such as [Constant folding and constant propagation](https://en.wikipedia.org/wiki/Constant_folding).
