### ISSUE TITLE
I have no idea why test version is different with running version

### ISSUE THREAD

**Issue by kaist-kihwan** [kaist-cp/cs420#38]
When I run my homework 1 with "cargo run -- -p examples/fibonacci.c" command, it works well. However, when I run "cargo test test_examples_write_c" command, it stuck because of parse error at examples/fibonacci.c
I tried "cargo build" and "cargo build --release"
Why test of my implementation works differently for same file?
I'm using Window but remoteing cs420 server by VS Code.

**Comment by cmpark0126** [comment]
In fact, the behavior of `cargo run -- -p examples/fibonacci.c` and `cargo test test_examples_write_c` are different.

For the former, only reprint the parsing results. In the latter case, however, not only reprint the parsed results but also parse the reprinted results and make sure that it has the same results as previously parsed.

I think your parse error occurs when parsing the reprinted c source file. Please refer to the testing code: https://github.com/kaist-cp/kecc-public/blob/cef3fb76505e4845e1ecf02e94395af746c627e5/src/tests.rs#L9-L22

**Comment by kaist-kihwan** [comment]
Oh, I mean, when I try cargo run, it prints something correct. However, when I try test, it miss some parenthesis that was printed before. How it could be?

**Comment by kaist-kihwan** [comment]
Sorry, I misunderstood. Thank you for your help.
