### ISSUE TITLE
[Homework 6] Deadcode Elimination (due: 6/20)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#381]
Implement deadcode elimination.

- **instruction**
    + https://www.youtube.com/watch?v=zoCikRTbDbY&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=26
    + https://docs.google.com/presentation/d/1SqtU-Cn60Sd1jkbO0OSsRYKPMIkul0eZoYG9KpMugFE/edit#slide=id.g87567d459f_0_5
- **skeleton**: https://github.com/kaist-cp/kecc-public/blob/main/src/opt/deadcode.rs
    + fill out `todo!()`.
    + **don't fork this repository.**  It'll be public!
- **self grader**
    + https://github.com/kaist-cp/kecc-public/blob/main/scripts/grade-hw6.sh
- **submission**: run `./scripts/make-submissions.sh` and then submit `hw6.zip`.
    + https://gg.kaist.ac.kr/assignment/55/
- **due**: 6/20 23:59:59 (KST = UTC+9)

**Comment by minseongg** [comment]
**IMPORTANT**: Please do not consider phinodes as unused registers: https://github.com/kaist-cp/cs420/issues/398#issuecomment-1126771077
