### ISSUE TITLE
[Homework 2] Fuzzer error 

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#386]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I'm currently getting the same error as shown in a previous post: #297 

```
& python3 tests/fuzz.py --irgen
Use default random seed
Building KECC..
    Finished release [optimized] target(s) in 0.06s
Fuzzing with infinitely many test cases.  Please press [ctrl+C] to break.
Test case #0 (skipped: 0)
Traceback (most recent call last):
  File "tests/fuzz.py", line 335, in <module>
    fuzz(tests_dir, fuzz_arg, args.num, args.easy)
  File "tests/fuzz.py", line 278, in fuzz
    raise Exception("Test `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Test `/home/s20150910/kecc-public/target/release/fuzz -i /home/s20150910/kecc-public/tests/test_polished.c` failed with exit code 101.
```
When I run test_polished.c, I get an error in dtype.rs:
```
$ cargo run --bin fuzz --features="build-bin" tests/test_polished.c -i
    Finished dev [unoptimized + debuginfo] target(s) in 0.07s
     Running `target/debug/fuzz tests/test_polished.c -i`
thread 'main' panicked at 'typedef should be replaced by real dtype', src/ir/dtype.rs:1333:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
When I try to reduce, it immediately fails:
```
$ python3 tests/fuzz.py --irgen --reduce
Use default random seed
Building KECC..
    Finished release [optimized] target(s) in 0.12s
  0%|                                                                                                                                                                             | [Elapsed:00:00, <ETA:?]
Traceback (most recent call last):
  File "tests/fuzz.py", line 333, in <module>
    creduce(tests_dir, fuzz_arg, args.clang_analyze)
  File "tests/fuzz.py", line 238, in creduce
    raise Exception("Reducing test_reduced.c by `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Reducing test_reduced.c by `creduce --tidy --timing --timeout 20 ./reduce-criteria.sh test_reduced.c` failed with exit code 1.
  0%|
```
I don't know if it's the problem with reduce-criteria-template.sh.  My repository is up to date, and the only file I modified is irgen/mod.rs.  Is there anything else I can try?

**Comment by minseongg** [comment]
Could you try to use reduce after change the `reduce-criteria-template.sh` like this?

```diff
diff --git a/tests/reduce-criteria-template.sh b/tests/reduce-criteria-template.sh
index 7fbe304..66c86a2 100644
--- a/tests/reduce-criteria-template.sh
+++ b/tests/reduce-criteria-template.sh
@@ -75,5 +75,5 @@ if
 then
   grep 'panicked' out_fuzz.txt
 else
-  grep 'assertion failed' out_fuzz.txt
+  grep 'panicked' out_fuzz.txt
 fi
```

If `python3 tests/fuzz.py --irgen --reduce` produce C program with undefined behavior, then try `python3 tests/fuzz.py --irgen --reduce --clang-analyze`.

**Comment by andersc97** [comment]
Thanks, changing 'assertion failed' into 'panicked' fixed my problem
