### ISSUE TITLE
[Question] (Should I submit write_c.rs file in Homework 1?)

### ISSUE THREAD

**Issue by murat1999** [kaist-cp/cs420#387]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

Should I only submit write_c.rs file to the website?

**Comment by minseongg** [comment]
Yes.

**Comment by murat1999** [comment]
And for the other homework also just the target files right?

**Comment by minseongg** [comment]
Yes. For example, you should submit `c/write_c.rs` and `irgen/mod.rs` for homework 2.

**Comment by murat1999** [comment]
thank you
