### ISSUE TITLE
[Question] Today's attendance quiz (4/27)

### ISSUE THREAD

**Issue by 3-24** [kaist-cp/cs420#388]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I have never heard of Prof's favorite label though I attended to today's lecture.. Can I get any hint for it?

**Comment by minseongg** [comment]
It was announced in the zoom chat. Hint: https://www.notion.so/A-Whirlwind-Tour-of-RISC-V-a7cae7ace87d4ebcbf490f59c4793033

**Comment by 3-24** [comment]
Oh the zoom chat! It was the point I missed. Thanks a lot.
