### ISSUE TITLE
[Question] [HW2] Can I use external crate?

### ISSUE THREAD

**Issue by akthddus22** [kaist-cp/cs420#389]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I'm dealing with HW2, and my code uses 'failure' crate, whichi is also used in skeleton code in HW2 instruction video.

But I found that initial cargo.toml do not include 'failure'. So I'm worry about my codes work well on submission server.

Can we use 'failure' or any other external crates?

**Comment by minseongg** [comment]
You cannot use external crates that is not specified in [`Cargo.toml`](https://github.com/kaist-cp/kecc-public/blob/main/Cargo.toml).

For error handling, we replaced `failure` crate into `thiserror` crate because `failure` is deprecated. Please use it. ([docs](https://docs.rs/thiserror/latest/thiserror/))
