### ISSUE TITLE
Hexademical?

### ISSUE THREAD

**Issue by kaist-kihwan** [kaist-cp/cs420#39]
There's an typo in kecc 'Hexademical' instead 'Hexadecimal'.
However, gg.kaist.ac.kr has right one. I think I should update my kecc, but how?
Can anybody help me updating my kecc?

**Comment by hyunsukimsokcho** [comment]
What do you mean by
> However, gg.kaist.ac.kr has right one.
 
Does the last request
> Can anybody help me updating my kecc?
refer to how to reflect the latest version of kecc to your local repo?

btw, the typo you pointed out is not our fault, but [lang_c’s](https://docs.rs/lang-c/0.5.2/lang_c/ast/enum.FloatBase.html#variant.Hexademical)

**Comment by kaist-kihwan** [comment]
I mean when I submit the file to gg.kaist.ac.kr, it raise an error for that typo,
and yes. I'm using cs420 server by VS code

**Comment by jeehoonkang** [comment]
`cargo update` will download the new version of dependency, resolving the problem.

**Comment by jeehoonkang** [comment]
Also, please merge the upstream changes as described in README.md.

**Comment by kaist-kihwan** [comment]
Thank you. After I change my lang-c to 0.8.0, typo fixed.
