### ISSUE TITLE
[HW4] Allow me to upload all previous optimization files to prevent `error: function is never used`

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#390]
I encountered `function is never used` in `opt_utils.rs`.

```
error: function is never used: `replace_operands`
   --> src/opt/opt_utils.rs:256:8
    |
256 | pub fn replace_operands(operand: &mut Operand, replaces: &HashMap<RegisterId, Operand>) {
    |        ^^^^^^^^^^^^^^^^
    |
note: the lint level is defined here
   --> src/lib.rs:4:9
    |
4   | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(dead_code)]` implied by `#[deny(warnings)]`

error: could not compile `kecc` due to previous error
```

I think this is because `simplify_cfg.rs` does not reference that function.

I think we should upload all previous optimizing task files in submission, to prevent those kinds of errors.

Could you fix the submission to includes all previous task files?

**Comment by minseongg** [comment]
Could you check if your kecc is up to date? We updated `opt_utils.rs` to allow to have dead code. ([`1e2e46c`](https://github.com/kaist-cp/kecc-public/commit/1d2e46cc81534f58f469b257c78fcf8313b459bb))

**Comment by gmlwns2000** [comment]
I check the upstream, and it seems work! Thank you :)
