### ISSUE TITLE
[HW5] ir::Instruction::is_pure() function

### ISSUE THREAD

**Issue by hyn2028** [kaist-cp/cs420#391]
The definition of the ir::Instruction::is_alive() function is as follows.

```rust
impl Instruction {
    pub fn is_pure(&self) -> bool {
        !matches!(self, Self::Store { .. } | Self::Call { .. })
    }
}
```

From the point of view of roles,`ir::Store`, `ir::Call`, and `ir::Load` are non-pure, and from the point of view of return values, only `ir::Call` and `ir::Load` are non-pure. Isn't it?

Why are only ` ir::Store`, `ir::Call` defined exactly as non pure?

**Comment by minseongg** [comment]
We changed the function name to `has_no_side_effects`. ([`64124bb`](https://github.com/kaist-cp/kecc-public/commit/64124bb68d470b5ad8e1f8eedcce918603bdb105)) Sorry for the confusion.

**Comment by hyn2028** [comment]
Thank you!
