### ISSUE TITLE
[HW4] Terms used in the code video 1

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#395]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I am watching the register promotion video code 1, and am confused about some terminologies in the video and want to ask about them.

1. What does **join** and **join table** mean and what is its role?
2. What does it mean to be a **nearest block**? 
More specifically, nearest in what sense? I thought it was the nearest block among the successors where phinodes could be inserted, but it is confusing since we retrieve the end value from `bid_join`.

It seems like understanding these concepts are really important, but I don't think I am clearly getting the concept. 

Thank you in advance!

**Comment by minseongg** [comment]
I hope https://github.com/kaist-cp/cs420/issues/183 answers your question.

**Comment by jirheee** [comment]
Oh thank you! I think I understand it now :)
