### ISSUE TITLE
[HW6] In `ir3/cond_and_loop.ir#b17#79`, why unused phinode is alive?

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#398]
Hello!

I am working on dead code elimination, I think unused phinode should be removed, except in `bid_init`.

But in fact, in `b13` line `79` in `ir3/cond_and_loop.ir`, 
```llvm
block b17:
  %b17:p0:i32:i
  %b17:p1:i32:t2
  j b8(%b17:p0:i32, %b14:p0:i32)
```
`%b17:p1` is still alive after dead code elimination.

Why this is happening?

**Comment by minseongg** [comment]
Good catch! That's a bug in the reference IR; we did not consider phinodes in unused registers.

But since the assignment has already out, we decided to keep it for this semester. So please implement deadcode elimination without removing unused phinodes. Sorry for confusion. We will update the reference IR after this semester.

**Comment by gmlwns2000** [comment]
Thank you for response!

I just ignore phinodes in the submission and all things just work well.

**Comment by minseongg** [comment]
We updated deadcode elimination examples to remove unused phinodes. https://github.com/kaist-cp/kecc-public/commit/fb05faa8b04d536a72a64d3098137dca30e40b42

**Comment by Re-st** [comment]
I have question.
I wanted to remove unused phinodes.
But the following error appeared.
According to this thread, b0:p0 should be deleted.
But in [after opt (expected)], it is not deleted.
Is this error?

Source : https://github.com/kaist-cp/kecc-public/blob/main/examples/deadcode/deadcode.output.ir 
[before opt]
fun i32 @deadcode () {
init:
  bid: b0
  allocations: 
    %l0:i32:x
    %l1:i32:y

block b0:
  %b0:i0:i32 = add 100:i32 200:i32
  %b0:i1:i32 = add %b0:i0:i32 300:i32
  %b0:i2:i32 = add %b0:i1:i32 400:i32
  %b0:i3:unit = store %b0:i0:i32 %l1:i32*
  br undef:i1, b1(), b2()

block b1:
  %b1:i0:unit = nop
  %b1:i1:unit = call @sink:[ret:unit params:(unit)]*(%b1:i0:unit)
  j b3()

block b2:
  %b2:i0:unit = store 42:i32 %l1:i32*
  j b3()

block b3:
  ret 0:i32
}

fun unit @sink (unit) {
init:
  bid: b0
  allocations: 


block b0:
  %b0:p0:unit
  ret unit:unit
}

[after opt]
fun i32 @deadcode () {
init:
  bid: b0
  allocations: 
    %l0:i32:y

block b0:
  %b0:i0:i32 = add 100:i32 200:i32
  %b0:i1:unit = store %b0:i0:i32 %l0:i32*
  br undef:i1, b1(), b2()

block b1:
  %b1:i0:unit = call @sink:[ret:unit params:(unit)]*(unit:unit)
  j b3()

block b2:
  %b2:i0:unit = store 42:i32 %l0:i32*
  j b3()

block b3:
  ret 0:i32
}

fun unit @sink (unit) {
init:
  bid: b0
  allocations: 


block b0:
  ret unit:unit
}

[after opt (expected)]
fun i32 @deadcode () {
init:
  bid: b0
  allocations: 
    %l0:i32:y

block b0:
  %b0:i0:i32 = add 100:i32 200:i32
  %b0:i1:unit = store %b0:i0:i32 %l0:i32*
  br undef:i1, b1(), b2()

block b1:
  %b1:i0:unit = call @sink:[ret:unit params:(unit)]*(unit:unit)
  j b3()

block b2:
  %b2:i0:unit = store 42:i32 %l0:i32*
  j b3()

block b3:
  ret 0:i32
}

fun unit @sink (unit) {
init:
  bid: b0
  allocations: 


block b0:
  %b0:p0:unit
  ret unit:unit
}

**Comment by m-spitfire** [comment]
@Re-st the unused phinodes should be deleted, unless they're in `bid_init` as that resembles function arguments.
