### ISSUE TITLE
Question about SSH setup for VSCode

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#4]
In the first online session, you showed us how to use VSCode using an existing network configuration.
Could you give us some instructions or references to how to create this configuration in the first place, especially using the Linux servers that has been(will be) assigned to each of us using our submitted SSH keys?
Thank you in advance.

**Comment by jeehoonkang** [comment]
Thank you for asking!  I just added the public keys submitted so far to the server.  Please read the documentation in README.md.
