### ISSUE TITLE
AssertSupported trait and Fuzzer do not eliminate extension property

### ISSUE THREAD

**Issue by j31d0** [kaist-cp/cs420#40]
As @Medowhill already pointed out in his suggestion, `__asm` should be removed in source code. But current latest commit does not handle this. When I face this issue, I also notice that in AssertSupported implementation for Declarator, they just call `self.extension.is_empty()` but it is just boolean value, so it does not raise panic even it has extensions. So, I suggest to patch AssertSupported for Declarator and ParameterDeclaration, and patch fuzzer to remove `__asm` extension.

```diff
diff --git a/src/c/parse.rs b/src/c/parse.rs
index be36ba6..19b6de3 100644
--- a/src/c/parse.rs
+++ b/src/c/parse.rs
@@ -217,7 +217,7 @@ impl AssertSupported for Declarator {
     fn assert_supported(&self) {
         self.kind.assert_supported();
         self.derived.assert_supported();
-        self.extensions.is_empty();
+        assert_eq!(true, self.extensions.is_empty());
     }
 }

@@ -282,7 +282,7 @@ impl AssertSupported for ParameterDeclaration {
     fn assert_supported(&self) {
         self.specifiers.assert_supported();
         self.declarator.assert_supported();
-        self.extensions.is_empty();
+        assert_eq!(true, self.extensions.is_empty());
     }
 }

diff --git a/tests/fuzz.py b/tests/fuzz.py
index f7ebcb2..1db1de3 100644
--- a/tests/fuzz.py
+++ b/tests/fuzz.py
@@ -36,6 +36,8 @@ REPLACE_DICT = {
     "\"g_\w*\", ": "",              # transparent_crc에서 프린트 목적으로 받은 StringLiteral 삭제
     "char\* vname, ": "",           # transparent_crc에서 사용하지 않는 파라미터 삭제
     r"[^\n]*_IO_2_1_[^;]*;": "",    # extern을 지우면서 생긴 size를 알 수 없는 struct 삭제
+    r"__asm\s*\([^\)]*\)": "",      # asm extension in mac
+    r"__asm__\s*\([^\)]*\)": "",    # asm extension in linux
 }
 CSMITH_DIR = "csmith-2.3.0"
```

_Originally posted by @j31d0 in https://github.com/kaist-cp/cs420/issues/27#issuecomment-608243411_

**Comment by hyunsukimsokcho** [comment]
Thanks, we'll take the suggestion into account very soon

**Comment by jeehoonkang** [comment]
Thank you for reporting this.  We updated the skeleton in this commit: https://github.com/kaist-cp/kecc-public/commit/6edb4665c008e899b6c4ba45e4f9220da6f0acdb

**Comment by kimkanu** [comment]
Has this fix been reflected on the homework grader? (`https://gg.kaist.ac.kr/check/`)

With my implementation of HW1, `python3 tests/fuzz.py --print` works well without any exceptions; but the grader always fails with the following message:
```
(above: omitted)
Fuzzing with 30 test cases.
Test case #0
Traceback (most recent call last):
  File "tests/fuzz.py", line 272, in <module>
    fuzz(tests_dir, fuzz_arg, args.num)
  File "tests/fuzz.py", line 234, in fuzz
    raise Exception("Test `{}` failed with exit code {}.".format(" ".join(args), proc.returncode))
Exception: Test `cargo run --release --bin fuzz -- -p /app/files/checks/<...>/checker/kecc-public/tests/test_polished.c` failed with exit code 1.
```
which was shown when I run `python3 tests/fuzz.py --print` with the fuzzer before this bug fix.

Is it due to bugs in my implementation?

**Comment by jeehoonkang** [comment]
The grader will be updated once everything is stabilized. For the time being, please check yourself with `cargo test` and the fuzzer.

**Comment by kimkanu** [comment]
Thanks for your reply!
