### ISSUE TITLE
[Question] [HW2] phinodes in ir0 directory?

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs420#402]
Hello. Now i'm doing hw2.

I found some kind of `%b0:p0:i32:x` ir statement in examples/ir0/foo.ir.
```
fun i32 @foo (i32, i32, i32) {
init:
  bid: b0
  allocations: 
    %l0:i32:x
    %l1:i32:y
    %l2:i32:z

block b0:
  %b0:p0:i32:x <- here
  %b0:p1:i32:y <- here
  %b0:p2:i32:z <- here
  %b0:i0:unit = store %b0:p0:i32 %l0:i32*
  %b0:i1:unit = store %b0:p1:i32 %l1:i32*
  %b0:i2:unit = store %b0:p2:i32 %l2:i32*
  %b0:i3:i32 = load %l0:i32*
  %b0:i4:i32 = load %l1:i32*
  %b0:i5:u1 = cmp eq %b0:i3:i32 %b0:i4:i32
  br %b0:i5:u1, b1(), b2()
...
```
From src/ir/write_ir.rs, I found that it is about phinodes.
But i think the notion of phinode is not mentioned on hw2 video yet.

Also when i execute IR with erasing that phinode -> `cargo run --features=build-bin -- --irrun examples/ir0/foo.i` then error happens.
```
thread 'main' panicked at 'dtype of args and phinodes of init block must be compatible', src/ir/interp.rs:1487:21
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

So do i have to do something about phinode on hw2? Am i something missing?

**Comment by AnHaechan** [comment]
In the video, it is mentioned that
the `RegisterId::Arg` or register named `...p...` stands for either
(1) function arguments
or (2) phinode value.

**Comment by junsooo** [comment]
Thank you for your answer. By the way, could you give me a hint about adding `%b0:p0:i32:x`?
I think we need some kind of ir::Instruction on `irgen.translate_parameter_decl`, but i don't know what exact instruction is need for parameters.

**Comment by junsooo** [comment]
I thought @AnHaechan 's comment is saying that, `%b0:p0:i32:x` is not for phinode but it is about function argument... 
i'll try it thank you for your fast reply.

**Comment by junsooo** [comment]
Thank you. It works well.
