### ISSUE TITLE
[TIP] VSCode syntax highlighter development for KECC-IR

### ISSUE THREAD

**Issue by hyn2028** [kaist-cp/cs420#403]
Hello.

From the middle of the assignment, you will often need to read `KECC-IR`. I wanted the syntax highlighter to be applied to `KECC-IR`, which is currently displayed as plain text. A syntax highlighter for `LLVM-IR` already exists, but I made a VSCode extension syntax highlighter specialized for `KECC-IR`.

![img](https://raw.githubusercontent.com/hyn2028/kecc-ir-highlight/main/imgs/img1.png)

Just search for `kecc` in the `VSCode Marketplace` and the extension will be found. Install it and the syntax highlighter will work right away.

It is a pity that it was produced and introduced in the middle of the semester. I hope it will be helpful not only for this semester, but also for students who are taking classes in the future.

If you have any problems or improvements, please feel free to let me know on GitHub Issues.

Thank you.

**Comment by drzix** [comment]
Very nice! It goes really well with the [theme](https://marketplace.visualstudio.com/items?itemName=drzix.hc-zenburn-vscode) I use!

![image](https://user-images.githubusercontent.com/9529786/168768468-efc63bac-c1b6-4973-835b-026c8a1731b3.png)

(ad. included)
#광고포함

**Comment by hyn2028** [comment]
There was an undiscovered bug with the recognition of numeric constants. It's patched now.

**Comment by gmlwns2000** [comment]
This is innovation of doing homework!!
Thank you so much.

**Comment by jeehoonkang** [comment]
@hyn2028 I'll like to acknowledge your contributions to the course by giving you extra credit. Again, thank you so much!

**Comment by m-spitfire** [comment]
Hello! For those who use vim/neovim here's syntax file I created for KECC IR. It will be helpful for HW2 and onwards:
`syntax/kecc_ir.vim`
```vim
" Vim syntax file
" Language:   KECC IR
" Maintainer: Murad Bashirov
" Version:      0.1.0
" Modified from: https://github.com/rhysd/vim-llvm/blob/master/syntax/llvm.vim

if version < 600
  syntax clear
elseif exists("b:current_syntax")
  finish
endif

syn case match

" Types.
syn match irType /\(i8\|i16\|i32\|i64\|u1\|u8\|u16\|u32\|u64\|f32\|f64\|unit\)\**/

" Instructions.
syn keyword irStatement nop store call load typecast to getelementptr offset cmp ret mul div mod add sub shl shr eq ne lt le gt ge and xor or plus minus negate j br switch default

syn match   irComment /;.*$/
" Keywords.
syn keyword irKeyword
    \ fun
    \ init
    \ block
    \ bid
    \ allocations
    \ var

syn match irVariable /%b[0-9]\+:i[0-9]\+/
syn match irVariable /%b[0-9]\+:p[0-9]\+/
syn match irVariable /%l[0-9]\+/

" Func
syn match irFunc /@[a-zA-Z]*/
syn match irFunc /b[0-9]\+/

" Misc syntax.
syn match irNumber /[0-9]\+/
syn keyword irUndef undef

" Named metadata and specialized metadata keywords.

if version >= 508 || !exists("did_c_syn_inits")
  if version < 508
    let did_c_syn_inits = 1
    command -nargs=+ HiLink hi link <args>
  else
    command -nargs=+ HiLink hi def link <args>
  endif

  HiLink irType Type
  HiLink irStatement Statement
  HiLink irNumber Number
  HiLink irKeyword Keyword
  HiLink irUndef Constant
  HiLink irVariable Identifier
  HiLink irFunc Identifier
  HiLink irComment Comment
  delcommand HiLink
endif

let b:current_syntax = "kecc_ir"
```

`ftdetect/kecc_ir.vim`
```vim
au BufRead,BufNewFile *.ir set filetype=kecc_ir
```
Create those directories/files inside your vim(`~/.vim`) or neovim (`~/.config/nvim`) config directory, and it should just work. Let me know if there're any issues.
