### ISSUE TITLE
[HW5] Question about GVN algorithm

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#407]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I am currently passing all the test cases except `complete_cond.ir` and debugging for this case, and I have a question about this.

How should we care the jumpargs with constant?

Below is the ir of func_0 in the test case.
<img width="349" alt="image" src="https://user-images.githubusercontent.com/65358599/169692973-dfcfdc25-7070-46ca-8039-2834567587de.png">

And in the expected output, it seems like the reference solution replaces the phinode `%b9:p0` to 1 since the jump args being passed from b7 and b8 are both 1.

To make this happen using the algorithm given in the lecture slides, I think 1 should be in the register table and should be in both final leader tables of b7 and b8. (since 1 cannot be in the leader table of b0, which is the idom of b9)

In order to make this happen, I think we should also run through the jump args and put them into the leader tables too.

Is this the intended way of implementing gvn algorithm? I am confused because the lecture slide only says about instruction/phinodes not the jump args.

**Comment by jirheee** [comment]
This is the expected output of func_0
```
block b0:
  %b0:i0:u1 = cmp ne 0:i32 0:i32
  br %b0:i0:u1, b7(), b8()

block b1:
  %b1:i0:u1 = cmp ne 0:i32 0:i32
  br %b0:i0:u1, b19(), b20()

block b2:
  %b2:i0:u1 = cmp ne 1:i32 0:i32
  br %b9:i0:u1, b31(), b32()

block b3:
  %b3:p0:i32:t12
  %b3:i0:u1 = cmp eq %b3:p0:i32 0:i32
  %b3:i1:i32 = typecast %b3:i0:u1 to i32
  ret %b3:i1:i32

block b4:
  %b4:i0:u1 = cmp ne 1:i32 0:i32
  br %b9:i0:u1, b10(), b11()

block b5:
  %b5:i0:u1 = cmp ne 0:i32 0:i32
  br %b0:i0:u1, b13(), b14()

block b6:
  %b6:p0:i32:t3
  %b6:i0:u1 = cmp ne %b6:p0:i32 0:i32
  br %b6:i0:u1, b1(), b2()

block b7:
  j b9(1:i32)

block b8:
  j b9(1:i32)

block b9:
  %b9:p0:i32:t0
  %b9:i0:u1 = cmp ne 1:i32 0:i32
  br %b9:i0:u1, b4(), b5()
```

**Comment by minseongg** [comment]
Related question: https://github.com/kaist-cp/cs420/issues/241

In the reference solution, `RT` is actually not a `Register -> Num`, but a `Operand -> Num ∪ Constant`. I believe, in doing so, you can naturally generalize the slide's algorithm to take into account constants. For the above example, `%b9:i0:i32 = ϕ(1:i32, 1:i32)` and `RT(1:i32) = 1:i32`, therefore `RT(%b9:i0:i32) = 1:i32` and `%b9:i0:i32` is replaced with `1:i32`.

**Comment by jirheee** [comment]
Thank you for the answer! It finished the homework with your answer 👍
