### ISSUE TITLE
[HW1] Nullified Submission

### ISSUE THREAD

**Issue by workstudy-zero** [kaist-cp/cs420#408]
Hello,

I've not seen [this notice](https://github.com/kaist-cp/cs420/issues/320#issuecomment-1088509521), and I notice that my submission of HW 1 has been nullified.
It is my fault that I did not see the notice, but I submitted it long ago(3/7), and I didn't have time to pay attention to HW 1 because I was struggling in HW 2.
In addition, it seems that my submission for HW1 pass the new criteria.

Could you withdraw the invalidation of my submission?
I'm Jaeho Choi (Student ID: 20223684).

Sorry for inconvenience.

**Comment by minseongg** [comment]
Please send email to jeehoon.kang@kaist.ac.kr with your (1) Student ID, (2) Submission ID.

**Comment by workstudy-zero** [comment]
Thanks a lot!
