### ISSUE TITLE
[HW] Debugging `test_examples_optimize`

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#410]
I finished all the given tests for optimization passes and trying to make my compiler work for `test_examples_optimize`.

But it seems like debugging to pass this test is almost impossible, since we cannot know which part of our optimization pass is malfunctioning. So I am currently trying to guess which optimization pass is not working just by the final output.

Can I ask for help in debugging this cases?

One idea is that if there is some kind of logging functionality in the kecc(like `--log` option) that writes the optimization result for each pass to the filesystem, I could better debug the optimizations.

**Comment by hyn2028** [comment]
I also found and fixed bugs in my optimization process, thanks to the new addition of `test_examples_optimize.` I did it in a very iterative and labor intensive way. I'd like to have these features too.
