### ISSUE TITLE
[Question] HW5: grading script shows pass, but doesn't work in gg server

### ISSUE THREAD

**Issue by woojinnn** [kaist-cp/cs420#412]
I'm done with my HW5 code.
However, when I submit my hw5.zip file, I get this error:
```
error: associated function is never used: `frontiers`
   --> src/opt/opt_utils.rs:350:12
    |
350 |     pub fn frontiers(&self, bid: BlockId) -> Option<&Vec<BlockId>> {
    |            ^^^^^^^^^
    |
note: the lint level is defined here
   --> src/lib.rs:4:9
    |
4   | #![deny(warnings)]
    |         ^^^^^^^^
    = note: `#[deny(dead_code)]` implied by `#[deny(warnings)]`

error: could not compile `kecc` due to previous error
```
I just used `frontiers` function for hw4, not in hw5.
When I comment out frontier function, it doesn't compile since I used it in hw4.

What's the problem and how can I troubleshoot this one?

**Comment by minseongg** [comment]
Could you check if your kecc is up to date? We updated `opt_utils.rs` to allow to have dead code. ([`1e2e46c`](https://github.com/kaist-cp/kecc-public/commit/1d2e46cc81534f58f469b257c78fcf8313b459bb))
