### ISSUE TITLE
[HW] Forgotten password and `sudo`

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#413]
I am working on `asmgen` and want to see how the test cases should be compiled, but I forgot my password on the server so I cannot install the dependencies for `riscv` compiling which needs `sudo`... What can I do to retrieve my password..?

**Comment by minseongg** [comment]
`gcc-riscv64-linux-gnu`, `g++-riscv64-linux-gnu` and `qemu-user-static` packages are installed in the server and you could compile the test cases by following this: https://github.com/kaist-cp/kecc-public#running-risc-v-binaries

Is there any problem for using it?

**Comment by jirheee** [comment]
Oh thank you! It seems to work fine :)
