### ISSUE TITLE
[Homework 7] Phinodes in KECC asmgen

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#415]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I'm still at the early stages of implementing HW7, and I was wondering if we would have to consider phinodes in this homework.
It seems that the test cases for this homework comes from /ir0, where there are no phinodes (except for as function arguments).  But I was wondering maybe the fuzzer would generate input IR codes that use phinodes?

**Comment by minseongg** [comment]
Since we use IRs from `ir0` ~ `ir4` for the test cases, (https://github.com/kaist-cp/kecc-public/blob/main/tests/test_examples.rs#L63-L69) you have to consider phinodes in the homework 7.
