### ISSUE TITLE
[homework 7] dynamically allocating stack pointer within function

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#418]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

Example assembly codes (godbolt) always allocate the precise amount of stack space needed in the beginning of the function.  For our own implementation, would it be okay to dynamically move the stack pointer whenever we need in the middle of the function? (instead of simply allocating a whole chunk of stack space in the beginning of the function)

**Comment by minseongg** [comment]
Yes, it's okay.

**Comment by andersc97** [comment]
FYI anyone who might be making the same mistake

Even though dynamic stack allocation technically has no problem in compilation, it is problematic in loops (because additional stack space would be generated every iteration)
I ended up simply allocating all the necessary stack space in the beginning of the function.
