### ISSUE TITLE
[Homework 7] Loading float immediates

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#420]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I'm currently working on loading float immediates (e.g. `double b = 0.1300852687485195f;`).  I have been referring to the method described in #274, where the bitwise representation of the float constant is loaded into an integer register using the `li` operator, and then transferring it into a float register.  However, I believe the implementation shown in #274 is wrong, because when transferring the value from A0 to FA0, they used `fcvt.s.l`, which performs a numeric casting from int to float rather than simply transferring the bits.

I think the correct implementation would be to use `fmv` to transfer the value from A0 to FA0, but it seems that using fmv on an integer register causes compilation error.  Is there any workaround to perform this bitwise transfer between int register and float register?

**Comment by minseongg** [comment]
> I think the correct implementation would be to use `fmv` to transfer the value from A0 to FA0.

Yes, you're right.

> Is there any workaround to perform this bitwise transfer between int register and float register?

Please refer to these instructions:

- `fmv.w.x`: https://msyksphinz-self.github.io/riscv-isadoc/html/rvfd.html#fmv-w-x
- `fmv.d.x`: https://msyksphinz-self.github.io/riscv-isadoc/html/rv64d.html#fmv-d-x
