### ISSUE TITLE
[HW4] What does OperandVar.lookup exactly do?

### ISSUE THREAD

**Issue by junsooo** [kaist-cp/cs420#424]
Hello, Now i'm doing HW4.
I have question about OperandVar.lookup.

On video, we use operandVar.lookup but i couldn't understand what it exactly do.

What i understand is:
if OperandVar itself is Operand: then just return it
if OperandVar itself is Phi:
   - we find the usize(alloc_id) from phinode_indexes(2nd parameter) and get usize
   - From that usize, Make new Operand which is Register, and RegisterId is Local { aid(usize) }
   - Finish making that Operand with dtype(1st parameter)

So i think that lookup function is doing if we find OperandVar which is phinode, than change it to "real" phinode operand. Is it correct?

**Comment by minseongg** [comment]
Yes. It is correct.
