### ISSUE TITLE
[HW7] Can I split the mod.rs into multiple files?

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#427]
My asmgen/mod.rs is pretty long, it is about 5500 lines (since my poor skill :( ). 

So I want to split the file, but it was not allowed in previous assignments.

Could you allow us to split files in asmgen module?

**Comment by minseongg** [comment]
Thanks for suggestion. We will update the submission format to allow it.

**Comment by gmlwns2000** [comment]
@minseongg @jeehoonkang 
Hi,

I just tried to upload to gg, but I noticed the only files in `asmgen` are included in the zip file.

I used some useful functions in `opt/opt_utils.rs` such as `reverse_cfg`. And I used `write_c.rs` for debugging and parsing purposes. Also, I included `irgen` stuff because for using the `WriteString` implementation to construct error messages.

Could you allow us to upload other rs files too? Such as `src/opt/*.rs`, `src/irgen/*.rs`, `src/c/*.rs`.

**Comment by minseongg** [comment]
@gmlwns2000 Ah, I see. We will change it and notice to you.

**Comment by gmlwns2000** [comment]
@minseongg Thank you!!

**Comment by minseongg** [comment]
We updated `./make-submission.sh` to include `src/c/write_c.rs`, `src/irgen/mod.rs`, `src/opt/opt_utils.rs`. (https://github.com/kaist-cp/kecc-public/blob/main/scripts/make-submissions.sh)

However, we did not update gg's grading script yet, so please wait until it. We will notice to you when it is done.

**Comment by minseongg** [comment]
Now we updated gg's grading script for hw7.

Please upload `hw7.zip` for the submission.

**Comment by gmlwns2000** [comment]
Thank you!
