### ISSUE TITLE
Installing packages in VM

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#43]
Hello,
I was trying to install YCM for Rust code completion in Vim, and as it turns out I cannot use `sudo apt` because I don't have root permission.
I completely understand that you cannot give root permission to students, but I cannot find another way because I have little knowledge of Ubuntu package managing. Is there a workaround that _doesn't_ require root permission?
Thank you.

**Comment by jeehoonkang** [comment]
- You can install software on your home directory.
- If you want me to install some packages, please give me the exact package name so that I can review and install.

**Comment by KunJeong** [comment]
https://github.com/ycm-core/YouCompleteMe
This is the package I'm trying to install. The problem is when installing its dependencies:
` sudo apt install build-essential cmake python3-dev `
I would appreciate it if you could install the packages, because currently I cannot find a way to install it in my home directory.

**Comment by jeehoonkang** [comment]
I installed them for you.

(Closing)

**Comment by KunJeong** [comment]
Hello. This package has stopped working after the latest server maintenance.

The following link seems to be the fix. However, it seems to require `sudo`, which I do not have access to. Could you please incorporate the fix?

**Comment by jeehoonkang** [comment]
Sorry, I just reinstalled it

**Comment by KunJeong** [comment]
Hmm..it still doesn't seem to work..

**Comment by jeehoonkang** [comment]
Here's the CLI result:

```
root@kaist-cp-cs420:~# apt install build-essential cmake python3-dev -y
Reading package lists... Done
Building dependency tree
Reading state information... Done
build-essential is already the newest version (12.8ubuntu1).
cmake is already the newest version (3.16.3-1ubuntu1).
python3-dev is already the newest version (3.8.2-0ubuntu2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

Please let me know if I can do more.

**Comment by KunJeong** [comment]
My mistake. I mentioned the 'link' and forgot to paste it.
[https://github.com/ycm-core/YouCompleteMe/issues/2259](url)
I think the command `sudo dnf install ncurses-compat-libs-6.0-5.20160116.fc24.x86_64` is the fix.

**Comment by jeehoonkang** [comment]
We're on Ubuntu.  Please give me `apt install` CLI command.

**Comment by KunJeong** [comment]
Ah yes. I checked the logs and it was a totally different issue.
The logs say libpython is not found. Could you please try`sudo apt-get install libpython3.6`?

**Comment by KunJeong** [comment]
Could you please try this? I'm sorry to press, but I'm worried that you might forget as this is a closed issue T.T

**Comment by jeehoonkang** [comment]
`libpython3.8-dev` is already installed.  Do you need the specific version of `libpython3.6-dev`?

```bash
$ apt search libpython
[...]
libpython3.8-dev/focal-updates,focal-security,now 3.8.2-1ubuntu1.1 amd64 [installed,automatic]
  Header files and a static library for Python (v3.8)
[...]
```

**Comment by KunJeong** [comment]
Ah, thanks for the info. I just figured out that it was a update/compile sort of problem (I'm not sure if it's because of the new server or a new update just happens to exist). It's fixed now. Thank you!
