### ISSUE TITLE
[HW7] Why `float2.ir` is not exception on small test set?

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#431]
Why `float2.ir` is not an exception on a small test set?

I think it should be an exception in the small test set since small one does not implement float.

**Comment by minseongg** [comment]
The difference between small test and big test is that big test includes array or struct. ([float.c](https://github.com/kaist-cp/kecc-public/blob/main/examples/c/float.c) includes `a[10]` which is array.)

Therefore, float2 is included in the small test.
