### ISSUE TITLE
[Final Project] Performance Competition (due: 6/20)

### ISSUE THREAD

**Issue by minseongg** [kaist-cp/cs420#433]
Performance Competition.

- **instruction**
  + https://docs.google.com/presentation/d/1SqtU-Cn60Sd1jkbO0OSsRYKPMIkul0eZoYG9KpMugFE/edit#slide=id.g8085bd6ec8_44_0
  + Since your solution will be linked with some [driver](https://github.com/kaist-cp/kecc-public/blob/main/bench/driver.cpp), you need to follow the [LP64D ABI](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/44f98e0fd8104def00f2a5a8d94b23dd647d18fb/riscv-elf.md#named-abis), which is the default ABI of RV64G ISA.
    + RVG Calling Convention: 18.2 of https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf
    + Godbolt's reference solution to [`exotic_arguments.c`](https://github.com/kaist-cp/kecc-public/blob/main/bench/exotic_arguments.c): https://godbolt.org/z/bzn6v7Pf8
  + Use `la` pseudo instruction instead of `HI20` and `LO12` pair: https://github.com/kaist-cp/cs420/issues/168#issuecomment-653044107
  + Check that your code does not have [unaligned memory access](https://github.com/westerndigitalcorporation/RISC-V-Linux/blob/master/linux/Documentation/unaligned-memory-access.txt).
  + The stack pointer should always be kept 16-byte aligned. (p3 of https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf) 
- **self grader**: https://github.com/kaist-cp/kecc-public#run-benchmark-for-performance-competition
  + It will build your compiler, build benchmark codes, run them, and measure the elapsed CPU cycles. The average is your score (lower is better).
- **submission**: run `./scripts/make-submissions.sh` and then submit `final.zip`.
  + There is 10 minute timeout for each submission.
  + https://gg.kaist.ac.kr/assignment/59/
- **leaderboard**
  + https://docs.google.com/spreadsheets/d/1eXmNAX_7dpojvv6BjLG__hcueg8_V2LANk9JF7GY6aQ/edit#gid=0
  + The next score on the leaderboard will be updated to `min(# of cycle on the leaderboard, # of cycle of the last success submission on gg)`.
- **due**: 6/20 23:59:59 (KST = UTC+9)

**Comment by minseongg** [comment]
Now you can submit your solution: https://gg.kaist.ac.kr/assignment/59/

**Comment by TanapTheTimid** [comment]
I am having trouble submitting to gg. The benchmark runs perfectly fine on both my local machine and on the ssh server, but on gg it simply stops and has return code 1 but there is no error message.

```
...
    Finished release [optimized] target(s) in 30.76s
(../target/release/kecc -O graph.c -o graph.s) || (rm graph.s -rf; exit 1)
(../target/release/kecc -O two_dimension_array.c -o two_dimension_array.s) || (rm two_dimension_array.s -rf; exit 1)
(../target/release/kecc -O matrix.c -o matrix.s) || (rm matrix.s -rf; exit 1)
(../target/release/kecc -O exotic_arguments.c -o exotic_arguments.s) || (rm exotic_arguments.s -rf; exit 1)
(../target/release/kecc -O fibonacci.c -o fibonacci.s) || (rm fibonacci.s -rf; exit 1)
riscv64-linux-gnu-g++ -O -fsigned-char -o driver.o -c -I. driver.cpp
riscv64-linux-gnu-g++ -o bench ./graph.s ./two_dimension_array.s ./matrix.s ./exotic_arguments.s ./fibonacci.s driver.o
```

**Comment by gmlwns2000** [comment]
@TanapTheTimid
I have the same situation...

**Comment by minseongg** [comment]
@TanapTheTimid @gmlwns2000 

It seems like the RISC-V machine has been shutdown, we will fix it asap. Sorry for the inconvenience..

**Comment by TanapTheTimid** [comment]
Also, do we get to see a leader board for the competition?

**Comment by minseongg** [comment]
@TanapTheTimid Yes, we will prepare leaderboard.

**Comment by minseongg** [comment]
@TanapTheTimid @gmlwns2000 We restored RISC-V grading machine. Please notice to me if you meet the same problem again.

**Comment by TanapTheTimid** [comment]
Out of curiosity, can you tell us what the score for GCC is on the RISC-V grading machine?

**Comment by minseongg** [comment]
@TanapTheTimid 

The score for GCC on the grading machine is as follows:

```
root@kaist-cp-dev-cs420:~# ./bench-gcc 
[exotic_arguments_struct_small] 199
[exotic_arguments_struct_large] 653
[exotic_arguments_struct_small_ugly] 242
[exotic_arguments_struct_large_ugly] 532
[exotic_arguments_float] 52
[exotic_arguments_double] 53
[fibonacci_recursive] 41075460
[fibonacci_loop] 1494
[two_dimension_array] 175509
[matrix_mul] 295262
[matrix_add] 47800
[graph_dijkstra] 84739256
[graph_floyd_warshall] 99937019
[fibonacci_recursive] 36151327
[fibonacci_loop] 1449
[two_dimension_array] 65203
[matrix_mul] 276021
[matrix_add] 47695
[graph_dijkstra] 76683360
[graph_floyd_warshall] 100443047
[fibonacci_recursive] 36185948
[fibonacci_loop] 1832
[two_dimension_array] 64783
[matrix_mul] 297135
[matrix_add] 48621
[graph_dijkstra] 78358512
[graph_floyd_warshall] 101140693
[fibonacci_recursive] 36315369
[fibonacci_loop] 1378
[two_dimension_array] 64723
[matrix_mul] 271088
[matrix_add] 46670
[graph_dijkstra] 76633662
[graph_floyd_warshall] 99971763
[fibonacci_recursive] 36150515
[fibonacci_loop] 1179
[two_dimension_array] 64717
[matrix_mul] 429953
[matrix_add] 48363
[graph_dijkstra] 77247150
[graph_floyd_warshall] 100009689
[fibonacci_recursive] 36399861
[fibonacci_loop] 1436
[two_dimension_array] 64494
[matrix_mul] 273225
[matrix_add] 49755
[graph_dijkstra] 76579710
[graph_floyd_warshall] 101178033
[fibonacci_recursive] 36165205
[fibonacci_loop] 1918
[two_dimension_array] 64571
[matrix_mul] 271172
[matrix_add] 48689
[graph_dijkstra] 80518464
[graph_floyd_warshall] 102840088
[fibonacci_recursive] 36659496
[fibonacci_loop] 1390
[two_dimension_array] 64471
[matrix_mul] 272030
[matrix_add] 46477
[graph_dijkstra] 77532584
[graph_floyd_warshall] 102186432
[fibonacci_recursive] 36636859
[fibonacci_loop] 1359
[two_dimension_array] 64811
[matrix_mul] 275482
[matrix_add] 50316
[graph_dijkstra] 78467037
[graph_floyd_warshall] 18446743967451757553
[fibonacci_recursive] 36226216
[fibonacci_loop] 1352
[two_dimension_array] 64044
[matrix_mul] 271521
[matrix_add] 48281
[graph_dijkstra] 76687166
[graph_floyd_warshall] 101586861
[AVERAGE] 1.28227e+06
```

**Comment by minseongg** [comment]
@TanapTheTimid Sorry, there was a mistake on the GCC score on the initial comment; please see the updated score.

**Comment by gmlwns2000** [comment]
😂 Mine is 3.6 times **worse** than GCC. Incredible.

**Comment by minseongg** [comment]
@hyn2028 Thanks! We fixed it.

**Comment by minseongg** [comment]
**IMPORTANT**: If your gg score is significantly worse than self grader, please check that your code does not have [unaligned memory access](https://github.com/westerndigitalcorporation/RISC-V-Linux/blob/master/linux/Documentation/unaligned-memory-access.txt). The grading RISC-V machine seems to be operating very slowly for unaligned memory access.

**Comment by minseongg** [comment]
**IMPORTANT**: The stack pointer should be always kept 16-byte aligned. (p3 of https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf, https://github.com/kaist-cp/cs420/issues/450#issuecomment-1159779360)

**Comment by minseongg** [comment]
**IMPORTANT**: There is 10 minute timeout for each submission.

**Comment by minseongg** [comment]
**IMPORTANT**: From now on, the next score on the leaderboard will be updated to `min(# of cycle on the leaderboard, # of cycle of the last success submission on gg)`.

**Comment by jeehoonkang** [comment]
The final leaderboard is here: [link](https://docs.google.com/spreadsheets/d/1eXmNAX_7dpojvv6BjLG__hcueg8_V2LANk9JF7GY6aQ/edit#gid=0)

Shout out to @TanapTheTimid, whose compiler outperforms `gcc -O1`. Even though the result is only for a very small unscientific set of benchmarks, it's a huge achievement for a University term project!

Honorable mention to @hyn2028 and @gmlwns2000, whose compilers outperform `gcc -O0`!

 Congratulations to every participant!
