### ISSUE TITLE
[Final] Makefile should not read stdout of kecc. It should use `-o` for generate `.s` file.

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#434]
Hi,

The makefile should not read stdout of kecc.  It should use `-o` to generate `.s` file.

My compiler has logging feature, so it may contains non assembly code in stdout.

**Comment by minseongg** [comment]
We updated it: https://github.com/kaist-cp/kecc-public/commit/f7def26ba5a40fe4e070a3228abdb97d462f8891
