### ISSUE TITLE
[Final] Makefile does not recompile the binary

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#435]
Makefile does not recompile my binary even if the source code is updated.

I am not sure why this is happening...

Thank you!

**Comment by minseongg** [comment]
We updated Makefile to remove KECC binary when do `make clean`: https://github.com/kaist-cp/kecc-public/commit/531a56c0ea5be1b6ab5427ea3cf22d8803189937

Please try again after `make clean`.

**Comment by gmlwns2000** [comment]
It seems works! Thank you
