### ISSUE TITLE
[HW8] Allow to using @PLT reallocation flag

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#436]
When I tried to run `make run` I encountered the error.

```
s20200535@kaist-cp-cs420:~/library/kecc-ainl/bench$ make run
riscv64-linux-gnu-g++ -o bench ./graph.s ./matrix.s ./fibonacci.s ./two_dimension_array.s ./exotic_arguments.s driver.o
/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/bin/ld: /tmp/ccubtstx.o: relocation R_RISCV_HI20 against `graph_weight' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/bin/ld: /tmp/ccLO4cTz.o: relocation R_RISCV_HI20 against `matrix_a' can not be used when making a shared object; recompile with -fPIC
/usr/lib/gcc-cross/riscv64-linux-gnu/9/../../../../riscv64-linux-gnu/bin/ld: /tmp/cczcoePx.o: relocation R_RISCV_HI20 against `two_dimension_array_arr' can not be used when making a shared object; recompile with -fPIC
collect2: error: ld returned 1 exit status
make: *** [Makefile:14: bench] Error 1
```

It says, I need to compile the source code `.s`, with `-fPIC` flag. I didn't know what is `PIC`, so I searched google.

[And I figured out the `fPIC` is a special flag](https://devanix.tistory.com/198) for formatting reallocation immediate in assembly code. But in the `asm/mod.rs` there is no such relocation function.

So what is the problem here? How can I fix this? Should we need new relocation function?

**Comment by minseongg** [comment]
Please follow this comment: https://github.com/kaist-cp/cs420/issues/168#issuecomment-653044107

**Comment by gmlwns2000** [comment]
@minseongg Thank you! I fix it :)
