### ISSUE TITLE
[HW8] make run not working

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#438]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

```
s20150910@kaist-cp-cs420:~/kecc-public/bench$ make run
(../target/release/kecc -O graph.c -o graph.s) || (rm graph.s -rf; exit 1)
thread 'main' panicked at 'not yet implemented: homework 3', src/opt/simplify_cfg.rs:30:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
make: *** [Makefile:29: graph.s] Error 1
```
This is the error message I get when I try to execute the makefile.  It seems to be using a wrong version of simplify_cfg.  I feel like I might be making a really stupid mistake but I can't figure out what it is.  What could be causing this?

**Comment by minseongg** [comment]
Could you try again after `make clean` ?
