### ISSUE TITLE
[HW8] passing struct via function argument

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#439]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

For HW7, I implemented struct argument such that the caller function stores the struct in its stack space and passes its address via A0 register.  The callee function would then load from the address received in A0, which means it would access its callee function's stack space.  Using this implementation, I successfully passed all tests in HW7.

However, when I run HW8, I am getting a segmentation fault in some of the test cases.  I was wondering if my method of passing struct argument was causing this segmentation fault, or if it's another issue.  `exotic_arguments_struct_small` is one of the test cases that are causing segmentation fault, and I included my assembly code for reference:

```
        .globl	exotic_arguments_struct_small
        .section	.text
exotic_arguments_struct_small:
        addi	sp,sp,-88
        sd	ra,80(sp)
        sd	s0,72(sp)
        addi	s0,sp,88
        ld	t0,0(a0)
        sd	t0,-24(s0)
        sw	a1,-32(s0)
exotic_arguments_struct_small.LB0:
        ld	a0,-24(s0)
        sd	a0,-40(s0)
        addi	a0,s0,-40
        li	a1,0
        add	a0,a0,a1
        sd	a0,-48(s0)
        ld	a0,-48(s0)
        lw	a0,0(a0)
        sw	a0,-56(s0)
        addi	a0,s0,-40
        li	a1,4
        add	a0,a0,a1
        sd	a0,-64(s0)
        ld	a0,-64(s0)
        lw	a0,0(a0)
        sw	a0,-72(s0)
        lw	a0,-56(s0)
        sext.w	a0,a0
        lw	a1,-72(s0)
        sext.w	a1,a1
        addw	a0,a0,a1
        sw	a0,-80(s0)
        lw	a0,-80(s0)
        sext.w	a0,a0
        lw	a1,-32(s0)
        sext.w	a1,a1
        addw	a0,a0,a1
        sw	a0,-88(s0)
        lw	a0,-88(s0)
        sext.w	a0,a0
        ld	s0,72(sp)
        ld	ra,80(sp)
        addi	sp,sp,88
        ret
```

**Comment by minseongg** [comment]
For the final project, you need to follow the [RV64G calling convention](https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf).

In the second paragraph of 18.2, it says that

> If the arguments to a function are conceptualized as fields of a C struct, each with pointer alignment, the argument registers are a shadow of the first eight pointer-words of that struct.

The arguments to the function `exotic_arguments_struct_small` is like this:

```c
typedef struct {
  int a;
  int b;
} small;

struct {
  struct small a,
  int nonce,
}
```

And this struct is memory-aligned like this:

```
0     4     8     12    16
+-----+-----+-----+-----+
| a.a | a.b |   nonce   |
+-----+-----+-----+-----+
```

Therefore, when driver calls `exotic_arguments_struct_small(small a, int nonce)` with arguments `a = small { .a = 3, .b = 4 }` and `nonce = 0x54`, the arguments are passed to the function with register `a0 = 0x400000003` and `a1 = 0x54`. (`a0` indicates the first 8 bytes of the arguments struct which contains `a.a` and `a.b`, `a1` indicates the next 8 bytes of the arguments struct which contains `nonce`)
