### ISSUE TITLE
[Lecture] Register Allocation Algorithms

### ISSUE THREAD

**Issue by hyn2028** [kaist-cp/cs420#442]
Hello.

I have a question regarding the register allocation algorithm I learned in class. The slides are `Stanford's Slides`.

1. In the `simple linear scanning` method, to assign a register to another variable (`r0` to `d`), the variable (`a`) that previously owned the register is spilled (p.91). In this case, will variable a spill from the beginning to the end of the program (except that it is temporarily loaded into a register for operation and then saved)? Or at the beginning of `d`'s live interval, `a` itself goes onto the stack and transfers the register ownership to `d`?

2. In the `second-chance bin packing` method, what is the criterion for when the spilled variable owns the register again? On slide p.119, the variable `a` never owned the register again after it spilled, but why was the variable `f` able to take the register again?

Thank you.

**Comment by jeehoonkang** [comment]
- A naive/simple linear scanning algorithm would spill the variable `a` for its entire life. The second-chance bin-packing algorithm is more clever and spills `a` when `d` becomes live.
- Good question. It seems `f` is **used at the line** so we need to "bring back" it to the register set. I believe that's why we assign `f` a register again.

**Comment by hyn2028** [comment]
So why doesn't `a` own the register again? In `a`, can it be assumed that the use of the variable has not yet occurred during the scanning period (the live interval continues as it will be used later, not shown in the table)?

**Comment by Lee-Janggun** [comment]
I think the "example" simply did not reach the point where it re-gives the register back to `a`.

**Comment by hyn2028** [comment]
@Lee-Janggun I think that's the most convincing. Thank you, it was very helpful.
