### ISSUE TITLE
Rust Tutor

### ISSUE THREAD

**Issue by shoh94** [kaist-cp/cs420#444]
# Parttime job offering: Rust tutor
@jeehoonkang (Thanks to prof. Jeehoon Kang for allowing us to post this invitation.)
We invite a Rust tutor who can give us a 2-day lecture including hands-on practice on Rust programming language.
We are astrophysicists and recently form a voluntary group "Numerical Astrophysics in Rust" to study Rust and find its potential applications to our research fields. Many of our members used to develop small codes for their research in C or Fortran, which means we are often lost in novel concept embraced. If you're intrigued, please do not hesitate to send your CVs to astrorust2022@gmail.com by Jun 15, 2022.

## A bit of details on tutoring
 * Venue: KIRD in Daeduk Business Center 11F, Daejeon (대전 대덕테크비즈센터 11층 국가과학기술인력개발원 세미나실)
 * Per diem: 600K (KRW) (1,200K in total)  / Lunch will be provided
 * Date: 2 days (negotiable, not necessarily consecutive days)
 * Lecture on Rust Basic Syntax / File IO / Smart Pointer / Concurrency / Object Oriented Programming
 * Language: Korean (English lectures are also acceptable)
 * Expected attendance: 10
 * Schedule  (Tentative)
   * 10:00 - 11:00 Lecture 1  (60min)
   * 11:00 - 12:00 Hands-on practice 1  (60min)
   * 12:00 - 13:00 Lunch
   * 13:00 - 13:30 Lecture 2  (30min)
   * 13:30 - 14:20 Hands-on practice 2  (50min)
   * 14:20 - 14:30 coffee break    (10min)
   * 14:30 - 15:00 Lecture 3  (30min)
   * 15:00 - 16:00 Hands-on practice 3  (60min)
 * Email applications and CVs should be delivered to astrorust2022@gmail.com  by Jun 15, 2022.
 * Announcement in Korean: https://sites.google.com/view/recruit-a-rust-tutor/

**Comment by jeehoonkang** [comment]
@shoh94 thanks for sharing a job posting for our students. I wish you could have a great seminar!
