### ISSUE TITLE
[HW3] In reach.input.ir, Why should we not optimize B1 as an empty or merged block? 

### ISSUE THREAD

**Issue by gjrud1470** [kaist-cp/cs420#445]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

For reach.input.ir, the output is designed to hold the two blocks (of inf loop) b0, b1

I'd like to be clarified why should block b1 be considered as an empty(no phinode and instructions for b1) or merging block(only b0 jumps to b1) and end with an output with only block b0 with self loop as following?

block b0:
   j b0()

Sorry for late question

**Comment by minseongg** [comment]
For `reach.output.ir`, only `SimplifyCfgReach` is applied to `reach.input.ir`. ([tests/test_examples.rs#L123-L127](https://github.com/kaist-cp/kecc-public/blob/main/tests/test_examples.rs#L123-L127))

If all simplify-cfg optimizations(`SimplifyCfgConstProp`, `SimplifyCfgReach`, `SimplifyCfgMerge`, `SimplifyCfgEmpty`) are applied, then as you mentioned, `b1` is considered as empty block and it is merged with `b0`.

```
fun i32 @foo () {
init:
  bid: b0
  allocations:


block b0:
  j b0()
}
```

**Comment by gjrud1470** [comment]
thank you! that cleared up my question
