### ISSUE TITLE
[HW8] Problem with register interference in ir2 codes involving loops

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#447]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

My register allocation algorithm is having problems returning the correct answer for ir2 codes involving loops (more specifically, cond_and_loop.ir and while_continue_break.ir).  Because it passes ir0 and ir1 codes, I suspect that this has something to do with phinodes (because ir2 introduces phinodes).  I believe this is a problem with register interference, because if I simply assign registers 1-to-1, it passes without any problem.  So I've been trying to find any interference in my register allocation, but I can't seem to find it.

Here is an example of my code's allocation (for ir2/while_continue_break.ir):
```
Temp { bid: BlockId(5), iid: 10 }: (Saved(Integer, 4),
--
Temp { bid: BlockId(5), iid: 2 }: (Saved(Integer, 5),
--
Temp { bid: BlockId(4), iid: 1 }: (Saved(Integer, 6),
--
Arg { bid: BlockId(1), aid: 0 }: (Saved(Integer, 7),
--
Arg { bid: BlockId(1), aid: 1 }: (Saved(Integer, 8),
--
Temp { bid: BlockId(0), iid: 3 }: (Saved(Integer, 9),
Arg { bid: BlockId(3), aid: 0 }: (Saved(Integer, 9),
--
Temp { bid: BlockId(2), iid: 2 }: (Saved(Integer, 10),
Temp { bid: BlockId(1), iid: 1 }: (Saved(Integer, 10),
Temp { bid: BlockId(5), iid: 9 }: (Saved(Integer, 10),
--
Temp { bid: BlockId(5), iid: 5 }: (Saved(Integer, 11),
Temp { bid: BlockId(0), iid: 2 }: (Saved(Integer, 11),
```
This is the control flow graph of ir2/while_continue_break.ir:
![image](https://user-images.githubusercontent.com/20104363/174428880-7e89eb62-cc61-4fca-a211-da506111e2cc.png)

I have considered every possible interference between IR registers assigned to the same ASM register, but it seems correctly allocated.  As I said before, simply assigning every IR register to a new ASM register solves this problem (so I suspect there is an interference I have failed to consider).  Can you check if there is any interference in the allocation I posted above?  If not, can you think of any possible reason for my code's behavior?

**Comment by minseongg** [comment]
I think one possible reason can be allocating same register (`s9`) to `%b0:i3` and `%b3:p0`.

Due to mem2reg optimization, [`%b0:i3` is also used in `b5` of `ir2/while_continue_break.ir`](https://github.com/kaist-cp/kecc-public/blob/main/examples/ir2/while_continue_break.ir#L53).

Now let's think one possible execution flow `b0 -> b1 -> b2 -> b5`. Here, the value of `%b0:i3` is saved to `s9` in `b0` and it is used in `b5`. If you changed the value of `s9` in `b1` to pass the phinode value to `b3` (`%b3:p0`), then the value of `%b0:i3` used in `b5` can be incorrect.

**Comment by andersc97** [comment]
The case you mentioned is definitely a problem, but I found another problem that's not related to phinodes:

![image](https://user-images.githubusercontent.com/20104363/174443802-dae7fbcf-79a3-4bd3-a564-85a510662d49.png)

Consider register `r1` is defined in `b3` and used in `b8`.  Another register `r2` is defined in `b14` and used in `b14`.  These 2 registers should be considered as interfering, because after the first iteration of the loop, the value of the ASM register would have been overwritten by `r2`.  However, using the method described in slide 106, this interference cannot be identified.

![image](https://user-images.githubusercontent.com/20104363/174443942-f2efab1b-2202-4f5f-92f8-df1b9333504c.png)

In thise case, `r1def` dominates `r2def` but `r2def` does not dominate `r1use`.  It seems that in the case of loops, it is not sufficient to simply consider that `r2def` dominates `r1use`, but we should consider if any path exists from `r2def` to `r1use`.

Is my analysis correct?  Is there any way to implement this without traversing every block each time to check for a path?

**Comment by Lee-Janggun** [comment]
It looks like this was an oversight :(. I followed what was shown in [here](https://www.cs.clemson.edu/course/cpsc827/material/Optimization/Live%20Range%20Analysis.pdf). It's kinda inefficient, but it seems to work.

**Comment by jeehoonkang** [comment]
@andersc97 thanks for pointing out the slide's bug. I'll fix it soon. Until then, please follow @Lee-Janggun's suggestion.

**Comment by andersc97** [comment]
The pdf's algorithm works perfectly fine.  My only disappointment is that this didn't really improve my performance compared to my previous method where I simply made a one-to-one map from ir register to asm register.  I guess this is because there are so many available registers and the functions in the benchmark code are not very long, so most variables fit inside the given available registers.

**Comment by Lee-Janggun** [comment]
Seems like the above pdf is incorrect for SSA programs, at least for them without some modification...

**Comment by andersc97** [comment]
Don't you mean inefficient?  I thought it was at least correct because my implementation passed all the hw7 tests without any problem.

The only edge case I had to consider was for variables whose live range didn't extend beyond a single block (i.e. defined and used within a single block).

I thought the usefulness of SSA is that it allows additional optimizations.. Can it actually invalidate some optimizations?

**Comment by Lee-Janggun** [comment]
What I meant is that I somehow am not getting to compute live ranges correctly in the presence of phinodes. What is their semantics?

**Comment by andersc97** [comment]
Oh, in terms of phinodes, I marked their definitions in the predecessor blocks of their actual definition.  Also, I marked the jump arguments' uses at the phinode's block.

This way, the interference between the phinode registers and their value registers will be acknowledged.

**Comment by Lee-Janggun** [comment]
@andersc97 
Oh that will work. For your second comment, you mean that , for exampe, if we have `j b3(%b2a1)` in block b4, we will mark `%b2a1` as used?

**Comment by andersc97** [comment]
I mean that %b2a1 will be marked as used in both b3 and b4.  Also, b3's phinode will be marked as defined in b4 and used in b3 (even though it's semantically defined in b3).

**Comment by Lee-Janggun** [comment]
Thank you for the detailed answer. I will definatly try this :)
