### ISSUE TITLE
[HW8] Processing caller-saved registers before and after function call

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#448]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--
Sorry for asking so many questions..

I'm currently having a problem where caller-saved register values are occasionally corrupted after a function call.  It causes problems only sometimes, and it seems to be random.
This is how I store and load caller-saved register values before and after every function call:
```
        sd	t5,-128(s0)
        sd	t1,-136(s0)
        sd	t4,-144(s0)
        sd	t2,-152(s0)
        sd	t3,-160(s0)
        sd	t6,-168(s0)
        mv	a0,s8
        call	foo
        ld	t6,-168(s0)
        ld	t3,-160(s0)
        ld	t2,-152(s0)
        ld	t4,-144(s0)
        ld	t1,-136(s0)
        ld	t5,-128(s0)
```
I use 64-bit store/load every time, regardless of the Dtype of the contents of the register.
I know that this segment of the code is what causes the problem, because if I remove the store/load instructions for these registers, the program behaves correctly.
In my implementation, the stack location of the store is not necessarily same at every function call.  I simply push to stack and then pop from stack depending on where my virtual stack pointer is at the time of the function call.

Am I implementing this incorrectly?  What might be the reason that the values are corrupted after the store/load?

**Comment by minseongg** [comment]
It seems there is no problem in your implementation..

I recommend you to check that (1) you are allocating enough amount of stack space for each function call and (2) you are not corrupting stack space which is allocated in other function call.

**Comment by andersc97** [comment]
As you said, I was using unallocated stack space
