### ISSUE TITLE
[HW8] gg submission fails without error message

### ISSUE THREAD

**Issue by andersc97** [kaist-cp/cs420#449]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

My code runs on the server, but my gg submission fails without any error message.
Can you check if there's a problem with the risc-v machine like last time?

![image](https://user-images.githubusercontent.com/20104363/174465082-595841c1-1087-4ebe-bec6-e98d13fc037e.png)

**Comment by minseongg** [comment]
We will restore it asap. Sorry for the inconvenience.

**Comment by minseongg** [comment]
We fixed the grading RISC-V machine. Could you please submit again?

**Comment by andersc97** [comment]
Thanks, it worked now
