### ISSUE TITLE
[HW2] Will interpreter of more unaryoperators be added?

### ISSUE THREAD

**Issue by LockOne** [kaist-cp/cs420#45]
There is only some unary operator interpretation implemented in KECC. (`+, -, ~`)
commonly `for statement` uses post or pre-incremental operator (i.e.` i++`),
but it is not implemented in KECC.
Should I wait for the implementation of interpreter or 
implement unary-operation with several save and load instructions?

\+ What is the intended size of long double in KECC?

**Comment by cmpark0126** [comment]
Thank you for the question :)

1. `kecc` covers all unary operators described here: https://docs.rs/lang-c/0.8.0/lang_c/ast/enum.UnaryOperator.html
Please check this code: [c/parse.rs#L550-L552](https://github.com/kaist-cp/kecc-public/blob/6edb4665c008e899b6c4ba45e4f9220da6f0acdb/src/c/parse.rs#L550-L552)

    FYI, if operator expression cannot be translated to [instruction](https://github.com/kaist-cp/kecc-public/blob/6edb4665c008e899b6c4ba45e4f9220da6f0acdb/src/ir/mod.rs#L184-L220) directly, you need to interpret that operator expression to appropriate form using existing instruction. For example, if unary operator expression is `++i`, it can be transformed to `i = i + 1`. If you have no idea how to interpret it, please refer to LLVM IR's result.

2. `kecc` does not cover `long double` type: [ir/mod.rs#L547-L549](https://github.com/kaist-cp/kecc-public/blob/6edb4665c008e899b6c4ba45e4f9220da6f0acdb/src/ir/mod.rs#L547-L549)

**Comment by LockOne** [comment]
What I meant was that there was no implementation for pre-incremental unary operation on the  [interp.rs calculate_unary_operator_expression](https://github.com/kaist-cp/kecc-public/blob/6edb4665c008e899b6c4ba45e4f9220da6f0acdb/src/ir/interp.rs#L331), but I'm not sure whether it is intended or not.
I think I got the answer.  Thank you.
