### ISSUE TITLE
[HW8] gg submission fails without error message again

### ISSUE THREAD

**Issue by psb0623** [kaist-cp/cs420#450]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I just finished HW8, and it works well on my server.

However, my gg submission fails just like https://github.com/kaist-cp/cs420/issues/449, without any error messages. (submission ID 10997 - 11000)

![image](https://user-images.githubusercontent.com/81062893/174474793-26187fb0-d2ef-4e59-936a-2adce8571d6f.png)
Can you check RISC-V machine again?

**Comment by minseongg** [comment]
We checked the RISC-V grading machine, and found that your submission works well in the qemu but it causes bus error in the grading machine.

Could you send your `final.zip` to minseong.jang@kaist.ac.kr ?

**Comment by psb0623** [comment]
I sended final.zip file!

What is the reason of this error? Should I fix my code for it?

**Comment by minseongg** [comment]
The bus error occurred at `sd` instruction when the stack pointer is not aligned to 16-byte.

Please modify the implementation to the stack pointer is always kept 16-byte aligned. (p3 of https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf)

**Comment by psb0623** [comment]
Oh... I missed that point. Sorry for my mistake.
I modified the stack pointer to be 16-byte aligned and now it works well.

Thank you so much for your help!
