### ISSUE TITLE
[HW8] Could you measure the best result only for competition?

### ISSUE THREAD

**Issue by gmlwns2000** [kaist-cp/cs420#451]
I updated my code a little bit about memory access, and I got significantly worse performance than before submission because of a known issue.

And I found out the performance leaderboard only gather the latest success result.

I think it should be the best result, not the latest.

**Comment by minseongg** [comment]
Thanks for reporting, we will fix it. Until then, could you submit the last best submission?

**Comment by gmlwns2000** [comment]
Ok I will resubmit in GG!

**Comment by minseongg** [comment]
We updated to measure the best result on the competition!

**Comment by minseongg** [comment]
We changed the leaderboard to the next score will be updated to `min(# of cycle on the leaderboard, # of cycle of the last success submission)`.
