### ISSUE TITLE
[Homework 1] C AST Printer (due: 3/31)

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs420#453]
Implement C AST Printer.

- **goal**: understanding the C AST provided by KECC
- **instruction**: https://www.youtube.com/watch?v=SOzsb09GldA&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=6
- **skeleton**: https://github.com/kaist-cp/kecc-public/blob/main/src/c/write_c.rs
    + fill out `todo!()`.
    + **don't fork this repository.**  It'll be public!
- **self grader**: https://github.com/kaist-cp/kecc-public/blob/main/scripts/grade-write_c.sh
    + run `./scripts/grade-write_c.sh`.
- **submission**: https://gg.kaist.ac.kr/assignment/90/ . Submit `write_c.rs`.
- **due**: 3/31 23:59:59 (KST = UTC+9)
- **Rust tutorial**: https://doc.rust-lang.org/book/
    + Chapters 1-15 and 18 would be especially beneficial to read.

**Comment by CuriousLocky** [comment]
I have a question about the evaluation. I just uploaded a version with some (rarely used or compiler specific) features not implemented to the server, and got a `success` result. Does it mean I can receive a full score for this homework?

**Comment by jirheee** [comment]
If gg says "Yes", you will receive full scores on that assignment. (FYI, we do not have any hidden test cases. If you succeed running the provided grading script, it means you will get full marks)

**Comment by jeehoonkang** [comment]
@CuriousLocky would you please share the feature with us? Maybe we should add test cases...

**Comment by CuriousLocky** [comment]
@jeehoonkang The features include variable arguments, TS18661 float, GNU extended asm statement with `goto` as qualifier, and Clang availability attribute with minor and subminor arguments. But please do not add more test cases, at least for this semester TAT

**Comment by m-spitfire** [comment]
@CuriousLocky I didn't check the other things you mentioned, but TS18661 floats are not supported by KECC by choice. See what's supported and what's not here: https://github.com/kaist-cp/kecc-public/blob/main/src/c/parse.rs

**Comment by jirheee** [comment]
due extended to April 7th: https://github.com/kaist-cp/cs420/issues/482
