### ISSUE TITLE
[Homework 2] IR Generation (due: 4/30)

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#454]
Implement IR generation.

- **goal**: understanding the IR provided by KECC
- **instruction**
    + https://www.youtube.com/watch?v=HjARCUoK08s&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=12
    + https://www.youtube.com/watch?v=Rszt9x0Xu_0&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=13
- **skeleton**: https://github.com/kaist-cp/kecc-public/blob/main/src/irgen/mod.rs
    + fill out `todo!()`.
    + **don't fork this repository.**  It'll be public!
- **self grader**
    + https://github.com/kaist-cp/kecc-public/blob/main/scripts/grade-irgen-small.sh (small)
    + https://github.com/kaist-cp/kecc-public/blob/main/scripts/grade-irgen.sh
- **submission**: run `./scripts/make-submissions.sh` and then submit `irgen.zip.`
    + https://gg.kaist.ac.kr/assignment/91/ (small)
    + https://gg.kaist.ac.kr/assignment/92/
- **due**: 4/30 23:59:59 (KST = UTC+9)
- **note**: I suggest you begin with the small hw2 and then move on to the full hw2. Each of the small and full hw2 assignments has the same weight as the other assignments.
- **model solution**: You can check the model solution in https://gg.kaist.ac.kr/assignment/100/. It will show the generated `kecc ir` given a C file.

**Comment by CuriousLocky** [comment]
I tried to implement the features in separated files using `mod`. It runs fine locally but cannot pass the test after submitted to gg. Are we required to write everything in one file?

**Comment by m-spitfire** [comment]
Hello. As you can see in the https://github.com/kaist-cp/kecc-public/blob/main/scripts/make-submissions.sh only `write_c.rs` and `irgen/mod.rs` files are being submitted to the gg.
