### ISSUE TITLE
[Homework 7] Assembly Generation (due: 6/19)

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#459]
Implement assembly generation.

- **instruction**
    + https://www.youtube.com/watch?v=qLZUtNTYIoo&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=28 and the following videos in the same playlist
    + https://docs.google.com/presentation/d/1SqtU-Cn60Sd1jkbO0OSsRYKPMIkul0eZoYG9KpMugFE/edit#slide=id.g8085bd6ec8_18_13
    + RISC-V ISA manual: http://csl.snu.ac.kr/courses/4190.307/2020-1/riscv-spec-v2.2.pdf
- **skeleton**: https://github.com/kaist-cp/kecc-public/blob/main/src/asmgen/mod.rs
    + fill out `todo!()`.
    + **don't fork this repository.**  It'll be public!
- **self grader**
    + https://github.com/kaist-cp/kecc-public/blob/main/scripts/grade-asmgen.sh
    + https://github.com/kaist-cp/kecc-public/blob/main/scripts/grade-asmgen-small.sh
- **submission**: run `./scripts/make-submissions.sh` and then submit `asmgen.zip`.
    + https://gg.kaist.ac.kr/assignment/98/ (full)
    + https://gg.kaist.ac.kr/assignment/97/ (small)
- **due**: 6/19 23:59:59 (KST = UTC+9)
- **model solution**: https://gg.kaist.ac.kr/assignment/101/

**Comment by AnHaechan** [comment]
Link for model solution added
