### ISSUE TITLE
[TIP] Using fuzzer with docker environment

### ISSUE THREAD

**Issue by sklationd** [kaist-cp/cs420#460]
Hi everyone,

I'm currently working on hw1. Since we don't have a VM yet, I use my local environment for now(macOS). And I faced an [issue](https://github.com/kaist-cp/cs420/issues/165) with using fuzzer. To solve this problem, I created a ubuntu docker environment with a few settings.

If you're also struggling with this issue, you can check out this [repository](https://github.com/sklationd/docker-kecc).

I hope this helps you with the issue of using fuzzer on your local environment.

### On my local machine
```sh
> python3 tests/fuzz.py --print --reduce
Use default random seed
Building KECC..
    Finished release [optimized] target(s) in 0.21s
Traceback (most recent call last):
  File "tests/fuzz.py", line 354, in <module>
    creduce(tests_dir, fuzz_arg, args.clang_analyze)
  File "tests/fuzz.py", line 244, in creduce
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=tests_dir)
  File "/Users/skla/opt/anaconda3/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Users/skla/opt/anaconda3/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'creduce'
```

### On docker environment
```sh
root@057fe9a7eaea:/home/kecc# python3 tests/fuzz.py --print --reduce
Use default random seed
Building KECC..
    Finished release [optimized] target(s) in 0.18s
|: 100%|███████████████████████████████████████| [Elapsed:04:20, <ETA:00:00]Reduce finished.
|: 100%|███████████████████████████████████████| [Elapsed:04:20, <ETA:00:00]
```

**Comment by jirheee** [comment]
Thank you for sharing your docker setup! I'll label this issue as `tip` so other students can refer to this issue when they want to run `kecc` in  their local machine.
