### ISSUE TITLE
[HW1] Does passing the grading scripts guarantee full credit?

### ISSUE THREAD

**Issue by sklationd** [kaist-cp/cs420#461]
Here is the output of executing `./scripts/grade-write_c.sh` (some lines have been omitted).

1. Does the output imply that I passed a grading script(Because it seemed like it accidentally stopped without printing any results.)?
2. If so, does it mean that I will receive full credit?

```sh
root@057fe9a7eaea:/home/kecc# ./scripts/grade-write_c.sh 
    Finished dev [unoptimized + debuginfo] target(s) in 0.25s
    Finished release [optimized] target(s) in 0.35s
     Running unittests src/lib.rs (target/release/deps/kecc-7065a22d2103757c)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/test_examples.rs (target/release/deps/test_examples-d8ae6d8bc74bd05f)

running 1 test
[testing "examples/c/alignof.c"]
[testing "examples/c/array.c"]
[testing "examples/c/array2.c"]
...
[testing "examples/c/unary.c"]
[testing "examples/c/while_continue_break.c"]
test test_examples_write_c ... ok

test result: ok. 1 passed; 0 failed; 0 ignored; 0 measured; 11 filtered out; finished in 5.07s

Set seed as 22
Building KECC..
    Finished release [optimized] target(s) in 0.16s
Fuzzing with 80 test cases.
Test case #0 (skipped: 0)
Test case #1 (skipped: 0)
Test case #2 (skipped: 0)
...
Test case #78 (skipped: 0)
Test case #79 (skipped: 0)
Test case #80 (skipped: 0)
root@057fe9a7eaea:/home/kecc#
```

**Comment by m-spitfire** [comment]
Yes, it means you passed the grading script. The reason why it didn't print anything was because the [test function](https://github.com/kaist-cp/kecc-public/blob/6401efb435a01b2447a74835a01c92b553870814/src/tests.rs#L76) doesn't actually print anything on the screen, instead it just creates a temp file and writes to it, then parses the written file. Professor also said in the class that if it passes the grading script, you will get the full credits as there are no private test cases.

**Comment by sklationd** [comment]
> Yes, it means you passed the grading script. The reason why it didn't print anything was because the [test function](https://github.com/kaist-cp/kecc-public/blob/6401efb435a01b2447a74835a01c92b553870814/src/tests.rs#L76) doesn't actually print anything on the screen, instead it just creates a temp file and writes to it, then parses the written file. Professor also said in the class that if it passes the grading script, you will get the full credits as there are no private test cases.

I see. Thank you @m-spitfire !

**Comment by jirheee** [comment]
Thank you @m-spitfire! FYI, passing submission in gg means you will get full credits.

**Comment by sklationd** [comment]
@jirheee Thank you!
