### ISSUE TITLE
[HW1] gg submission fails with utf-8 error message

### ISSUE THREAD

**Issue by healwon** [kaist-cp/cs420#465]
Hello,

I finished hw1 and now trying to submit, but there is some trouble I cannot guess the cause.

In server, I passed the grading script `kecc-public/scripts/grade-write-c.sh` including fuzzing, and I download submission file(`irgen.zip` for hw1) made by running `kecc-public/scripts/make-submission.sh`.

However, it fails with the log:
```
===== SETUP =====

===== CHECK =====
[2023-03-09 08:15:31,163: WARNING/ForkPoolWorker-32] Demoting to runner...
info: downloading installer
info: profile set to 'default'
info: default host triple is x86_64-unknown-linux-gnu
warning: Updating existing toolchain, profile choice will be ignored
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: default toolchain set to 'stable-x86_64-unknown-linux-gnu'

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.67.1 (d5a82bbd2 2023-02-07)


Rust is installed now. Great!

To get started you may need to restart your current shell.
This would reload your PATH environment variable to include
Cargo's bin directory ($HOME/.cargo/bin).

To configure your current shell, run:
source "$HOME/.cargo/env"
Cloning into 'kecc-public'...
error: couldn't read /app/files/checks/08bf8958-dce7-47e1-a5bf-e2db21b61047/kecc-public/src/c/write_c.rs: stream did not contain valid UTF-8
 --> /app/files/checks/08bf8958-dce7-47e1-a5bf-e2db21b61047/kecc-public/src/c/mod.rs:3:1
  |
3 | mod write_c;
  | ^^^^^^^^^^^^

Error writing files: failed to resolve mod `write_c`: cannot parse /app/files/checks/08bf8958-dce7-47e1-a5bf-e2db21b61047/kecc-public/src/c/write_c.rs

```

So I checked if it is written in a valid format referring to this post,
(https://stackoverflow.com/questions/115210/how-to-check-whether-a-file-is-valid-utf-8)

Even though I checked, the same problem occurs. Is Anyone having the same problem?

Always thanks for the great lecture.

**Comment by kingdoctor123** [comment]
I had the same problem, and I solved it by submitting `write_c.rs` file only. Can you try this?

**Comment by healwon** [comment]
OMG It works.. I stucked in a strange place actually.

Thanks for sharing your experience.

**Comment by m-spitfire** [comment]
FYI: `irgen.zip` is for Homework 2 - IR Generation.
