### ISSUE TITLE
[HW2] behavior of sizeof expression on negate operator

### ISSUE THREAD

**Issue by sklationd** [kaist-cp/cs420#468]
This is my `custom.c`.
```c
int main()
{
    int a = 3;
    int b = sizeof(!a);
    return b;
}
```

This is my IR for this source.
```ir
fun i32 @main () {
init:
  bid: b0
  allocations: 
    %l0:i32:a
    %l1:i32:b

block b0:
  %b0:i0:unit = store 3:i32 %l0:i32*
  %b0:i1:i32 = typecast 1:u64 to i32
  %b0:i2:unit = store %b0:i1:i32 %l1:i32*
  %b0:i3:i32 = load %l1:i32*
  ret %b0:i3:i32

block b1:
  ret 0:i32
}
```

And this is IR of model solution from gg.
```ir
fun i32 @main () {
init:
  bid: b0
  allocations: 
    %l0:i32:a
    %l1:i32:b

block b0:
  %b0:i0:unit = store 3:i32 %l0:i32*
  %b0:i1:i32 = typecast 1:u64 to i32
  %b0:i2:unit = store %b0:i1:i32 %l1:i32*
  %b0:i3:i32 = load %l1:i32*
  ret %b0:i3:i32

block b1:
  ret 0:i32
}
```

I believe that these IRs are identical. However, when I run the grader script, It fails with the following message:
```
...
[testing "examples/c/custom.c"]
testing "examples/c/custom.c"
clang (expected): 4, kecc: 1
thread 'test_examples_irgen_small' panicked at 'assertion failed: `(left == right)`
  left: `4`,
 right: `1`', src/tests.rs:190:5
...
```

I suspected that this is because, according to C11 §6.5.3.3/5:
> The result of the logical negation operator ! is 0 if the value of its operand compares unequal to 0, 1 if the value of its operand compares equal to 0. The result has type int. The expression !E is equivalent to (0==E).

Therefore, I adjusted the behavior of the `sizeof` operator in accordance with the C11 document, and it seems to be working for now.

My question is, is the model solution incorrect in this case, or did I overlook something?

**Comment by jirheee** [comment]
Also, for the `sizeof` operator, I think [this issue](https://github.com/kaist-cp/cs420/issues/353) would help.

**Comment by sklationd** [comment]
Thank you! I will keep this issue open until it is resolved.

**Comment by jirheee** [comment]
The reference binary has been updated! Thank you for asking valuable question 😄

**Comment by sklationd** [comment]
I think there are similar problems with compare operator `Equals`, `NotEquals`, `Less`, `LessOrEqual`, `Greater`, `GreaterOrEqual`.

In C11 §6.5.8.6:
>Each of the operators < (less than), > (greater than), <= (less than or equal to), and >= (greater than or equal to) shall yield 1 if the specified relation is true and 0 if it is false.107) The result has type int.

In C11 §6.5.9.3:
>The == (equal to) and != (not equal to) operators are analogous to the relational operators except for their lower precedence.108) Each of the operators yields 1 if the specified relation is true and 0 if it is false. The result has type int. For any pair of operands, exactly one of the relations is true.

Below is my testcase for this problem.
```c
int main()
{
    int a = sizeof(1 == 2);
    int b = sizeof(1 < 2);
    int c = sizeof(1 > 2);
    int d = sizeof(1 <= 2);
    int e = sizeof(1 >= 2);
    int f = sizeof(1 != 2);
    int g = sizeof(!1);

    return a == 4 && b == 4 && c == 4 && d == 4 && e == 4 && f == 4 && g == 4;
}
```

__And I think `interp.rs` has a problem related to this issue.__
The [implementation](https://github.com/kaist-cp/kecc-public/blob/a02a928bf94af90ba934f00533daa0a7925019eb/src/ir/interp.rs#L483) of `Equals` operator returns unsigned integer with width `1`. I believe it should return a signed integer with width `4`. And `NotEquals`, `Less`, `LessOrEqual`, `Greater`, `GreaterOrEqual`, `Negate` have same problem.

[This](https://pastebin.com/5fURx6Ge) is my temporary modification for `interp.rs`.

Please let me know if I missed something.
