### ISSUE TITLE
The cmp.c test case seems not to be able to be passed

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#47]
Hi.

In the latest change, `cmp.c` has been added to the test cases. It requires a comparison between signed integers. However, the current version of the IR interpreter does not support comparisons between signed integers. Therefore, it seems that `cmp.c` cannot be passed even though one implements IRgen correctly. I believe that it is not a big problem since there are some TODO parts in the interpreter and they will be implemented soon. However, I think it would be nice to share the issue so that one can avoid spending one's time to fix correct code.

If I am missing something, please let me know.

Thank you.

**Comment by cmpark0126** [comment]
Thank you for your sharing! As you expected, that part will be fixed soon :)

**Comment by cmpark0126** [comment]
We updated the skeleton in this commit: https://github.com/kaist-cp/kecc-public/commit/72ec63ea82509b3e15ee023def875efb65b0b11c
