### ISSUE TITLE
[Announcement] Homework submissions nullified due to additional testcase

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#470]
We have added a [new testcase](https://github.com/kaist-cp/kecc-public/blob/main/examples/c/sizeof4.c) to check behavior related to negation operator. You will have to pass the new testcase to pass the assignment.

Please pull the upstream repository to update the test suite, and submit your assignments again since all previous assignments has been nullified.

Sorry for the inconvenience.

**Comment by AnHaechan** [comment]
Additionally, homework 6 has been nullified at March 18, 3:10 am (KST). 
Those who have already submitted homework 6 to gg should submit it again.
Thank you.
