### ISSUE TITLE
[HW2] Should I manage the order of Post-Increment/Decrement?

### ISSUE THREAD

**Issue by YoonseokJeong** [kaist-cp/cs420#472]
Originally, Pre-increment/decrement should increment/decrement the value of the variable before its use, 

while Post ones change the value after the use of the variables.

But in my opinion, managing the order of the operations for Post ones is quite a hard work since unary operations are located 

at the leaves of C AST, so it always translated earlier than the wrapper nodes when we use recursion.

Is it indeed a demanding task which I have to dig into or am I missing some easy way?

Or hopefully, don't we have to consider the order?

**Comment by AnHaechan** [comment]
You have to consider the order of operation, but the difficulty of translating pre-increment/decrement and post-increment/decrement will not differ.

I recommend you to try the [model solution of IRgen in gg](https://gg.kaist.ac.kr/assignment/100/) and translate the following C program into KECC IR.
```
int main() {
    int a = 1;
    int b = a++;
    int c = ++a;
}
```

In general, if you're not sure with the semantics of IRgen, creating a minimal example program and translating with the model solution will help a lot.
