### ISSUE TITLE
[HW2] Interpretation of =, !=, <, >, <=, >=, ! is seemed wrong

### ISSUE THREAD

**Issue by sklationd** [kaist-cp/cs420#473]
I cannot reopen the issue, so I make a new one.
Please refer to this [issue](https://github.com/kaist-cp/cs420/issues/468)

<del>I think there are similar problems with compare operator `Equals`, `NotEquals`, `Less`, `LessOrEqual`, `Greater`, `GreaterOrEqual`.</del>(Edited: I think it is already handled in reference solution, but there is still a problem about `interp.rs`.)
<details>
<summary>Edited</summary>
In C11 §6.5.8.6:
>Each of the operators < (less than), > (greater than), <= (less than or equal to), and >= (greater than or equal to) shall yield 1 if the specified relation is true and 0 if it is false.107) The result has type int.

In C11 §6.5.9.3:
>The == (equal to) and != (not equal to) operators are analogous to the relational operators except for their lower precedence.108) Each of the operators yields 1 if the specified relation is true and 0 if it is false. The result has type int. For any pair of operands, exactly one of the relations is true.

Below is my testcase for this problem.
```c
int main()
{
    int a = sizeof(1 == 2);
    int b = sizeof(1 < 2);
    int c = sizeof(1 > 2);
    int d = sizeof(1 <= 2);
    int e = sizeof(1 >= 2);
    int f = sizeof(1 != 2);
    int g = sizeof(!1);

    return a == 4 && b == 4 && c == 4 && d == 4 && e == 4 && f == 4 && g == 4;
}
```
</details>

__And I think `interp.rs` has a problem related to this issue.__
The [implementation](https://github.com/kaist-cp/kecc-public/blob/a02a928bf94af90ba934f00533daa0a7925019eb/src/ir/interp.rs#L483) of `Equals` operator returns unsigned integer with width `1`. I believe it should return a signed integer with width `4`. And `NotEquals`, `Less`, `LessOrEqual`, `Greater`, `GreaterOrEqual`, `Negate` have same problem.

Please let me know if I missed something.

_Originally posted by @sklationd in https://github.com/kaist-cp/cs420/issues/468#issuecomment-1475162185_

**Comment by sklationd** [comment]
@jirheee I'm sorry, there is no label on this issue. I think it is because I created this issue from other issue instead of creating directly.

**Comment by sklationd** [comment]
I think above explanation about `interp.rs` problem quite ambiguous. I add an example.

This is my `custom.c`
```c
int main()
{
    if (!(1 == 2))
    {
        return 1;
    }
}
```

And this is my IR for `custom.c`
```ir

fun i32 @main () {
init:
  bid: b0
  allocations: 


block b0:
  %b0:i0:u1 = cmp eq 1:i32 2:i32
  %b0:i1:i32 = typecast %b0:i0:u1 to i32
  %b0:i2:i32 = typecast 0:u1 to i32
  %b0:i3:u1 = cmp ne %b0:i2:i32 %b0:i1:i32
  %b0:i4:i32 = negate %b0:i3:u1
  %b0:i5:u1 = cmp ne 0:i32 %b0:i4:i32.  <----- panicked part
  br %b0:i5:u1, b1(), b2()

block b1:
  ret 1:i32

block b2:
  j b3()

block b3:
  ret 0:i32

block b4:
  j b3()
}
```

But when I interpret this ir, an error occurs.
```
thread 'test_examples_irgen_small' panicked at 'assertion failed: `(left == right)`
  left: `32`,
 right: `1`', src/ir/interp.rs:628:17
```
Even it compare two `i32` type operand.

"I think it's because the interpretation of `%b0:i4:i32` returns a `u1` type integer due to the [implementation](https://github.com/kaist-cp/kecc-public/blob/a02a928bf94af90ba934f00533daa0a7925019eb/src/ir/interp.rs#L700) of the negate interpretation, which returns a `u1` integer.

**Comment by AnHaechan** [comment]
Summary: You should fix your IRgen implementation!

Your IRgen implementation generates an invalid program given `custom.c`.
Please look at  the below annotated IR.
```
fun i32 @main () {
init:
  bid: b0
  allocations: 


block b0:
  %b0:i0:u1 = cmp eq 1:i32 2:i32
  %b0:i1:i32 = typecast %b0:i0:u1 to i32
  %b0:i2:i32 = typecast 0:u1 to i32
  %b0:i3:u1 = cmp ne %b0:i2:i32 %b0:i1:i32
  %b0:i4:i32 = negate %b0:i3:u1 <--- Invalid instruction
  %b0:i5:u1 = cmp ne 0:i32 %b0:i4:i32. 
  br %b0:i5:u1, b1(), b2()

block b1:
  ret 1:i32

block b2:
  j b3()

block b3:
  ret 0:i32

block b4:
  j b3()
}
```
Here, an invalid instruction `%b0:i4:i32 = negate %b0:i3:u1` has been generated, making `interp.rs` to panic.

FYI, the model solution generates the following IR given `custom.c`.
```
fun i32 @main () {
init:
  bid: b0
  allocations: 


block b0:
  %b0:i0:u1 = cmp eq 1:i32 2:i32
  %b0:i1:u1 = negate %b0:i0:u1
  br %b0:i1:u1, b1(), b2()

block b1:
  ret 1:i32

block b2:
  j b3()

block b3:
  ret 0:i32

block b4:
  j b3()
}
```

**Comment by sklationd** [comment]
But I believe that the return type of negate operator should be 'i32 according to linked issue.
Then, is it okay to store 'i32' value to 'u1' without typecasting?

**Comment by AnHaechan** [comment]
I'll discuss this issue with @jirheee and inform you the conclusion.

**Comment by AnHaechan** [comment]
**It is correct that the `negate` operator returns a value of type `u1`.** 
**The same goes for any other comparison operators.**

This is because in KECC IR, we use `u1` (i.e. "boolean") type for the ease of manipulation.
Then you might ask "doesn't it conflict with the C11 specification?".

Short answer is: It does not matter only if we take care of `sizeof`.
For most of cases, whether the result of comparison is 4-byte integer or 1-byte integer does not matter; Knowing whether 0(false) or 1(true) is enough.
The only case where 4-byte vs. 1-byte matters is `sizeof` expression and your IRgen should do special treatment here.

Going back to original question, comparison operator may just return `u1` in KECC IR, without tedious typecasting between `i32` and `u1`.

For more details, please refer to this #384 .

**Comment by sklationd** [comment]
Oh, I'm sorry.
I couldn't found the related issues since I tried with keywords `sizeof`, `negate`, and `interp.rs`.
Thank you for your precise explanation!
