### ISSUE TITLE
[Misc] We don't have lecture for this week, right?

### ISSUE THREAD

**Issue by sklationd** [kaist-cp/cs420#474]
I'm not sure about the announcement in last lecture.
Do we have lecture this week?

**Comment by jeehoonkang** [comment]
Yes lecture this week

**Comment by sklationd** [comment]
Thank you for your quick response!

**Comment by sklationd** [comment]
I'm sorry, but you mean we don't have lectures this week right? just for sure.

**Comment by jeehoonkang** [comment]
ah... we will **have** lectures this week.

**Comment by sklationd** [comment]
I see. Thank you.
Sorry about the confusion.
