### ISSUE TITLE
[Final Project] Performance Competition (due: 6/19)

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs420#475]
Performance Competition.

- **instruction**
  + https://docs.google.com/presentation/d/1SqtU-Cn60Sd1jkbO0OSsRYKPMIkul0eZoYG9KpMugFE/edit#slide=id.g8085bd6ec8_44_0
  + Since your solution will be linked with some [driver](https://github.com/kaist-cp/kecc-public/blob/main/bench/driver.cpp), you need to follow the [LP64D ABI](https://github.com/riscv-non-isa/riscv-elf-psabi-doc/blob/44f98e0fd8104def00f2a5a8d94b23dd647d18fb/riscv-elf.md#named-abis), which is the default ABI of RV64G ISA.
    + RVG Calling Convention: 18.2 of https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf
    + Godbolt's reference solution to [`exotic_arguments.c`](https://github.com/kaist-cp/kecc-public/blob/main/bench/exotic_arguments.c): https://godbolt.org/z/bzn6v7Pf8
  + Use `la` pseudo instruction instead of `HI20` and `LO12` pair: https://github.com/kaist-cp/cs420/issues/168#issuecomment-653044107
  + Check that your code does not have [unaligned memory access](https://github.com/westerndigitalcorporation/RISC-V-Linux/blob/master/linux/Documentation/unaligned-memory-access.txt).
  + The stack pointer should always be kept 16-byte aligned. (p3 of https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf) 
  + Also refer to #467 and the [model solution](https://gg.kaist.ac.kr/assignment/101/).
- **self grader**: https://github.com/kaist-cp/kecc-public#run-benchmark-for-performance-competition
  + It will build your compiler, build benchmark codes, run them, and measure the elapsed CPU cycles. The average is your score (lower is better).
- **submission**: run `./scripts/make-submissions.sh` and then submit `final.zip`.
  + There is 10 minute timeout for each submission.
  + https://gg.kaist.ac.kr/assignment/99/
- **leaderboard**
  + [Leaderboard](https://docs.google.com/spreadsheets/d/1L5RzJcddB-vsiJFc9yF2PqXumnfaX8lMpU10zbmun_Y/edit?usp=sharing)
  + The next score on the leaderboard will be updated to `min(# of cycle on the leaderboard, # of cycle of the last success submission on gg)`.
- **due**: 6/19 23:59:59 (KST = UTC+9)

**Comment by CuriousLocky** [comment]
Is the online test code same as the self grader?

**Comment by Lee-Janggun** [comment]
@CuriousLocky it is the same, but the online grader runs the code on actual RISC-V hardware, while the provided development machines run on QEMU. This may lead to some bugs not found on QEMU, so please read the instructions above carefully.

**Comment by CuriousLocky** [comment]
@Lee-Janggun On the slide it says `If any of the results are wrong, you’ll be disqualified`. Does it mean the score for that specific round is disqualified or there no second chance of fixing it?

**Comment by Lee-Janggun** [comment]
@CuriousLocky Ah, it means that the results for **that specific submission** is disqualified. You are free to re-submit and try again.

**Comment by CuriousLocky** [comment]
I just submitted my code to gg, and it shows as successful. But I cannot see my score on the leaderboard so far. Is there anything I should do other than simply uploading `final.zip`?

**Comment by AnHaechan** [comment]
@CuriousLocky It is now updated. Our automatic leaderboard updater is having some issues :lady_beetle:. If same issue recurrs, please contact us!

**Comment by CuriousLocky** [comment]
@AnHaechan It looks like it's having the same issue again.

**Comment by AnHaechan** [comment]
@CuriousLocky We'll fix the leaderboard tomorrow. Sorry for inconvenience.
Even if the leaderboard is not updated, your submission and performance in gg will be used for grading.

**Comment by jirheee** [comment]
We have just fixed the crawler! Also, we added a field **Updated at** in 
the sheet so that you can see when was the last update.

**Comment by jlee335** [comment]
@jirheee @AnHaechan I think I'm facing the same issue. I also submitted my HW8 code last night with a success, but cannot see my results on the leaderboard.

**Comment by AnHaechan** [comment]
@jlee335 Sorry for inconvenience. We'll fix the updater soon. Even if your score is not updated on the leaderboard, your submissions in gg will be used for graidng, so don't worry..

**Comment by travis1829** [comment]
It seems like the RISC V machine isn't running... probably because it's almost the deadline and a lot of people are submitting.

@jirheee I'm sorry but could you please take a look?

**Comment by jirheee** [comment]
Yeah I think it is due to too much workload on the server. Since we have only 3 minutes left, I don't think fixing it right now is not possible. But all of your submissions until 11:59 will be graded and the highest among your submissions will be your final score.

**Comment by CuriousLocky** [comment]
@jirheee It's a minor problem but I also want to point out that the leaderboard does not seem to show my highest submission score. It's just 1% difference and does not affect the ranking though.

**Comment by jirheee** [comment]
@CuriousLocky Oh that is weird.. I will look through the submissions considering that too 🫠

**Comment by CuriousLocky** [comment]
@jirheee FYI, the submission ID is 21543
