### ISSUE TITLE
(March 28th) Video Lecture

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs420#476]
On **March 28th (Tue)**, the professor will not be able to teach the session in-person.
Instead, you're going to watch the following videos:
* on the nature of pointers and alias analysis: https://www.youtube.com/watch?v=r0XVS4Atl3U
* on dependence analysis and MemorySSA: https://www.youtube.com/watch?v=1e5y6WDbXCQ

We will not have a quiz for this day, too.

**Comment by m-spitfire** [comment]
Professor mentioned last week in the lecture that we'll need to come to the classroom in both lecture days this week. I'm assuming it's not necessary for tomorrow's lecture?

**Comment by AnHaechan** [comment]
@m-spitfire Yes, you don't need to come.

**Comment by kingdoctor123** [comment]
Are these videos included in the scope of midterm exam?

**Comment by AnHaechan** [comment]
@kingdoctor123 Yes, it will be included.

**Comment by jeehoonkang** [comment]
I'll close this issue after the midterm exam.
