### ISSUE TITLE
[HW2] Should I support list initializer?

### ISSUE THREAD

**Issue by YoonseokJeong** [kaist-cp/cs420#477]
I'm confused whether I should support list initializer(initializer in the form of '{a, b, c}' ) in my 'irgen', since it is successfully interpreted via model solution of IR generator at gg.kaist, while the  model solution of youtube lecture(18:00 at https://www.youtube.com/watch?v=jFahkyxm994) indicates that list initializer is not supported.

**Comment by sklationd** [comment]
I think so. While I have completed hw2, it does not meet the passing all of the grade scripts without the support for list initializer. For instance, in struct2.c, a list initializer is needed for a struct field.

```c
typedef struct {
  char a;
  struct {
    int b[4];
  };
  long c;
} Temp;

int main() {
    const Temp temp = {1, {{2, 3, 4, 5}}, 6};
    
    Temp temp2;
    temp2 = temp;

    int sum = temp2.a + temp2.b[2] + temp2.c;
    
    return sum == 11;
}

```

**Comment by jirheee** [comment]
You should pass all given test cases including struct2.c, which contains list initializer.
