### ISSUE TITLE
[HW1 QUESTION] File Error in file parse.rs for Statement-Labeled

### ISSUE THREAD

**Issue by Moa1er** [kaist-cp/cs420#478]
Hello,
After reading the file [parse.rs](http://parse.rs/) to determine what needeed to be implemented or not I have observed something that I think is an error : for the class "Statement" the file [parse.rs](http://parse.rs/) tells us to not implement the case "Labeled" (see photo below).
![image](https://user-images.githubusercontent.com/44988543/227760349-bafb80ef-1a33-44c4-bafb-7922cf90b9f7.png)
But in the test files for the [write_c.rs](http://write_c.rs/) there are multiple switch case which uses this "Labeled" case. So I believe that we do have to implement the case "Labeled" for the class Statement and that this is an error in the [parse.rs](http://parse.rs/) file.
Maybe I didn't understand something properly or have made an error somewhere ?

**Comment by jirheee** [comment]
The kind of labeled statement we do not support in `kecc` is labeled statement which are not in switch statement like below(which is particularly used together with `goto`, which is also unsupported feature of `kecc`).

```c
// goto.c
#include <stdio.h>

int main()
{
    int i, j;

    for ( i = 0; i < 10; i++ )
    {
        printf_s( "Outer loop executing. i = %d\n", i );
        for ( j = 0; j < 3; j++ )
        {
            printf_s( " Inner loop executing. j = %d\n", j );
            if ( i == 5 )
                goto stop;
        }
    }

    /* This message does not print: */
    printf_s( "Loop exited. i = %d\n", i );

    stop: printf_s( "Jumped to stop. i = %d\n", i );
}
```

So it is not a bug, and you can just implement the test cases.

**Comment by Moa1er** [comment]
Thank you for the answer ! But when I don't implement this part the code panics since it enters the "Labeled" case for the Statement class so I don't know what to do. It may be that my program has a problem but I asked some students that already submitted the assignement and they told me I had to implement this "Labeled" case otherwise it doesn't work. The test file that makes the code enter this "Labeled" case is examples/c/switch.c

**Comment by jirheee** [comment]
I meant that you "should" implement the `Labeled` case for supported cases of `kecc`. So as you said, `examples/c/switch.c` contains labeled statements in switch case syntax and you should translate them into kecc ir.

In short,
1. Labeled statement can be used in multiple contexts: (1) jump destination with `goto` (2) switch statement.
2. For (1), you don't have to care since `kecc` ir does not support them.
3. For (2), you should implement.

Do you think this makes things clear? Feel free to ask more questions if you have any confusion 😄

**Comment by Moa1er** [comment]
I understand better thank you ! So we shoudn't rely on the file parse.rs to know what we have to implement in the write_c.rs if I understand correctly the implications of what you just said ?

**Comment by m-spitfire** [comment]
@Moa1er If you look at https://github.com/kaist-cp/kecc-public/blob/main/src/c/parse.rs#L405 you can see that the `Labeled` statement inside switch case is actually supported, it shouldn't panic.

**Comment by jirheee** [comment]
As @m-spitfire told, those two are treated differently in parse.rs.

**Comment by Moa1er** [comment]
Perfect thank you very much !
