### ISSUE TITLE
(March 30th) Q&A session by TAs

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#479]
Dear students of CS420,

I hope you all are doing well and enjoying the course so far. I would like to remind you that we will be having a Q&A session next week to help you follow up with the class.

To make the most of this session, I kindly request you to **send in your questions before the class through the Google Form link** provided below. This will enable us to prioritize and organize the questions for the session and make sure that we cover as many topics as possible.

Google Form link: https://forms.gle/saQEwtqjs8MCD9WT8

Please keep in mind that this is an excellent opportunity for you to clarify any doubts or confusion you may have about the course material, so please do not hesitate to send in your questions.

Thank you, and I look forward to seeing you all at the Q&A session.

Best regards,

Jung In Rhee & Haechan An - TAs of CS420

**Comment by AnHaechan** [comment]
FYI, we'll have no quiz for this lecture.
