### ISSUE TITLE
Question about: impl TryFrom<Dtype> for Declaration 

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#48]
Hello!
Im trying to understand the try_from function defined for the Declaration (i.e. row 34 in src/ir//mod.rs). 

In the documentation comments above the function definition, it says that it can return a Declaration::Variable with "Some(...)" as initializer. But in the code, it seems as it sets the initializer to "None" for all cases. 
Is there something deeper happening in the code that will make the initializer of the Declaration::Variable into a "Some(...)-instance" or will it always be returned with None as initializer?

Thankful for any input!

Best regards
Jesper

**Comment by cmpark0126** [comment]
Sorry for the late answer. `TryFrom<Dtype> for Declaration` just create new `Declaration` instance corresponding to `Dtype`. However, `Dtype` has no `initializer` information, we cannot derive `Some` instance for `initializer` here. Actually, finding `initializer` is part of the homework. If you analyze `ast` well, you could get a hint on how to initialize `Declaration`. Good luck :)
