### ISSUE TITLE
[Question] [HW2] Why integer promotion in IRgen acts like this?

### ISSUE THREAD

**Issue by Meraroo** [kaist-cp/cs420#481]
```
void a() {
    short x = 10;
    ~x;
}
```
Model solution converts this simple code above into
```
fun unit @a () {
init:
  bid: b0
  allocations: 
    %l0:i16:x

block b0:
  %b0:i0:i16 = typecast 10:i32 to i16
  %b0:i1:unit = store %b0:i0:i16 %l0:i16*
  %b0:i2:i16 = load %l0:i16*
  %b0:i3:i32 = typecast %b0:i2:i16 to i32
  %b0:i4:i32 = typecast -1:i16 to i32
  %b0:i5:i32 = xor %b0:i3:i32 %b0:i4:i32
  ret unit:unit
}
```
this.

The workflow seems like
`translate x` -> `generate -1 with datatype of x` -> `integer promotion` -> `typecast x` -> `typecast -1`

Then why don't we do
`translate x` -> `integer promotion` -> `typecast x` -> `generate -1 with datatype of x` 
?

```
fun unit @a () {
init:
  bid: b0
  allocations: 
    %l0:i16:x

block b0:
  %b0:i0:i16 = typecast 10:i32 to i16
  %b0:i1:unit = store %b0:i0:i16 %l0:i16*
  %b0:i2:i16 = load %l0:i16*
  %b0:i3:i32 = typecast %b0:i2:i16 to i32
  %b0:i4:i32 = xor %b0:i3:i32 -1:i32
  ret unit:unit
}

```
I think these two are same. Do we have any optimization technique for this?

**Comment by sklationd** [comment]
I think the model solution may have translated it in a verbose way to explicitly indicate integer promotion.

Such as, If we consider below code.

```c
void a() {
    long x = 10;
    ~x;
}
```

The generated IR by model solution is.

```
fun unit @a () {
init:
  bid: b0
  allocations: 
    %l0:i64:x

block b0:
  %b0:i0:i64 = typecast 10:i32 to i64
  %b0:i1:unit = store %b0:i0:i64 %l0:i64*
  %b0:i2:i64 = load %l0:i64*
  %b0:i3:i64 = xor %b0:i2:i64 -1:i64
  ret unit:unit
}
```

There is no integer promotion part, since we don't need it.

And optimization for this verbose translation.. I'm not sure but maybe constant propagation and GVN?
