### ISSUE TITLE
[Question] New domtree construction method actually converges

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs420#484]
In previous class, we proved correctness of a new domtree construction method proposed by some student.

$$\forall X \neq I, idom(X) = \bigcap_{Y \in pred(X)} Y$$

($I$ : initial block, $\cap$ symbol means meet operation in slide)

Professor mentioned that we don't use it because it does not converge, and we use the one in the slide instead. But I think this new version indeed converges. Furthermore, the algorithm shown in lecture video seems to implement this approach.

Brief proof: 
We know domtree uniquely exists and is actually a tree. So, we can guarantee
* once idom of a node is set correctly, it will not be updated further.
* in iteration 1, every node in level 2 of domtree has correct idom. (level 1 of tree : root node, level 2 : nodes right under the root)
* in iteration 2, every node in level 3 of domtree has correct idom.
* ...

This reasoning terminates in finite time since we have finite number of nodes in domtree and it is independent of the exact order we traverse the node during the update. □

In the end, I couldn't get what the professor meant by saying "we use the fixed method introduced in the slide because this algorithm does not converge". Can you clarify about this? 

Thank you in advance.

**Comment by AnHaechan** [comment]
I'll answer this until tomorrow. Sorry for late response.

**Comment by prime235711** [comment]
Is this issue resolved in the office hour or anywhere?
I'm also confused with this problem.

**Comment by kingdoctor123** [comment]
@prime235711 unfortunately not resolved yet..

**Comment by jeehoonkang** [comment]
Sorry for the late response and all the confusion I've made. I'd like to clarify about the convergence here.

To avoid any confusion, **I will not ask questions about convergence in the midterm.**

The algorithm seems to be converging. But to see why, I need to develop the theory a little bit more...

First, let's distinguish the following:
- the hypothetical "top" element that represents the computation has not begun; and
- the hypothetical "undef" element that represents the entry point of the CFG.

Then in the iteration algorithm, we can define idom0 as follows:
- idom0(init) = bottom
- idom0(b) = undef for all b != init

Second, we inductively define the (transitive) order for the given idom as follows:
- if a = idom(b), then a < b.
- if bottom <= b, then b < under.

The order is carefully defined to ensure convergence for the following reasons:
- once idom(b) becomes non-undef, then it will not become undef again in the following iterations.
- if idom(b) is non-undef, then "height" from "bottom" is strictly decreasing for each iteration.
