### ISSUE TITLE
Midterm exam on April 18th (Tue), 13:00-15:00 in the lecture room (E3 1101)

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#485]
Dear students,

Please read carefully for the exam.

### Date and Place

We will conduct the **midterm exam on April 18th (Tue), 13:00-15:00 in the lecture room (E3 1101).**

### Range

* Everything you've learned before the midterm (lecture, slides, assignments, video lectures, etc)
* All the discussions we had during the lecture and GitHub issues

### Presence

* You must be **physically present** in the lecture room.
* You must not take a break for restrooms or other reasons.
* You may leave 30 minutes after the beginning.

### Supplies

* You should bring **your own laptop** to take the exam.
* If you don't any, please borrow one from the CS admin office by sending an email to [Mr. Gwonhyu Jin](https://cs.kaist.ac.kr/people/view?idx=594&kind=staff&menu=25) with me cc'ed.
* You should have **a valid Google account** because the problem/answer sheet will be given as a Google Form.
* You should bring your **student ID card.** If you don't have any, bring a government-issued ID card.
* You may use pencil and paper, but you must not use calculators, tablets, and text editors.

### Screen Policy

On the laptop screen, you can only look at the following websites:

* https://gg.kaist.ac.kr/

  * Go to https://gg.kaist.ac.kr/course/15/ and click the exam event.

  * Here, you can see the "event token" (see below).

  * Here, you can also ask questions.
    If your question is not answered for 10 minutes, please let us know.
Your questions can be written either in English or Korean. Answers will be in English.

* The problem/answer sheet as a Google Form

  * It will be announced in gg.

  * To answer the Google Form, you need to (1) log in with a Google account, and (2) fill out your KAIST email address, name, student ID, and the event token.

  * The problems will be in English. You may answer either in English or Korean.

  * Frequently save your answer.
    Google Form does not automatically save your answers unless you "submit" them.
    You are allowed to resubmit the answers as many times as you want, so it is strongly recommended for you to submit your answers frequently.
    It is your responsibility to maintain your answers reliably and we will not make any exceptions due to technical problems such as network disconnections, web browser crashes, web browser hanging, etc.

  * Here's a [practice answer sheet](https://docs.google.com/forms/d/1gdHk2z2vMt5bOWEH7kLzALDLhCBvuG5q9ZjxkCm0jQo/viewform). Please make sure you successfully submitted your solution to the practice sheet **before taking the exam.**

### Practice Session at April 13th (Thu) 13:00-15:00 at E3 1101
* We will hold a practice session for the midterm exam in tomorrow's lecture.
* We will prepare the environment as similar with the midterm environment as possible(google form, gg, etc), so we recommend you to participate the session to avoid  

### Remote Participation Policy

* If you really cannot be physically present in the lecture room, send an email to [jeehoon.kang@kaist.ac.kr](mailto:jeehoon.kang@kaist.ac.kr) to **ask for explicit permission for remote participation.**
  Without such explicit permission, you will be regarded as absent from the exam.

* You should **join two Zoom rooms with two Zoom accounts:** ["Announcement" room](https://kaist.zoom.us/my/jeehoon.kang) and the "CCTV" room (privately emailed).
  If you have only one account, please sign up once again.

* Join the Announcement room with a device (probably desktop/laptop) in which you'll solve the exam problems.
  Turn off the camera and microphone.

* Join the CCTV room with another device (probably a laptop/mobile) that observes you during the exam.
  **For the entirety of the meeting, you need to (1) turn on the camera and microphone; (2) show your hand, paper, keyboard, and monitor; and (3) turn off the speaker.**
  (For privacy concerns: please be noted that you agreed to do this at the beginning of the semester.)
I've attached the model scene from the experienced TA below.

* **You should be properly present in both the Announcement and CCTV rooms 10 minutes before the beginning to the end of the exam.**
  If you disappear from the camera after the exam starts, we will assume that you gave up on the exam and your score will be automatically zero.
  Network disconnections and/or power outages will not be excuses. Make sure you find a place where you can get a reliable internet connection and power supply.

* Your Zoom name should be in the form of "200711632 강지훈". Otherwise, you may be disqualified.

* At the beginning of the exam, you will be asked to show your student card.
  Please show it in front of the CCTV camera.

* Frequently read Announcement Zoom room messages. We'll DM you when your CCTV doesn't work properly.

<img width="880" alt="image" src="https://user-images.githubusercontent.com/65358599/231482691-9569a12d-fbcb-4e79-9371-e1f8f3350083.png">

**Comment by derick321** [comment]
Should I study all the contents of assignments that the professor explained in class? (It's until HW4 for now.)

**Comment by AliAhmed36** [comment]
What's the duration of the exam? I have another exam at 2:30 pm on 18th April.

**Comment by jirheee** [comment]
@derick321 Yes the everything professor explained in class including assignments will be part of the exam.

**Comment by jirheee** [comment]
@AliAhmed36 As far as I know, 13:00-16:00 is reserved for us as exam time. So I think you should check again if 14:30 is the right exam time.(If the class it Tue/Thu 14:30-16:00, I think it's exam time should be between Thu 13:00 and 16:00)

For the end time, we will announce it ASAP.

**Comment by AnHaechan** [comment]
Notice: The exam ends at 15:00.

**Comment by AnHaechan** [comment]
Also, don't forget to test if your laptop's battery is enough.
If your laptop goes off, (obviously) you cannot proceed your exam...

If your laptop's battery is not enough, please connect to the outlet(콘센트) before the exam starts.
We're preparing two 6-outlet power strips(6구 멀티탭), and there are a few power outlets in the exam room.

**Comment by jirheee** [comment]
We have finished grading the exam, and your scores for each part are published at gg.

- min, max: 61, 196
- average, median, 3q: 152.5, 156.5, 175.5

![image](https://user-images.githubusercontent.com/65358599/234736286-08a4697a-1616-4196-a144-83f97b460adc.png)
