### ISSUE TITLE
Previous exam problems are released

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs420#486]
Dear students,

We have decided to release previous exam problems openly.
This is following the general policy of KAIST SoC to prevent selling and buying exam materials.
~~However, please do not share the problems out of KAIST.~~

The problems are in this google form: [2022 spring CS420 final exam](https://forms.gle/shAyUV9F9hAsH3Rw5).
Note: As we only had a final exam without a midterm last year, it will include problems out of this midterm's scope.

Best regards,
TA Haechan An

**Comment by jeehoonkang** [comment]
@AnHaechan the problem sheet is already shared publicly on GitHub :) Let's say everyone can freely share the problem sheet to everyone...

**Comment by AnHaechan** [comment]
#opensource

**Comment by AnHaechan** [comment]
2023 Spring: #530
