### ISSUE TITLE
[Question] Dominance frontier of a set of blocks

### ISSUE THREAD

**Issue by leejy12** [kaist-cp/cs420#487]
Hi, I'm studying about CFGs and I have a question about dominance frontier.

![image](https://user-images.githubusercontent.com/60320918/231814667-34f07b0d-090b-4707-8427-0349c1e86ec7.png)

I'm confused about the meaning of "dominance frontier of {A2, B2}". Does it mean the intersection of DF(A2) and DF(B2)?

**Comment by AnHaechan** [comment]
No, it is the union of DF(A2) and DF(B2).

**Comment by leejy12** [comment]
Thank you!
