### ISSUE TITLE
[HW2] Merging type

### ISSUE THREAD

**Issue by YoonseokJeong** [kaist-cp/cs420#488]
I want to know the standard of type merging in KECC IR.

I think the merged type of `u8` and `i8` must be `u8`, but KECC irgen merges them into `i32`.

Below is the problematic part (block 0 of `char_greater_than()` function) after generating IR of `/examples/c/cmp.c`

`exmaples/ir0/cmp.ir` (solution)
```
%b0:i2:i8 = load %l0:i8*
%b0:i3:u8 = load %l1:u8*
%b0:i4:i32 = typecast %b0:i2:i8 to i32
%b0:i5:i32 = typecast %b0:i3:u8 to i32
```

my irgen
```
%b0:i2:i8 = load %l0:i8*
%b0:i3:u8 = load %l1:u8*
%b0:i4:u8 = typecast %b0:i2:i8 to u8
```

The semantics of type merging is quite confusing, and I want to know if there is any concrete document that defines the semantic of type merging.

**Comment by jirheee** [comment]
For implicit type casting including integer promotions, return type casting and etc, your Ir must follow the semantics of C specification(look at https://github.com/kaist-cp/cs420/issues/106). And for type merging(merge_dtype function from the video), it is a helper function for handling such implicit cast, so you can refer to C specification or above issue to implement it correctly.

**Comment by YoonseokJeong** [comment]
Thank you!
