### ISSUE TITLE
[Question] I have a question about the algorithm for finding idom.

### ISSUE THREAD

**Issue by lhi0901** [kaist-cp/cs420#489]
![KakaoTalk_Photo_2023-04-16-21-37-49](https://user-images.githubusercontent.com/101685866/232312457-8f338d9b-4f57-4cfd-9fae-37d5254768c5.png)

How should we calculate idom1 in this diagram? In my opinion, idom1(B), idom1(C), and idom1(D) should be A. But, how can we say that A dominates B, C, and D? because idom0 maps all elements to None.

**Comment by jirheee** [comment]
What is idom0 and idom1?

**Comment by travis1829** [comment]
> What is idom0 and idom1?

I think he is talking about the iterative process of finding the idom.
That is,
* idom0: result after 0 iterations (all initialized as None)
* idom1: result after 1 iteration
* idom2: result after 2 iterations
...
(repeat until idom_(n-1) and idom_n are the same)

> How should we calculate idom1 in this diagram? In my opinion, idom1(B), idom1(C), and idom1(D) should be A. But, how can we say that A dominates B, C, and D? because idom0 maps all elements to None.

In this case, I think you should use the fact that the initial block dominates all other blocks. For example, in the [slides](https://docs.google.com/presentation/d/1SqtU-Cn60Sd1jkbO0OSsRYKPMIkul0eZoYG9KpMugFE/edit#slide=id.g8489bbc41c_7_22) we can see that
* idom(X) = y if ∃ y ∈ pred(X) s.t. forall z ∈ pred(X), y=z or y dominates z

but actually we should do something like
* idom(X) = y if ∃ y ∈ pred(X) s.t. **y is initial block** or forall z ∈ pred(X), y=z or y dominates z

(BTW, this is similar to how its actually done in the videos.)

Then idom(B) = idom(C) = idom(D) = A, maybe just after 1 iteration.

**Comment by jlee335** [comment]
<img width="283" alt="스크린샷 2023-04-16 오후 4 55 07" src="https://user-images.githubusercontent.com/29758894/232404401-2e502c37-5ccc-4642-abfd-1af63b73d9a5.png">
I think this example may be a related question. I am also curious about the behaviour of idom tree building algorithm when one of its predecessors are not traversed yet

Assume 0,5,4,3,2,1 is a valid RPO order. Despite RPO order, the existance of loops cause some of the predecessors to not be traversed.

0th iter (aka idom0)
0 -> None
5 -> None
4 -> None
3 -> None 
2 -> None
1 -> none

1th iter
0 -> Root
5 -> 0 
4 -> meet of {5} = 5
3 -> meet of {5} = 5
**2 -> Meet of {1,3} ->  {3} = 3 ** **Assume I ignore 1**, 3 is incorrect but dominated by answer Idom.**
> Like the initial question, 1 is not traversed, so Idom(1) is set to None

1 -> Meet of {4,2} = 5

2nd iter (converges from here)
0 -> Root
5 -> 0
4 -> 5
3 -> 5
2 -> Meet of {1,3} =  5 ** Converged to proper idom node
1 -> 5

**Comment by travis1829** [comment]
I think your method is right at least according to the method presented in the video.

i.e. During each iteration, when evaluating idom(X), evaluate the meet of Y∈pred(X) s.t. idom(Y) is not None. (That is, we just ignore predecessor nodes whose idom is None)

**Comment by jeehoonkang** [comment]
I believe this comment is useful for this discussion: https://github.com/kaist-cp/cs420/issues/484#issuecomment-1511160954

If you have remaining questions, please feel free to ask follow-up questions.
