### ISSUE TITLE
[Question] Question about Dominance Frontier in slide 73

### ISSUE THREAD

**Issue by snurf198** [kaist-cp/cs420#491]
I have a question about dominance frontier in slide 73's CFG. Since block B can be jumped from A and E, I was thinking DF({A}) should be {B}. But thinking differently, because A dominates E, DF({A}) is {}. Can I have an answer whether which one is correct? 
<img width="1107" alt="image" src="https://user-images.githubusercontent.com/55132820/232334671-28972a3a-0465-46ba-b98c-682090ffde34.png">

**Comment by jirheee** [comment]
DF({A}) = {}
DF({C}) = {D}
=>
DF({})

DF^2({})
