### ISSUE TITLE
[Question] Does a block dominate itself?

### ISSUE THREAD

**Issue by jlee335** [kaist-cp/cs420#492]
I have a question regarding the definition of dominance.

From slide 68, a dominance relation is defined as:
> A dominates B if all paths from I to B, visits A in-between

**In this case, I am curious whether a block dominates itself by definition. Or simply A ∈ Dom(A)?**

I have provided a phi-node insertion example below. For this to work I found out that for block B, **B ∉ Dom(B)** should hold in order to insert phi-nodes appropriately.

**Sample CFG containing loop**
<img width="252" alt="image" src="https://user-images.githubusercontent.com/29758894/232372692-81c00997-78f5-4dfc-b3cb-875493d7b698.png">

**Definition of Dominace Frontier from slide 71.**
<img width="720" alt="image" src="https://user-images.githubusercontent.com/29758894/232373165-280f16be-2d87-4f0d-95f5-9f37e4a57446.png">

Following the definition above,
* One of B's predecessors is dominated by B (or B itself) ✅ 
* B itself is not dominated by B ❓ 

For the second statement to hold, and phi-node inserted at B, a block should not dominate itself by definition.
And for this example, B should be in the dominance frontier of B.

DF(A) = {}
DF(B) = {B}
DF(C) = {}

**Comment by jirheee** [comment]
> In this case, I am curious whether a block dominates itself by definition. Or simply A ∈ Dom(A)?

For this question, *block does not dominates itself by definition*. Let's look at B for your given example. If $B \in dom(B)$, then B should be **in between** all paths coming into B. But if we look at path $A -> B$, B does not exist between A and B, so B does not dominate B.

**Comment by jlee335** [comment]
Thank you very much!
