### ISSUE TITLE
[Question][Dep. Analysis] Regarding a problem in the past paper

### ISSUE THREAD

**Issue by m-spitfire** [kaist-cp/cs420#495]
Hello. In the past exam questions there was this question asking to change the loop such that its iterations are independent of each other:
```c
// N >= 2
for (int i = 0; i < N; ++i) {
  A[i][N] = A[0][2] + A[N-1][2];
}
```

I wonder what's the dependent part here? I think every iteration of the loop is independent, as it just assigns a constant value(`A[0][2] + A[N-1][2]`) to an entry. It might have been dependent if let's say was `i` was `N` at some point, but `i`'s max value is `N-1`

**Comment by antony-jeong** [comment]
I think the dependency exists if and only if N is exactly 2. If and only if N == 2, there is a WAR dependency on A[1][2].

**Comment by AnHaechan** [comment]
Consider when `i=0` and `i=N-1`.

**Comment by m-spitfire** [comment]
Thanks!
