### ISSUE TITLE
[Question] Type of integer literals in model IR generator

### ISSUE THREAD

**Issue by CuriousLocky** [kaist-cp/cs420#496]
When doing homework 2, I passed the following C program to the model IR generator. 
```
char b = 137;
int main() {
  return b < 9805967853324902922;
}
```
I got the following results. 
```
var i8 @b = 137

fun i32 @main () {
init:
  bid: b0
  allocations: 


block b0:
  %b0:i0:i8 = load @b:i8*
  %b0:i1:u32 = typecast %b0:i0:i8 to u32
  %b0:i2:u1 = cmp lt %b0:i1:u32 9805967853324902922:u32
  %b0:i3:i32 = typecast %b0:i2:u1 to i32
  ret %b0:i3:i32

block b1:
  ret 0:i32
}
```
Note that the integer literal `9805967853324902922` is parsed as u32 type. 

However, as described by C11 standard 6.4.4, the type of an integer literal with no suffix should be the first in `int, long int, long long int` that can be represented.  Is it a bug or intended?

**Comment by CuriousLocky** [comment]
> It is intended. Look at [this](https://github.com/kaist-cp/kecc-public/blob/a02a928bf94af90ba934f00533daa0a7925019eb/src/ir/mod.rs#L648).

I noticed `9805967853324902922` is larger than `UINT_MAX`, meaning it does not fit in a 32-bit value but fits in unsigned 64-bit one. Is the choice of size also intended?

**Comment by AnHaechan** [comment]
About correctness problem after following model solution:
- As long as one's implementation passes grading script, they will get full credit.
