### ISSUE TITLE
[Question] Is it forbidden to use a `continue` statement right within a switch case?

### ISSUE THREAD

**Issue by antony-jeong** [kaist-cp/cs420#497]
Is it forbidden to use a `continue` statement right within a switch case?

- **I've searched about this using search engines** and it says `continue` statement within a switch statement doesn't do anything with the switch statement. However, it `continue`s another iteration of the innermost loop which the `continue` statement is in.
- **[The model IR generator provided in gg](https://gg.kaist.ac.kr/assignment/100/)** rejects `continue` statement within a switch case. For example, putting
  ```
  int main() {
      while (1) {
          switch (1) {
              case 1: {
                  continue;
                  break;
              }
          }
      }
  }
  ```
  results
  ```
  error: continue statement not within a loop
  
  code: continue;
  ```
  .

**Comment by jirheee** [comment]
We have looked at this issue, and it is a bug in reference compiler. Thank you for reporting! But we will not add additional case that checks this case, since the due for irgen is geting very close.
