### ISSUE TITLE
[Question] HW2 about member expression with call expression

### ISSUE THREAD

**Issue by Meraroo** [kaist-cp/cs420#498]
```
int nonce = 1; // For random input

struct Foo
{
    int x;
};

struct Foo f()
{
    struct Foo x;
    x.x = nonce;
    return x;
}

int main()
{
    int t0;
    f().x;
}
```
Sample irgen soultion of the c code above gives this error message : 
```
error: redefinition, `t0`

code: (f)().x
```
I think this is because of temporal allocation of f() whose name is t0.
Is it allowed to get exact name for temporal allocation?

**Comment by jirheee** [comment]
What do you mean by "get exact name of temp allocation"?

**Comment by Meraroo** [comment]
Then I guess such naming is not allowed for our happier campus life!

**Comment by jirheee** [comment]
Yes you won't have to care such cases 😄
