### ISSUE TITLE
Permission Denied Error when I install CodeLLDB Extension in VSCode

### ISSUE THREAD

**Issue by minseongg** [kaist-cp/cs420#5]
When I install CodeLLDB Extenseion in VSCode, Permission Denied Error occured with below OUTPUT

```
Installing platform package from https://github.com/vadimcn/vscode-lldb/releases/download/v1.5.0/codelldb-x86_64-linux.vsix
Error: Error: EACCES: permission denied, open '/tmp/vscode-lldb-full.vsix'
```

![image](https://user-images.githubusercontent.com/37203263/76812451-3aab8d00-6838-11ea-99d5-903dad55370b.png)

May I ask how to solve it?

**Comment by jeehoonkang** [comment]
I just fixed something.  Would you please retry?

**Comment by minseongg** [comment]
Sorry.. same error occured when I uninstalled CodeLLDB Extension and reinstall it.

**Comment by jeehoonkang** [comment]
Sorry, I cannot reproduce the bug...  Please send me and TA an email that contains your student ID so that we can look into your account.

**Comment by jeehoonkang** [comment]
- It seems a well-known strangeness of VSCode...  Here's a workaround.
- Download this file at the server: https://github.com/vadimcn/vscode-lldb/releases/download/v1.5.0/codelldb-x86_64-linux.vsix
- Install it: https://code.visualstudio.com/docs/editor/extension-gallery#_install-from-a-vsix

**Comment by minseongg** [comment]
Thanks! Now Extension installed successfully.

**Comment by Reinose** [comment]
I think the problem is due to the `/tmp/vscode-lldb-full.vsix` in the server, whose sha1sum is exactly same to the one's that @jeehoonkang provided.
Since its ownership is root:root and it does not allow others to overwrite, it seems to be solved by removing the file from the given server.

**Comment by jeehoonkang** [comment]
@Reinose thanks for the analysis.  but I think it's dangerous to give write permission to students, because it may introduce security vulnerability.  Please follow the workaround written in the README.

**Comment by KAIST-JongchanPark** [comment]
@jeehoonkang For installing manually, I think there is easier way with GUI. Here is for link, https://stackoverflow.com/questions/42017617/how-to-install-vs-code-extension-manually
