### ISSUE TITLE
Some broad questions involving homework

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#50]
My favorite thing about this course is that the assignments are iterative processes that are due the end of the semester.
However, because of this, and because we are having classes in a way that can feel sort of disconnected, it is difficult to check if I'm following the class in a good pace.

In addition, for some recent lectures that explain our homework(e.g. the two recent IRGen videos), it is somewhat confusing whether I should start the homework after all the IRGen videos are over, or I should start the homework beforehand so that I can understand the videos more easily, or I should try to follow along as each video is released.

So how many homework should we expect, and when is the best(expected) time to start each homework?

**Comment by jeehoonkang** [comment]
- I expect you to start programming as soon as the corresponding "code" videos are uploaded.  I try to make the goal of each homework as clear as possible, and hope each "code" video is a guide for eaching the goal.  I recommend you to watch the video, and then to implement your compiler as much as you can from the video.

- I expect about 7 homework assignments.  But please be noted that homework 2 (IRgen) is probably the biggest homework, as it needs to deal with the corner cases of C.  Later homework assignments will deal with IR, which should be smaller I believe.
