### ISSUE TITLE
[Midterm Exam] Claim session on April 28st (Fri) 9:00am-10:00am.

### ISSUE THREAD

**Issue by jirheee** [kaist-cp/cs420#500]
As we have announced before, we will have claim session on this week's office hour, April 28st (Fri) 9:00am-10:00am.

* If you want to claim on the midterm exam, please come to KAIST E3-1, Rm 4441.

* If you cannot come to the session due to personal reason, then please send email to jungin.rhee@cp.kaist.ac.kr with your claim before April 28st (Fri) 14:00pm.

**PLEASE DESCRIBE YOUR CLAIM IN AS MUCH DETAIL AS POSSIBLE.** Otherwise, it will be extremely difficult for us to process the claims. Please prioritize your claim points so that we can focus on more urgent claims first.

**Comment by jirheee** [comment]
https://github.com/kaist-cp/cs420/issues/485#issuecomment-1524382973

**Comment by m-spitfire** [comment]
Hello. Has the exam statistics changed much after the claim?
