### ISSUE TITLE
[Question] creduce creates UB program

### ISSUE THREAD

**Issue by prime235711** [kaist-cp/cs420#501]
Here's my test_reduced.c

```
int a;
int main() {
  int b;
  for (; a < 6; a++)
    if (b)
      b = 0;
}
```
As mentioned in https://github.com/kaist-cp/cs420/issues/193, b is uninitialized here and it makes undefined behavior.
My second reduce also leads to the same result, so I'm stuck with the fuzzer.

**Comment by m-spitfire** [comment]
Hello. See "Reducing" part of [fuzzer documentation](https://github.com/kaist-cp/kecc-public/blob/main/tests/README.md). You can use a flag to make sure it'll be UB free, but it'll be slower to reduce.

**Comment by AnHaechan** [comment]
Please call TAs if this problem persists, after trying @m-spitfire 's solution.

**Comment by prime235711** [comment]
I found the buggy program after trying @m-spitfire 's solution.  Thank you very much!
