### ISSUE TITLE
[Question][Hw2] Is sizeof4 a hidden test case for IrgenSmall?

### ISSUE THREAD

**Issue by Re-st** [kaist-cp/cs420#502]
By implementing and passing the IRgenSmall test on machine, I submitted but got 'fail' log with 'sizeof4' (left) != (right).
That case is not in the repository I'm having, neither on the kecc official website (the number of testcases have even got smaller)
Is it a hidden test case or is there somewhere else I can get the testcase?

**Comment by jirheee** [comment]
It is a public test case in the [kecc-public repository](https://github.com/kaist-cp/kecc-public/blob/main/examples/ir0/sizeof4.ir). I think your current repository is not up to date, so we recommend you to pull the testcase from remote repo. 😄

**Comment by Re-st** [comment]
Oh it seems like that was the only added thing in the repository. Thanks
