### ISSUE TITLE
[Question] In what cases can double type annotation occur?

### ISSUE THREAD

**Issue by YoonseokJeong** [kaist-cp/cs420#507]
I'm implementing GVN for HW5 and below is a snippet of IR that I've got after applying my GVN to `complete_cond.ir`.

```
...
block b14:	
  j b15(1:i32:i32)		 
block b15:		
  %b15:p0:i32:t2		 
  j b6(%b15:p0:i32:i32)	
...
```	 

I passed all other test cases but only the `complete_cond.ir` shows such double type annotations. (There are other types of error on this test case though...)

More specifically, this double type annotation occurs only at the jump arguments.

Since writing IR is not implemented by myself, I'm wondering how this can happen.

**Comment by jirheee** [comment]
Is your local version synced with the latest kecc-public version? I remember that we have fixed similar issue this semester.

**Comment by YoonseokJeong** [comment]
That was the exact problem. Thank you for your checking.
