### ISSUE TITLE
An unexpected behavior of creduce

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#51]
Hi.

When I execute `python3 tests/fuzz.py --reduce --irgen`, after the reduce, the content of the `tests/test_reduce.c` file is the same as the following:

```c
void main() {}
```

For me, it seems a bit weird since `tests/test_polished.c` contains the following:

```c
int main (void)
{
...
```

Even though the original source code has the `main` function with the return type `int`, the reducer produces the `main` function with the return type `void`.

I believe that the behavior can be problematic. My IRgen generates an IR function that returns the value `Unit` if its return type is `void`. For this reason, `void main() {}` cannot be passed since its expected result is `0`, which is the exit code. It implies that the reducer always results in the same code unless I change IRgen to return `0` from the `main` function with the return type `void`.

Do we have to consider the `main` function with the return type `void`? It seems `main` returning `void` is not a part of the standard semantics.

> The function called at program startup is named main. The implementation declares no prototype for this function. It shall be defined with a return type of int and with no parameters:
> `int main(void) { /* ... */ }`
> or with two parameters (referred to here as argc and argv, though any names may be
used, as they are local to the function in which they are declared):
> `int main(int argc, char *argv[]) { /* ... */ }` or equivalent; or in some other implementation-defined manner.

It looks like that whether one allows `main` to return `void` depends on implementation.

Otherwise, could you revise the reducer not to make the `main` function return `void`? Also, It might be possible to consider `Unit` as `0` when the tester checks results.

Thank you.

**Comment by cmpark0126** [comment]
Thank you for your reporting! Actually, we already know the problem you pointed out, and we are currently working on the issue. Please wait for the revised version of `kecc`, and sorry for the inconvenience.

**Comment by cmpark0126** [comment]
Sorry for the late consideration. We work on this issue, and the patched version will be merged to `kecc-public` very soon. 

The `creduce` of patched version of `kecc-public` will not make `void main() {}` case you mentioned above, so you don't need to consider this case.

**Comment by cmpark0126** [comment]
Now we just update `kecc-public`!: https://github.com/kaist-cp/kecc-public/commit/7569d5ad83398ee5daf386d852acf6ecab381ba6. This update includes patches that resolve this issue. 

Again, thank you for your reporting!

**Comment by Medowhill** [comment]
I have just checked that it works fine. Thank you for the fix. :)
