### ISSUE TITLE
[Question] issue with new login method & development environment

### ISSUE THREAD

**Issue by healwon** [kaist-cp/cs420#510]
Hello.
I always appreciate for your great lecture.

Unfortunately, I'm having trouble with gg and develop environment again.

1. At the start of the semester, my account had trouble with different student id with same kaist email and same problem happend. I can login to the [https://auth.fearless.systems](https://auth.fearless.systems/) with new student id, but it redirect to gg with the OLD student id, so I cannot access the cs420 lecture homepage. 

<img width="599" alt="화면 캡처 2023-05-25 162313" src="https://github.com/kaist-cp/cs420/assets/54568153/97e61b43-0e5e-4ccf-8d3a-60d7d726762c">
<img width="598" alt="image" src="https://github.com/kaist-cp/cs420/assets/54568153/a1d86d81-a588-47e3-b85e-5661e911b4f0">

2. With the new environment, I want to restore the old files, which is not pushed yet. Is there any method?

Sorry for the bothering request.

**Comment by jeehoonkang** [comment]
Would you please send me an email <jeehoon.kang@kaist.ac.kr>? Please specify old/new student ids, email, ...

**Comment by jeehoonkang** [comment]
@healwon 
- login problem: I think it's resolved now.
- development machine: oh sorry, the URL has been changed. Please see https://github.com/kaist-cp/cs420#tools

**Comment by healwon** [comment]
Really thanks for all responses! I'll close the issue since the problems are resolved.
