### ISSUE TITLE
[Question] GVN: Slide error(?), regarding locality of RT and ET

### ISSUE THREAD

**Issue by m-spitfire** [kaist-cp/cs420#512]
Hello. I was reading through GVN slides and one thing took my attention. In this slide
![image](https://github.com/kaist-cp/cs420/assets/66242799/db70af49-077a-43b8-b1b0-6cceb39cdc62)

`%c1` and `%c2` are both assigned with number $(3)$. Why is this? I think one of them should be $(4)$, since RT and ET should be global tables, not local to the block. I think ET has to be global no matter what, but if the RT is local to the block, how did we know with which number to start? We should start with maximum number + 1 in LT at $B_{\text{init}}$?(here $B$ is any block) But that feels hacky (maybe not). Please let me know if I understood any part wrong, or does it even matter?

**Comment by jirheee** [comment]
RT, ET are global, and you can think the slide as RT, ET calculation for new information that has been calculated in the block.

So here is the process: 
Traverse the blocks in RPO order,
1. B0:
- RT:
  - %a -> (1)
  - %b0 -> (2) // new 
- ET: 
  - (1) + 1 -> (2) // new

2. B1: 
- RT:
  - %a -> (1)
  - %b0 -> (2)
  - %b1 -> (2) // new
  - %c1 -> (3) // new
- ET:
  - (1) + 1 -> (2)
  - (2) + 2 -> (3) // new

3. B2
- RT:
  - %a -> (1)
  - %b0 -> (2)
  - %b1 -> (2)
  - %c1 -> (3)
  - %c2 -> (3)  // %c2 = RT[%b0] + 2 = (2) + 2 => ET[(2) + 2] = (3)
- ET:
  - (1) + 1 -> (2)
  - (2) + 2 -> (3)

**Comment by m-spitfire** [comment]
Oh, I see. I've missed the part that `%c1` and `%c2` has the value. Thank you!!

**Comment by jirheee** [comment]
Here are quick answers:

0. LT is `Line -> Num -> Operand`
1. True
2. Why did you think like that? Could you tell us?

I will come back soon with the leader table calculation.

**Comment by jirheee** [comment]
@rexes-ND   I forgot to come back to this issue.. Sorry for late response. And actually, leader table calculation for each block is already in the slide. Does each step mean after each instruction?

**Comment by rexes-ND** [comment]
@jirheee Sorry for the late response. I've just finished GVN. Your RT and ET calculations really helped. Thank you very much!
