### ISSUE TITLE
[HW8] gg fails without error message, so how can I debug the code?

### ISSUE THREAD

**Issue by kingdoctor123** [kaist-cp/cs420#513]
Hello

As like in #449 and #450, my submission at gg just fails without printing any error message that might be useful for debugging.
```
(... omitted)
   Compiling thiserror-impl v1.0.38
   Compiling clap_derive v4.1.7
   Compiling clap v4.1.7
   Compiling kecc v0.1.0 (/app/files/checks/68188128-45c7-41cc-b5cf-19dc8e1d5a33/kecc-public)
    Finished release [optimized] target(s) in 18.01s
(../target/release/kecc -O graph.c -o graph.s) || (rm graph.s -rf; exit 1)
(../target/release/kecc -O exotic_arguments.c -o exotic_arguments.s) || (rm exotic_arguments.s -rf; exit 1)
(../target/release/kecc -O two_dimension_array.c -o two_dimension_array.s) || (rm two_dimension_array.s -rf; exit 1)
(../target/release/kecc -O fibonacci.c -o fibonacci.s) || (rm fibonacci.s -rf; exit 1)
(../target/release/kecc -O matrix.c -o matrix.s) || (rm matrix.s -rf; exit 1)
riscv64-linux-gnu-g++ -O -fsigned-char -o driver.o -c -I. driver.cpp
riscv64-linux-gnu-g++ -o bench ./graph.s ./exotic_arguments.s ./two_dimension_array.s ./fibonacci.s ./matrix.s driver.o
```
I have already read the entire assembly files (`exotic_argument.s`, `fibonacci.s`, ...) generated by my solution, and I'm highly confident that there is no misaligned memory access. Also, the executable program `bench` runs very well on both the provided server and my own laptop, so I cannot get any useful information by using `gdb`.

In this case, what can be the possible source of error? Or is there any way for me to directly see the situation where the executable file fails during execution so that I can debug?

Thank you in advance.

**Comment by jirheee** [comment]
Well that is very strange.. I will look at the issue and respond as soon a possible. Sorry for inconvenience🥲

**Comment by jeehoonkang** [comment]
@kingdoctor123 sorry, would you please try again?

**Comment by kingdoctor123** [comment]
@jeehoonkang It works now. Thank you
