### ISSUE TITLE
[gg] I have no access to gg

### ISSUE THREAD

**Issue by wooriel** [kaist-cp/cs420#514]
When I try to access [good game](https://gg.kaist.ac.kr/accounts/login/?next=/), somehow the site directs me to authentic or Google login page. The student id and the password that I set do not work.
I have to submit the assignment, but it does not work.
Is my account deleted? (or am I on the wrong site?)

**Comment by jeehoonkang** [comment]
https://github.com/kaist-cp/cs420/issues/508
