### ISSUE TITLE
[HW7] Result of assembly generation model solution of foo4.ir

### ISSUE THREAD

**Issue by SIC98** [kaist-cp/cs420#515]
Hello,

While testing the Assembly Generation model on the gg website, I have a question because I don't understand the the assembly of `examples/ir0/foo4.ir`.
```c
int foo(int i, int j, int k) {
  return i + j + k;
}

int (* foo2())(int, int, int){
  return foo;
}

int (* (* foo3())())(int, int, int){
  return foo2;
}

int main() {
  return foo3()()(2, 2, 2) == 6;
}
```
The assembly of main function is as follows.
```
.main_L1:
        li	a0,0
        ld	s4,-24(s0)
        ld	ra,-16(s0)
        ld	s0,16(sp)
        addi	sp,sp,24
        ret
main:
        addi	sp,sp,-24
        sd	s0,16(sp)
        addi	s0,sp,24
        sd	ra,-16(s0)
        sd	s4,-24(s0)
        call	foo3
        mv	s4,a0
        jalr	s4
        mv	s4,a0
        li	a0,2
        li	a1,2
        li	a2,2
        jalr	s4
        li	a3,6
        xor	a3,a0,a3
        seqz	a0,a3
        ld	s4,-24(s0)
        ld	ra,-16(s0)
        ld	s0,16(sp)
        addi	sp,sp,24
        ret
```
I have two questions about this:

1) It seems like the instructions `sd s4,-24(s0)` and `ld s4,-24(s0)` in the main function serve the purpose of backing up the `s4` register to memory, and then restoring it after the `s4` register has been fully utilized in the main function. Am I understanding this correctly?
2) If 1) is correct, is there a need for this even if the `s4` register is not used outside of the main function in the assembly of the model solution?

**Comment by AnHaechan** [comment]
1. Yes, you're correct.

2. Yes, there is a need.
  Because any assembly program must follow a *calling convention*. According to the [calling convention of RISC-V](https://riscv.org/wp-content/uploads/2015/01/riscv-calling.pdf), `s4` is callee-saved register. That is, the value inside `s4` must be preserved after executing a function.
  Then why is a calling convention required? Imagine there is no consensus between arbitrary assembly functions on how they will use `s4` register. Then, for compiling a single function `main`, a compiler needs to be aware of the whole assembly program, which is not desirable.

**Comment by SIC98** [comment]
Thank you! I understood answers.

Then, is it totally okay to implement assembly using the caller-saved register `t0` instead of the callee-saved register `s4` as follows?

```
.main_L1:
        li	a0,0
        ld	s4,-16(s0) // 24 -> 16
        ld	ra,-8(s0) // 16 -> 8
        ld	s0,8(sp) // 16 -> 8
        addi	sp,sp,16 // 24 -> 16
        ret
main:
        addi	sp,sp,-16 // 24 -> 16
        sd	s0,8(sp) // 16 -> 8
        addi	s0,sp,16 // 24 -> 16
        sd	ra,-8(s0) // 16 -> 8
        call	foo3
        mv	t0,a0 // s4 -> t0
        jalr	s4
        mv	t0,a0 // s4 -> t0
        li	a0,2
        li	a1,2
        li	a2,2
        jalr	t0 // s4 -> t0
        li	a3,6
        xor	a3,a0,a3
        seqz	a0,a3
        ld	ra,-8(s0) // 16 -> 8
        ld	s0,8(sp) // 16 -> 8
        addi	sp,sp,16 // 24 -> 16
        ret
```

**Comment by AnHaechan** [comment]
It is okay for your example.

**Comment by AnHaechan** [comment]
It may not be okay.

As `t0` is a caller-saved register, its value may change after a procedural call (here, `jalr`).
If you want to use `t0` instead of `s4`, you need to save `t0` into somewhere else before invoking a procedural call.

**Comment by SIC98** [comment]
Thank you for the reply! I'll close this issue.
