### ISSUE TITLE
[HW6] Unused phinodes still exist at deadcode.output.ir

### ISSUE THREAD

**Issue by Re-st** [kaist-cp/cs420#516]
I have a question.
I wanted to remove unused phinodes.
But the following error appeared.
According to this thread, b0:p0 should be deleted.
But in [after opt (expected)], it is not deleted.
Is this error?

Source : https://github.com/kaist-cp/kecc-public/blob/main/examples/deadcode/deadcode.output.ir 

If I don't delete phinodes, the particular example discussed in this thread is the stopper.
If I delete the phinodes, this example is stopper.

Since it's already almost end of semester, I think my misunderstanding could be possible reason of this.
Can I ask you for the reason the p0 is not deleted?
Thank you!

[before opt]
fun i32 @deadcode () {
init:
  bid: b0
  allocations: 
    %l0:i32:x
    %l1:i32:y

block b0:
  %b0:i0:i32 = add 100:i32 200:i32
  %b0:i1:i32 = add %b0:i0:i32 300:i32
  %b0:i2:i32 = add %b0:i1:i32 400:i32
  %b0:i3:unit = store %b0:i0:i32 %l1:i32*
  br undef:i1, b1(), b2()

block b1:
  %b1:i0:unit = nop
  %b1:i1:unit = call @sink:[ret:unit params:(unit)]*(%b1:i0:unit)
  j b3()

block b2:
  %b2:i0:unit = store 42:i32 %l1:i32*
  j b3()

block b3:
  ret 0:i32
}

fun unit @sink (unit) {
init:
  bid: b0
  allocations: 

block b0:
  %b0:p0:unit
  ret unit:unit
}

[after opt]
fun i32 @deadcode () {
init:
  bid: b0
  allocations: 
    %l0:i32:y

block b0:
  %b0:i0:i32 = add 100:i32 200:i32
  %b0:i1:unit = store %b0:i0:i32 %l0:i32*
  br undef:i1, b1(), b2()

block b1:
  %b1:i0:unit = call @sink:[ret:unit params:(unit)]*(unit:unit)
  j b3()

block b2:
  %b2:i0:unit = store 42:i32 %l0:i32*
  j b3()

block b3:
  ret 0:i32
}

fun unit @sink (unit) {
init:
  bid: b0
  allocations: 

block b0:
  ret unit:unit
}

[after opt (expected)]
fun i32 @deadcode () {
init:
  bid: b0
  allocations: 
    %l0:i32:y

block b0:
  %b0:i0:i32 = add 100:i32 200:i32
  %b0:i1:unit = store %b0:i0:i32 %l0:i32*
  br undef:i1, b1(), b2()

block b1:
  %b1:i0:unit = call @sink:[ret:unit params:(unit)]*(unit:unit)
  j b3()

block b2:
  %b2:i0:unit = store 42:i32 %l0:i32*
  j b3()

block b3:
  ret 0:i32
}

fun unit @sink (unit) {
init:
  bid: b0
  allocations: 

block b0:
  %b0:p0:unit
  ret unit:unit
}

_Originally posted by @Re-st in https://github.com/kaist-cp/cs420/issues/398#issuecomment-1575618345_

**Comment by m-spitfire** [comment]
Unused phinodes should be deleted, unless they're in `bid_init`.

**Comment by Re-st** [comment]
Thank you for your kind reply!
