### ISSUE TITLE
[HW2] how can we get the pointer of other function's local variables?

### ISSUE THREAD

**Issue by LockOne** [kaist-cp/cs420#52]
```
void f1 (int * a) {
  a[1] = 1;
}
void main () {
  int a[5];
  f1(a);
}
```
In this example, `main `will allocate 5 int variables for its own stack frame, and it will pass the pointer to `f1`.
Then, `f1` will allocate a local pointer variable `a` in its own stack frame, so we can get the value a[0], but I'm not sure how to get other allocated values (a[1] ... a[4]) via pointer operation. It seems typecast is also not an answer because there is no interpreter code to typecast integer to pointer.
Also, we can use only allocation ids (`aid`) but not `bid` (the one used for memory, not block id) because there are 3 `registerId` types : local, args, and temp.

Any hints to get the pointer of other function's local variables?

**Comment by cmpark0126** [comment]
Thank you for the good question! I think the explanation below will help you.

---
**1st**, when `main` function is called, *`int a[5]` is allocated to memory*
After the allocation, the `RegisterId` of `a` represents a pointer.

**2nd**, let's `a` of `main` function is `Value::Pointer{bid: 0, offset: 0, dtype: int }`. After you pass the pointer of `a` of `main` function as a parameter of `f1`, *parameter `a` of `f1` function represents same pointer value of `a` of `main` function*

**3rd**, `a[5]` is allocated to memory as a form below:
```c
bid:0
// [int] => [byte][byte][byte][byte]
   [int][int][int][int][int]
// ^
// Value::Pointer{bid: 0, offset: 0, dtype: int }
```

In this case, if you want to access a[1], *you need to adjust `offset` of pointer value like below:*
```c
bid:0
// [int] => [byte][byte][byte][byte]
   [int][int][int][int][int]
//      ^
//      Value::Pointer{bid: 0, offset: 4, dtype: int }
```
Note that, `offset` indicates which `byte` you will start with, and to learn how to adjust `offset`, see `GetElementPtr` Instrunction.
---

For the above reason, you can use the `main` function's local variables especially the array variable in the `f1` function. 

I'm not sure if this answer helped you. If you have further questions, feel free to comment. :)

**Comment by LockOne** [comment]
Ah, there is an `offset` field in `Pointer` value.
Thanks.
