### ISSUE TITLE
[Question] Is there any specific syntax in asm model solution?

### ISSUE THREAD

**Issue by Meraroo** [kaist-cp/cs420#525]
```
fun i32 @main () {
init:
  bid: b0
  allocations:

block b0:
  %b0:i0:u64 = typecast 4:i32 to u64
  %b0:i1:u1 = cmp eq 4:u64 %b0:i0:u64
  %b0:i2:i32 = typecast %b0:i1:u1 to i32
  ret %b0:i2:i32
}
```
I gave this ir (alignof.ir) to model solution uploaded in gg and it occurs error:
```
Parse(ParseError { location: LineCol { line: 1, column: 1, offset: 0 }, expected: ExpectedSet { expected: {"\"fun\"", "EOF", "\"struct\"", "\"<named_struct>\"", "\"var\""} } })
```

**Comment by AnHaechan** [comment]
Hi, can you 
(1) try again to submit your IR file to gg
(2) mail me(haechan.an@cp.kaist.ac.kr) the exact file you've submitted?

I submitted your ir to gg but failed to reproduce the error.

IR I've submitted (copy & pasted your IR)
```
fun i32 @main () {
init:
  bid: b0
  allocations:

block b0:
  %b0:i0:u64 = typecast 4:i32 to u64
  %b0:i1:u1 = cmp eq 4:u64 %b0:i0:u64
  %b0:i2:i32 = typecast %b0:i1:u1 to i32
  ret %b0:i2:i32
}
```

GG's output I've got
```
===== SETUP =====

===== CHECK =====
[2023-06-12 06:15:47,345: WARNING/ForkPoolWorker-32] Demoting to runner...
        .globl	main
        .section	.text
        .type	main, @function
main:
        li	t3,4
        li	t2,4
        xor	t3,t2,t3
        seqz	a0,t3
        ret
```

**Comment by Meraroo** [comment]
- file 
https://drive.google.com/file/d/1N6NyKuCNz-2Ya5Es_XzeHnEQ7tc5N1pE/view

- error 
![image](https://github.com/kaist-cp/cs420/assets/81629557/4056b16a-3146-4a9d-ad32-423d69eb2a50)

**Comment by kingdoctor123** [comment]
@Meraroo I had the same issue and it seems it happens due to encoding problem. When I submit it using Windows, error occurred like you, but when I submit using Linux, error did not occur. 

So, the method I use is: save the content of `ir` file on the provided server, download it (using vscode, ...) onto your computer, and submit it on gg. I think it may work for you.

**Comment by Meraroo** [comment]
Oh, I see. the encoding!
Thank you very much and have a good evening!
