### ISSUE TITLE
[Question] Google forms loading issue

### ISSUE THREAD

**Issue by Re-st** [kaist-cp/cs420#526]
At finals exam, for pushing 'submit' before time ends up i pushed 'next' button very fast that the last Q5's my (previously saved) answers did not even load to the answer box. May it cause the Q5 answers to be cleared blank? Trying to simulate the same circumstance in the example google form but the loading never becomes slow enough to observe the answers not being load to the answer box before clicking on next button.
Sorry to ask for the google forms problem.

**Comment by AnHaechan** [comment]
All of your answers for question 5 (5-1 to 5-6) are not blank and seemed to have good amount of texts, thereby indicating your answers are saved safely.

**Comment by Re-st** [comment]
I am so much relieved by your kind answers. Really thank you so much for the check!! Have a good day!
