### ISSUE TITLE
[Final exam] Schedule for the score release and claim session + Quick survey

### ISSUE THREAD

**Issue by AnHaechan** [kaist-cp/cs420#527]
* Score for the **final exam** will be released until ~~June 18th (Sun)~~ June 19th (Mon) 6 pm.
* **Claim session** will be on June 21st (Wed), 11:00am~11:55am.
  * If you cannot physically attend to the claim session, please email me (haechan.an@cp.kaist.ac.kr) with your claim until June 20th (Tue).
  * Please describe your claim in as much detail as possible. Otherwise, it will be difficult for us to process the claims.
  
* Before you leave, please take a **quick survey** on how you've used LLMs(e.g. chatGPT) for this course! 
  * It won't take more than 1~2 minutes, yet will be extremely helpful for making this course better.
  * Link: https://forms.gle/19tABsoDoWA7docT9

**Comment by minizzang** [comment]
Survey link doesn't seem to work.
It says we need a permission. Could you check this problem?

**Comment by AnHaechan** [comment]
Thanks for reporting. It has been fixed now.
(Link is the same: https://forms.gle/yyWdkaZPSv6QBNmx6)

**Comment by AnHaechan** [comment]
UPDATE: We'll release the score for final exam until June 19th (Mon), 6 pm. Sorry for delaying.

**Comment by AnHaechan** [comment]
UPDATE: We'll release the score during 6~7pm today, sorry for a bit of delay!

**Comment by AnHaechan** [comment]
We have finished grading the exam, and your scores for each part are published at gg.

Total: 94
Max: 85
3Q: 70.5
2Q (median): 57
Average: 56.2
1Q: 45.5
Min: 15
[](url)
![Histogram of total (94)](https://github.com/kaist-cp/cs420/assets/48047392/9b86ca00-fb56-40db-9a05-ca4dfb36e6d6)

**Comment by jirheee** [comment]
We have found a synchronization problem with the google sheets, and the verification part needed to be written correctly. So we have updated the verification credit in gg. The statistics given above are correct so you can check your updated verification scores in gg.

**Comment by Re-st** [comment]
Hi. I am at empty E3-1 1501. Is claim held on somewhere else? Thanks!
