### ISSUE TITLE
[Question] only exotic_arguments.c shows nothing

### ISSUE THREAD

**Issue by Jihwan-Yoon** [kaist-cp/cs420#529]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--

I tried to run benchmark for performance competition.
So I used following commands.

```sh
cd bench
make run
```

But exotic_arguments.c showed nothing and terminal just froze. All of my other homeworks including irgen, optimize, asmgen are correct but only exotic_arguments.c doesn`t work. Other c files such as matrix.c, graph.c and fibonacci.c show
``` 
runner: ~~ bid: ~~ idom: ~~
```
but exotic_arguments.c shows nothing.

I tried several hours to figure out the problem but couldn`t.

What should I do...

**Comment by Jihwan-Yoon** [comment]
And also, I can not use gdb.
Gdb is not installed.

**Comment by jirheee** [comment]
1. Could you tell us in what stage your terminal is being frozen? It can be either the compilation stage or actual benchmark that is causing the problem

2. You can install gdb yourself. You can refer to the updated readme for installation

**Comment by Jihwan-Yoon** [comment]
1. Terminal forze at this stage 
```
(../target/release/kecc -O exotic_arguments.c -o exotic_arguments.s) || (rm exotic_arguments.s -rf; exit 1)
|
```
2. I tried
```sh
sudo apt-get install gdb
```
but didn`t work

**Comment by jirheee** [comment]
1. Then is is the compilation stage that has a infinite loop. -O option will try to run the optimization as much as possible(untill it converges), which can possibly lead to dead loop.

2. I recommend to try again after sudo apt update

**Comment by Jihwan-Yoon** [comment]
1. Then should I fix one of the optimization algorithm to make it converge?

2. sudo command is not working at all
```sh
$ sudo apt update
bash: sudo: command not found
```

**Comment by AnHaechan** [comment]
1. Yes you should, if your terminal is being frozen only when you turn on `-O` option.
  Try compiling the `exotic_arguments.c` files without `-O` option first, to track down the problem.
2. I think googling `bash: sudo: command not found` and trying existing solutions will help. If you feel stuck again, please feel free to ask question again.
  FYI, below is the answer from chatGPT.
---
If you're getting the error message "bash: sudo: command not found," it means that the "sudo" command is not available or not installed on your system. 

The "sudo" command allows you to run commands with administrative privileges. Here are a few steps you can take to fix this issue:

1. Check if sudo is installed: Run the following command to check if the "sudo" package is installed on your system:
   ```
   which sudo
   ```
   If it returns a path (e.g., "/usr/bin/sudo"), it means sudo is installed.

2. Verify the PATH variable: The "sudo" command may not be found if the PATH variable is not properly configured. Run the following command to check your current PATH variable:
   ```
   echo $PATH
   ```
   Make sure that the path to the directory containing the "sudo" command is included in the output. Typically, it should be "/usr/bin" or "/usr/sbin".

3. Reinstall sudo (if necessary): If the "sudo" package is not installed or appears to be missing, you can reinstall it using the package manager for your operating system. The exact command may vary depending on your distribution. Here are a few examples:

   - Ubuntu or Debian:
     ```
     apt-get install sudo
     ```

   - CentOS or RHEL:
     ```
     yum install sudo
     ```

   - macOS (with Homebrew):
     ```
     brew install sudo
     ```

4. Check for system issues: If the above steps don't resolve the issue, it's possible that there are deeper system problems causing the "sudo" command to be unavailable. In such cases, it may be necessary to seek assistance from a system administrator or consult relevant support resources for your operating system.

Note: If you don't have administrative privileges on the system or you're working on a restricted environment, you may not be able to use "sudo" at all. In such cases, you'll need to work with the permissions and access levels provided to you.
