### ISSUE TITLE
About Rust and lib linking

### ISSUE THREAD

**Issue by mechu1205** [kaist-cp/cs420#53]
From the Rust Book:
Rust is an ahead-of-time compiled language, meaning you can compile a program and give the executable to someone else, and they can run it even without having Rust installed.

Does this mean that every library is statically linked and included in the exe file? Wouldn't that make the exe too big?

**Comment by jeehoonkang** [comment]
You can configure a crate lib to be dynamically linked: https://doc.rust-lang.org/reference/linkage.html
