### ISSUE TITLE
[Question] What is the license for KECC?

### ISSUE THREAD

**Issue by solomatov** [kaist-cp/cs420#533]
I want to use KECC for self education. However, kecc-public doesn't have any license in there. Would be great if you clarify it? 

P.S. Excuse me for posting it here, but the issues for kecc-public are closed.

**Comment by jirheee** [comment]
Why do you want a license for self-education? You can use them for your self-education unless you don't publically publish your solution.

**Comment by solomatov** [comment]
@jirheee I got used to using materials under some license. Just wanted to resolve ambiguity here. What if you created this just for students of your university.

P.S. The course which you provided on youtube is fantastic. Thanks for sharing it!
