### ISSUE TITLE
[Question] Github homework links

### ISSUE THREAD

**Issue by fakhrimammadli** [kaist-cp/cs420#535]
When you're asking a question, please make sure:

- [ ] You clarify your questions as clear as possible.  If possible, please make it a yes/no question.  If possible, please summarize your question in one sentence at the beginning of an issue.

- If you're asking a question on concepts:
    + [ ] You read the corresponding sections of the slide.
    + [ ] You searched for the concepts using search engines and Wikipedia.

- If you're asking a question on Rust programming:
    + [ ] You searched for error messages or any relevant logs using search engines.
    + [ ] Your problem is reproducible in the provided server.  Please describe how others can reproduce your problem.
    + [ ] You paste code, if any, in text with [syntax hightlight](https://docs.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks).  No images.
    + [ ] You paste code, if any, that is minimized as much as possible.  Your code should be immediately relevant to your question.

--
Hello
Following links in github repository do not work for me:
https://github.com/kaist-cp/cs420/tree/main/homework/src/hello_server
https://github.com/kaist-cp/cs420/blob/main/homework/README.md

**Comment by jirheee** [comment]
The issue template is outdated, so please ignore it and follow the instructions in the [README.md](https://github.com/kaist-cp/cs420/blob/main/README.md).

Sorry for the confusion.
