### ISSUE TITLE
[Session 10] April, 16th (REALTIME Q&A)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#57]
- On 16th of April, we will have a realtime Q&A session.  Please join in Google Hangout Meet (https://meet.google.com/bms-btcx-ohp) at 10:30am.

- It's not mandatory: I'll not ask attendance quiz.  But **I strongly encourage you to attend the session** and to ask questions.

- If you have questions, please ask them in the issue tracker first, and label them as `question`.  You can write down questions in Korean.  For management purposes, I may not be able to answer pop questions during the realtime Q&A session.

**Comment by jeehoonkang** [comment]
If anyone is not able to enter the meeting room, please leave a comment here.

**Comment by KunJeong** [comment]
Just to let you know, I believe students are currently not allowed to add labels on our issues.
