### ISSUE TITLE
cargo docs not showing 'crate::ir'

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#58]
I want to read the documentation for `crate::ir`. However, running `cargo doc --open` does not show the ir crate anywhere. What am I doing wrong?

P.S. I made sure I was up to date with the upstream, and I ran the command in `kecc-public`.

**Comment by cmpark0126** [comment]
Thank you for the question :)

In fact, `cargo doc` only shows public elements designated in [src/lib.rs](https://github.com/kaist-cp/kecc-public/blob/master/src/lib.rs). So, if you want to refer a private element of `kecc`, you need to find code directly.

**Comment by KunJeong** [comment]
Thank you! That would be much appreciated.

**Comment by KunJeong** [comment]
Upon using the ir::Declaration::try_from and ir::Declaration::dtype methods as in the lectures, I get the following errors.

- no variant or associated item named `try_from` found for enum `ir::Declaration` in the current scope
- no variant or associated item named `try_from` found for enum `ir::Constant` in the current scope
- no method named `dtype` found for enum `ir::Declaration` in the current scope

Could this be related to the ir crate not being public? Adding import statements `use crate::ir` or `use crate::ir::Declaration`doesn't work either.

**Comment by KunJeong** [comment]
Solved: I thought try_from was in `ir::Declaration`, but it was in `core::convert::TryFrom`. Using the same imports as the lecture and removing the `#[deny(warnings)]` in lint settings fixed the error.
