### ISSUE TITLE
[HW 2 Question]

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#61]
Hello

I have a question about the declaration of a function.
We have that a _Declarator_ contains a list _derived = Vec<Node<DerivedDeclarator>>_ such that the _DerivedDeclarator_ contains the function parameters. 

The question is, when a function is declared, will this list _derived_ always contain only one element when declaring a function (i.e. the parameters)? Or could it contain more elements, and what are inside them if such is the case?

**Comment by cmpark0126** [comment]
Thank you for the question. :)

The short answer is no. Even though the function is declared, the derived list can contain the other elements. 

Here is the example:
```c
int *foo(int i);
```
```rust
derived: [Node { node: Pointer([]), .. }, 
          Node { node: Function(Node { node: FunctionDeclarator { .. }), .. }]
```

The above function `foo` has a very simple form of function declaration. In this case, `foo` declarator has two derived elements: `Pointer`, `Function`.

**Comment by christofides** [comment]
Okay, great answer, thank you!
