### ISSUE TITLE
[HW1] Submission fail while testing using fuzzer.py passed

### ISSUE THREAD

**Issue by umartaufiqul** [kaist-cp/cs420#62]
Hello, I have question regarding the submission.

So I submitted my implementation for homework 1 after I passed all the examples test and the random test case generated from fuzzer.py . However, the submission said my implementation failed when applied to fuzzer.. 

I'm quite confused on how to debug this, because after I make sure that I have the latest version from upstream and I let it ran through fuzzer indefinitely, yet it doesn't throw any failure.

Is there anyway I could debug the error that happen in the submission?

**Comment by cmpark0126** [comment]
Thank you for reporting. Could you let me know what is your student id? I will reply to you after checking the submission and test system. (maybe tomorrow)

**Comment by umartaufiqul** [comment]
Here is my student id: 20170896. I did fetch and merge from the upstream, and it said that it was already up to date

**Comment by KunJeong** [comment]
Have you also run `cargo test`? I found that the given version of the fuzzer doesn't generate certain kinds of statements, such as `do {} while`, so I passed all the test even when I didn't implement those statements, while the tests include all the cases we need.

**Comment by cmpark0126** [comment]
@umartaufiqul 
We have a plan to ask you again to resubmit your homework. So, please wait next announcement related to HW1. Sorry for the inconvenience.

**Comment by umartaufiqul** [comment]
No problem! Thank you for looking into this. For now I will close the issue.

**Comment by cmpark0126** [comment]
@KunJeong 
Thank you for the reporting! Actually, we expect `do while` case is checked at `examples/fib5.c`. I wonder your implementation also pass this example when you run `cargo test` run.

**Comment by cmpark0126** [comment]
@KunJeong I misunderstand your comment before;; haha... thank you for the comment!
