### ISSUE TITLE
SSH Connection Issue

### ISSUE THREAD

**Issue by mechu1205** [kaist-cp/cs420#63]
I can't connect to the server right now, is the server down?
I've tried with Putty and got a connection time error.
When I tried with VS Code, I got a 'tried to write to a nonexistent pipe' error
(which I'm not sure what it means specifically- could it mean that something went wrong with the ssh server on my local machine?)

**Comment by jeehoonkang** [comment]
Closing (continuing discussion here: https://github.com/kaist-cp/cs420/issues/17#issuecomment-615034057)
