### ISSUE TITLE
functions having &self as parameters

### ISSUE THREAD

**Issue by mechu1205** [kaist-cp/cs420#64]
Does this have any meaning?
Would there be a problem if it was removed?

i.e.
pub fn get_int_width(&self) -> Option<usize> {
        if let Self::Int { width, .. } = self {
            Some(*width)
        } else {
            None
        }
    }

**Comment by cmpark0126** [comment]
Thank you for the question! :)

Even if you delete the skeleton code of the file other than the file you need to submit, the test server (gg.kaist.ac.kr) will still use that code. So, I strongly recommend don't remove the skeleton code.
However, If you don't need the skeleton code, you don't have to use it.

FYI, when you attach reference code into the issue, please use source code permalink or [fenced code block](https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks) of markdown like below:
- permalink example
https://github.com/kaist-cp/kecc-public/blob/72ec63ea82509b3e15ee023def875efb65b0b11c/src/ir/dtype.rs#L507-L513
- fenced code block
  ```rust
  pub fn get_int_width(&self) -> Option<usize> {
      if let Self::Int { width, .. } = self {
          Some(*width)
      } else {
          None
      }
  }
  ```

**Comment by mechu1205** [comment]
no, i meant: why do you put &self as the parameter?
Would just () instead of (&self) cause a problem?

**Comment by cmpark0126** [comment]
Ah, ok I understand what you really want to know.
If the function has no `&self` parameter, it cannot perform the role of `method`. 
For example, `self` of `if let Self::Int { width, .. } = self {` line of above function cannot be used if there is no `&self` parameter

**Comment by mechu1205** [comment]
thank you!
