### ISSUE TITLE
[Homework2] Question on how our IR interprets binary operator instructions and typecast

### ISSUE THREAD

**Issue by wenko99** [kaist-cp/cs420#67]
In our IR interpreter, [ir/interp.rs#L271-416](https://github.com/kaist-cp/kecc-public/blob/72ec63ea82509b3e15ee023def875efb65b0b11c/src/ir/interp.rs#L271-L416), 

it seems that binary operator instructions are supported only for integer values.

Is it going to be updated to support float values for binary operator instructions?

If not, is there a way to translate codes such as

```c
float a = 1.0;
float b = 2.0;
float c = a + b;
```

into our IR?

In addition to that, for some C code involving implicit typecast (like below example), should we translate them into IR w/ explicit typecast? I wonder if our IR interpreter will take implicit typecasting in consideration.

```c
int x = 3;
float c = x * 2.0;
```

Thanks in advance : )

**Comment by cmpark0126** [comment]
Thank you for your great question!

First, as you expected, we are working on supporting binary operator expression for float value. Perhaps within this week, the patched version will be updated.

Second, yes, you need to translate implicit typecast to IR explicitly. `kecc` follows the `LLVM`'s rule of implicit typecast, so it should be helpful that check the how `LLVM` translate implicit typecast to IR. (please use https://godbolt.org/ actively)

FYI, The IR below is an example of compiling the example code you mentioned above with `kecc`:
```c
int main() {
    int x = 3;
    float c = x * 2.0;
    return 0;
}
```
```llvm
define i32 @main() {
init:
  bid: b0
  allocations: 
    %l0:i32:x
    %l1:f32:c

block b0
  %b0:i0:unit = store 3:i32 %l0:i32*
  %b0:i1:i32 = load %l0:i32*
  %b0:i2:f64 = typecast %b0:i1:i32 to f64
  %b0:i3:f64 = mul %b0:i2:f64 2:f64
  %b0:i4:f32 = typecast %b0:i3:f64 to f32
  %b0:i5:unit = store %b0:i4:f32 %l1:f32*
  ret 0:i32

block b1
  ret 0:i32
}
```

**Comment by wenko99** [comment]
Thank you for the answer :)
