### ISSUE TITLE
[Homework 1] Question on the code from HW1 video

### ISSUE THREAD

**Issue by Changrim** [kaist-cp/cs420#68]
Hello, I'm Changrim Lee and my student ID is 20198208.

I've started the entire homework quite recently, and I'm currently trying to understand the code reference from HW1 video and use some of those codes, thanks to #60.

So what I understand right now is that I have to implement `write_line` and `write_string` functions (and possibly `write_operation` which I found from write_base.rs?) in recursive ways, and the HW1 video shows the example for `ExternalDeclaration` and `Declaration`, and so on.
I also understand that specific rules can be found on lang_c document and C11 standard document.

I'm trying to understand this part of code from the video:
(on 7:47)
```rust
impl WriteString for (&Vec<Node<DeclarationSpecifier>>, &Declarator) {
    fn write_string(&self) -> String {
        format!(
            "{} {}",
            self.0
                .iter()
                .map(WriteString::write_string)
                .collect::<Vec<_>>()
                .join(" "),
            self.1.write_string()
        )
    }
}
```

In details, I can't understand why we are implementing `WriteString` for `(&Vec<Node<DeclarationSpecifier>>, &Declarator)` rather than `(&Vec<Node<DeclarationSpecifier>>, &InitDeclarator)` or `(&Vec<Node<DeclarationSpecifier>>, &Vec<Node<InitDeclarator>>)`.

I thought the above code block is implementing the `write_string` function for the code block below, which can be also found from the same video.

```rust
impl WriteLine for Declaration {
    fn write_line(&self, indent: usize, write: &mut dyn Write) -> Result<()> {
        write_indent(indent, write)?;
        writeln!(write, "{};", self.write_string())?;
        Ok(())
    }
}
```

So my understanding is that we need to implement for `self.write_string()` here, and the first code block is doing that. But then, the lang_c document says that declaration of `Declaration` is:
```rust
pub struct Declaration {
    pub specifiers: Vec<Node<DeclarationSpecifier>>,
    pub declarators: Vec<Node<InitDeclarator>>,
}
```

I wonder where are `&Declarator` coming from, since it is not shown in the declaration above.
Thanks in advance!

**Comment by Changrim** [comment]
I've been thinking about this for few more hours, I think I got something.
If I make a declaration like
```c
int a, b, c = 3;
```
Then `int` is the declaration-specifiers, and `a, b, c = 3` should be the init-declarator-list from C11 6.7, and each of `a`, `b` and `c` should be the declarator.
So if I implement the function as
```rust
impl WriteString for (&Vec<Node<DeclarationSpecifier>>, &Declarator) {
    ...
}
```
Then I'm only allowing the declaration something like
```c
int a;
```
I suppose this is not desired behavior as parse.rs contains this code block:
```rust
impl AssertSupported for InitDeclarator {
    fn assert_supported(&self) {
        self.declarator.assert_supported();
        self.initializer.assert_supported();
    }
}
```

So I guess I should change the declaration and the function body rather than copying the original function from the video.
Am I thinking correctly?
Again, thanks in advance!

**Comment by christofides** [comment]
Hello,

I dont work for the course but i had this issue earlier so i hope it is alright if I answer anyway. I think there is some intermediate function not shown in the video since the call made from write_line for Declaration should not be made to the write_string from the video. As you say, the types of function parameters and passed arguments differ.

Although please tell me if I could be wrong since it would mean i misunderstood something or that the Rust language has some cool feature I dont know,

Br
Jesper Amilon

**Comment by cmpark0126** [comment]
Thank you for your question. The presence of `WriteString for (&Vec<Node<DeclarationSpecifier>>, &Declarator)` seems to have confused you. 

First of all, as @christofides says(thank you for your comment!),  we also have `WriteString for Declaration` to print `int a, b, c = 3;` properly. (as you expected, `int a;` is not desired output) Actually, you can easily infer the existence of this function from the definition of `WriteLine for Declaration`: `self.write_string()`.

By the way, you don't need to use all of the functions shown in the video when you resolve homework as long as `write_c.rs` reprint the original code properly.

FYI, `WriteString for (&Vec<Node<DeclarationSpecifier>>, &Declarator)` is a function implemented to cover a particular case. When you implement `write_c.rs`, you may find that certain case is easily solved when using the this functions.

**Comment by cmpark0126** [comment]
@christofides Once again, thank you for your comment! ;)

**Comment by Changrim** [comment]
@christofides @cmpark0126 

Thank you for the answer! Now I finally understood everything.

It's hard to imagine the need of the function since I'm on the very beginning, but later I might also find out if I really need ```WriteString for (&Vec<Node<DeclarationSpecifier>>, &Declarator)``` or not.
