### ISSUE TITLE
[Homework 1] Is there any rule for printing new line and indentation?

### ISSUE THREAD

**Issue by Changrim** [kaist-cp/cs420#69]
As far as I know, C does not require any new line or indentation on most of the language feature except `#include` or something.
So I guess the parsed AST would be the same even if we don't print any indentation or new line.
Then is there some additional rule for printing the indentation/new line for HW1?

I've been implementing most of my functions as `write_string` rather than `write_line` because I thought this kind of code (using `write_line` inside `write_string`) is likely to mess up everything, and I started from `impl WriteString for Declaration` in #68 .
```rust
impl WriteString for Foo {
    fn write_string(&self) -> String {
        ...
        write_line(...); // ?
        ...
    }
}
```

And I found this nightmare scenario on the C11 document, section 6.7.2.1 when implementing `StructField`... (we don't need to take care of `union`, but it's still the same anyway)
```c
struct v {
    union {
        struct { int i, j; };
        struct { long k, l; } w;
    };
    int m;
} v1;
```

I think I have two options right now:
1) Re-design the entire code again using `write_line` for every functions which requires indentation from itself or lower level
2) Not print the indentation/new line for some situations, which would print code like this:
```c
struct v { union { struct { int i, j; }; struct { long k, l; } w; }; int m; } v1;
```

I personally want to stick on to option 2, but I need to check if I'm allowed to do so.
And I also want to check if there are specific rules about printing indentation and new line, as the professor mentioned about indentation on HW1 video, but didn't explain the details.

Thanks in advance!

**Comment by cmpark0126** [comment]
Thank you for the question. You can do whatever you want, as long as your implementation passes the test. ;) By the way, I recommend considering `indentation`.

**Comment by Changrim** [comment]
Thank you for the answer!
