### ISSUE TITLE
Debug command displays error

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#7]
I have setup the rust environment and builded successfully. However, upon selecting 'Run > Start Debugging', I get the following error.
Internal debugger error: unable to find executable for '/home/s20180595/Works/crossbeam/<your program>'
Then it says 'Open launch.json', which I think means that I need to add a configuration for debugging. However, none of the options generated from the 'Add Configuration' button seems to be working.
This seems to be related to a dialog that I accidentally dismissed, that said something about auto-creating a configuration when I was running the build command (how stupid of me to press cancel..😣)
Any ideas on how to solve this problem?

**Comment by jeehoonkang** [comment]
How about deleting `launch.json` and retry?

**Comment by KunJeong** [comment]
Wow, yes it totally worked thank you!
