### ISSUE TITLE
Minor suggestions for the tests of KECC

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#71]
Hi.

I found that tests may silently fail.

First, `cargo` does not print any log messages when it succeeds a test unless the `--nocapture` flag is given. Second, in `src/tests.rs`, the `test_irgen` function simply returns instead of being panic in some erroneous cases. For example, compilation failures and timeouts are such cases. Even though the function prints log messages in some cases, the behavior of `cargo` does not allow us to know that there was an error.

The above situation actually happened in my machine. A timeout had happened, but `cargo` said that I passed all the tests. Since one can incorrectly think that one's implementation is complete, I believe that it would be nice to fix KECC to prevent similar situations, though I checked that there is currently no problem if I use the provided server.

I think that it is worth mentioning the `--nocapture` flag in the README file even if one can easily find the flag from `cargo test --help`. In addition, it seems that silent failures can be prevented by substituting every `return` with `panic!()` in `src/tests.rs`.

Thank you.

**Comment by cmpark0126** [comment]
Thank you for the reporting!

Actually, just skipping the `fuzzer` test when `compile error` or `timeout` occurs is intended to use `--reduce` option of the previous version of `kecc-public`. We will revise this option to give an informative message to the developer. Please wait next update of `kecc-public`.

**Comment by cmpark0126** [comment]
Sorry for the late consideration. I am working on this issue.

**Comment by cmpark0126** [comment]
Now we just update kecc-public: https://github.com/kaist-cp/kecc-public/commit/3bef06455ea35c39555020fe44fdee496dba402d. The update includes patches that resolve this issue.
