### ISSUE TITLE
[Session 11] April, 21th

### ISSUE THREAD

**Issue by cmpark0126** [kaist-cp/cs420#74]
Please do the following for the online session.

* Watch the"IRgen (Code, Statement 2)" video: https://www.youtube.com/watch?v=UkaXaNw462U

* Homework 1(#8) and 2(#35) skeleton is being improved. Please merge the upstream changes.

**Comment by jeehoonkang** [comment]
No quiz today; but the video contains many details necessary for irgen.  So I assume everyone is eager to watch the video...
