### ISSUE TITLE
CS420 server maintenance

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#75]
~~First of all, we will have a powerout on this Saturday (25th of April), 9:00AM-11:59AM.~~
First of all, **we will have a powerout on this Saturday (25th of April), 00:00-18:00**.

Furthermore, we're decommisioning the physical server hosting the cs420 virtual server, and we moved the virtual server to another physical server.  Due to the migration, you may get the following error message when ssh-ing to the server:

```
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@    WARNING: REMOTE HOST IDENTIFICATION HAS CHANGED!     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
IT IS POSSIBLE THAT SOMEONE IS DOING SOMETHING NASTY!
Someone could be eavesdropping on you right now (man-in-the-middle attack)!
It is also possible that a host key has just been changed.
The fingerprint for the ECDSA key sent by the remote host is
<redacted>
Please contact your system administrator.
Add correct host key in /home/jeehoon.kang/.ssh/known_hosts to get rid of this message.
Offending ECDSA key in /home/jeehoon.kang/.ssh/known_hosts:35
  remove with:
  ssh-keygen -f "/home/jeehoon.kang/.ssh/known_hosts" -R "[cp-service.kaist.ac.kr]:10005"
ECDSA host key for [cp-service.kaist.ac.kr]:10005 has changed and you have requested strict checking.
Host key verification failed.
```

Please execute a command like `ssh-keygen -f "/home/jeehoon.kang/.ssh/known_hosts" -R "[cp-service.kaist.ac.kr]:10005"` as instructed above.

**Comment by kaist-kihwan** [comment]
Am I the only one having connection timeout with cs420 server now?
Is there any problem in server now, professor?

**Comment by jeehoonkang** [comment]
The server is up and running.  Would you please report your environment and the input/output?

**Comment by kaist-kihwan** [comment]
Oh, I changed my internet and it works. Sorry.

**Comment by mechu1205** [comment]
is the server down already? im getting a network error: software caused connection abort

**Comment by jeehoonkang** [comment]
- Hmm, I can connect to the server.
- When reporting a connection problem, please write down your full log, including CLI input and output.  And try to use `-v` options (verbose output).

**Comment by mnj1071** [comment]
My friends and I cannot connect to the server, too.
Here is the log.
<img width="1136" alt="스크린샷 2020-04-24 오후 5 30 57" src="https://user-images.githubusercontent.com/38163941/80192100-a829b500-8651-11ea-81d5-ad78cb5f4dc7.png">

**Comment by jeehoonkang** [comment]
Now I cannot connect to the server, too...  We're investigating the connection problem.  Sorry for inconvenience.

**Comment by jeehoonkang** [comment]
It's not up and running.  Sorry for inconvenience.

**Comment by jeehoonkang** [comment]
Maintenance is done, and the server is now up and running.
