### ISSUE TITLE
[question] Can we use while-translation to for-translation in IRgen?

### ISSUE THREAD

**Issue by kaist-kihwan** [kaist-cp/cs420#76]
In my opinion, we can make a bijection between while statement and for statement.

for( A; B; C ) { D }
 can be translate to
A
while(B) { D; C; }
*if B is none, than put true instead. 

Then we can use while-translation to for-translation, and it will make code management easier by re-using codes.
Is it okay?

**Comment by christofides** [comment]
What happens to the scope of variables declared in A? Im not sure how C deals with scope of variables in for-initializer but if the scope is gone after for-loop, I think it could change behaviour?

**Comment by kaist-kihwan** [comment]
Well, there was an issue about scope. So I changed it to

{
  A
  {
  while ( B ) {
    {
      D
    }
    C
  }
}
(*also if B is none, put true instead)

**Comment by cmpark0126** [comment]
Thank you for the question :)

Actually, I don't want to recommend a trick in such a case. Even though code reusable is important when you develop, using these tricks can be harmful to readability and maintenance of the code. 

For example, when you meet some bug related to `for loop`, maybe you need to spend some time to understand why you handle `for-loop` logic as `while-loop`.

**Comment by jeehoonkang** [comment]
On the contrary to what @cmpark0126 said, I'd like to encourage you to use the conversion trick, as far as you're confident with that.  It's clever and worth exploring a design choice.  Even if the conversion is wrong, which I don't bellieve it is, the fuzzer will find a buggy input.

**Comment by kaist-kihwan** [comment]
Thank you for the answer!
