### ISSUE TITLE
[HW1] about fuzzing reduce

### ISSUE THREAD

**Issue by rubidam** [kaist-cp/cs420#77]
`python3 tests/fuzz.py --print --reduce`
`cat tests/test_reduced.c`
When I execute above commands, I can get below output.
`long a { +(+b); }`
However, I cannot understand this output.(How should I use this output) I read a Readme file in 'kecc-public', and what I understood is that when I input this output into my code, it will give me some error. However, when I run my code with this output, it runs well. 
How can I fix this problem? Did I misunderstand about reducing?

**Comment by kaist-kihwan** [comment]
That is the example that your implementation gets wrong.
So your code cannot work well for input "long a { +(+b); }"
I recommend you to put that input to test folder and check whats going wrong.

**Comment by rubidam** [comment]
I  fixed my problem. thank you!
