### ISSUE TITLE
[Invited Talk] June Paik (CEO, FuriosaAI) on June, 4th

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#79]
On the 4th of June, June Paik (CEO, FuriosaAI) will give us an invited talk.  FuriosaAI "build[s] high-performance AI inference coprocessors that can be seamlessly integrated into various computing platforms including data centers, servers, desktops, automobiles and robots" (https://www.furiosa.ai/).  Compiler technology is a key ingredient of the company since AI workloads need to be efficiently compiled to the designed coprocessors.

It is **mandatory** to (virtually) attend this talk at [Google Hangout Meet](https://meet.google.com/bms-btcx-ohp).  It will be a joint invited talk of CS420: Compiler Design and CS492G: Systems for Machine Learning (Prof. Jongse Park).  If you're interested in personally meeting with June, please [send me an email](mailto:jeehoon.kang@kaist.ac.kr).

--

Title: Challenges of building production AI chips for AI computing infrastructure
Speaker: June Paik (CEO, FuriosaAI)
Date/time: 4th of June (Thu), 10:30am-11:45am
Place: https://meet.google.com/bms-btcx-ohp

Abstract:

FuriosaAI builds high-performance AI inference coprocessors that seamlessly integrate with various computing platforms, including data centers, servers, desktops, automobiles, and robots. These platforms are under the great transformation to adopt AI to process the massive amounts of sensor data under the increasing pressure of real-time service requirements. The rise of AI chips, as we all know, is due to the breakthrough capabilities and generalities of deep neural networks, which enable us to solve complex problems where traditional algorithms approaches have shown its clear limitations, and can be applied to incredibly diverse areas, including computer vision, speech recognition, natural language processing and e-commerce. However, despite its promising future, there are many challenges currently facing AI chip designs as deep neural networks ask for an unprecedented level of scalability. We need improvements by at least an order of magnitude in all areas of computing: computation, communication bandwidth, memory bandwidth, and storage capacity with the same power and cost budget. Without proper solutions, the demands of scalability will make AI processing impractical in terms of cost, when we have to provide AI services as a commodity in the years ahead before long. The scalability challenges are also compounded by hurdles of plugging AI chips into existing software and hardware systems, whose legacy components might not be designed to accommodate and interface with them. In this talk, we will talk about how to attack these challenges.

Bio:

Current: CEO of FuriosaAI
2013-2016: Samsung Memory Solution Lab
2010-2013: AMD GPU SW Development team
2006-2008: AMD CPU Development team

Georgia Tech, M.S, Electrical Engineering

**Comment by christofides** [comment]
Hello! 

Can I ask what it means to personally meet with the speaker?
Do you mean meet up in person to listen to the lecture or to meet up in person with the speaker at some other time than during the lecture? 

Br
Jesper

**Comment by jeehoonkang** [comment]
if you're interested in the company, I can arrange a personal meeting between you and June.  Please send me an email.

**Comment by jeehoonkang** [comment]
The talk information is updated.  Again, It is mandatory to (virtually) attend this talk on the 4th of June, 10:30-11:45am, at https://meet.google.com/bms-btcx-ohp .

**Comment by jeehoonkang** [comment]
The talk will be in Korean, as contrary to what was announced.  Sorry for the inconvenience.  Foreign students are not required to attend the talk.

**Comment by jeehoonkang** [comment]
Reminder: the talk in 15 minutes https://meet.google.com/bms-btcx-ohp

**Comment by jeehoonkang** [comment]
If you want to contact the speaker, please send an email to junepaik@furiosa.ai or jeehoon.kang@kaist.ac.kr .  Thank you all for attending the talk.
