### ISSUE TITLE
[Homework 1] C AST printer (due: 8th of July)

### ISSUE THREAD

**Issue by jeehoonkang** [kaist-cp/cs420#8]
- Refer to the skeleton code: https://github.com/kaist-cp/kecc-public  Please be noted that the skeleton code is not just for homework 1 but for the entire KECC.  It will likely change quite frequently.  Please merge the upstream changes to your development.

- Here's a [guide video](https://www.youtube.com/watch?v=SOzsb09GldA&list=PL5aMzERQ_OZ8RWqn-XiZLXm1IJuaQbXp0&index=5&t=191s).

- For homework 1, implement a C AST (abstract syntax tree) printer: https://github.com/kaist-cp/kecc-public/blob/master/src/c/write_c.rs#L45  Given a C AST, you should print a valid C code.  We will not deal with the "full" C but focus on a subset of C that is defined in https://github.com/kaist-cp/kecc-public/blob/master/src/c/parse.rs .  The purpose of this homework is getting acquainted with the C language we will deal with, and in general, the skeleton code written in Rust.

- I strongly recommend you to run `cargo doc --open` and browse the repository, and specifically, the definition of C AST (the [`lang_c`](https://docs.rs/lang-c/0.7.0/lang_c/) library).

- While it is due on 8th of July, I strongly recommend you to start as early as possible.  We will enjoy other pieces of homework at the later stage of the semester.

- The grading scheme is simple: you either implement a complete C AST printer or not.  You can submit your code multiple times.  You can grade your submission yourself by running, e.g., `cargo test --release test_examples_write_c` and `python3 tests/fuzz.py -p -n30`.

- Submit your `write_c.rs` to https://gg.kaist.ac.kr/assignment/7/ .

**Comment by Reinose** [comment]
> * For homework 1, implement a C AST (abstract syntax tree) printer: https://github.com/kaist-cp/kecc-public/blob/master/src/write_c.rs#L45  Given a C AST, you should print a valid C code.  We will not deal with the "full" C but focus on a subset of C that is defined in https://github.com/kaist-cp/kecc-public/blob/master/src/parse.rs .  The purpose of this homework is getting acquainted with the C language we will deal with, and in general, the skeleton code written in Rust.

I thought that we do not have to implement pretty printer for those handled by the macro `panic!` in `src/parse.rs`.
However, in the guide video, the reference also implemented for them.
For example, `Statement::Labeled` is covered by `panic!` in https://github.com/kaist-cp/kecc-public/blob/master/src/parse.rs#L305, but in the guide video, it isn't.
Therefore, now I'm confused whether we would implement a complete C AST printer or not.
(Are we going to deal with full C eventually?)

**Comment by jeehoonkang** [comment]
**IMPORTANT**: the skeleton code is updated.

- Please merge the upstream changes in the repo: https://github.com/kaist-cp/kecc-public/
- Please be noted that the file to submit is moved from `src/write_c.rs` to `src/c/write_c.rs`.
- We enlarged the coverage of C syntax and enhanced tests.  As a result, we will nullify the existing submissions of homework 1 to gg.kaist.ac.kr .  Please resubmit your homework 1.  Sorry for the inconvenience.

**Comment by jeehoonkang** [comment]
- Fuzzer is updated again: https://github.com/kaist-cp/kecc-public/commit/2a5a5e71eded12bc3b6192f787f3c766d0b6c5dc  Please download the upstream changes.
- Now you can use test-driven development more easily.  See the [README](https://github.com/kaist-cp/kecc-public/blob/master/README.md#fuzzing).

**Comment by coolofficials** [comment]
Professor, I think link for parse.rs should be fixed either:)

**Comment by cmpark0126** [comment]
**IMPORTANT**

- Fuzzer is updated again: https://github.com/kaist-cp/kecc-public/commit/5b45cf1fd8b26b3f08b90a9e8ec21b016c96573e, https://github.com/kaist-cp/kecc-public/commit/7569d5ad83398ee5daf386d852acf6ecab381ba6 Please download the upstream changes.
  - Now `--irgen --reduce` option of `fuzzer` works properly. (resolve #51)
  - `parse.rs` is updated. Now you need to consider the [`lang_c::ast::Initializer::List`](https://docs.rs/lang-c/0.8.1/lang_c/ast/enum.Initializer.html#variant.List).

All updates related to homework 1 and homework 2 are scheduled to be completed within this week. Sorry for the inconvenience caused by the late update.

**Comment by jeehoonkang** [comment]
- All previous submissions have been nullified due to the updates in the skeleton code.
- You can resubmit now at https://gg.kaist.ac.kr/assignment/7/ .
- (I will soon provide the submission page for other assignments as well.)

**Comment by cmpark0126** [comment]
**IMPORTANT**

`examples/c/float2.c` has fixed in the latest update, because it showed undefined behavior before.
So, please resubmit your solution to gg. (I expect your solution works well with the new example if it passed the test before)

Sorry for the inconvenience.
