### ISSUE TITLE
as_ref() vs deref() for Box

### ISSUE THREAD

**Issue by KunJeong** [kaist-cp/cs420#81]
For some reason, using the `deref()` method for the `Box<T>` types in the C AST doesn't seem to work. Instead, I have to change to `as_ref()` to make it work. This feels different from both the Rust documentation and the code in the video. Can you help me figure out why this happens?

**Comment by jeehoonkang** [comment]
Would you please paste a short repro code?  What's expected and what's actually happening?

**Comment by KunJeong** [comment]
```rust
match dtype {
    ...
    ir::Dtype::Array { inner, size } => inner.deref().clone()
    ...
}
```
in the above code, `inner` is type `&'<empty> std::boxed::Box<ir::dtype::Dtype>` according to my type checker. However, it displays an error saying "no method named `deref` found for type `std::boxed::Box<ir::dtype::Dtype>`", and it only works when I change the `deref` to `as_ref`.
Then I remembered that I made the same changes in HW1, but now that I check again the code in HW1 is applied to `Option<T>` instead of `Box<T>`, which makes sense.

**Comment by LockOne** [comment]
I think you need to include deref in `src/irgen/mod.rs` to use `deref()` for `Box`;
`use core::ops::Deref;`
Did you included it?

**Comment by cmpark0126** [comment]
As @LockOne mentioned, you need to add `use core::ops::Deref;` if you use `deref()` method. :)

**Comment by KunJeong** [comment]
Oops, guess I missed that part :( Thank you!
On a side topic, could you explain how `as_ref()` and `deref()` are different? I didn't see the difference during HW1, so I'm just curious.

**Comment by cmpark0126** [comment]
@KunJeong 
For `Box<T>`, there is no difference between `as_ref()` and `deref()`: https://doc.rust-lang.org/src/alloc/boxed.rs.html#1068-1072, https://doc.rust-lang.org/src/alloc/boxed.rs.html#927-933.

If you want to understand the brief difference between `AsRef` and `Deref` please refer to this link: https://www.reddit.com/r/rust/comments/ex50zg/difference_among_deref_borrow_and_asref/fg6h2ci/

**Comment by KunJeong** [comment]
Thank you so much for your helpful answers!
