### ISSUE TITLE
reference and mutable

### ISSUE THREAD

**Issue by mechu1205** [kaist-cp/cs420#82]
let mut v = vec![100, 32, 57];
for i in &mut v {
    *i += 50;
}

and

let v = vec![100, 32, 57];
    for mut i in v {
        i += 50;
        println!("{}", i);
    }

yield the same results,
but I am curious in how they work differently in terms of type/ownership handling/mutability.

**Comment by Changrim** [comment]
I've added another line of code to find out the difference.

```rust
let mut v = vec![100, 32, 57];
for i in &mut v {
    *i += 50;
}
println!("v[0] = {}, v[1] = {}, v[2] = {}", v[0], v[1], v[2]);
```
This code will print:
```
v[0] = 150, v[1] = 82, v[2] = 107
```

```rust
let v = vec![100, 32, 57];
for mut i in v {
    i += 50;
    println!("{}", i);
}
println!("v[0] = {}, v[1] = {}, v[2] = {}", v[0], v[1], v[2]);
```
This code does not compile with the error message below:
```
error[E0382]: borrow of moved value: `v`
 --> src/main.rs:7:49
  |
2 |     let v = vec![100, 32, 57];
  |         - move occurs because `v` has type `std::vec::Vec<i32>`, which does not implement the `Copy` trait
3 |     for mut i in v {
  |                  -
  |                  |
  |                  value moved here
  |                  help: consider borrowing to avoid moving into the for loop: `&v`
...
7 |     println!("v[0] = {}, v[1] = {}, v[2] = {}", v[0], v[1], v[2]);
  |                                                 ^ value borrowed here after move

error: aborting due to previous error

For more information about this error, try `rustc --explain E0382`.
```

And... I think I need to read the Rust documentation again.

**Comment by cmpark0126** [comment]
- Please use: https://help.github.com/en/github/writing-on-github/creating-and-highlighting-code-blocks#fenced-code-blocks
- the codes you mentioned are different. In the first example, you can borrow `v` again because `for loop` just use `v` as reference. However, in the second example, you cannot borrow `v` again because `v` is moved out at `for mut i in v`.
