### ISSUE TITLE
[HW1] Question about fuzz

### ISSUE THREAD

**Issue by zzanggu9399** [kaist-cp/cs420#83]
안녕하세요 HW1을 열심히 하고 있는 학생입니다.

cargo test를 다 통과하고 fuzz 테스트를 하고 있습니다.

![스크린샷 2020-04-22 오후 5 28 29](https://user-images.githubusercontent.com/48054186/79959121-b1364d00-84be-11ea-967d-cb941eef34e9.png)

틀린부분이 있어 reduce 후에 출력해보니 ';' 하나만 출력되어있어 어디가 틀렸는지 감조차 오지 않는 상황입니다.

혹시 어디가 틀렸는지 더 자세히 알수 있는 방법이 있을까요? ㅜㅜ 혹은 제가 무언가 잘못하고 있는 부분이 있을까요?

**Comment by hyunsukimsokcho** [comment]
프로젝트 루트에서 
```
$ cat tests/reduce-criteria.sh
```
아웃풋을 보여주실수 있나요?

**Comment by zzanggu9399** [comment]
![스크린샷 2020-04-22 오후 6 08 46](https://user-images.githubusercontent.com/48054186/79963411-51db3b80-84c4-11ea-9d8f-1e679dd9b8d6.png)

이렇게 출력됩니당

**Comment by hyunsukimsokcho** [comment]
공유해주신 스크립트가 불완전해보이네요. 혹시 upstream 반영되있나요?

**Comment by zzanggu9399** [comment]
감사합니다 깃 풀이 적용이 안된 상태로 계속 짜고있었네요 해결했습니다!
