### ISSUE TITLE
[HW2] Reduce gives error

### ISSUE THREAD

**Issue by christofides** [kaist-cp/cs420#89]
Hello,

I am doing the homework locally on Ubuntu 18.04.
I am trying to fuzz + reduce but when running the reduce, I get an error.

I run
_$ python3 tests/fuzz.py -i -n 2_
Followed by
_$ python3 tests/fuzz.py -i --reduce_

However, when reducing, there is an error saying that file or directory "creduce" does not exist, and the output in test_reduced.c is not reduced. 

I'm just wondering if anyone had similar issue and could resolve it or is it perhaps only possible to reduce when using the server?

This is the error stacktrace I get from Python33:
_Traceback (most recent call last):
  File "tests/fuzz.py", line 263, in <module>
    creduce(tests_dir, fuzz_arg)
  File "tests/fuzz.py", line 193, in creduce
    proc = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.STDOUT, cwd=tests_dir)
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'creduce': 'creduce'_

**Comment by hyunsukimsokcho** [comment]
Install Creduce as well if you already installed Csmith in your local machine.

**Comment by christofides** [comment]
Aha, yes, it makes sense. How silly of me, thx a lot for the help!
