### ISSUE TITLE
[HW 1] Wrong assert_supported implementation?

### ISSUE THREAD

**Issue by LockOne** [kaist-cp/cs420#9]
Hello,
I'm not sure about the purpose of assert_supported, but I guessed that it limits the range of statements and expressions we are going to support in our class.

Currently, `Statement::Labeled(labelstatment)` is classified to panic, ([parse.py#L305](https://github.com/kaist-cp/kecc-public/blob/1b7d25314d048c72902dd67b137535ebf432ba56/src/parse.rs#L305))
while label statements are used in switch statements.
There were many `Label` assert_supported implementations in parse.py, 
so I guess it was a mistake.

Thank you.

**Comment by cmpark0126** [comment]
Thank you for the suggestion. But that implementation is intended.

Currently, `KECC` allows only `Statement::Labeled(...)` within `SwitchStatement`.
For this reason, `Statement::Labeled(...)` does not cause a panic when used within `SwitchStatement`([parse.rs(1)](https://github.com/kaist-cp/kecc-public/blob/1b7d25314d048c72902dd67b137535ebf432ba56/src/parse.rs#L356)), but you can see that it causes a panic when used alone([parse.rs(2)](https://github.com/kaist-cp/kecc-public/blob/1b7d25314d048c72902dd67b137535ebf432ba56/src/parse.rs#L305)).
