### ISSUE TITLE
Compile error occurred in KECC source code

### ISSUE THREAD

**Issue by thecasterian** [kaist-cp/cs420#90]
I cloned the latest kecc-public repository (including the commit "Update mem2reg test") and tried to build it with `cargo build`. However, a compile error occurred even without any modification on the code:

```sh
error[E0599]: no method named `write_string` found for reference `&lang_c::ast::Initializer` in the current scope
  --> src/ir/write_ir.rs:63:30
   |
63 |                         init.write_string()
   |                              ^^^^^^^^^^^^ method not found in `&lang_c::ast::Initializer`
   |
   = note: the method `write_string` exists but the following trait bounds were not satisfied:
           `&lang_c::ast::Initializer : write_base::WriteString`
   = help: items from traits can only be used if the trait is implemented and in scope
   = note: the following trait defines an item `write_string`, perhaps you need to implement it:
           candidate #1: `write_base::WriteString`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0599`.
error: could not compile `kecc`.

To learn more, run the command again with --verbose.
```

In addition, fuzz.rs, kecc.rs, and other files show "can't find crate for `kecc`" error at the statement `extern crate kecc;`. Please check the latest commits.

**Comment by lomotos10** [comment]
TAs acknowledged this issue in #70 ; they said the issue would be fixed within this week.
For now, a temporary write_string function for Initializer inside `write_c.rs` would fix the build issue.
```
impl WriteString for Initializer{
    fn write_string(&self) -> String {
        panic!("Waiting for fix... TAs pls...");
        "".to_string()
    }
}
```

**Comment by thecasterian** [comment]
Thank you! I completed to implement `write_string` functions for `Initializer` and its related classes and I don't get any compile error.

**Comment by cmpark0126** [comment]
Now we just update kecc-public: https://github.com/kaist-cp/kecc-public/commit/3bef06455ea35c39555020fe44fdee496dba402d. The update includes patches that resolve this issue.
