### ISSUE TITLE
I cannot connect to the server after server maintenance

### ISSUE THREAD

**Issue by rubidam** [kaist-cp/cs420#91]
I couldn't connect to the server since yesterday 4 pm. I saw that some people got same problems. I thought it will be solved after server maintenance. However, I tried to connect to server just before, it says 'cannot establish connection to cs420'. How can I solve this problem?

**Comment by jeehoonkang** [comment]
Please write down your input/output/configuration in more details so that we can help you debug the connection problem.  (I can connect to the server now...)

**Comment by rubidam** [comment]
아래 사진과 같이 나옵니다. 이부분을 보여드리는게 맞는지 잘 모르겠습니다.
![error1](https://user-images.githubusercontent.com/44969740/80279867-1bf3bc80-873b-11ea-8863-87d670062b6a.JPG)
![error2](https://user-images.githubusercontent.com/44969740/80279869-1dbd8000-873b-11ea-8948-bae110766655.JPG)

**Comment by jeehoonkang** [comment]
- Please paste the output as text, not image.
- As discussed in https://github.com/kaist-cp/cs420/issues/75#issue-603677257, it's due to the fact that "REMOT HOST IDENTIFICATION HAS CHANGED".  Please edit your `~/.ssh/known_hosts` and remove the first line.

**Comment by rubidam** [comment]
I tried to remove the first line in 'known_hosts' file yesterday, but problem was not solved. However, I retried the remove just before, it is solved. Thank you professor.

**Comment by rubidam** [comment]
> PS C:\Users\Hansung\.ssh> ssh cs420
ssh: connect to host cp-service.kaist.ac.kr port 10005: Connection timed out

방금전에 known_hosts의 내용을 지우고 접속을 하니 되었는데 다시 시도하니 되지않습니다..
위처럼 'ssh cs420'커맨드를 이용하여 접속을 시도하면 connection timed out이 뜨며 아웃풋 창에는 아무것도 뜨지 않습니다. 

visual studio code의 왼쪽 아래에 초록색 버튼을 눌러 'Remote SSH: Connect to host -> cs420'과 같은 방식으로 접속 시도시 이전과 같이 'could not establish connection'과 함께 아래와 같이 아웃풋이 출력됩니다.

> [14:06:26.636] Log Level: 2
[14:06:26.640] remote-ssh@0.51.0
[14:06:26.640] win32 x64
[14:06:26.642] SSH Resolver called for "ssh-remote+cs420", attempt 1
[14:06:26.642] SSH Resolver called for host: cs420
[14:06:26.642] Setting up SSH remote "cs420"
[14:06:26.706] Using commit id "ff915844119ce9485abfe8aa9076ec76b5300ddd" and quality "stable" for server
[14:06:26.709] Install and start server if needed
[14:06:26.713] Checking ssh with "ssh -V"
[14:06:26.771] > OpenSSH_for_Windows_7.6p1, LibreSSL 2.6.4
[14:06:26.773] Running script with connection command: ssh -T -D 50131 cs420 bash
[14:06:26.778] Terminal shell path: C:\Windows\System32\cmd.exe
[14:06:26.934] > 
[14:06:26.934] Got some output, clearing connection timeout
[14:06:47.971] > ssh: connect to host cp-service.kaist.ac.kr port 10005: Connection timed out
> 프로세스에서 없는 파이프에 쓰려고 했습니다.
> [14:06:48.219] "install" terminal command done
[14:06:48.220] Install terminal quit with output: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[14:06:48.220] Received install output: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[14:06:48.221] Stopped parsing output early. Remaining text: 프로세스에서 없는 파이프에 쓰려고 했습니다.
[14:06:48.221] Failed to parse remote port from server output
[14:06:48.222] Resolver error: 
[14:06:48.225] ------

**Comment by kaist-kihwan** [comment]
I'm struggling with same issue.

```
C:\Users\User>ssh cs420 -v
OpenSSH_for_Windows_7.7p1, LibreSSL 2.6.5
debug1: Reading configuration data C:\\Users\\User/.ssh/config
debug1: C:\\Users\\User/.ssh/config line 1: Applying options for cs420
debug1: Connecting to cp-service.kaist.ac.kr [143.248.140.83] port 10005.
debug1: connect to address 143.248.140.83 port 10005: Connection timed out
ssh: connect to host cp-service.kaist.ac.kr port 10005: Connection timed out
```

**Comment by cmpark0126** [comment]
@rubidam @kaist-kihwan 
Sorry for the late consideration.

Actually, I can connect to the server now. So I would like to ask you to check if it is set to block the ssh connection in firewall settings. Occasionally, firewall settings can cause `Connection timed out`.

**Comment by kaist-kihwan** [comment]
After I delete all the file in "~/.vscode-server/bin/" now I can connect well. I think it's a vs code error.

**Comment by cmpark0126** [comment]
@kaist-kihwan Great! 
@rubidam Please try out @kaist-kihwan's approach if you still have a problem ;)

**Comment by rubidam** [comment]
In my case, I don't have '.vscode-server' directory, and I still get a problem...
When I input the command "ssh cs420", I can connect to the server.
However, if I try to connect to server using "Remote ssh: Connect to Host", it makes some error like above. Also, after this problem, I cannot connect to the server using commands("ssh cs420") for a few hours(this is my guess).

**Comment by kaist-kihwan** [comment]
.vscode-server is secret directory so you cannot find it by normal way including ls command. Please do "cd .vscode-server" in "~/" directory by cmd since you can connect to server with cmd. I was struggle with same issue with you.

**Comment by rubidam** [comment]
@kaist-kihwan Thank you! It works very well!!!!

**Comment by gfhd0054** [comment]
@kaist-kihwan Sorry for bothering, but what should I do if I cannot connect to server also via cmd...? Would you share how you have solved it?

**Comment by kaist-kihwan** [comment]
If you are having same issue with me, when you try to connect server with vs code, you cannot connect with cmd after few minute. Just try it later, and DO NOT open vs code if you are not confident with solving the problem.

**Comment by gfhd0054** [comment]
Thanks a lot! I finally accessed to my server.

**Comment by ChaerinMin** [comment]
"remote-ssh : uninstall vscode server from host" worked for me
