### ISSUE TITLE
[Homework 2] A problem with reduce (generating code with an undefined behavior)

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#93]
Hi.

After reduce, the fuzzer gave me the following:

```c
int a[6];
int b;
int main() {
  for (; b < 6; b++)
    ;
  a[b] = b;
}
```

In the 6th line, `a[6] = 6` is evaluated, but the length of `a` is `6`. To the best of my knowledge, it causes an undefined behavior since the C language specification says that the following is considered as an undefined behavior:

> An array subscript is out of range, even if an object is apparently accessible with the given subscript (as in the lvalue expression a[1][7] given the declaration int a[4][5]) (6.5.6).

Also, the IR interpreter seems to crash when an offset exceeding the size of a block is accessed. On the other hand, `gcc` can compile the above code, and the resulting binary terminates with return status `0`. It makes my implementation not be able to pass the above test. Therefore, I believe that the provided reducer needs to be fixed.

Thank you.

**Comment by cmpark0126** [comment]
Thank you for the report, and we already know this problem.
Unfortunately, we have confirmed that `creduce` generate quite a number of undefined behavior cases and are currently discussing how to deal with it. So, please wait for the next comment on this issue.

Sorry for the inconvenience.

**Comment by cmpark0126** [comment]
- Actually, this is a bug of `creduce`. 
- How often generated the code having undefined behavior in your case? Will it continue to occur even if you find a new bug sample by running fuzzer and run `creduce`?

**Comment by Medowhill** [comment]
I made 10 trials, and the following are the results:

1.
```c
void(a)() { 0 == a; }
int main() {}
```

The failure is due to my implementation. However, I wonder whether we can implement comparisons between pointers under the current version of the IR interpreter. The interpreter seems to handle only comparisons between integers. Besides, type casts from pointers to integers or the opposites seem to be unsupported as well. We may handle the above as a special case since a comparison between a pointer to a function and the null pointer always results in `false`. However, it cannot be a general solution.

2.
```c
short a;
int main() { 0 && a--; }
```

The failure was due to my implementation, and I fixed it.

3.
```c
typedef struct a b;
int main() {}
```

The failure was due to my implementation, but it seems difficult to handle it, and I thus will report this one as a separate issue.

4. (6 times)
```c
struct {
} a;
int main() {}
```

It seems to be an undefined behavior. The C specification says the following causes an undefined behavior.

> A structure or union is defined without any named members (including those specified indirectly via anonymous structures and unions) (6.7.2.1).

5.
```c
int a[6];
int b;
int main() {
  for (; b < 6; b++)
    ;
  a[b] = b;
}
```

It is the same as the code of this issue.

It looks like that code with undefined behaviors often appears.

**Comment by cmpark0126** [comment]
Thank you for the deep answers!

`1` is an issue. Actually, we don't have any plan to check whether student's code has an ability to handle the case that comparing pointer and int. But if you want to handle this case, just leave comparing two operands `a` and `0`. Then, `KECC` interpreter will calculate correctly only if the integer part is zero. (this function is added in the next version of `KECC`)

Ok, `1`, `4` and `5` is undesirable behavior in our homework. But, It seems that if you try `creduce` several times, you can avoid this situation. It's not easy to resolve the bug you mentioned right now, so if this happens occurs again, I hope you can do your homework by trying `creduce` other bug samples.

Sorry for the inconvenience, please let me know again if you can't proceed with your homework even if you do this again and again.

**Comment by cmpark0126** [comment]
FYI, In my implementation, I handle the case comparing `pointer` and `int` like below:
```c
void(a)() { 0 == a; }
```
```llvm
fun unit @a {
init:
  bid: b0
  allocations: 

block b0:
  %b0:i0:u1 = cmp eq 0:i32 @a:*unit ()
  ret unit:unit
}
```

**Comment by Medowhill** [comment]
Thank you. :)

**Comment by Medowhill** [comment]
I fixed my implementation to resolve `1`, `2`, `3`, and `4`. (For `4`, I made IRgen simply replace an empty struct type with `Dtype::BOOL` when it is found to prevent the panic of IRgen.) Then, I tried fuzzing and reducing again and got the code exactly the same as `5` seven times in a row. Moreover, it usually takes more than ten minutes to reduce a single file. Multiple trials take too much time. For this reason, the fuzzer currently cannot help me debug the implementation.

**Comment by Medowhill** [comment]
I tried using GCC flags to reject code with undefined behaviors. The following is my fix:

```diff
--- a/src/tests.rs
+++ b/src/tests.rs
@@ -1,6 +1,6 @@
 use lang_c::ast::*;
 use std::fs::{self, File};
-use std::io::{stderr, Write};
+use std::io::{stderr, Write, Read};
 use std::path::Path;
 use std::process::{Command, Stdio};
 use tempfile::tempdir;
@@ -37,7 +37,7 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {

     // Compile c file: If fails, test is vacuously success
     if !Command::new("gcc")
-        .args(&["-O1", &file_path, "-o", &bin_path])
+        .args(&["-fsanitize=undefined", "-fno-sanitize-recover=all", "-O1", &file_path, "-o", &bin_path])
         .stderr(Stdio::null())
         .status()
         .unwrap()
@@ -48,6 +48,7 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {

     // Execute compiled executable
     let mut child = Command::new(fs::canonicalize(bin_path.clone()).unwrap())
+        .stderr(Stdio::piped())
         .spawn()
         .expect("failed to execute the compiled executable");

@@ -69,6 +70,13 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {
     );
     let status = some_or!(status.code(), return);

+    let mut s = String::new();
+    child.stderr.unwrap().read_to_string(&mut s).unwrap();
+    if !s.is_empty() {
+        println!("error occurs");
+        return;
+    }
+
```

After the fix, I got the following after reducing:

```c
struct {
  struct {};
} a;
int main() {}
```

The fix seems to work. Also, I believe that empty structures can be avoided as well by using other flags. If I succeed, I will add a comment.

**Comment by Medowhill** [comment]
When the `--pedantic` flag is given and an empty structure is found, the compiler raises a warning that says "struct has no members." Therefore, we can avoid empty structures. The following is my fix:

```diff
--- a/src/tests.rs
+++ b/src/tests.rs
@@ -1,6 +1,6 @@
 use lang_c::ast::*;
 use std::fs::{self, File};
-use std::io::{stderr, Write};
+use std::io::{stderr, Write, Read};
 use std::path::Path;
 use std::process::{Command, Stdio};
 use tempfile::tempdir;
@@ -36,18 +36,28 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {
     let bin_path = path.with_extension("irgen").as_path().display().to_string();

     // Compile c file: If fails, test is vacuously success
-    if !Command::new("gcc")
-        .args(&["-O1", &file_path, "-o", &bin_path])
-        .stderr(Stdio::null())
-        .status()
+    let mut child = Command::new("gcc")
+        .args(&["-fsanitize=undefined", "-fno-sanitize-recover=all", "--pedantic", "-O1", &file_path, "-o", &bin_path])
+        .stderr(Stdio::piped())
+        .spawn()
+        .expect("failed to compile");
+    if !child
+        .wait()
         .unwrap()
         .success()
     {
         return;
     }
+    let mut s = String::new();
+    child.stderr.unwrap().read_to_string(&mut s).unwrap();
+    if s.contains("struct has no members") {
+        println!("empty struct");
+        return;
+    }

     // Execute compiled executable
     let mut child = Command::new(fs::canonicalize(bin_path.clone()).unwrap())
+        .stderr(Stdio::piped())
         .spawn()
         .expect("failed to execute the compiled executable");

@@ -69,6 +79,13 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {
     );
     let status = some_or!(status.code(), return);

+    let mut s = String::new();
+    child.stderr.unwrap().read_to_string(&mut s).unwrap();
+    if !s.is_empty() {
+        println!("undefined behavior");
+        return;
+    }
+
     let ir = match Irgen::default().translate(unit) {
         Ok(ir) => ir,
         Err(irgen_error) => panic!("{}", irgen_error),
```

After the fix, I got the following:
```c
long a;
int main() {
  3 ^ 4073709551615 || (a = 2);
  return a;
}
```
It seems to be more useful than before.

The fix may not work if one uses a different version of the compiler or a different OS due to a different warning message. However, it would be fine if everyone runs the fuzzer in the provided server.

**Comment by Medowhill** [comment]
I found that modifying the reduce criteria would be a better way.

```diff
--- a/src/tests.rs
+++ b/src/tests.rs
@@ -1,6 +1,6 @@
 use lang_c::ast::*;
 use std::fs::{self, File};
-use std::io::{stderr, Write};
+use std::io::{stderr, Write, Read};
 use std::path::Path;
 use std::process::{Command, Stdio};
 use tempfile::tempdir;
@@ -37,7 +37,7 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {

     // Compile c file: If fails, test is vacuously success
     if !Command::new("gcc")
-        .args(&["-O1", &file_path, "-o", &bin_path])
+        .args(&["-fsanitize=undefined", "-fno-sanitize-recover=all", "-O1", &file_path, "-o", &bin_path])
         .stderr(Stdio::null())
         .status()
         .unwrap()
@@ -48,6 +48,7 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {

     // Execute compiled executable
     let mut child = Command::new(fs::canonicalize(bin_path.clone()).unwrap())
+        .stderr(Stdio::piped())
         .spawn()
         .expect("failed to execute the compiled executable");

@@ -69,6 +70,13 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {
     );
     let status = some_or!(status.code(), return);

+    let mut s = String::new();
+    child.stderr.unwrap().read_to_string(&mut s).unwrap();
+    if !s.is_empty() {
+        println!("undefined behavior");
+        return;
+    }
+
     let ir = match Irgen::default().translate(unit) {
         Ok(ir) => ir,
         Err(irgen_error) => panic!("{}", irgen_error),

--- a/tests/reduce-criteria-template.sh
+++ b/tests/reduce-criteria-template.sh
@@ -29,6 +29,7 @@ if
   grep 'non-void function does not return a value' out.txt ||\
   grep 'too many arguments in call' out.txt ||\
   grep 'declaration does not declare anything' out.txt ||\
+  grep 'struct has no members' out.txt ||\
   ! gcc -Wall -Wextra -O2 test_reduced.c > outa.txt 2>&1 ||\
   grep 'uninitialized' outa.txt ||\
   grep 'without a cast' outa.txt ||\
```

**Comment by Medowhill** [comment]
I found that modifying the reduce criteria would be a better solution.

```diff
--- a/src/tests.rs
+++ b/src/tests.rs
@@ -1,6 +1,6 @@
 use lang_c::ast::*;
 use std::fs::{self, File};
-use std::io::{stderr, Write};
+use std::io::{stderr, Write, Read};
 use std::path::Path;
 use std::process::{Command, Stdio};
 use tempfile::tempdir;
@@ -37,7 +37,7 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {

     // Compile c file: If fails, test is vacuously success
     if !Command::new("gcc")
-        .args(&["-O1", &file_path, "-o", &bin_path])
+        .args(&["-fsanitize=undefined", "-fno-sanitize-recover=all", "-O1", &file_path, "-o", &bin_path])
         .stderr(Stdio::null())
         .status()
         .unwrap()
@@ -48,6 +48,7 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {

     // Execute compiled executable
     let mut child = Command::new(fs::canonicalize(bin_path.clone()).unwrap())
+        .stderr(Stdio::piped())
         .spawn()
         .expect("failed to execute the compiled executable");

@@ -69,6 +70,13 @@ pub fn test_irgen(unit: &TranslationUnit, path: &Path) {
     );
     let status = some_or!(status.code(), return);

+    let mut s = String::new();
+    child.stderr.unwrap().read_to_string(&mut s).unwrap();
+    if !s.is_empty() {
+        println!("undefined behavior");
+        return;
+    }
+
     let ir = match Irgen::default().translate(unit) {
         Ok(ir) => ir,
         Err(irgen_error) => panic!("{}", irgen_error),

--- a/tests/reduce-criteria-template.sh
+++ b/tests/reduce-criteria-template.sh
@@ -29,6 +29,7 @@ if
   grep 'non-void function does not return a value' out.txt ||\
   grep 'too many arguments in call' out.txt ||\
   grep 'declaration does not declare anything' out.txt ||\
+  grep 'empty struct is a GNU extension' out.txt ||\
   ! gcc -Wall -Wextra -O2 test_reduced.c > outa.txt 2>&1 ||\
   grep 'uninitialized' outa.txt ||\
   grep 'without a cast' outa.txt ||\
```

**Comment by cmpark0126** [comment]
Thank you for your great work! If only `creduce` is considered, I would recommend you to modify `reduce-criteria-template.sh` only like below:
```diff
-  (! clang -pedantic -Wall -Werror=strict-prototypes -O1 -c test_reduced.c  > out.txt 2>&1 ||\
+  (! clang -pedantic -fsanitize=undefined -fno-sanitize-recover=all -Wall -Werror=strict-prototypes -O1 -c test_reduced.c  > out.txt 2>&1 ||\
...
+   grep 'empty struct is a GNU extension' out.txt ||\
```

The `creduce` only generates the code which can pass criteria given by `reduce-criteria-template.sh`.

**Comment by Medowhill** [comment]
I am afraid that would not work. The reason is that adding the `-fsanitize=undefined -fno-sanitize-recover=all` flags do not make the compiler print warning messages even when a given program leads to out-of-bounds access to an array. Instead, the compiler adds run-time checks to the resulting binary. If out-of-bounds access to an array happens at run time, then the execution immediately terminates with an error message. That is why I try to check `stderr` of the execution of the generated binary, not of the compiler.

**Comment by cmpark0126** [comment]
Ok, I check you pointed out. Thank you for your suggestion :)

**Comment by cmpark0126** [comment]
FYI, we changed the way comparing `pointer` and `int`. please refer the code below:
```c
void(a)() { 0 == a; }
```
```llvm
fun unit @a {
init:
  bid: b0
  allocations: 

block b0:
  %b0:i0:*unit () = typecast 0:i32 to *unit ()
  %b0:i1:u1 = cmp eq %b0:i0:*unit () @a:*unit ()
  ret unit:unit
}
```

**Comment by Medowhill** [comment]
It has been fixed by the latest [commit](https://github.com/kaist-cp/kecc-public/commit/f4dc5e426c200f6415858a113e2628ef0dd7ee95). Thank you!
