### ISSUE TITLE
[Homework 3] Empty src/opt/opt_utils.rs

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#95]
Hi.

I found that the `src/opt/opt_utils.rs` [file](https://github.com/kaist-cp/kecc-public/blob/master/src/opt/opt_utils.rs) is empty. I just wonder whether it is intended and whether the file will be filled in the future.

Thank you.

**Comment by cmpark0126** [comment]
1. [`src/opt/opt_utils.rs`](https://github.com/kaist-cp/kecc-public/blob/master/src/opt/opt_utils.rs) is a file that the student is given to implement.
2. we'll add the relevant comments into this file soon.

**Comment by Medowhill** [comment]
Thank you for the reply. Then, will we be required to submit `opt_utils.rs`? Currently, #84 and #86 say that we need to submit `simplify_cfg.rs` and `mem2reg.rs`.

**Comment by jeehoonkang** [comment]
@Medowhill yes, you are.  We will update the instruction soon.  Thank you for reporting this.

**Comment by Medowhill** [comment]
Thank you!

**Comment by jeehoonkang** [comment]
I updated the skeleton code. Thank you again for reporting this issue
