### ISSUE TITLE
[Homework 2] About the behavior of is_const in dtype.rs when the name of a struct is not found

### ISSUE THREAD

**Issue by Medowhill** [kaist-cp/cs420#98]
Hi.

I am trying to handle the following code in IRgen.

```c
typedef struct a b;
void f(b *p) {}
int main() {}
```

After transforming the first line, IRgen has a typedef map with a mapping from `"b"` to `Struct { name: Some("a"), fields: None, is_const: false, size_align_offsets: None }` and the empty struct map. I think that it is correct since `b` is an alias of `struct a` and there is no information about `struct a`.

When IRgen deals with the second line, it should resolve the type of the function. Before the resolution, the type is `Function { ret: Unit { is_const: false }, params: [Pointer { inner: Typedef { name: "b", is_const: false }, is_const: false }] }`. However, if I call the `resolve_typedefs` method for the type, a panic happens. The reason is that the method tries to check whether `Typedef { name: "b", is_const: false }`, which denotes `struct a`, is a constant type by calling the `is_const` method. In the `is_const` method, the following part causes a panic when the name of the struct type is not found in a given struct map:

```rust
let struct_type = structs
    .get(name)
    .expect("struct type matched with `name` must exist")
    .as_ref()
    .expect("`struct_type` must have its definition");
```

[https://github.com/kaist-cp/kecc-public/blob/61b21624081e78085c6073aa6d2c53d9cfa792df/src/ir/dtype.rs#L735-L739](https://github.com/kaist-cp/kecc-public/blob/61b21624081e78085c6073aa6d2c53d9cfa792df/src/ir/dtype.rs#L735-L739)

I believe that to handle the above code, `dtype.rs` needs to be fixed not to panic even though the name of a given struct type is not found.

Thank you.

**Comment by cmpark0126** [comment]
Thank you for the report! we just fixed this issue, and `kecc-public` will be updated soon (maybe today or tomorrow)

**Comment by cmpark0126** [comment]
Now we just update kecc-public: https://github.com/kaist-cp/kecc-public/commit/3bef06455ea35c39555020fe44fdee496dba402d. The update includes patches that resolve this issue.
